### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by ttv20** [ONLYOFFICE/DesktopEditors#10]
There is a RTL support in planning?
I saw that hebrew translate in process, but its not worth it if hebrew document will not work properly on your editor
thanks

**Comment by ShockwaveNN** [comment]
See https://github.com/ONLYOFFICE/DocumentServer/issues/19

**Comment by xunilarium** [comment]
For a great app (DesktopEditors) this is a big disadvantage, please add RTL feature ASAP.

**Comment by ShockwaveNN** [comment]
Closing since RTL will be appear only after fix of, so basically it's a duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/19
