### ISSUE TITLE
Integrate draw.io as Visio-like drawing application 

### ISSUE THREAD

**Issue by Norbert80** [ONLYOFFICE/DesktopEditors#1002]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Integrate draw.io as Visio-like drawing application. It is open-source, based on web-technologie (available through Browser and stand-alone like OnlyOffice). It supports MS Visio file formats.

![grafik](https://user-images.githubusercontent.com/6921696/185672614-c5e4e214-2345-4b4f-92cd-765d7182ccc3.png)

For me draw.io looks like a great fit for OnlyOffice.

**Comment by ShockwaveNN** [comment]
Hi, there is already a [draw.io plugin](https://github.com/ONLYOFFICE/plugin-drawio)

**Comment by Norbert80** [comment]
@ShockwaveNN thanks for the info. I cannot find a download link for the plugin file. Could you please post one?

**Comment by ShockwaveNN** [comment]
If you are using DesktopEditors v7.2 it should be in the plugin store

**Comment by Norbert80** [comment]
I cannot confirm this.

![grafik](https://user-images.githubusercontent.com/6921696/192610774-beb06a28-7774-4e2c-b455-7e90c36fb8cd.png)

ONLYOFFICE Desktop Editors Version 7.2.0.204 (deb package)

**Comment by VladimirProkofiev52** [comment]
Hi, @Norbert80 !
At the moment, the marketplace is not available on the desktop version of our application. We are working on this issue.  The marketplace appear in the next versions of our product.
You can add the required plugin on the desktop editor, following instruction: "https://api.onlyoffice.com/plugin/installation/desktop".
The "draw.io" plugin is currently available on the web version of our editor.
Periodically we update the Web page: "https://www.onlyoffice.com/en/app-directory", "draw.io" should appear the next time we update.
