### ISSUE TITLE
Functions don't calculate

### ISSUE THREAD

**Issue by itis-mmi** [ONLYOFFICE/DesktopEditors#1003]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.1.1.57

### Expected Behavior

I expect my formulas to calculate correctly when I enter them in the function bar. 

### Actual Behavior

When I enter a function in the function bar and press Enter, nothing happens. 
There's no formula error, and the function doesn't seem to execute, staying in the cell instead of the result : 
![image](https://user-images.githubusercontent.com/103992393/185889275-7a3d47c8-fdd0-43ec-bbda-36a66c90faee.png)

### Reproduction Steps

1. Select a cell
2. Enter a formula in the function bar at the top
3. Press Enter

**Comment by ShockwaveNN** [comment]
Hi, this may be an issue for specific formula language

Could you check that for english formula language this formula calculates correctly?

And if so - please add details about which formula lang you've using

**Comment by itis-mmi** [comment]
Hi, 
I'm using the french language.

I was initially working with the CONCAT/CONCATENER formula, and thought this was just a problem with this one. 
I then tested the SOMME formula, which isn't working, but even the SUM version doesn't work. 
About the CONCAT formula, the CONCATENATE version doesn't work either.

**Comment by ShockwaveNN** [comment]
I see in you screenshot you've referencing A1 cell and B4:B5 cells which is not visible

We need this file you've working on or some steps how to reproduce problem on empty file

**Comment by itis-mmi** [comment]
okay I found the origin of the issue. 
I converted the whole page into the "General" digits format, and now the functions work. 

The document was originally from another system, maybe there was a compatibility issue
