### ISSUE TITLE
Loss of focus inside an open document on tab switch and alt-tab from another application issues

### ISSUE THREAD

**Issue by serpinio** [ONLYOFFICE/DesktopEditors#1008]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.1.0.215

### Expected Behavior

- When switching between open documents in the DesktopEditors window, which are represented as tabs, when you switch using either a mouse click or a CTRL+TAB focus should be put inside the active document, at the place where caret is, and you should be able to continue typing
- When you alt+TAB into another application and back into the DesktopEditors window with an open document you should be able to switch between opened documents tabs with CTRL+TAB
- When you click inactive DesktopEditors window when another window is in the foreground, the Editors window should activate and become foreground - that is - shown above other windows

### Actual Behavior

- When switching between open documents in the DesktopEditors window, which are represented as tabs, when you switch using either a mouse click or a CTRL+TAB to any other document, you can see the cursor blinking as usual, but typing seems unresponsive until you do a mouse click inside the document. What is actually happening is - you're still typing in the previous document. Switch to it to see for yourself. It makes impossible to work with several documents with just a keyboard
- If you CTRL+TAB to another text document which doesn't get typing focus as described above, but also ALT+TAB to another window in the system and then back - the whole DesktopEditors window becomes **completely** unresponsive to **all** hotkeys or any keyboard keys until you click anywhere - on the window or inside a document, whatever. If makes impossible to work with the whole DesktopEditors window with just a keyboard when alt-tabbing between apps
- When you click inactive DesktopEditors window anywhere **except** the title bar when another window is in the foreground, the Editors window does activate but **doesn't get drawn above other windows** like any other normal application window would. Only Alt+tabbing, clicking taskbar icon or clicking the title bar of the Editors window fully brings the Editors window to the front.

### Reproduction Steps

**Typing focus:**

1. Open two documents at tabs
2. Place caret in document 1, place caret in document 2
3. Press CTRL+TAB or click tab of _another_ document from which is active and you can type in
4. Try typing - seems like there's _no reaction_ until you click in this document. But if you switch back to the previous one - you can type and in some cases everything you tried typing will have ended up in this one, as if it never lost typing focus

**ALT+TAB focus loss:**

1. Do all of the above and when you are in an _unresponsive_ document do an ALT+TAB to another window in the OS
2. ALT+TAB back to the DesktopEditors window
3. Press CTRL+TAB or any other key - arrows whatever - _no reaction_ until you click anywhere in the window

**Foreground bug:**

1. ALT+TAB to any other window in the system so that part of the DesktopEditors window is visible and a non-focused/unresponsive document displayed - see above
2. Click anywhere in the window **except** the title bar - it activates but is not brought to the foreground

### Additional information

Windows 10 2004, 1920x1080

**Comment by NoEpicLoot** [comment]
Having the same problem on Desktop Editors Version 7.1.1.57 with windows 10 21H2 (build 19044.1826)

**Comment by LuckySpecialist** [comment]
Hi @NoEpicLoot!
This is a known issue 56672 and has already been fixed in hotfix 7.2.1.
Please, check and write the result whether everything works correctly for you.
Thanks.

**Comment by ShockwaveNN** [comment]
I'close this issue since v7.2.1 is released. 

But feel free to comment if got any troubles with new version

**Comment by serpinio** [comment]
**Thank you!** Works as it should now, I'll close the Issue.

**Comment by HectorB-2020** [comment]
> * When you click inactive DesktopEditors window anywhere **except** the title bar when another window is in the foreground, the Editors window does activate but **doesn't get drawn above other windows** like any other normal application window would. Only Alt+tabbing, clicking taskbar icon or clicking the title bar of the Editors window fully brings the Editors window to the front.

@ShockwaveNN, I'm afraid this particular issue hasn't been fixed with v7.2.1. Let me file a new one: #1165.
