### ISSUE TITLE
[Feature] Print only on PDF attribute

### ISSUE THREAD

**Issue by blaggacao** [ONLYOFFICE/DesktopEditors#101]
As a Corporate Identity professional, I want to make sure that even the less gifted user is generating digital and printed output in the correct styling, without needing to pass through a design approval department, in this context...

One feature I'm commonly missing in other word processors (I actually haven't found one, who does it right) is,
- I want to define a Background image
- I want to set a flag on this image ("print only on digital format")
- When printing on paper I want to specify "exclude digital format elements"

Because I have a pre-printed letterhead, but also want to create same-looking documents to send via mail as PDF.

**Comment by vatterspun** [comment]
I believe only Acrobat Pro has some of that functionality.  Even if they included that functionality, Microsoft's document edit restrictions are sort of a joke and extremely easy to disable.

**Comment by ShockwaveNN** [comment]
Hi there, currently we have no plans to implement such feature, but you can contact our sales department at sales@onlyoffice.com and discuss this

**Comment by LuckySpecialist** [comment]
Hi, @blaggacao!
Can you show an example of such a file and in which application it was done?

**Comment by blaggacao** [comment]
Oh, this thought is well past it's expiration date, ai can't provide any useful context anymore. :-/

**Comment by Rita-Bubnova** [comment]
Sorry for the long wait.
So I close this issue. Feel free to comment or reopen it if you got further questions.
