### ISSUE TITLE
Support for Bitrix24 Cloud

### ISSUE THREAD

**Issue by pablomedok** [ONLYOFFICE/DesktopEditors#1013]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Please, add support for Bitrix24 Cloud, so users of server and cloud versions of Bitrix24 would be able to use Onlyoffice desktop editors for editing and collaboration. Now one can only use a built-in online editor, which is not very convenient and doesn't support shortcuts, offline editing and so on.

**Comment by VladimirProkofiev52** [comment]
Hello!, @pablomedok, I created enhancement 58969 in our private enhancement tracker. 
Thank you for report.

**Comment by VladimirProkofiev52** [comment]
@pablomedok, at the moment we do not have the technical ability to implement your request.
As soon as our specialists implement your request, we will inform you.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
