### ISSUE TITLE
PDF and PDF/A export from .PPTX does not preserve external Internet hyperlinks

### ISSUE THREAD

**Issue by eSavior** [ONLYOFFICE/DesktopEditors#1014]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.1.1

### Expected Behavior

When I export a PDF or PDF/A version of a presentation, I expect the hyperlinks to be clickable and to go to the reference hyperlink when clicked from the exported PDF file. This works properly in Apache OpenOffice.

### Actual Behavior

The PDFs that are exported do appear to be clickable, but when they are clicked or the links are attempted to be copied, the links contain no references and do nothing when clicked (from the macOS "Preview" application).

### Reproduction Steps

- Create a slide with some text. 
- Make the text a hyperlink to your favorite cat video on your favorite video streaming service (or whatever). 
- Export the presentation as a PDF or PDF/A file. 
- Open the PDF file in the macOS Preview application and (attempt to) click the link

**Comment by ShockwaveNN** [comment]
Hi to be sure - could you open resulting pdf files in some other apps, which can view PDF - like Google Chrome or LibreOffice viewer (I see that you've checked OpenOffice, but not sure that it's updated regularly and alive as product)

**Comment by eSavior** [comment]
Good call. The PDF links *do* open in other apps. Found this article on Stack Exchange that says the macOS Preview app is "picky" about what the link encoding looks like:
https://apple.stackexchange.com/questions/195716/preview-disables-clickable-links-in-pdf-files

Apparently this can be solved on the OnlyOffice side if they create the links in a format that satisfies the Preview app's pickiness.

**Comment by eSavior** [comment]
Oh...I didn't mention in the original report that the links don't work when you open the PDF in the OnlyOffice PDF viewer, either...which was the primary reason I assumed that they didn't work at all.  Very interesting :-)

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
