### ISSUE TITLE
Insert ODD section breaks

### ISSUE THREAD

**Issue by lorenzoale** [ONLYOFFICE/DesktopEditors#1019]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hello, 
following the instructions in https://helpcenter.onlyoffice.com/onlyoffice-editors/onlyoffice-document-editor/usageinstructions/sectionbreaks.aspx, I add some content to a document, add a section break odd, add more content and when I print double sided, it prints on both sides (even if it should start a new page). 
If I add the page number it shows the correct page number but it does not show or print the page number 2.
Is it the right behaviour or am I missing something?
Thanks in advance, 
Alejandra

**Comment by XDmitryK** [comment]
@lorenzoale Hi
I did not quite understand you, but in most cases it all depends on what settings you print. You can describe in more detail and attach a screenshot to pinpoint the problem

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
