### ISSUE TITLE
[Feature] Support SVG image files

### ISSUE THREAD

**Issue by blaggacao** [ONLYOFFICE/DesktopEditors#102]
As a Corporate Identity professional,
I want to issue cross platform compatible high resolution (somewhat scriptable) letter heads,
I chose SVG.

In my quick review an imported SVG image was displayed as a object block (red cross)

**Comment by ShockwaveNN** [comment]
Seems like a good idea, created and issue in our private bug tracker (#37564)

**Comment by lePereT** [comment]
Hey! Any word on this feature?

**Comment by ShockwaveNN** [comment]
@lePereT Hi, sorry no news, currently it's not high priority task

**Comment by donalturrentine** [comment]
Bump!

**Comment by simon511000** [comment]
I hope this feature will be added someday

**Comment by parrenin** [comment]
I just to post a workaround.
OnlyOffice Desktop Editors seem to well support the .emf format (Windows Metafile).
And with Inkscape, you can transfer a .svg image into a .emf image.

**Comment by blaggacao** [comment]
I reached a state of git backed markdown and pandoc empowered publishing workflow for everything. It makes more sense and has easy to handle metadata.

**Comment by xyont** [comment]
> I just to post a workaround. OnlyOffice Desktop Editors seem to well support the .emf format (Windows Metafile). And with Inkscape, you can transfer a .svg image into a .emf image.

i tested for OnlyOffice latest verions (Win10 64bit) and it's displayed normally after insert image commands, but the problems comes with printing and reopening the document.

**Comment by pwnoobz** [comment]
I just tried adding an ".SVG" image and figured it wouldn't happen. What can we possibly do to emphasize the importance of the feature?

**Comment by ShockwaveNN** [comment]
@pwnoobz Sorry, nothing we can do here. Best way is to contact sales@onlyoffice.com

**Comment by parrenin** [comment]
I wanted to post an update of this issue as of OO 7.3.0.
It is possible to insert an SVG image in Microsoft Office and then the created .docx file will open and display correctly in OO and you can modify the file without loosing the image.
So it seems SVG is somehow supported in OO, yet it is not yet possible to directly insert an SVG image within OO.
I am wondering why there still is this limitation.

**Comment by risacher** [comment]
@parrenin I suspect what happens is that MS Office stores it as an SVG internally, but also with a rastered preview, and OO is showing the rastered preview.

**Comment by Gingetsu** [comment]
Hello, @parrenin! In the server version this is true support of SVG graphics, but for the desktop it will get better in the hotfix.

**Comment by Rita-Bubnova** [comment]
DesktopEditors v7.5.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by SohnyBohny** [comment]
svg works perfectly if I edit a local presentation in the DesktopEditor. However, if I try to edit a document in nextcloud (via the DesktopEditor) there is no svg support.

Both my local DesktopEditor and the one running behind nextcloud are on version v.8.0.1.31

**Comment by Gingetsu** [comment]
Hello, @SohnyBohny! Create a new issue, please.
