### ISSUE TITLE
The spell check is not working (no underlined misspelled words) when working on OpenXML (.docx) documents in french created with MS Word

### ISSUE THREAD

**Issue by therealrem** [ONLYOFFICE/DesktopEditors#1021]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

ONLYOFFICE Desktop Editors version 7.1.1.57

### Expected Behavior

When working on an OpenXML (.docx) file, OnlyOffice Desktop Editor's spell checking should work as expected (i.e. underline misspelled words) regardless of the application that created the file (Word or OnlyOffice).

### Actual Behavior

When working with OnlyOffice Desktop Editor in Linux Mint Debian Edition v5 on an OpenXML (.docx) file created with Microsoft Word for MS 365 (Version 2208 Build 16.0.15601.20148 - 64 bit - on Microsoft Windows 10 x64 22H1), OnlyOffice Desktop Editor's spell check does not work (i.e. that is, no misspelled words are underlined). Operating systems, applications and content are all in French.

In constrat if I copy this content (the one from the "Word" file) into a new "OnlyOffice" file, the spelling checker works correctly. Same thing if I create a new file from scratch with OnlyOffice : the spelling checker is working as expected.

### Reproduction Steps

1. Create a .docx file with Microsoft Word in french. Test the spell checker (it is working).
2. Open the same file with OnlyOffice Desktop Editor : the spell checker is not detecting misspelled words.

### Additional information

I *assume* that this problem is somehow related to French but I'm not sure. I can't remember if I encountered this bug before, nor from which version it appeared.

**Comment by ShockwaveNN** [comment]
Could you attach file you've using? Maybe you didn't select language correctly in spellchecker settings or something like this, so we need file

**Comment by therealrem** [comment]
Hello,

Thanks for your assistance

Here is an example file (with two words in french, the first is correct and the second is misspelled). The file has been created with MS Word under Windows 10. I can create as many example files as I want. All I have to do is create a new file from Word then opening it with OnlyOffice.
[Exemple.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/9593251/Exemple.docx)


I can confirm that the spellchecker has been enabled and the selected language is french.
[Exemple.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/9593255/Exemple.docx)

**Comment by therealrem** [comment]
Screenshots
![Spellcheck not working with OnlyOffice](https://user-images.githubusercontent.com/113786459/190890901-1150eae3-766d-4ce4-a827-39ecb274d616.png)
![Spellcheck working with MS Word](https://user-images.githubusercontent.com/113786459/190890902-c1d912bc-b705-4014-a478-8da9b8a6444c.png)

**Comment by ShockwaveNN** [comment]
Your document has `Frence (Belgian)` language

![image](https://user-images.githubusercontent.com/668524/190890868-a1d2af72-f9d7-4bdd-ac32-7ba307a54959.png)

We do not support spellchecker in belgian variation in french (you can see spellcheck-support languages in list of lang, lines that have (abc icon)

If you change doc lang to `France (France`) spellchecker will work

![image](https://user-images.githubusercontent.com/668524/190890887-051105cd-ddd2-4dbd-b6de-11dee0af63f3.png)

**Comment by therealrem** [comment]
Sorry... it is still not working despite the document language has been switched to Français (France)
See by yourself :
![Spellcheck still not working with OnlyOffice with Français (France)](https://user-images.githubusercontent.com/113786459/190890988-980d0119-70b8-4a7b-95b1-8f067f72a25d.png)

**Comment by ShockwaveNN** [comment]
You change text language, document language change by icon with globe to the right of `France (France)` text line

**Comment by therealrem** [comment]
Oups, yes, my bad. Problem solved !

Thank you for your kind assistance Sir.

**Comment by ShockwaveNN** [comment]
Glad to help you
