### ISSUE TITLE
Ctrl + V don't paste image in document editor (in other editors same behaviour)

### ISSUE THREAD

**Issue by SirDK** [ONLYOFFICE/DesktopEditors#1025]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.2.0.204

### Expected Behavior

Copy image into clipboard. Ctrl + V hotkeys in document editor paste copied image.

### Actual Behavior

Image was copied. Ctrl + V in document editor paste file system path to image in format: file:///home/$USER/Download/image.jpg

### Reproduction Steps

1. Copy image in any way;
2. Paste with Ctrl + V in document editor.

### Additional information

Operating System: openSUSE Tumbleweed 20220922
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.5
Kernel Version: 5.19.8-1-default (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8265U CPU @ 1.60GHz
Memory: 11.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
System Version: 1.0

**Comment by Rita-Bubnova** [comment]
@SirDK  Sorry for late restonse, seems we missed this issue.
DesktopEditors v7.4.1 is released. Please state is this problem still actual for you?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
