### ISSUE TITLE
The French word "aujourd'hui" is underlined as incorrect by the spell checker

### ISSUE THREAD

**Issue by echanaron** [ONLYOFFICE/DesktopEditors#1026]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.1.1.57

### Expected Behavior

The French word "aujourd'hui" is properly recognized.

### Actual Behavior

The French word "aujourd'hui" (which means "today", obviously a very very very common word) is red underlined as miswritten by the spell checker. Maybe it's because of the apostrophe in the middle?

### Reproduction Steps

Always

**Comment by Rita-Bubnova** [comment]
@echanaron, Sorry for the long wait.
DesktopEditors v7.4.1 is released. Is this issue relevant?

**Comment by echanaron** [comment]
Not anymore. It has been corrected.
Thanks for asking! :smiley:

**Comment by Rita-Bubnova** [comment]
@echanaron Thank you for response. 
It's good news!
