### ISSUE TITLE
MacOs: Can't type special characters in Dokuments (7.1 and 7.2)

### ISSUE THREAD

**Issue by spreeni151** [ONLYOFFICE/DesktopEditors#1028]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.2

### Expected Behavior

Hello,
I'm using OnlyOffice 7.x on my Macbook (Apple Silicon with the latest updates). After updating from 7.01, I noticed that special characters are not displayed in any OnlyOffice documents when typed. For example, if I want to type the "@" character, nothing is shown when I press [option]+[L]. 
I went back to OnlyOffice 7.01 wich is working without problems (with working special character types). I'm trying OnlyOffice 7.2 now and there is still the issue with special characters not working.
Can anyone confirm that behavior?
Regards, Frank

### Actual Behavior

please look at "expected behavior"

**Comment by Gingetsu** [comment]
Hello, @spreeni151. Could you tell me the keyboard language, please?

**Comment by spreeni151** [comment]
Hi Gingetsu, 
I'm using german keyboard language.

**Comment by Gingetsu** [comment]
@spreeni151, we know about this behaviour. We discuss this issue with our development team (issue 58111 and 59171 in our internal issue tracker). Thank you for report.

**Comment by spreeni151** [comment]
you're welcome - and thanks for the explanation.

**Comment by spreeni151** [comment]
Just an update: The bug seems to be fixed in the latest version 7.2.1.  :-)
Thank you very much!

**Comment by ShockwaveNN** [comment]
@spreeni151 Thanks for checking, but seems not all the edge cases are fixed so I'll leave this issue opened until developers confirm that it's all possible cases are OK

**Comment by DenisDeeSign** [comment]
Since version is released I close this issue. Feel free to comment or reopen it if you got further questions.
