### ISSUE TITLE
No desktop icon and start menu entries after install the onlyoffice using msi installer

### ISSUE THREAD

**Issue by kenifanying** [ONLYOFFICE/DesktopEditors#1033]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.0.204

### Expected Behavior

Get desktop icon and start menu entries after install the onlyoffice using msi installer

### Actual Behavior

No desktop icon and start menu entries after install the onlyoffice using msi installer

### Reproduction Steps

1.  Install the onlyoffice using msi installer
2. check desktop icon and start menu entries

### Additional information

OS: Windows 11

**Comment by DAumkraft** [comment]
Hello, @kenifanying!
I can't confirm your scenario. In my tests, shortcuts are created
I need more information.
1. What language is used in your OS?
2. Do you install applications using GUI?
3. Does the user have administrator rights?
4. Is there a folder in the Start menu named "Property.SHORTCUT_FOLDER_NAME" after installation?

**Comment by kenifanying** [comment]
> Hello, @kenifanying! I can't confirm your scenario. In my tests, shortcuts are created I need more information.
> 
>     1. What language is used in your OS?
Simplified Chinese
> 
>     2. Do you install applications using GUI?
Yes, the only thing I changed  was disable all file types association
> 
>     3. Does the user have administrator rights?
Just double click it and get administrator rights
> 
>     4. Is there a folder in the Start menu named "Property.SHORTCUT_FOLDER_NAME" after installation?
no

This is the file I used.  https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v7.2.0/DesktopEditors_x64.msi

**Comment by DAumkraft** [comment]
Thank you @kenifanying!
I will check and let you know the results.

**Comment by ShockwaveNN** [comment]
Closing this issue since DesktopEditors v7.2.1 are released
