### ISSUE TITLE
Open file a little bit lower than Microsoft Office 365 or WPS Office

### ISSUE THREAD

**Issue by zenfas** [ONLYOFFICE/DesktopEditors#1036]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2

### Expected Behavior

Open file (word or excel) faster, at least similar to Microsoft Office 

### Actual Behavior

Open file a little bit lower than Microsoft Office 365 or WPS Office on the same computer 

### Reproduction Steps

Open any office file

**Comment by ShockwaveNN** [comment]
Sorry, I don't think we can diagnose this issue without specific file

And yes, we can be a little slower since MS office and WPS office use completely different engine

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
