### ISSUE TITLE
[Feature] True letterhead support

### ISSUE THREAD

**Issue by blaggacao** [ONLYOFFICE/DesktopEditors#104]
As a corporate identity professional I want to generate documents with true letterhead support, meaning that:

- It will by default scale to the paper format (not anything else, like page or header something really annoying in LibreOffice)
- It will have a menu-based workflow of incorporating it
- The letter head graphic can be protected
- The letter head graphic is not selectable by the end user on the normal canvas just by clicking on a white space (background), even if not protected. (therefore menu-backed configuration)
- The letterhead graphic is only printed on digital documents. see #101

**Comment by KirillovIlya** [comment]
The only way to protect anything in DOCX  - it's an encryption. So you will have to create a password for each document.
There is no other way to protect anything in DOCX format, since it's not a graphical format of a file like PDF.

**Comment by blaggacao** [comment]
I understand this is a limitation of the DOCX format itself, so I'll close.

**Comment by blaggacao** [comment]
I think https://github.com/ONLYOFFICE/DesktopEditors/issues/100#issuecomment-383857376 solves this kind of...
