### ISSUE TITLE
Radio button group functionality broken in PDF form

### ISSUE THREAD

**Issue by mosquitomeal** [ONLYOFFICE/DesktopEditors#1041]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.0.204

### Expected Behavior

One group should only have one radio button selected. If there are options A, B, and C, and I select A first, then change my mind and select B, then A should be deselected automatically.

### Actual Behavior

 If there are options A, B, and C, and I select A first, then change my mind and select B, then A remains selected and B becomes selected too!

### Reproduction Steps

1. Open form template in DesktopEditors
2. Add three radio buttons
3. Make sure they all belong to the same group
4. Save as PDF or PDF /A
5. Open PDF in favorite editor (I use atril)
6. Select first radio button, then second, then third. They should be seen as behaving like checkboxes....

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
