### ISSUE TITLE
Saving a file in .ods format creates incompatibilities with LibreOffice: "The data could not be loaded completely because the maximum number of columns per sheet was exceeded."

### ISSUE THREAD

**Issue by wonx** [ONLYOFFICE/DesktopEditors#1044]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.2.5

### Expected Behavior

Onlyoffice should be able to save documents in .ods (libreoffice calc) format without compatibility issues. However, every time a .ods file is modified from Onlyoffice, a warning is displayed.

It happens after either editing an existing .ods file, or creating a new one from scratch.

### Actual Behavior

This warning message appears upon opening the spreadsheet with LibreOffice¨

`The data could not be loaded completely because the maximum number of columns per sheet was exceeded.`

![Screenshot_20221010_160852](https://user-images.githubusercontent.com/2736639/194944432-419dba79-b49c-48ec-be49-17f7850ab8d3.png)

### Reproduction Steps

1. Open ONLYOFFICE, create a spreadsheet (with any content), and save it in .ods format.
2. Open that spreadsheet with LibreOffice Calc.

**Comment by ShockwaveNN** [comment]
Hi, which version of LibreOffice you're using?

**Comment by wonx** [comment]
Hi,

Libreoffice 7.3.6.2

**Comment by ShockwaveNN** [comment]
Oh, seems I've missed that you've using DocumentServer 7.0.2
You should update to v7.2.0 and recheck it, because I've never heard that anyone has similar error

**Comment by ShockwaveNN** [comment]
I've checked your issue with empty spreadsheet file created in DesktopEditors v7.2.0 and saved to ods and open in LibreOffice calc v7.4.1.2 - there is no errors

Maybe update LibreOffice? I'm using latest stable version

**Comment by Rita-Bubnova** [comment]
@wonx, DesktopEditors v7.4.1 is released. Is this issue relevant?

**Comment by wonx** [comment]
Hi. Yes, I tested with version 7.4.1.36, and I get the exact same error.

**Comment by rsnegirev** [comment]
Hi @wonx 

I've tried to reproduce this behavior with ONLYOFFYCE 7.4.1.36 and LibreOffice 7.6.0.3 and didn't get any error or warning message.

Can you please provide more detailed reproduction steps and example file?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
