### ISSUE TITLE
pptx: An error occurs when selecting multiple lines

### ISSUE THREAD

**Issue by Themistoklis** [ONLYOFFICE/DesktopEditors#1049]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.2 (534)

### Expected Behavior

I select text of mixed font size in a pptx slide and I get that error:
<img width="428" alt="Screenshot 2022-10-13 at 13 57 38" src="https://user-images.githubusercontent.com/5711602/195590026-3c704822-810d-4dec-b23f-27cc2f36c47b.png">

I haven't tried older versions.

### Actual Behavior

I should be able to select the text without that error.

### Reproduction Steps

Open this document and select the main text on slide 2 (v7.2 tested on Mac desktop editor and document server editor):

[test.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/9776348/test.pptx)

### Additional information

This bug also happens with the document server.

**Comment by ShockwaveNN** [comment]
I think it's a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1917#issuecomment-1276303918

**Comment by Themistoklis** [comment]
Good catch forgot to look at the document server issues.
