### ISSUE TITLE
Find and replace does not search through numbering in headings and table of contents

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1051]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.0.204

### Expected Behavior

My expectation is that headings and the generated table of contents are taken into account while a user is trying to find certain number automatically assigned to a heading.

### Actual Behavior

Currently OpenOffice doesn't allow to search through these numbers.

### Reproduction Steps

Have a document with a few numbered headings.
`Ctrl`-`F`, try searching for their numbers.

### Additional information

<img width="104" alt="OO-Search-1" src="https://user-images.githubusercontent.com/64358003/195923041-69eb6d06-f31e-4eb1-b2f0-d86cf019d574.png">
<img width="185" alt="OO-Search-2" src="https://user-images.githubusercontent.com/64358003/195923059-ee407e50-6a9e-4d4f-839f-d526476dd17d.png">

**Comment by Rita-Bubnova** [comment]
@HectorB-2020, Sorry for late restonse, seems we missed this issue
DesktopEditors v7.4.1 is released. Please state is this problem still actual for you?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
