### ISSUE TITLE
`Ctrl`-`C` `Ctrl`-`V` fails to insert text content between different document tabs

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1052]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.0.204

### Expected Behavior

The copied text is pasted into the current (active) document tab.

When an arbitrary user switches to certain document tab, he/she sees a blinking cursor. So it's obvious for users that having pressed `Ctrl`-`V` inserts text in that exact place of the document.

### Actual Behavior

The behavior vary. 

The worst example is when `Ctrl`-`V`pastes the same content into previous document tab from which the text had been just copied.
User is usually not aware that `Ctrl`-`V` worked in the previous document tab. She/he can keep pressing `Ctrl`-`V`, hoping that finally Only Office will've inserted the desired text into the current document tab. The cursor is blinking here, isn't it? While the same text is being inserted again and again. 
Imagine her/his surprise when they finally switched back to the the previous document tab to find numerous text lines they've just pasted.

### Reproduction Steps

1. Start Only Office, create/open a couple of documents in each tab.
2. Highlight and copy (`Ctrl`-`C`) some text in the first document.
3. Switch to the second document tab.
4. Watch that a cursor is already located somewhere in text but don't click anywhere in the document tab to point cursor to new place. Let's assume that cursor has been already in the right place where we left it before.
5. Press `Ctrl`-`V` or `Shift`-`Insert`.
6. Witness that the desired text is not inserted to the second document.
7. Check the _first_ document tab. It can be still unmodified or the copied text has been added there as many times as you pressed `Ctrl`-`V` in the _second_ document tab.

**Comment by VladimirProkofiev52** [comment]
@HectorB-2020 Hello!

I see problems with pasting in version 7.2.0.204

We recently released an updated version of the app 7.4.1.36.

In the new version, I could not repeat the problem according to your scenario.

Please update our desktop editor on your computer and try to reproduce the issue again.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
Feel free to comment or reopen it if you got further questions.
