### ISSUE TITLE
CTRL+N does not create a new file

### ISSUE THREAD

**Issue by guilamu** [ONLYOFFICE/DesktopEditors#1054]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

All

### Expected Behavior

When pressing CTRL+N a brand new file/sheet is created and opened (like in any other app).

### Actual Behavior

When pressing CTRL+N nothing happens.

### Reproduction Steps

1. Open any only office app
2. Press CTRL+N
3. Nothing happens

**Comment by HectorB-2020** [comment]
I believe that was asked some time ago, see #200

**Comment by guilamu** [comment]
> I believe that was asked some time ago, see #200

Oh, indeed. Is this some incredibly hard to code feature or has it just been ignored for 4 years?

**Comment by ShockwaveNN** [comment]
Closing this as duplicate
