### ISSUE TITLE
Cannot start OnlyOffice Editors (the launcher) when other OO windows are open.

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1058]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.0.204

### Expected Behavior

When the initial application launcher "OnlyOffice Editors" is not running it should start when a user clicks on its icon.

### Actual Behavior

The opposite: OnlyOffice Editors, the launcher, does not start when other OO editors are open.

### Reproduction Steps

Ensure this setting is used: Open file: `In its own window`.
Open a few documents, they are to open in their own windows as demanded in the previous step.
Close the application launcher.
Try staring it again from menu or a desktop icon.

**Comment by Rita-Bubnova** [comment]
Hello, @HectorB-2020. 
Thanck you for report. 
I can confirm - this is bug, issue 59469 in our private issue tracker.

**Comment by HectorB-2020** [comment]
Here is another scenario.
A user clicks on an attachment in email. It opens Document editor.
And until this editor window is closed, it's impossible to start any other OnlyOffice application unless it's opened likewise from an email attachment.

**Comment by Rita-Bubnova** [comment]
DesktopEditors v7.4.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
