### ISSUE TITLE
Numbering using 1. space causes extra tab and gap 

### ISSUE THREAD

**Issue by fastrizwaan** [ONLYOFFICE/DesktopEditors#1061]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2 (mistakenly typed 7.0 earlier)

### Expected Behavior

Just like using Numbering tool button, `1. space` should behave.

### Actual Behavior

Tab and Gap between number and text.

### Reproduction Steps

1. New Document
2. type "1. space"

### Additional information

Bug in action:
![numbering-bug](https://user-images.githubusercontent.com/1161682/196348258-15ba67de-2d22-4361-bfe2-a9185d66666c.gif)

**Comment by ShockwaveNN** [comment]
Hi, could you update to the latest v7.2

I've check and typing `1.{space}` in empty doc create a numbered list

**Comment by fastrizwaan** [comment]
![image](https://user-images.githubusercontent.com/1161682/196611489-fc5e246a-8986-406a-9f54-b1c4e803da72.png)

I'm using 7.2

**Comment by TatianaKirillova** [comment]
Hey, @fastrizwaan!

Do you have this problem again on version 7.4.0?

**Comment by fastrizwaan** [comment]
7.4.0.163 (flatpak)

Fixed.

**Comment by fastrizwaan** [comment]
Closing as it is fixed. Thanks.
