### ISSUE TITLE
Euro sign (€) and others with alt not working on Mac OSX spreadsheets

### ISSUE THREAD

**Issue by arnauvp** [ONLYOFFICE/DesktopEditors#1065]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.2 (534) x86_64

### Expected Behavior

The Euro sign can be normally typed on spreadsheet cells without the need of insert symbol or any other workaround.

### Actual Behavior

Nothing is typed with Alt+E

On the Mac version of OnlyOffice desktop editor (*), it is not possible to enter the euro sign (€) on a spreadsheet, as it uses the alt+E key combination - French and Spanish keyboards. This used to work on the desktop app version 7.0, and broke after updating to 7.2 534 x86_64 in my case (unsure about the intermediate versions). 

* also happening on OnlyOffice community server (docker) and any Mac OS browser.

ONLYOFFICE_COMMUNITYSERVER_IMAGE_TAG=12.0.1.1748
ONLYOFFICE_DOCUMENTSERVER_IMAGE_TAG=7.1.1

### Reproduction Steps

1. create a spreadsheet
2. type alt (option) + E in a cell. Left Alt brings
3. nothing is printed
4. if left option is used, the hotkey shortcut hints appear in yellow.

**Comment by Gingetsu** [comment]
Hello, @arnauvp! We know about this behaviour. We discuss this issue with our development team (issue 59171 in our internal issue tracker). Thank you for report.

**Comment by maruacat** [comment]
Hello, @arnauvp 
Thanks for waiting!
I have good news, we have fixed the problem and in the latest release version - 7.3.3 of the desktop editor and DocumentServer, you can use the following keyboard shortcuts to add the euro symbol to documents, presentations and spreadsheets:
- Spanish layout - option + e
- French layout - option + $
Thanks for your feedback and have a nice day!
