### ISSUE TITLE
Only Office dies compleatly on calculating sumifs with isoweek(range)

### ISSUE THREAD

**Issue by Codeleiche** [ONLYOFFICE/DesktopEditors#1066]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.1.1

### Expected Behavior

when using =SUMIFS(Sheet!$S$3:$S$500;ISOWEEKNUM(Sheet!$R$3:$R$500);30) I should get all values added up that are from week 30 or an error.

### Actual Behavior

Only office dies and I have to kill every process with an htop sudo session

### Reproduction Steps

- build a sheet with the name Sheet and fill range S3:S500 with numeric data and range R3:R500) with dates. 
- add a new sheet and enter the formula:
=SUMIFS(Sheet!$S$3:$S$500;ISOWEEKNUM(Sheet!$R$3:$R$500);30)

### Additional information

I did try the same formula in Openoffice and google sheets.

**Comment by ShockwaveNN** [comment]
Hi, could you check the same problem in the current stable v7.2.0? I think we made some improvements, but not 100% sure that this issues is fixed

**Comment by Rita-Bubnova** [comment]
DesktopEditors v7.4.1 is released. 

This issue was closed due no response.
