### ISSUE TITLE
Crash to desktop when printing PDF to physical printer

### ISSUE THREAD

**Issue by jack0tr** [ONLYOFFICE/DesktopEditors#1068]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.0.204

### Expected Behavior

print the PDF file after selecting the printer.
only tested on version 7.2.0.204
tested on desktop and laptop, both windows 10, with different PDF files, on different printers, and with no printer at all.

### Actual Behavior

after selecting the printer on the pop up window and clicking ok, when the message says it's printing (i.e. "printing 1 of 4"), it crashes onlyoffice

### Reproduction Steps

1.- open any pdf file with images
2.- select to print the file
3.- select printer and click ok

### Additional information

after further testing the only way to print from the pdf is if the file is only text, if it has any image it crashes. 
this is somethin like issue #1029, but that was an xlsx file, an as that issue was on linux i was advised to post as a different issue.
i attached 2 file for test, 1 only text and one with images.
[document1.pdf](https://github.com/ONLYOFFICE/DesktopEditors/files/9831513/document1.pdf)
[test.pdf](https://github.com/ONLYOFFICE/DesktopEditors/files/9831514/test.pdf)

**Comment by VladimirProkofiev52** [comment]
Hello.
@jack0tr , I can confirm - this is a bug, issue 59161 in our private tracker.
We aware of this bug and it will not be in the next version of our editor.
Thanks for the report.

**Comment by VladimirProkofiev52** [comment]
@jack0tr, We have released a new version of ONLYOFFICE Desktop Editors version 7.2.1.36.
You can upgrade to version 7.2.1.36.
It fixes your problem.

**Comment by ShockwaveNN** [comment]
Closing this issue, the problem should be resolved in v7.2.1

**Comment by jack0tr** [comment]
it works great now, thanks a lot!
