### ISSUE TITLE
[Feature] Line Numbers

### ISSUE THREAD

**Issue by unsocialwhoyou** [ONLYOFFICE/DesktopEditors#107]
There needs to be a way to put line numbers on the document. This is the one thing that prevents me using OnlyOffice.

**Comment by ShockwaveNN** [comment]
@unsocialwhoyou Thank you, we think about this, issue 37107 in our private issue tracker

**Comment by parrenin** [comment]
Meanwhile, would it be possible to preserve the line numbers when working with a .docx file?
I would make easier the collaboration with MS Office users.

**Comment by ShockwaveNN** [comment]
This feature is implemented in https://github.com/ONLYOFFICE/web-apps/commit/db7d0d1e363456a09872797a9f76d2dc44a90237
And was released in v6.1.0
