### ISSUE TITLE
Document Viewer dark mode improvements

### ISSUE THREAD

**Issue by LeBrick-Studio** [ONLYOFFICE/DesktopEditors#1072]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

- [ ] In addition to the "Dark document" setting, add an option to forcefully invert and hue-rotate **all** the images in the document, off by default. The current system seems to only work with text and some vector graphics but not the regular images, which breaks the dark mode when used with scanned books and converted/poorly designed documents:
![изображение](https://user-images.githubusercontent.com/93297305/197805032-f4f14c43-9739-4737-b8e3-0ad364c14cfc.png)
![изображение](https://user-images.githubusercontent.com/93297305/197805483-252b180e-cf9b-4ffb-ae91-c45daed57b99.png)
![изображение](https://user-images.githubusercontent.com/93297305/197805759-fdf229c0-903e-4786-901a-6bb5f4b0ba02.png)

- [ ] The dark view page colour doesn't fit with the rest of the "Dark Contrast" theme, and should be darker.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/93297305/197810258-7dd1fe0a-77ce-483e-a4ee-fef5c62d002d.gif)

- [ ] Page loading uses the light placeholder despite the dark theme ON, which is... _not very funny_, especially when you're reading some document at 3AM.
![изображение](https://user-images.githubusercontent.com/93297305/197806261-8854b5bf-a4de-4c11-b12b-79851eb962fa.png)

**Comment by ShockwaveNN** [comment]
Hi, could you split those 3 unrelated tasks into new issues, it's hard to track issues if the different problems (although related to Dark mode) are in a single issue

**Comment by LeBrick-Studio** [comment]
Done!

#1077, #1078, #1079
