### ISSUE TITLE
Keyboard shortcuts don't work after opening documents

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1074]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36

### Expected Behavior

Shortcuts like `Ctrl`-`F` or `Ctrl`-`H` should work right after document are opened. Clicking inside the document should not be required.

### Actual Behavior

Quite often they don't. Pressing `Ctrl`-`F` or `Ctrl`-`H` in freshly opened documents with content don't cause any expected dialogs until user explicitly clicks somewhere to the document.
Seems like focus is not set inside editor.

### Reproduction Steps

This doesn't happen in 100% cases.
Usually I face such behaviour in documents which I haven't touched for a while. Maybe they document which I never opened with OnlyOffice.
Interestingly, once I've opened a document in OnlyOffice and manually positioned cursor inside, all other consequential attempts work as expected - `Ctrl`-`F` or `Ctrl`-`H` raise appropriate small dialogs.

I guess this might be related to other issues: #1052 and #921.

**Comment by HectorB-2020** [comment]
I noticed that this behaviour is observed after playing with editor's window size: try 'restore' or 'maximize'.
After this change the editor loses focus and I can neither use shortcuts nor even type text.

**Comment by maruacat** [comment]
Hello @HectorB-2020  
Sorry for the long wait. I was able to reproduce the issue of losing focus after resizing the window in version 7.2.1.36, but this issue does not reproduce in the latest version 7.4.1.36.
Could you tell me if this problem is reproduced in version 7.2.1.36?
Thank you for your submission.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
