### ISSUE TITLE
Ability to run several instances of DesktopEditors

### ISSUE THREAD

**Issue by kabeersvohra** [ONLYOFFICE/DesktopEditors#108]
As above

**Comment by ShockwaveNN** [comment]
Try to run it from terminal via `desktopeditors` command and show output

**Comment by kabeersvohra** [comment]
![image](https://user-images.githubusercontent.com/5859986/39634533-fbf74486-4fb2-11e8-9862-619ce31bf83a.png)

**Comment by kabeersvohra** [comment]
when trying to open a new window after the first one has been opened, I get that error

**Comment by Rita-Bubnova** [comment]
Hello, @kabeersvohra.
Thank you. I can confirm - this is a bug, issue 37664 in our internal issue tracker.

**Comment by maxkadushkin** [comment]
multi window mode still locked, but in development. it'll be available in near releases

**Comment by nath5394** [comment]
Do you have any update about that ? 
It would be very useful to be able to have one window per doc.

**Comment by ewscott9** [comment]
I'm interested in an update as well. So far I love this document editor, the only thing that seems to be holding it back it the lack of being able to use multiple windows.

Keep up the great work on this project!

**Comment by dc46and2** [comment]
As of v7.0.0.127, I'm still unable to open a second instance or window via the command line or via the Gnome application launcher, but I did find a work-around that might help others. When a document is open, you can grab the tab at the top with the mouse and drag it. This will move the tab to a new window.

**Comment by bmalynovytch** [comment]
Feature seems to be available for Windows user, but still absent for macos.
