### ISSUE TITLE
Spreadsheet: Additional visibility is needed when a filter is used in a column.

### ISSUE THREAD

**Issue by sigulete** [ONLYOFFICE/DesktopEditors#1084]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I would like to request the implementation of a better visibility when a column is filtered.

On one hand, the columns that are using filters should be easier to spot. Maybe adding a color to the filter widget.
Another useful functionality would be to change the color of the row numbers when a filter is being used.

The above is particularity useful (and important) when dealing with large spreadsheets with over a hundred columns. If someone set a filter, it is quite time consuming to find the column that is filtered. So by first knowing in advance that there is a filter somewhere (row numbers have a different color), and highlighting the column that is filtered, it would improve a lot the usability.

**Reference:** Please look at the latest version of WPS as an example of this feature.

**Comment by VladimirProkofiev52** [comment]
@sigulete1 Hello! 
I couldn't find the required functionality in WPS.
Please send a screen recording or a more detailed description of the requested function.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
