### ISSUE TITLE
Columns size is not being saved

### ISSUE THREAD

**Issue by RDKRACZ** [ONLYOFFICE/DesktopEditors#1087]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.1.0.215

### Expected Behavior

The size of columns should save

### Actual Behavior

I was not able to reproduce this issue in LibreOffice and **it is specific only to this one file** https://anonfiles.com/67Pdo4Fdya/ILO_PACZEK_ods

Every time I change the size of columns and save the file it changes when I reopen this file.

### Additional information

I'm using an older OnlyOffice version since I don't have admin rights on this company device. The software is updated once a year... If this bug is already fixed in a newer version please let me know.
Maybe related to bug #42790?

**Comment by ShockwaveNN** [comment]
I've rechecked this issue on latest stable version (v7.2.1) and it seems fine, after reopening file - column width is saved

![image](https://user-images.githubusercontent.com/668524/198985344-99bbed42-2a4c-469e-ab82-bbfb719f318e.png)

I'm not 100% sure that we fixed that bug, so please check on another computer with latest version and reopen this issue if problem still occurs with you, and attach some video
