### ISSUE TITLE
macos: keyboard shortcut add cell/row not working

### ISSUE THREAD

**Issue by hoare** [ONLYOFFICE/DesktopEditors#1089]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.2.1 (535) Apple Silicon

### Expected Behavior

when pressing Ctrl+⇧ Shift+= i would expect a pop up on how to insert cells, but nothing happens.

delete on the other hand works.

similar to: https://github.com/ONLYOFFICE/DocumentServer/issues/1972
see my comment there.

From the doku: https://helpcenter.onlyoffice.com/onlyoffice-editors/onlyoffice-spreadsheet-editor/helpfulhints/keyboardshortcuts.aspx

<html><head></head><body>

Insert cells | Ctrl+⇧ Shift+= | Open the dialog box for inserting new cells within current  spreadsheet with an added parameter of a shift to the right, a shift  down, inserting an entire row or an entire column.
-- | -- | --
Delete cells | Ctrl+⇧ Shift+- | Open the dialog box for deleting cells within current  spreadsheet with an added parameter of a shift to the left, a shift up,  deleting an entire row or an entire column.

</body></html>

### Actual Behavior

nothing

### Reproduction Steps

open new spreadsheet
add text to a1
press the keyboard shortcut control shift =

**Comment by Gingetsu** [comment]
Hello, @hoare! I checked it in Spreadsheet Editor versions 7.2.1 macOS 12.5.1 (21G83) and it works for the English keyboard layout. Could you tell me which keyboard layout you are using?

**Comment by Gingetsu** [comment]
We know about this behaviour. We discuss this issue with our development team (issue 59171 in our internal issue tracker). Thank you for report.

**Comment by maruacat** [comment]
Hello @hoare
I have great news. We've fixed this bug https://github.com/ONLYOFFICE/web-apps/commit/5fb08b30bbda1fc616523b67121ab3697fe9d9df and you should be able to use the keyboard shortcut Ctrl+⇧ Shift+0 ("0" and "=" are placed on the same button on a German keyboard layout) to insert cells into a table in the new version of the editor with a German keyboard layout.
Have a good day!

**Comment by Rita-Bubnova** [comment]
DesktopEditors v7.5.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by hoare** [comment]
Hello @marucat,
works thank you!!
