### ISSUE TITLE
Cannot type Apostrophe, Single Quote or backtick with an US international keyboard layout

### ISSUE THREAD

**Issue by DevPre24** [ONLYOFFICE/DesktopEditors#109]
I'm on Arch Linux + KDE and i'm using onlyoffice 4.8.7.392-1 from the AUR. In order to type accents with an US Keyboard, i set my keyboard layout to US international with dead keys, this way by pressing apostrophe, single quote or backtick on my keyboard followed by a letter i can add an accent to that letter. In order to type the apostrophe or quote i have to press the key on my keyboard followed by the spacebar which escapes from the accent mode. This unfortunately doesn't work on OnlyOffice.

**Comment by Rita-Bubnova** [comment]
Hello, @DevPre.

Could you attach video or gif of problem, so we can reproduce this problem correctly?
Also, please include in this video layout settings.

**Comment by Rita-Bubnova** [comment]
Thank you. I can confirm - this is a bug, issue 37819 in our internal issue tracker.

**Comment by DevPre24** [comment]
Any ETA on the fix? It's very frustrating to have to switch keyboard layout in order to type the aforementioned characters.

**Comment by Rita-Bubnova** [comment]
Sorry, there is no ETA for this problem.

**Comment by DevPre24** [comment]
Doesn't seem to be an OS related issue. I can reproduce the issue on Windows 10.

**Comment by K0R0L** [comment]
Fixed.
https://github.com/ONLYOFFICE/sdkjs/pull/509/commits/3049f81e6aa928ec89ae6c83d4a7f0ce9446cb95

**Comment by ShockwaveNN** [comment]
DesktopEditors 5.3.3 was released. Issue should be fixed
