### ISSUE TITLE
BUG: Horizontal scroll using horizontal scroll wheel affects vertical scrolling too

### ISSUE THREAD

**Issue by S-trace** [ONLYOFFICE/DesktopEditors#1094]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1.36

### Expected Behavior

When using a horizontal scroll wheel (like on Logitech MX Master 3) OnlyOffice Calc should scroll documents only in the left or right direction (depending on the scroll wheel direction).

### Actual Behavior

When using a horizontal scroll wheel (like on Logitech MX Master 3) OnlyOffice Calc scrolls the document not only in the left or right direction (depending on the scroll wheel direction), but also up or down (depending on the scroll wheel direction).

### Reproduction Steps

1. Open OnlyOffice Calc
2. Use the horizontal scroll wheel to scroll the document to the right
3. Note that the document was not only scrolled horizontally by 1 column but also was scrolled vertically by 3 lines

### Additional information

I'm using Manjaro Linux, don't know really which distribution (RPM or DEB) it uses.
Horizontal scrolling in other apps like OnlyOffice Writer, Kate, or Firefox works as expected, without affecting vertical scroll.

**Comment by Rita-Bubnova** [comment]
I think this issue is a duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/536.

**Comment by S-trace** [comment]
Well, will it be fixed soon?

**Comment by S-trace** [comment]
This issue is very annoying(
