### ISSUE TITLE
Empty bullets palette when Navigation menu is active

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1095]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36

### Expected Behavior

The bullets palette must always contain symbols 
![OO-Bullets-Empty2](https://user-images.githubusercontent.com/64358003/199796824-de66b1c4-a711-420c-8b4a-53a68e01f89f.png)

### Actual Behavior

However when the Navigation menu is active on the left, this drop-down selection is empty. It's worth mentioning that the upper right frame in the palette correctly reflects bullet style where cursor is positioned even its symbol is not rendered in the menu.

![OO-Bullets-Empty](https://user-images.githubusercontent.com/64358003/199797176-52b3c9e9-1d32-47df-841e-4620ca2373ac.png)

Reproduced in 100% in Windows version. Didn't work in Linux version though.

**Comment by HectorB-2020** [comment]
@Rita-Bubnova, looks like this issue was fixed, nice job! Thank you!

**Comment by Rita-Bubnova** [comment]
@HectorB-2020, Thank you for answered.
