### ISSUE TITLE
Duplicated numbering in Navigationb menu (Headings)

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1097]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36

### Expected Behavior

Numbers in the navigation menu are unique or at least reflect actual state of headings in the document.

### Actual Behavior

Please find duplicated the redacted screenshot. 2.2.21 is mentioned twice. That hadn't changed until the document was closed.
<img width="232" alt="OO-Nav-Dub1" src="https://user-images.githubusercontent.com/64358003/199813884-6b67a4af-7433-4592-a2fc-ca5d44499a2d.png">
In fact the actual headings in the document have unique sequential number, see below.
<img width="339" alt="OO-Nav-Dub2" src="https://user-images.githubusercontent.com/64358003/199814402-7c033ced-f5b4-4d7f-bb3f-0e3573419b98.png">

After the document has been closed and re-oped, the navigation started showing accurate numbering. No duplicates, see below.
<img width="185" alt="OO-Nav-Dub3" src="https://user-images.githubusercontent.com/64358003/199815060-faab2ebf-e220-425e-81ff-7614874f06d7.png">

**Comment by ShockwaveNN** [comment]
Hi, could you attach this file?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
