### ISSUE TITLE
Corrupted Table of Contents (ToC) on fourth level numbered headings

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1098]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36

### Expected Behavior

The Table of Contents has consistent styles.
<img width="497" alt="OO-ToC4" src="https://user-images.githubusercontent.com/64358003/199821154-a61e2f73-a017-44ac-8b43-bf319995c922.png">
<img width="533" alt="OO-ToC5" src="https://user-images.githubusercontent.com/64358003/199821179-cdf91d39-aef7-414d-9a19-f7683cc5f8fd.png">

### Actual Behavior

Sadly when forth level is added to the ToC, the picture gets twisted:
<img width="602" alt="OO-ToC3" src="https://user-images.githubusercontent.com/64358003/199821542-63778538-d91e-451c-a49e-6a761183d0c1.png">

### Reproduction Steps

<img width="634" alt="OO-ToC1" src="https://user-images.githubusercontent.com/64358003/199821591-c8314d05-3cac-4452-855b-5a47e127fa12.png">
<img width="455" alt="OO-ToC2" src="https://user-images.githubusercontent.com/64358003/199821628-6f6f7b74-0edb-47d7-91fc-7e89b23f099c.png">

**Comment by HectorB-2020** [comment]
Here is another similar issue, just for records: https://github.com/ONLYOFFICE/DesktopEditors/issues/1080

**Comment by maruacat** [comment]
Hello @HectorB-2020
Sorry for the long wait. I was able to reproduce the issue in version 7.2.1.36, but it doesn't reproduce in the latest version 7.4.1.36.
Could you tell me if this problem is reproduced in version 7.4.1.36?
Thank you for your submission.

**Comment by HectorB-2020** [comment]
OK, let's see. :crossed_fingers:

**Comment by maruacat** [comment]
Hello, @HectorB-2020! 
Were you able to verify the current status of the issue in version 7.4.1.36?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
