### ISSUE TITLE
Strange (unexpected) names of styles

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1099]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36

### Expected Behavior

Style title must be the same as I named it.
If I named a style "Style1" it must be shown among other styles as "Style1".

### Actual Behavior

Some leading information is prepended to the name.
Look, I created a style, gave it name ''Test-Style" and successfully saved it.
<img width="284" alt="OO-Style2" src="https://user-images.githubusercontent.com/64358003/199832227-1080c1cf-f7e0-4cfa-be03-0dcc8cb9470b.png">

Surprisingly for me I now see it as something different. "1.1.1.1" was added in front of the name. I cannot even see its name actually. :anguished: Cannot rename it either.
But when I hover mouse on it, it finally shows its real name I gave to this style. Why?

<img width="219" alt="OO-Style3" src="https://user-images.githubusercontent.com/64358003/199832645-e9c98b5e-97df-481c-86db-575bac264f32.png">

**Comment by TatianaKirillova** [comment]
Hello, @HectorB-2020 
Thanks for your request!
The style panel shows a preview of the style, how the style will look in text. And the name itself is visible only in the tooltip.
