### ISSUE TITLE
apt-get purge onlyoffice-desktopeditors do not clear connected portals

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DesktopEditors#110]
**Steps**
1. `sudo apt install onlyoffice-desktopeditors`
2. Open DesktopEditors -> Share & Collaborative and login to any portal
3. Close DesktopEditors
4. `sudo apt purge onlyoffice-desktopeditors`. This should delete any stored config data.
According to `man apt-get`
>purge is identical to remove except that packages are removed and purged (any configuration files are deleted too).

5. `sudo apt install onlyoffice-desktopeditors` and open editors again

**What is the expected behavior?**
List of portals not cleared

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ubuntu 18.04 
deb: 5.1.27-125
About: 5.1.29.348

**Comment by agolybev** [comment]
Fixed by https://github.com/ONLYOFFICE/desktop-apps/pull/28

**Comment by ShockwaveNN** [comment]
Problem is fixed on `onlyoffice-desktopeditors` 5.2.4-16
