### ISSUE TITLE
Equations shows squares with question mark

### ISSUE THREAD

**Issue by UriMtzF** [ONLYOFFICE/DesktopEditors#1100]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.2.1.36

### Expected Behavior

When viewing a document that contains an equation it should show the equation like in MS Word.
![image](https://user-images.githubusercontent.com/39018208/200091525-3e72d59a-034c-4066-9227-70c6cb5230c1.png)

### Actual Behavior

Trying to see or write a formula shows a square with a question mark inside of the correct character.
![image](https://user-images.githubusercontent.com/39018208/200091579-64647a3d-25ef-40f2-9ea9-d248a90dff4d.png)

### Reproduction Steps

Open any document which contains equations or write a new one using the equations function.

### Additional information

The OS is Fedora 36, OnlyOffice installed as native package from RPM.

**Comment by UriMtzF** [comment]
It's fixed now, not relevant anymore

**Comment by Rita-Bubnova** [comment]
Thank you for answer. Feel free to comment or reopen it if you got further questions.
