### ISSUE TITLE
Document editor doesn't preserve "Track Changes" settings

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1104]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36

### Expected Behavior

When I set "**OFF for me**" and close/save the document, I expect that when next time I open it this document, this Tracking Changes is OFF for me indeed.
![image](https://user-images.githubusercontent.com/64358003/201292482-225289be-a24e-4708-a346-1545c37ba932.png)

### Actual Behavior

Sadly now it is not preserved.

![image](https://user-images.githubusercontent.com/64358003/201292357-7791aa18-8d5c-4b6e-9f65-e646ded022bc.png)

**Comment by matveevms** [comment]
Hi, @HectorB-2020 
That's right. The first two items "ON for me" and "OFF for me" are not stored in the document. The global flags that will be saved when the document is closed are the flags "ON for me amd everyone" and "OFF for me amd everyone".

**Comment by HectorB-2020** [comment]
Well, I have to admit that there is nothing else we can discuss here. :disappointed:

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
