### ISSUE TITLE
Onlyoffice doesn't save auto-scale preferences, and also automatically turns light theme when opening up two files.

### ISSUE THREAD

**Issue by rwang5203** [ONLYOFFICE/DesktopEditors#1106]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1

### Expected Behavior

1. The software should automatically save the preferences unless altered by users.
2. The theme should remain the same with more files opened up in the same windows unless altered by users.

### Actual Behavior

1. I have a laptop, connected to an external monitor, so I used different scales on them. I like how onlyoffice provided the option to autoscale, except everytime I saved the preference and re-open the software, it turned back to 100% by defaults.
2. When I open up two files in the same window, the dark theme I pre-setted turns back to light.

**Comment by LuckySpecialist** [comment]
Hi @rwang5203!
1. This is the planned behavior of the application and it is implemented the same for all systems. Sometimes you even need to restart it so that all the settings are applied correctly.
2. Can you clarify the resolution of your internal monitor and the external one?

**Comment by HectorB-2020** [comment]
I can't help reminding that the navigation menu is not preserved either: #1096

**Comment by LuckySpecialist** [comment]
Hi @rwang5203,
We have released a new version of editors 7.3, which included a fix to save the Auto option (to scale the interface in the application settings). Can you check it and let me know if everything is working correctly for you?

**Comment by LuckySpecialist** [comment]
The fix https://github.com/ONLYOFFICE/desktop-apps/pull/696 is included in the release 7.2.2.
Issue can be closed.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
