### ISSUE TITLE
PowerPoint diagram (wmf) isn't rendered correctly on pdf export/print

### ISSUE THREAD

**Issue by 1nikolas** [ONLYOFFICE/DesktopEditors#1110]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1.36

### Expected Behavior

Diagram is shown correctly when exported to pdf / printed

### Actual Behavior

When printing/saving to pdf, the diagram doesn't display correctly (some backgrounds are missing)

![image](https://user-images.githubusercontent.com/30593419/201544904-c4faabda-8245-44c7-acf2-b11fa309a589.png)

It should look like this (screenshot from InkScape, opened the wmf file)

![image](https://user-images.githubusercontent.com/30593419/201762663-122a12b3-d5f8-4c3d-aa57-b3cfcd5dda44.png)

### Reproduction Steps

[Example files](https://github.com/ONLYOFFICE/DesktopEditors/files/9998241/Archive.zip)
The zip file contains both the pptx and the wmf of the diagram shown above (you can also extract it from the pptx).

I should also mention that this diagram is made using a really old version of MS Office (and then modified with a newer one, you can look at the created/modify dates). 

### Additional information

Possibly related to ONLYOFFICE/DocumentServer#2100, was asked to open separate issue

**Comment by Gingetsu** [comment]
Hello, @1nikolas.
Our dev team is fixed your issue in 7.3.0 version.
Thank you for report.

**Comment by DenisDeeSign** [comment]
I close this issue since DesktopEditors v7.3.0 is released. Feel free to comment or reopen it if you got further questions.

**Comment by 1nikolas** [comment]
@DenisDeeSign it works fine now. Weird because it doesn't render correctly on the ui (https://github.com/ONLYOFFICE/DocumentServer/issues/2100)
