### ISSUE TITLE
PowerPoint diagram (wmf) rendered incorrectly when copied as image

### ISSUE THREAD

**Issue by 1nikolas** [ONLYOFFICE/DesktopEditors#1111]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1.36

### Expected Behavior

Diagram renders correctly when copied as image

### Actual Behavior

When copying the diagram (as an image) and pasting it, it shows only a part of it

https://user-images.githubusercontent.com/30593419/201545188-2c8adf31-b941-4ce6-a883-bc72d6ab3174.mp4

Also the diagram is displayed incorrectly (see ONLYOFFICE/DocumentServer#2100). It should look like this (screenshot from InkScape, opened the wmf file)

![image](https://user-images.githubusercontent.com/30593419/201762663-122a12b3-d5f8-4c3d-aa57-b3cfcd5dda44.png)

### Reproduction Steps

[Example files](https://github.com/ONLYOFFICE/DesktopEditors/files/9998241/Archive.zip)
The zip file contains both the pptx and the wmf of the diagram shown above (you can also extract it from the pptx). 

I should also mention that this diagram is made using a really old version of MS Office (and then modified with a newer one, you can look at the created/modify dates). 

### Additional information

Possibly related to ONLYOFFICE/DocumentServer#2100, was asked to open separate issue

**Comment by 1nikolas** [comment]
The less correct render (on the pptx, #1109) is now displayed even more messed up when copied over to docx
(same file. new version)

![image](https://user-images.githubusercontent.com/30593419/216793378-b275499b-9e4c-4a33-857b-56a6f01c5509.png)
![image](https://user-images.githubusercontent.com/30593419/216793393-093566fe-c0fd-4e23-a3dd-26b2949e2b47.png)

**Comment by Gingetsu** [comment]
Hello, @1nikolas .
I can confirm - this is bug.
I created issue 61091 in our private issue tracker.
Thank you for report.

**Comment by 1nikolas** [comment]
7.3.3 still a problem

Powerpoint:
![image](https://user-images.githubusercontent.com/30593419/226114515-a4156170-5ae8-47d1-99c9-8b9665d8ebbf.png)

Word:
![image](https://user-images.githubusercontent.com/30593419/226114505-2f74c43d-8ac2-4419-bbc5-c2f055adac02.png)

**Comment by Gingetsu** [comment]
Hello, @1nikolas . Our dev team is fixed your issue in next version (But sorry, no exact ETA)This fixed here: https://github.com/ONLYOFFICE/core/commit/9d9edd2cfc68c01740c67c238a15dcf401c47464

**Comment by DenisDeeSign** [comment]
DesktopEditors v7.4.0 are released so I close this issue. Feel free to comment or reopen it if you got further questions.
