### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by vatterspun** [ONLYOFFICE/DesktopEditors#112]
I thought someone had already posted about this but I can't find it.  Could someone point me to the Windows build instructions?  Thanks.

**Comment by ShockwaveNN** [comment]
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/4

**Comment by vatterspun** [comment]
Sorry, I'm not trying to harp on this, I tried several different ways to find the topic and just couldn't find it.  Thanks for the pointer.
