### ISSUE TITLE
Inconsistent Document Scroll

### ISSUE THREAD

**Issue by kojq** [ONLYOFFICE/DesktopEditors#1123]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1

### Expected Behavior

Regardless of prior actions, a scroll indicating the upward direction should scroll up from the current location while a scroll indicating the downward direction should scroll down from the current location within the document.

### Actual Behavior

The document jumps down or to another location before the scroll functions as intended. Often times, if this action does not occur, there will be a noticeable scroll hiccup instead. Finally, if neither of these occur, scroll proceeds as normal.

### Reproduction Steps

This occurs when not interacting with the document for a while and potentially when using other applications. This behavior occurs sporadically.

### Additional information

There is no reliable way to replicate this (at least for the moment). However, this does occur relatively frequently.

**Comment by ElenaMaaya** [comment]
Hello, @kojq!
Thanks for the report.
I followed the instructions, but I can't reproduce this issue. If you can, please attach the problem file for a more complete test.

**Comment by kojq** [comment]
This issue persists at least across various `.docx` `Document` files and was attempted on different systems. I can submit a video file containing a demonstration when I get a chance.

**Comment by ElenaMaaya** [comment]
Thanks, this is a great idea! I will wait for more information and video file from you. We are always happy to help with technical problems that can be repeated by our specialists.

**Comment by kojq** [comment]
I cannot currently record, but I will look into doing so within a week at the latest. However, I believe this occurs on X11 specifically, as I cannot replicate this exact behavior on Wayland.

**Comment by ElenaMaaya** [comment]
Thanks for the details. Sorry, I can't reproduce this issue in version 7.2.2.25 (deb package) (Kubuntu 22.04 X11) and version 7.2.2.25 (x64 exe package) (Win11 Home 21H2 x64).

**Comment by ElenaMaaya** [comment]
Version 7.2.1 is the current version for users.
I can't reproduce this issue in version 7.2.1.
Please make a video file if the error happens again.

**Comment by kojq** [comment]
I believe this was caused by an upstream issue in GNOME and KDE releases at the time. We can close this. Thank you.
