### ISSUE TITLE
Wireshark strings in OnlyOffice?

### ISSUE THREAD

**Issue by SimoLRepo** [ONLYOFFICE/DesktopEditors#1126]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36

### Expected Behavior

Normal execution

### Actual Behavior

On startup it establishes a connection with 192.168.188.1 and it also checks if there are files belonging to Wireshark.

See [editors.exe on hybrid-analysis](https://www.hybrid-analysis.com/sample/6b664b24a8e7d1885f5cf9f79bcfb4e1c12e778a469d020813585a3d5a5d5680/637cfdc3a5b918517b1b1ecf) and [editors_helper.exe on hybrid-analysis](https://www.hybrid-analysis.com/sample/5c392788f9a2b89f5b18aa1d1ddef950196333dc5d3f294c8b9f49e2ef7bd8b8/637cfe393f575259172d544d)

Why does he perform such actions?

**Comment by ShockwaveNN** [comment]
Thanks, those seem to be some leftovers from the build process, maybe forgot to clean something

@DAumkraft will try to analyze it

**Comment by SimoLRepo** [comment]
> Thanks, those seem to be some leftovers from the build process, maybe forgot to clean something

Thanks for the clarification

**Comment by DAumkraft** [comment]
Hello @SimoLRepo! I have analyzed your reports and I have some explanations.
1. ONLYOFFICE does not access WireShark files. WireShark is installed in the guest system of the hybrid-analysis.com service and has registered the path to its folder in the [PATH system variable](https://en.wikipedia.org/wiki/PATH_(variable)).
When ONLYOFFICE starts, it tries to find its system files in all folders specified in the PATH variable, one of which is the WireShark folder. This behavior is completely normal and should not cause concern. This is how absolutely all programs in Windows work.
2. I looked at both reports, but nowhere did I find any mention of trying to reach the address 192.168.188.1. Could you point to the exact place where you found this information? I also checked where ONLYOFFICE accesses at startup and it was only our update service.

**Comment by SimoLRepo** [comment]
Hi, @DAumkraft . First of all thanks for the clarification (so basically the same environment variable is used by both software), regarding the IP address 192.168.188.1 (internal IP) this connection was noticed by my firewall. Most likely it creates an internal connection to the PC to be able to search for updates. Thank you
