### ISSUE TITLE
exit confirmation when document is open

### ISSUE THREAD

**Issue by chaserene** [ONLYOFFICE/DesktopEditors#1132]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

it's way too easy to accidentally close the Desktop Editors window. could you display a confirmation dialogue when the user tries to close the whole Desktop Editors window while a document is open?

**Comment by TatianaKirillova** [comment]
Hey, @chaserene!
check your Desktop Editors version please! In version 7.2, if there are changes in the file, a warning message appears when the editor is closed

**Comment by TatianaKirillova** [comment]
Thx, @chaserene!
This behavior is correct. In the near future, the behavior will not change under this scenario...

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
