### ISSUE TITLE
Text editing goes through a "text box"

### ISSUE THREAD

**Issue by SoftExpert** [ONLYOFFICE/DesktopEditors#114]
**Do you want to request a *feature* or report a *bug*?**
The following bug occurs when typing text on the Document page: a "text box" is used for collecting typed text and its content is "committed" to the page only when ENTER is pressed.
Space can be freely entered without making the text box appear.

**What is the current behavior?**
I included a short animation to describe the  behavior.
![peek 2018-06-12 14-09](https://user-images.githubusercontent.com/1254018/41289555-7fb14726-6e4a-11e8-97a3-56d1c6fd937f.gif)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open a new Document
Start typing.

**What is the expected behavior?**
The "text box" should not be displayed, instead the text should be freely entered.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Currently using KUbuntu 18.04, OnlyOffice Desktop Editors 5.1.29.350
Used previously on KUbuntu 16.04 with OnlyOffice Desktop Editors 4.8.7 and the issue was not present.

**Comment by Rita-Bubnova** [comment]
Hello, @SoftExpert. 
To enter text on the page without the appearance of a text field, you must disable the alternative input option. To do this, go to the File tab, select the "Advanced Settings" section and uncheck the "Turn on hieroglyphs" option (as shown in the screenshot).
![default](https://user-images.githubusercontent.com/25282241/41337863-1bebb0c8-6ef9-11e8-958e-9339a6c544a2.png)

**Comment by SoftExpert** [comment]
That solved it, thank you !
