### ISSUE TITLE
Linux printing bug when document include image

### ISSUE THREAD

**Issue by jacceko** [ONLYOFFICE/DesktopEditors#1140]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.0.204

### Expected Behavior

when try to print word document with jpg/png etc. on Llinux - printing dialog is displayed, click ok, and then display small popup with print progress and finally print

### Actual Behavior

when try to print word document with jpg/png on Linux etc. - printing dialog is displayed, clieck ok, and then display small popup about print progress and then program make self kill (whole onflyoffice windows disapear).

Linux Mint 21 (=Ubuntu 22.04) with XFCE windows.

### Reproduction Steps

Make new Word document
Insert image - for ex. some jpg
Click File > Print
On printing dialog click ok (it can be print to pdf or any printer)
Printing progress popup is displayed - and after few seconds whole OnlyOffice window disapear.

**Comment by Rita-Bubnova** [comment]
Hello, @jacceko.
Could you check the problem in Desktop Editors version 7.2.1? 
I think this is duplicate https://github.com/ONLYOFFICE/DesktopEditors/issues/1029.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
