### ISSUE TITLE
docx size doubles after saving in MS Word

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1141]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36

### Expected Behavior

Document size doesn't vary significantly when a file is exchanged between different applications preserving the same format (.docx).

### Actual Behavior

I'm not claiming this is an issue in Only Office, but if a document (.docx) firstly saved in Only Office and then opened in MS Word (the latest one whatever the version is) and finally saved in MS Word, its size literally doubles.

Interestingly, if this file then opened in Only Office and saved there with some really minor change, its size shrinks back twice.
:smile: 

The reason for such strange behaviour is contents of folder `word`\\`media`. It's populated with lots of graphical PNG files.
In my case it originally contained 39 files with total size around 5 MB. 
`image1.png` .. `image39.png`
After saving this .docx file in MS Word, number of PNG files the folder `word`\\`media` grew to 78, twice, you see. The size bumped up to 10 MB.

`image110.png` became a copy of `image1.png`
`image210.png` became a copy of `image2.png`
`image310.png` became a copy of `image3.png`
`image390.png` became a copy of `image39.png`

**Comment by LuckySpecialist** [comment]
Hi @HectorB-2020!
I apologize for the long wait.
In general, it is clear what you are talking about, but what result should be correct in your opinion? The file size should not increase/decrease and in which application?
Can you attach a file on which you noticed this problem and I will try to reproduce this behavior?

**Comment by HectorB-2020** [comment]
@LuckySpecialist, like I said from the start I was not claiming this is bug in Only Office, no offense.
However if MS Word for some reason decides to duplicate existing png files, this might give you some insights about what might be wrong in the file format, which Only Office produces.
Another question - why Only Office drops these excessive file which, according to Only Office algorithm, are unnecessary.

**Comment by LuckySpecialist** [comment]
I can only assume that some optimizations are applied when saving. Perhaps some settings are not supported by our application. This is all guesswork...
if you provide a file, I will be able to analyze this behavior in more detail.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
