### ISSUE TITLE
Right Click crashes presentation editor 

### ISSUE THREAD

**Issue by gaming128** [ONLYOFFICE/DesktopEditors#1143]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36

### Expected Behavior

Right click should open a small pop up menu
worked fine in LInux version 

### Actual Behavior

Presentation editor crashes 

### Reproduction Steps

1. open up any presentation
2. right click on something like text or an item
3. see if you can click anything else after that

### Additional information

tried both .msi and .exe apps and none worked

**Comment by TatianaKirillova** [comment]
Hey, @gaming128
Thanks for your request!
Is your issue still current in version 7.4.1?
If so, please attach a video of the problem playback!

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
