### ISSUE TITLE
`Update Heading Style` doesn’t apply to remaining headings of the same style

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1146]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, Linux (DEB package)

### Version information

7.2.1.36

### Expected Behavior

Usually this works as expected in non-sophisticated documents with basic formatting.
Let’s paste my dummy text to new document.
Highlight the first and few other lines, make them `Heading 2`. This also works with other styles of headings.
![image](https://user-images.githubusercontent.com/64358003/205509602-7ead979f-9c52-476f-85f7-5524c35ab078.png)
The result is to look like this.
![image](https://user-images.githubusercontent.com/64358003/205509624-bea4c2ce-a6a6-4d47-a5dd-0ae49b22128f.png)
Now we change font of the first heading as an example ...
![image](https://user-images.githubusercontent.com/64358003/205509566-ac2e15dc-69cd-4675-b2d3-b60b74a24153.png)
... and update this style with the changes (font) what we've just applied.
![image](https://user-images.githubusercontent.com/64358003/205509692-ae3bda2c-7ae2-4643-89b7-f763dcdde457.png)
The expected result is that the new font is immediately applied to all headings sharing the same style.
![OO-Style6](https://user-images.githubusercontent.com/64358003/205510959-105a37b8-06ab-4414-a98b-5984514019c2.png)

### Actual Behavior

Under specific circumstances the sequence described above doesn't work.
After different formatting has been applied to one of headings and the style has been updated, other remaining headings with the same style still preserve old formatting (font as in this example).

Checking each heading shows that they have style with the same expected name, `Heading 2` like in this example.

However if I select one of those headings and click on `Heading 2` in the style menu above, the correct desired style with new font is going to be immediately applied but only to the selected heading.

### Additional information

Other issues with styles and headings, keep them here for records:
* https://github.com/ONLYOFFICE/DocumentServer/issues/2282
* https://github.com/ONLYOFFICE/DesktopEditors/issues/1099
* https://github.com/ONLYOFFICE/DesktopEditors/issues/1347
* https://github.com/ONLYOFFICE/DesktopEditors/issues/771
* https://github.com/ONLYOFFICE/DocumentServer/issues/1949
* https://github.com/ONLYOFFICE/DocumentServer/issues/1894

**Comment by HectorB-2020** [comment]
@matveevms and @DenisDeeSign, does the text above look like a reproducible set of steps?
Because if the answer is "yes", I wonder why you are asking other people. I'm not trying not being rude, mind you. I'm merely curious why the question.

**Comment by oMrSmith** [comment]
In general updating styles does not seem to work properly. Here is another issue I just discovered:

https://github.com/ONLYOFFICE/DesktopEditors/assets/78870770/64818f38-df9d-4105-8370-3b49322b6da0

**Comment by matveevms** [comment]
The problems described above are not repeated on version 8.1.1.26.
Please update your editor version.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
