### ISSUE TITLE
Version 7.x.x Spreadsheet fail to save pdf

### ISSUE THREAD

**Issue by rakhmatvaris** [ONLYOFFICE/DesktopEditors#1147]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36

### Expected Behavior

After I updated to version 7.2.1.36, my spreadsheet file couldn't "save as pdf" normally. Likewise version 7.1.0.215, the "save as pdf" failed. Last time I used version 6.3.1.56, when I "saved as pdf" the results were normal

This my file
![image](https://user-images.githubusercontent.com/110417136/206139879-5c249b28-5b31-4442-a4c8-29d21f48650b.png)
file created with version 7.2.1.36
![image](https://user-images.githubusercontent.com/110417136/206132932-f91fd211-da86-48ed-934a-310c96dea705.png)
"save as pdf"
![image](https://user-images.githubusercontent.com/110417136/206140227-fc408ead-71e7-477c-a616-de1794db96eb.png)
the pdf result
![image](https://user-images.githubusercontent.com/110417136/206133466-9aa68477-66d5-46f1-afde-1024bddacaee.png)

### Actual Behavior

This after uninstal 7.2.1.36, then i use the older version 6.3.1.56
![image](https://user-images.githubusercontent.com/110417136/206135754-d409d34b-d120-4a7a-9fa2-1ef3ffb67d65.png)
same file from 7.2.1.36
![image](https://user-images.githubusercontent.com/110417136/206136189-6cdabd5d-9f42-4a2e-a612-d499240bc369.png)
"save as pdf"
![image](https://user-images.githubusercontent.com/110417136/206140276-8d6c3657-9466-409f-8b55-9ce89c0e653e.png)
version 6.3.1.56 pdf result
![image](https://user-images.githubusercontent.com/110417136/206140408-74b63862-fb02-4016-953e-ca3d529fa38b.png)

### Additional information

for the time being I will stick with version 6.3.1.56

**Comment by Rita-Bubnova** [comment]
Hello, @rakhmatvaris. 
Could you attach the file with problem?

**Comment by rakhmatvaris** [comment]
yes, thank you for your attention.

[Faktur Pelunasan.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/10175633/Faktur.Pelunasan.xlsx)

**Comment by Rita-Bubnova** [comment]
Thank you for your file.
The file has a print area. Desktop Editor does not allow you to ignore this setting when saving to PDF.  I created issue  60078 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by rakhmatvaris** [comment]
> Sorry, we forgot to mention that issue was fixed. I close this issue. Feel free to comment or reopen it if you got further questions.

thank you. i will try it
