### ISSUE TITLE
/usr/bin/onlyoffice-desktopeditors is not executable

### ISSUE THREAD

**Issue by 532910** [ONLYOFFICE/DesktopEditors#115]
```
% wget https://github.com/ONLYOFFICE/DesktopEditors/releases/download/ONLYOFFICE-DesktopEditors-5.1.27/onlyoffice-desktopeditors_amd64.deb
% sudo dpkg -i onlyoffice-desktopeditors_amd64.deb
% ls -l /usr/bin/onlyoffice-desktopeditors
-rw-rw-r-- 1 root root 14 2018-05-25 17:34 /usr/bin/onlyoffice-desktopeditors
```

**Comment by c-e-p-x-u-o** [comment]
Moreover it MUST NOT be group writable!

**Comment by c-e-p-x-u-o** [comment]
Moreover it MUST NOT be group writable!

Moreover it is just a trash!

**Comment by ShockwaveNN** [comment]
Related to https://github.com/ONLYOFFICE/DesktopEditors/issues/98

**Comment by agolybev** [comment]
Fixed by https://github.com/ONLYOFFICE/desktop-apps/pull/27

**Comment by c-e-p-x-u-o** [comment]
It must be removed. See the content.

**Comment by ShockwaveNN** [comment]
@c-e-p-x-u-o could you describe why it should be removed?
I take a look at my `/usr/bin/` on Ubuntu 18.04 and there is a lot of sh files which looks like our `/usr/bin/onlyoffice-desktopeditors` so we have no idea why it should be removed, if you can point out for some guideline for such files it be good for us.

**Comment by c-e-p-x-u-o** [comment]
This is not an 'sh' file.
Could you show and example of another file that looks like this one?

**Comment by c-e-p-x-u-o** [comment]
1. There are symlinks for for this purpose.
2. sh files MUST start with shebang
3. it will not work without PATH:

```
% l /usr/bin/onlyoffice-desktopeditors
-rwxr-xr-x 1 root root 14 2018-05-25 17:34 /usr/bin/onlyoffice-desktopeditors*

% cat /usr/bin/onlyoffice-desktopeditors
desktopeditors%

% PATH=

% /usr/bin/onlyoffice-desktopeditors  
/usr/bin/onlyoffice-desktopeditors: 1: /usr/bin/onlyoffice-desktopeditors: desktopeditors: not found
```

**Comment by ShockwaveNN** [comment]
@c-e-p-x-u-o oh, sorry i confused 2 files.
I mean `/usr/bin/onlyoffice-desktopeditors` which contain
```
#!/bin/sh

export LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH
export LD_PRELOAD=./libcef.so
cd /opt/onlyoffice/desktopeditors/
exec ./DesktopEditors "$@"
```
looks like almost all files in `/usr/bin`
but I agree we should replace `/usr/bin/onlyoffice-desktopeditors` with symlinks

**Comment by c-e-p-x-u-o** [comment]
```
% cat /usr/bin/onlyoffice-desktopeditors
desktopeditors%

% apt policy onlyoffice-desktopeditors 
onlyoffice-desktopeditors:
  Installed: 5.1.27-126
  Candidate: 5.1.27-126
  Version table:
 *** 5.1.27-126 100
        100 /var/lib/dpkg/status
```

**Comment by ShockwaveNN** [comment]
@c-e-p-x-u-o oh, seems I have leftovers from beta version on my pc
I cleanup and now 
```
cat /usr/bin/desktopeditors

#!/bin/sh

export LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH
export LD_PRELOAD=./libcef.so
cd /opt/onlyoffice/desktopeditors/
exec ./DesktopEditors "$@"
```
and 
```
cat /usr/bin/onlyoffice-desktopeditors
desktopeditors
```
This is is a mess :(

**Comment by ShockwaveNN** [comment]
@c-e-p-x-u-o we make a fix https://github.com/ONLYOFFICE/desktop-apps/pull/29
(please note that github show symbolic links like file with content in web interface, `desktopeditors` is symbolic link)
```
ls -la win-linux/package/linux/common/onlyoffice/usr/bin/desktopeditors
lrwxrwxrwx 1 lobashov lobashov 25 июн 20 12:43 win-linux/package/linux/common/onlyoffice/usr/bin/desktopeditors -> onlyoffice-desktopeditors
```

**Comment by 532910** [comment]
Looks like it's fixed and should be closed, is not it?

**Comment by ShockwaveNN** [comment]
@532910 yeah, thanks
