### ISSUE TITLE
Spreadsheet: Y-axis shifts to the right of graph when `Values in reverse order` is checked.

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1150]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36

### Expected Behavior

I'm accustomed to behaviour when Y-axis always stays on the left side even after I've checked 'Values in reverse order'.

### Actual Behavior

Was that a wrong assumption to expect the vertical axis to be on the left side of graphs? I apologies for submitting this issue if this is "by design".
Anyway, when I choose 'Values in reverse order',
<img width="254" alt="OO-V-axis2" src="https://user-images.githubusercontent.com/64358003/206547670-8f5033ac-b055-4905-bab3-38f9f5267303.png">
the Y-axis moves to the right:
<img width="261" alt="OO-V-axis1" src="https://user-images.githubusercontent.com/64358003/206547798-b165ca80-f326-4fac-bf61-b87fd97fdc3c.png">

**Comment by VladimirProkofiev52** [comment]
Hello!, @HectorB-2020 
The behavior you describe is normal.
The zero points of the X-axis and the Y-axis must converge in one place.
If you apply 'Values in reverse order' to the X-axis only while leaving the Y-axis on the left. You get two zero marks: at the beginning and end of the X axis - This will be an error.

For example, in the MS Excel, the behavior is similar to ours editor.

**Comment by HectorB-2020** [comment]
Thanks very much for checking! In this case I don't see a reason to keep this issue open any longer.
