### ISSUE TITLE
french spell check does not correct accents

### ISSUE THREAD

**Issue by ggrrll** [ONLYOFFICE/DesktopEditors#1151]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

 7.2.1.36 (snap package)

### Expected Behavior

correct accents

### Actual Behavior

does not detect missing accents

### Reproduction Steps

(try to write in french)

**Comment by matveevms** [comment]
Hello, @ggrrll 
What system are you using and what French layout? If possible, please attach a screenshot with the layout settings and an example of the input you make.

**Comment by bmalynovytch** [comment]
Using v7.2.1 on macos, I can confirm that missing french accents are properly identified and suggested for modification (was looking for another issue while typing a document and fell here by accident ^^)

**Comment by ggrrll** [comment]
sorry for the late reply

here is a file on https://drive.switch.ch/, which uses OO web editor -- same issue

<img width="614" alt="Screenshot 2023-02-16 at 14 32 05" src="https://user-images.githubusercontent.com/15370425/219378536-82917d5d-1a04-4062-833d-a02e2d6ea8a0.png">

**Comment by ggrrll** [comment]
sorry, not sure -- I use more often web editor , as it's embedded on https://drive.switch.ch/

and it seems fine ... so maybe we can close it (still to check on linux)

**Comment by ggrrll** [comment]
ok, it seems to be working fine actually
