### ISSUE TITLE
[UX] Grab area to move column or row in a spreadsheet is too thin

### ISSUE THREAD

**Issue by 12people** [ONLYOFFICE/DesktopEditors#1158]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

When trying to move a column or a row in the spreadsheet to the left or to the right, it seems like the cursor has to be exactly on the 1 px line between the column/row header and the cell below it. As such, it's extremely hard to target.

There are a number of ways to potentially fix this. For example:
1. The default behavior for dragging the column or row header could be to move the column/row, just like in Google Sheets. (To select multiple columns/rows, one would just click on one header, then press shift and click on another header.)
2. Alternatively, a drag indicator (with a 3x2 dot icon) could appear on hover over a column / row header, allowing the user to drag that row or header via this indicator.

**Comment by VladimirProkofiev52** [comment]
Hi @12people!
I compared our editor's to Google Sheets.
Move icon appears under the same conditions.

Please tell me which version of our editor you are using?
What is your screen resolution?

We released version 7.3. If you haven't updated your desktop editor yet, please update and try to reproduce your issue.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
