### ISSUE TITLE
Double-click on a file in file manager doesn't bring Only Office application to foreground

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1165]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, Linux (DEB package)

### Version information

7.2.1.36

### Expected Behavior

When a user clicks on an office file in any file manager, whether it is Windows Explorer or Caja (MATE), the office application loads the file and opens its window above all other applications in foreground.

### Actual Behavior

Regrettably current behaviour is different.
The application starts indeed and certainly loads the selected file but this doesn't bring its windows to the front.
At best it will flash in task bar in Windows, sadly it doesn't show any sign of successful loading in MATE.

**Comment by Rita-Bubnova** [comment]
Hello, @HectorB-2020.
Thank you for the report. 
This is known as issue 58401 in our private issue tracker. And the problem fixed (https://github.com/ONLYOFFICE/desktop-apps/commit/ad6f46fd7293df71c095cf0e66875ffb7a5a0539) in a future major release.

**Comment by HectorB-2020** [comment]
Glad you are fixing issues! :+1: 
Any chance you can include other minor things like #1058 into the coming release?

**Comment by Rita-Bubnova** [comment]
Thanks for your feedback.

If the problem will fix and checked we will write it at https://github.com/ONLYOFFICE/DesktopEditors/issues/1058.
But I can't give any guarantees, I haven't ETA.

**Comment by DenisDeeSign** [comment]
DesktopEditors v7.3.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
