### ISSUE TITLE
Scaling Display Issue on Linux

### ISSUE THREAD

**Issue by PhilipYip1988** [ONLYOFFICE/DesktopEditors#1168]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package), Linux (RPM package)

### Version information

7.2.1

### Expected Behavior

Only Office Desktop Editors should automatically scale on a High DPI Screen on Linux. Similar to Libre Office:
![Libre Office](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/Screenshot%20from%202022-12-30%2012-36-32.png)

### Actual Behavior

Only Office Desktop Editors does not display properly on a High DPI Screen and the text is tiny:

![Only Office Desktop Editors](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/Screenshot%20from%202022-12-30%2011-59-26.png)

The system has a High DPI Screen 3200 by 1800 pixels and 200 % Scale:

![Display Settings](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/Screenshot%20from%202022-12-30%2012-00-06.png)

### Reproduction Steps

Install Ubuntu 22.10 or Fedora 37 on a system with a High DPI Screen.
This system for example has a High DPI Screen 3200 by 1800 pixels and 200 % Scale.
Install Only Office Desktop Editors using the DEB or RPM.
Launch Only Office Desktop Editors.
Text is too small to read. 

### Additional information

The system has a High DPI Screen 3200 by 1800 pixels and 200 % Scale.

**Comment by LuckySpecialist** [comment]
Hi, @PhilipYip1988!
Can you specify the manufacturer/brand/model of your device. It seems that the application incorrectly determined the ratio of resolution to screen size and therefore the scale remained 100%.
If you manually switch the scale to 200% in the app settings, does it work like this?

**Comment by PhilipYip1988** [comment]
Hi @LuckySpecialist it is a Dell XPS 13 9365 2 in 1.

Manually changing to 200 % worked:
![img1](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/Screenshot%20from%202023-01-14%2015-54-15.png)

I had the wrong settings open earlier and didn't see that option:
![img3](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/Screenshot%20from%202023-01-14%2015-54-53.png)

![img2](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/Screenshot%20from%202023-01-14%2015-54-25.png)

**Comment by LuckySpecialist** [comment]
Hi @PhilipYip1988!
Document editors are guided by the settings of the main application and there is no separate scaling option for them.
Now we need to summarize, there are several questions for this:
1. The option to automatically determine the scale of the interface does not work correctly for you and it remains 100%?
2. In the case of manual switching to 200%, everything works correctly?
3. Are you satisfied with this scale or do you need a different value?

**Comment by PhilipYip1988** [comment]
Hi @LuckySpecialist 

1. Automatically incorrectly determines the scale of the interface to be 100 %. It should be 200 % on this screen. GNOME settings use 200 % for example by default and it scales correctly in most other Linux Applications.
2. 200 % works fine for this screen, there is no need for an additional value.

**Comment by LuckySpecialist** [comment]
Hi @PhilipYip1988!
We have released a new version of editors 7.3.
Can you check the problem with automatic scaling detection on it and tell if the problem persists?

**Comment by PhilipYip1988** [comment]
Just installed it and the auto setting is now working correctly on my system. Thanks.

![img](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/6f3f6000590e5e8479d3e8b023e5dc228c558db5/onlyofficescalingfixed.png)
