### ISSUE TITLE
Shortcut is named "Property.SHORTCUT_FOLDER_NAME" when using the msi installer

### ISSUE THREAD

**Issue by maeries** [ONLYOFFICE/DesktopEditors#1174]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36 (x64 msi package)

### Expected Behavior

Have a link on the desktop and start menu called "ONLYOFFICE Editors" like when using the .exe installer

### Actual Behavior

Have a shortcut with the right icon, but it's called "Property.COMMON_SHORTCUT_NAME" on the desktop and start menu

### Reproduction Steps

1. Download the .msi installer
2. Click through the installer without changing anything

### Additional information

- maybe related to #1033 
- no such issue when using the .exe installer

**Comment by DAumkraft** [comment]
Hello, @maeries!
What language is used in your operating system?

**Comment by maeries** [comment]
> Hello, @maeries! What language is used in your operating system?

german

**Comment by DAumkraft** [comment]
Greetings, @maeries!
Thanks for writing about this problem!
This is indeed a problem, it is related to another [issue](https://github.com/ONLYOFFICE/DesktopEditors/issues/1157).
I created a bug in our internal bugtracking system. The problem will be fixed in an upcoming release.

**Comment by DenisDeeSign** [comment]
DesktopEditors v7.3.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
