### ISSUE TITLE
Formula function not working on pre-created excel sheet

### ISSUE THREAD

**Issue by jxs714** [ONLYOFFICE/DesktopEditors#1175]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.1.1.57

### Expected Behavior

Hey guys,

Been realizing this problem for quite some time. When I open an excel document created elsewhere (such as finance software), I highlight all of the cells id like with the function option. I use SUM and the output is always zero no matter what. The moment I manually enter new numbers into the sheet cells in onlyoffice, the sum function works on the new cells and gives me the proper output (1+1 = 2).

What is going on? - Is there something specific in this document on the backend code of the document that onlyoffice isn't reading?

### Actual Behavior

output is always zero

### Reproduction Steps

Use FUNCTION into a new cell with sum. Then highlight each box that I'd like to get the total sum of.

**Comment by Rita-Bubnova** [comment]
Hello, @jxs714.
Could you attach your file with the problem?
