### ISSUE TITLE
Respect Desktop Environment per monitor scaling

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#1176]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1

### Expected Behavior

OO Desktop Editors should respect the Desktop Environment (Gnome, KDE, etc.) scaling per monitor which is possible under Wayland. 

### Actual Behavior

OO DE has global scaling but does not respect the per monitor scaling set for the Desktop Environment.
This is problematic when you use different scaling per monitor (e.g., 200% for a 4k screen and 100% for a FHD screen).

### Additional information

I use Debian Bookworm with KDE/Wayland.

**Comment by LuckySpecialist** [comment]
Hi @parrenin,
We have released a new version of Desktop Editors 7.3.
Can you check on it and let us know if this problem is relevant for you?

**Comment by matveevms** [comment]
Hello, @parrenin 
I tested on my Debian system with Wayland and two FullHD and 4K monitors. Currently, the editor recalculates the application scale value when moving it to another screen. Please check the operation of our editor 7.4.1 on your system.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by parrenin** [comment]
Sorry for the late answer, I was having an issue with my github and was not receiving notifications...
I tested again with: 1) the internal FHD screen of my laptop 2) a 4k external screen, both running side by side.
It is not clear to me what the auto mode does: the scaling is 200% on both screen, which is inappropriate for the FHD internal screen.
Again, apart form the "Auto" mode, I think there should be a "from DE" setting, where the scaling is taken from the Desktop Editor.
For me, this issue is not fixed properly.
