### ISSUE TITLE
Unreadable installer options -> Dialog.FileAssociationsDlg | ationsDlg#

### ISSUE THREAD

**Issue by Commandcracker** [ONLYOFFICE/DesktopEditors#1180]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1

### Expected Behavior

Readable options

### Actual Behavior

Unreadable options

### Reproduction Steps

1. Download the [DesktopEditors_x64.**msi**](https://www.onlyoffice.com/en/download-desktop.aspx)
   SHA256 8c12e045b1f1a5acd1ef0876c285cc0e3f8879bc55c7bc4863794a6515cea99a  DesktopEditors_x64.msi
![grafik](https://user-images.githubusercontent.com/49335821/212542432-6f693b7b-dee8-47a3-a9b7-25fff2d57b9d.png)

2. Run the **msi**
3. Go thrue the installation until the screenshot below is visible

### Additional information

![grafik](https://user-images.githubusercontent.com/49335821/212542072-b646b574-9814-47c3-893a-3a72d02159f7.png)

The System is running Windows 11 Home 22H2 22621.1105.
Language: German (Germany).

**Comment by Commandcracker** [comment]
After the installation, I found this
![grafik](https://user-images.githubusercontent.com/49335821/212543233-5028eaae-7691-4ea4-8ed9-794ffaf3ecca.png)
![grafik](https://user-images.githubusercontent.com/49335821/212543243-f9f5ae0a-82c0-4289-b23d-57af595d1517.png)
![grafik](https://user-images.githubusercontent.com/49335821/212543261-0dfa39f3-4837-4309-b364-84f432a7abf9.png)

**Comment by HectorB-2020** [comment]
Does it look the same if you choose English?

**Comment by Commandcracker** [comment]
Works with English (UK)
![grafik](https://user-images.githubusercontent.com/49335821/212732470-1f6c51c3-772e-403a-9c94-09a5a839bd8e.png)

**Comment by Commandcracker** [comment]
The EXE is working as it should
![grafik](https://user-images.githubusercontent.com/49335821/212733282-4e5835ca-484d-41b2-83cc-04c1bcd9065d.png)
It might be because I can change the language with the EXE as for the MSI I was forced to change my Windows language
![grafik](https://user-images.githubusercontent.com/49335821/212733429-c2612bc3-917a-422e-9419-9b3cbf604111.png)

**Comment by DenisDeeSign** [comment]
DesktopEditors v7.3.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
