### ISSUE TITLE
How to add fonts？

### ISSUE THREAD

**Issue by whutkk** [ONLYOFFICE/DesktopEditors#119]
![image](https://user-images.githubusercontent.com/11452106/41887625-18454b42-7934-11e8-9329-43bc5ffe41e5.png)

RT: I want to save the RTF file as a PDF file, but the Chinese text cannot be displayed, how to solve this problem？

**Comment by K0R0L** [comment]
PDF file created in ONLYOFFICE save as PDF? Can you attach a file?

**Comment by ShockwaveNN** [comment]
This issue is being closed due to no response
