### ISSUE TITLE
ABNT2 Keyboard is not working

### ISSUE THREAD

**Issue by luanrafael19** [ONLYOFFICE/DesktopEditors#12]
ABNT2 Keyboard is not working in OnlyOffice

**Comment by kilZHlik** [comment]
Kubuntu 16.04.1 (x64)

Same stuff(
The new version does not work the keyboard.
How to downgrade to the old version?

And yet, the version referred to in the downloaded package does not match the version of the program.
![screenshot_20161128_210215](https://cloud.githubusercontent.com/assets/20541445/20679949/113e4e2a-b5ae-11e6-98be-27a07edeec62.png)

**Comment by maxkadushkin** [comment]
[duplicate](https://github.com/ONLYOFFICE/DesktopEditors/issues/8)

**Comment by maxkadushkin** [comment]
did it work on previous version? our examination revealed that it's old bug

**Comment by kilZHlik** [comment]
@maxkadushkin 

> did it work on previous version? our examination revealed the bug is old

Yes, I have it worked at least version 4.1.2.270

**Comment by bigbruno** [comment]
In version 4.2.3.290 debian package, not possible use Brazilian ABNT keyboard, because don't show accents.

**Comment by trofim24** [comment]
Close as duplicate. See #8
