### ISSUE TITLE
symbol lookup error. AppImage on Solus OS

### ISSUE THREAD

**Issue by Juankz** [ONLYOFFICE/DesktopEditors#120]
Trying to use appimage of desktop editors in Solus OS. Does not run.

At first it shows:
`./DesktopEditors: error while loading shared libraries: libkeyutils.so.1: cannot open shared object file: No such file or directory
`

Which can be easily solved by installing keyutils. (However isn't it supposed that appimage bundle all neccesary dependencies?). Well never mind, then trying to run it again but throws:

`./DesktopEditors: symbol lookup error: /usr/lib/libgnutls.so.30: undefined symbol: __gmpn_cnd_sub_n
`

And I'm stuck in there.

**Comment by ShockwaveNN** [comment]
Hi there, please recreate this issue in https://github.com/ONLYOFFICE/appimage-desktopeditors repo
