### ISSUE TITLE
Add support for Aarch64

### ISSUE THREAD

**Issue by liberodark** [ONLYOFFICE/DesktopEditors#1201]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hi,

I want to use your software on manjaro aarch64 you can make a build for arm64 ?
Have see you have a build for apple silicon too.

Best Regards

**Comment by MaicolFA** [comment]
yes, compatibility with ARM devices is required.
very necessary.
onlyoffice needs compatibility with: windows arm and linux arm

**Comment by alfredonodo** [comment]
Hi,
do you have any updates on this?
Thank you

**Comment by Rita-Bubnova** [comment]
Hello, @liberodark, @ghost, @alfredonodo.
Support ARM for Linux - this is a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/270.
Support ARM for Windows - this is a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/988.
You can follow these issues for updates.

So I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by defencedog** [comment]
With rising SBC popularity certainly OnlyOffice will be great for ARMBIAN under GNOME
