### ISSUE TITLE
EXE installer Chinese (简体中文) translation error.

### ISSUE THREAD

**Issue by JiNiTaiMei2023** [ONLYOFFICE/DesktopEditors#1205]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.3.0

### Expected Behavior

创建 ONLYOFFICE Desktop Editors 的桌面图标

### Actual Behavior

创建ONLYOFFICE Desktop Editors和桌面图标

### Reproduction Steps

1.Open exe installer, select language Chinese (简体中文)
2.On the "Select Additional Tasks(选择附加任务)" page,"创建ONLYOFFICE Desktop Editors和桌面图标" should be "创建 ONLYOFFICE Desktop Editors 的桌面图标" or "创建桌面图标".

### Additional information

I only tested exe installer,msi installer maybe has the same issue too.

**Comment by ElenaMaaya** [comment]
Hello @JiNiTaiMei2023!
Thank you for report!
I can confirm that the problem exists. I created ticket 61365  in our private tracker with your issue.
The problem was actually in ONLYOFFICE Desktop Editors

**Comment by ElenaMaaya** [comment]
Hello @JiNiTaiMei2023! This bug is fixed in DesktopEditors v7.4.0. Thanks for contacting us!
