### ISSUE TITLE
Render artifacts in upper right corner

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1206]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.3.0.184

### Expected Behavior

Windows borders are not littered with remains of other text or picture.

### Actual Behavior

Since version 7.3.0.184 I started noticing the following artifacts in Document Editor and Spreadsheet.
<img width="61" alt="OO-upper-right" src="https://user-images.githubusercontent.com/64358003/219744418-4d04acae-194d-46de-a0f0-f98f777932d9.png">  <img width="62" alt="OO-upper-right2" src="https://user-images.githubusercontent.com/64358003/219744451-f122e4d7-8e54-4c05-af83-3a60be995578.png">
Please note something unusual under `X`. Looks like it's a maximized copy of the oval with user initials.

**Comment by ElenaMaaya** [comment]
Hello @HectorB-2020!
Thank you for report! Sorry, I can't replicate the issue (Product Version: 7.3.0.184, OS Windows 11). Please, make a video with problems for a more detailed test. Thank you!

**Comment by ElenaMaaya** [comment]
Hello @HectorB-2020! The problem is not repeated in the release version 7.4.0 on Windows 11.

**Comment by ElenaMaaya** [comment]
I repeated the problem after changing the custom scaling in Windows.
This is a known bug 62931 in our internal  issue tracker.
Thank you for contacting us.

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by ElenaMaaya** [comment]
> @Rita-Bubnova, thanks very much indeed! BTW in which version?

Hello, @HectorB-2020! This is fixed in Desktop Editors v. 8.0.
