### ISSUE TITLE
Compile error on altlinux.

### ISSUE THREAD

**Issue by p12** [ONLYOFFICE/DesktopEditors#121]
[error.5.1.27.txt](https://github.com/ONLYOFFICE/DesktopEditors/files/2145495/error.5.1.27.txt)

Hi, I try build tag ONLYOFFICE-DesktopEditors-5.1.27:
`git clone https://github.com/ONLYOFFICE/DesktopEditors
cd DesktopEditors
git submodule init
git submodule update
cd desktop-apps
make`
and view:
`......
g++ -c -pipe -O2 -std=gnu++11 -pthread -pthread -pthread -Wall -W -D_REENTRANT -fPIC -DLINUX -D_LINUX -DDOCUMENTSCORE_OPENSSL_SUPPORT -DLINUX -D_LI
NUX -D_LINUX_QT -D_GLIBCXX_USE_CXX11_ABI=0 -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_N
ETWORK_LIB -DQT_CORE_LIB -I../../win-linux -I. -I../../../desktop-sdk/ChromiumBasedEditors/lib/include -I../../../desktop-sdk/ChromiumBasedEditors/
lib/qcefview -I../../../core/DesktopEditor -I../src/prop -I../src -isystem /usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -isystem /usr/includ
e/gtk-2.0 -I/usr/lib64/gtk-2.0/include -isystem /usr/include/pango-1.0 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/cairo -isystem /u
sr/include/freetype2 -isystem /usr/include/libpng12 -isystem /usr/include/gtkglext-1.0 -I/usr/lib64/gtkglext-1.0/include -isystem /usr/include/atk-
1.0 -isystem /usr/include/gtk-unix-print-2.0 -isystem /usr/include/qt5/QtWidgets/5.9.6 -isystem /usr/include/qt5/QtWidgets/5.9.6/QtWidgets -isystem
 /usr/include/qt5 -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/includ
e/qt5/QtGui/5.9.6 -isystem /usr/include/qt5/QtGui/5.9.6/QtGui -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/i
nclude/qt5/QtCore/5.9.6 -isystem /usr/include/qt5/QtCore/5.9.6/QtCore -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -isy
stem /usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++ -o cdownloadwidget.o ../src/cdownloadwidget.cpp
In file included from ../../../desktop-sdk/ChromiumBasedEditors/lib/include/./applicationmanager_events.h:36:0,
                 from ../../../desktop-sdk/ChromiumBasedEditors/lib/include/applicationmanager.h:38,
                 from ../src/cascapplicationmanagerwrapper.h:36,
                 from ../src/main.cpp:41:
../../../desktop-sdk/ChromiumBasedEditors/lib/include/./../../../../core/DesktopEditor/Word_Api/Editor_Api.h:2361:35: warning: unused parameter ‘nE
ventType’ [-Wunused-parameter]
   virtual bool IsSupportEvent(int nEventType)
                                   ^
../../../desktop-sdk/ChromiumBasedEditors/lib/include/./../../../../core/DesktopEditor/Word_Api/Editor_Api.h:2403:35: warning: unused parameter ‘nE
ventType’ [-Wunused-parameter]
   virtual bool IsSupportEvent(int nEventType)
                                   ^
In file included from ../src/cascapplicationmanagerwrapper.h:36:0,
                 from ../src/main.cpp:41:
../../../desktop-sdk/ChromiumBasedEditors/lib/include/applicationmanager.h:188:28: error: ‘ICertificateSelectDialogOpenSsl’ has not been declared
     void OpenSsl_SetDialog(ICertificateSelectDialogOpenSsl* pDialog);
                            ^
`

**Comment by ShockwaveNN** [comment]
Hi there, currently we have no working instruction for building DocumentEditors on AltLinux, you can monitor #4

**Comment by ShockwaveNN** [comment]
Closing this issue, since now we got building instruction for at least Ubuntu

All other question should be discussed in [build_tools](https://github.com/ONLYOFFICE/build_tools/) repo
