### ISSUE TITLE
No subpixel font rendering in ONLYOFFICE flatpak for Linux 

### ISSUE THREAD

**Issue by guilbut** [ONLYOFFICE/DesktopEditors#1213]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

ONLYOFFICE Desktop Editors version 7.2.1.36 (flatpak package)

### Expected Behavior

Subpixel font rendering doesn't work in ONLYOFFICE document writer . 

### Actual Behavior

When i do a screen shot of text in ONLYOFFICE and zoom on it, I can see only gray antialiasing, when I should see blue and red pixels if subpixel rendering was working. 
(see https://en.wikipedia.org/wiki/Subpixel_rendering )

![Crayon_only_office](https://user-images.githubusercontent.com/31963936/220408768-a6e8773e-abf2-42f6-b2c3-dc31c172009a.png)

instead of : 
![Crayon_subpixel_rendering](https://user-images.githubusercontent.com/31963936/220408973-cd85bc9b-0fbf-4510-91a2-53f2023f30f2.png)

### Reproduction Steps

1. write text
2. make a screen shot 
3. zoom on this screen shot 
4. look if only gray or blue and red pixels

**Comment by Rita-Bubnova** [comment]
@guilbut, Sorry for the long wait.
DesktopEditors v7.4.1 is released. Is this issue relevant?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by retiarylime** [comment]
No subpixel rendering and it strains my eyes cuz the fonts looks blurry.
