### ISSUE TITLE
White bar on the right screen when maximised

### ISSUE THREAD

**Issue by liperium** [ONLYOFFICE/DesktopEditors#1217]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.3.0.184

### Expected Behavior

There shouldn't be anything outside of the actual application window.

### Actual Behavior

There's a white bar on the screen to the right of the one where the window is maximized.

![Fullscreen_OnlyOffice_WhiteBar](https://user-images.githubusercontent.com/48138387/220760912-71e411ef-8881-4879-8201-d0e544fd92cb.png)
_Documents blurred for privacy reasons_

### Reproduction Steps

1. Open document
2. Maximize the window

### Additional information

Windows 11
Screen resolution 1440p
GPU : AMD - 6600 XT
CPU : AMD - 7700x

Looked in the search bar with "White Bar" see nothing, even marked closed.

**Comment by HectorB-2020** [comment]
Something suggests me that this is somehow related to #1206.

**Comment by ElenaMaaya** [comment]
Hello, @liperium.
Thank you for report!
This is known as issue 60899  in our private issues tracker. 
This issue will be fixed in the next version. Wait for the application update.
