### ISSUE TITLE
Cannot type in spinboxes on right panel

### ISSUE THREAD

**Issue by andreh11** [ONLYOFFICE/DesktopEditors#1221]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.3.0.184

### Expected Behavior

When I click on any of the spinboxes on the right panel, I should see a blinking cursor and I should be able to type any valid value without having to click on the arrows to change the value.

### Actual Behavior

I see no cursor and cannot type, so I must click zillions of times to reach the value I want.

### Reproduction Steps

1. Open any document.
2. Click on any spinbox on the right panel.
3. Try to type.

### Additional information

[spinboxes.webm](https://user-images.githubusercontent.com/46482611/221600259-66aa3a38-749d-4959-91d0-c96b84eb3b22.webm)

**Comment by XDmitryK** [comment]
@andreh11 Hi
This is known as issue 61259 in our private issues tracker.
This issue will be fixed in the next version

**Comment by andreh11** [comment]
Thanks! I'll check this out!
