### ISSUE TITLE
App crashes while editing math equations in .docx

### ISSUE THREAD

**Issue by visvaldas01** [ONLYOFFICE/DesktopEditors#1224]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.3.0-1

### Expected Behavior

I was editing a math equation in text, accidentally pressed Shift+Home and the left arrow, after which I expected it just to move to the start of the line.

### Actual Behavior

The app just crashed with this error. After that it became only able for viewing and saving, but not editing.

![picture](https://user-images.githubusercontent.com/60853667/221935296-b1aae959-6ef3-4647-be0e-9fc66277b5e6.png)

### Reproduction Steps

I clicked Insert -> Equation/Insert Equation -> Brackets -> Binomial coefficient, got into the formula from the right, pressed Shift+Home and the left (although it works with any) arrow.
It also works with combinations like Ctrl+Shift+Left/Right - you should just highlight the whole formula and press an arrow (not a left click, it won't work!).
BTW, Shift+Home doesn't work with a formula with an overbar (e.g. Accents -> ABC with overbar) if the cursor is not under the bar.

### Additional information

I'm on Manjaro 22.0.4 Sikaris with x86_64 Linux 5.15.94-1-MANJARO kernel, using the onlyoffice-desktopeditors from the community repository (I checked that bug happens on onlyoffice-bin from the AUR too). I've managed to reproduce this error on virtual machine with Ubuntu 22.04.

onlyoffice --ascdesktop-support-debug-info output:

DevTools listening on ws://127.0.0.1:8080/devtools/browser/5d445925-cb2c-45bb-b1e2-e2ffd2987226
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1806, resource id: 83886152, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1809, resource id: 83886152, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1812, resource id: 83886152, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1843, resource id: 83886152, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1903, resource id: 83886152, major code: 130 (Unknown), minor code: 3

(This QXcbConnection output was printed after I closed the window)

**Comment by Rita-Bubnova** [comment]
This is duplicate #https://github.com/ONLYOFFICE/DocumentServer/issues/2131.
