### ISSUE TITLE
Hyperlink to local files (not allowed)

### ISSUE THREAD

**Issue by JoeyGH** [ONLYOFFICE/DesktopEditors#1227]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.3.0.184

### Expected Behavior

I have a simple Spreadsheet with one hyperlink to an image on my local filesystem.
Path to the image is: C:\output\picture.jpg
So I set the hyperlink to: file:///C:/output/picture.jpg

![Pic1](https://user-images.githubusercontent.com/1660786/222130770-6cb9234a-05db-4a75-b600-9337d93008eb.png)

When I click on the hyperlink, the file should open normally.

### Actual Behavior

When I click on the hyperlink, I get the following error:
**`Not allowed to load local resource: file:///C:/output/picture.jpg`** (in Console @ debug mode).

![Pic2](https://user-images.githubusercontent.com/1660786/222130895-1048803e-f394-4b8c-9954-bb883644f9e2.png)

How can I give DesktopEditors access to local filesystem?

### Reproduction Steps

1. Open new Spreadsheet.
2. Select random cell and create new hyperlink, which points to a file on a local filesystem.
3. Click on the link.

**Comment by VladimirProkofiev52** [comment]
Hello!
@JoeyGH 
I've looked into your problem but unfortunately couldn't replicate it.
Could you please describe the issue in more detail.

Please make sure that in the system settings all users have access to the folder and files "C:/output/picture.jpg".

Does the problem repeat if you specify the path to another folder and another file?

**Comment by JoeyGH** [comment]
Hello @VladimirProkofiev52,

file has security permissions set to "Everyone" and "Full control", so this is not an issue. I tried to do the exact same thing in Excel and Excel opened the file via hyperlink just fine. Below you can find a link to a video, where I demonstrate my problem. In video, I compare the behaviour between DesktopEditors and Excel.

Link:
[https://www.dropbox.com/s/xnyfccvjhnovkki/2023-03-03%2010-19-15.mkv](url)

**Comment by Rita-Bubnova** [comment]
DesktopEditors v7.4.1 is released. Please state is this problem still actual for you?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
