### ISSUE TITLE
Impossible to print something on Linux

### ISSUE THREAD

**Issue by solisinvictum** [ONLYOFFICE/DesktopEditors#1228]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package), Linux (RPM package)

### Version information

7.3.0.184

### Expected Behavior

pressing the "Print" button on top of the menubar, document should get printed.

### Actual Behavior

Onlyoffice crashs.

### Reproduction Steps

1. open any document
2. press on printing (or use ctrl+p)
3. see how onlyoffice crashs

### Additional information

Archlinux.

```
[user@1950x ~]$ onlyoffice-desktopeditors 
namespace error : Namespace prefix new on cell is not defined
<Settings><new:cell></new:cell><new:word></new:word></Settings>
                   ^
namespace error : Namespace prefix new on word is not defined
<Settings><new:cell></new:cell><new:word></new:word></Settings>
                                        ^
namespace error : Namespace prefix new on cell is not defined
<Settings><new:cell></new:cell><new:word></new:word></Settings>
                   ^
namespace error : Namespace prefix new on word is not defined
<Settings><new:cell></new:cell><new:word></new:word></Settings>
                                        ^
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1710, resource id: 153092159, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1713, resource id: 153092159, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1716, resource id: 153092159, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1738, resource id: 153092159, major code: 130 (Unknown), minor code: 3
Abgebrochen

```
Same like here: https://github.com/ONLYOFFICE/DesktopEditors/issues/1029

**Comment by LuckySpecialist** [comment]
Hi @solisinvictum!
I have not been able to reproduce your problem on my systems, Arch Linux with 6.1.15-1-lts kernel (AUR package) and Ubuntu 22.04 (DEB package).
Can you provide some details, for example, a specific document (if reproduced only on it) or your environment (SW/HW), which will help to understand the problem?
A video demonstrating the problem will also be helpful.
Thanks.

**Comment by LuckySpecialist** [comment]
Thanks for the information, it will take some time to find a similar configuration and reproduce the problem.

**Comment by solisinvictum** [comment]
Using a local one. In this case KDE uses cups.

**Comment by LuckySpecialist** [comment]
Hi @solisinvictum,
I installed the same system as yours on the virtual machine and added two virtual PDF printers. Still couldn't repeat your problem. Perhaps the problem is related to specific hardware and its connection with the printer.

**Comment by raedkit** [comment]
Hi @LuckySpecialist I'm having also the same problem and as in the case @solisinvictum this problems occurs with KDE.
I'm using ONLYOFFICE Desktop Editors version 7.3.0.184

**Comment by osoibol** [comment]
I'm experiencing the same issue on Manjaro KDE 6.1.19-1-MANJARO x86_64 and Onlyoffice 7.3.3.50 (onlyoffice-desktopeditors from community official repositories)

I tried opening onlyoffice both as a normal user and as sudo but the error remains the same.

Attached are the screenshots of me creating a test word document, clicking the print button, then the print screen appears, then I click 'print' and for a second the printing screen of KDE appears and then everything crashes. It might be a KDE/Plasma issue/bug??? just trying to figure this out.

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1397, resource id: 65011775, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1400, resource id: 65011775, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1403, resource id: 65011775, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1425, resource id: 65011775, major code: 130 (Unknown), minor code: 3
[1]    5500 IOT instruction  sudo onlyoffice


![Screenshot_20230316_161143](https://user-images.githubusercontent.com/35267770/225662030-dde26c47-a1a1-4c0b-92d1-863e08bfe24c.png)
![Screenshot_20230316_161240](https://user-images.githubusercontent.com/35267770/225662075-9f9396ea-384a-4292-a03c-dcb3e927e11a.png)
![Screenshot_20230316_161300](https://user-images.githubusercontent.com/35267770/225662095-0e08225f-7910-45a0-aeb3-ea4b5d5e4ddb.png)
![Screenshot_20230316_161312](https://user-images.githubusercontent.com/35267770/225662121-2e923d43-4cc3-4df6-8215-d04711f16d34.png)

**Comment by tleepa** [comment]
I have also got the same issue. Same "XCB error" messages as above.

My system: Fedora 37 KDE Spin, printer is Brother HL-L8260CDW with CUPS driver (connected via network) and is my only printer.

**Comment by elbc56** [comment]
Same thing for me, last stable Manjaro XFCE edition : 

 onlyoffice-desktopeditors 
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1387, resource id: 77594687, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1390, resource id: 77594687, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1393, resource id: 77594687, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1415, resource id: 77594687, major code: 130 (Unknown), minor code: 3
Abandon (core dumped)

For testing I've installed mate desktop to compare : no core dumped under mate desktop

**Comment by osoibol** [comment]
For the people trying to print in the meantime it seems like the only workaround is to either save the document as PDF and then printing it from a PDF Viewer/Editor like Evince, Firefox, or Master PDF Editor.

I tried to print a Word Document with LibreOffice as well with mixed results (sometimes the printer would just 'spit' the paper without printing anything and then the 'printer jam' light turns on, sometimes it gets added to the cue but doesn't start, sometimes it works, the printer is new, just bought it 3 weeks ago, the printer model is a Canon PIXMA MG36505). Now, I'm not sure if it's a totally unrelated issue or if it has any connection with the Onlyoffice problem, but it might indicate that the problem is with KDE Plasma in general, with Manjaro/Arch, or with cups...

**Comment by elbc56** [comment]
As I said before, been testing under Manjaro with two different desktops (Xfce and mate desktop, not KDE), onlyoffice works under mate desktop, not under xfce (segfault under Xfce when printing window opens, not under mate). If issue appears under KDE, I think it is maybe linked to a qt issue (see the error QXcbConnection: XCB error: 8 (BadMatch) ) .
Tested on Debian 11 with Xfce 4.18 : no issue.

**Comment by ScaMar** [comment]
The only workaround i found is to save as "PDF" (not print to PDF), then print withing a PDF viewer

Environment is:
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.1.25-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 32 × AMD Ryzen 9 7950X 16-Core Processor
Memory: 62,5 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT
Manufacturer: ASUS

**Comment by jlr1001** [comment]
Hey,

An alternate workaround that I'm using is to simply download the appimage for OO v.7.2.1 to your Downloads folder or some separate directory. You can find the link here:
[https://github.com/ONLYOFFICE/DesktopEditors/releases/tag/v7.2.1](url)

I then edited my OnlyOffice .desktop file to change the executable location to the 7.2.1 appimage. Printing work just fine in this version.

Sure, this can be a bit of a pain (especially when updating your system). Ideally, I'll see OO has an update which I'll build, test, and see that printing is working again. Worst case, I go back into the .desktop file and manually point it to the 7.2.1 appimage executable.

Cheers!

**Comment by osoibol** [comment]
small discovery: If I go to the "print" options when my printer is turned off, the window and the application doesn't close, so theoretically I can change the options and send a document to the printing cue before turning on the printer. 

Also the "Fast Print" option seems to work fine now.

I tested this today on OnlyOffice 7.3.3.50 on my Manjaro machine.

**Comment by doubleddav** [comment]
I'm getting almost identical behaviour . Running Nixos Unstable, current version listed as "ONLYOFFICE Desktop Editors version 7.2.0.204 (deb package)"

Run KDE plasma 5.27.6

**Comment by LuckySpecialist** [comment]
Hi @doubleddav, you are watching an outdated version.
Yesterday 7.4.1 was released - [try it.](https://github.com/ONLYOFFICE/DesktopEditors/releases)

I still can't reproduce the problem on:
Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-26-generic (64-bit)
Graphics Platform: X11
ONLYOFFICE Desktop Editors version 7.4.1.36 (deb)

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by solisinvictum** [comment]
> This issue was closed due no response.

Answer from whom?

So with other words, this never get fixed?

**Comment by LuckySpecialist** [comment]
Hi, @solisinvictum!
> Answer from whom?

The answer is from those who participate in the discussion and have the same problem.

> So with other words, this never get fixed?

Fixing the problem depends on its cause. To find out, we need to repeat it in our environment and show it to developers. This has not been done yet. If you have a 100% scenario to reproduce the problem, please describe it.

This issue can be reopened if there are new facts about whether it is repeated or not.
Please note that we are considering problems only on the current version of the application.
Thanks for understanding.

**Comment by blueOkiris** [comment]
This occurs on the current NixOS build. That is reproducible. You cannot print anything.

If run in the terminal, you get a segfault
