### ISSUE TITLE
Save button is not saving

### ISSUE THREAD

**Issue by PauLuke** [ONLYOFFICE/DesktopEditors#1229]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.3.0.184

### Expected Behavior

I expected the save button to save the modifications made to the document.

### Actual Behavior

The save button does not make any changes to the edited file.

### Reproduction Steps

Open a .docx document.
Make any changes.
Click the save button.
Check the file properties to see if any changes were written to the document.

### Additional information

I'm using Arch Linux, kernel: 6.1.12-arch1-1 and I've downloaded the software from the Arch User Repository.

**Comment by visvaldas01** [comment]
Sometimes it's even worse, when you're trying to save the file, the app tells you that the file is read-only, corrupted or something and then it just becomes empty, and the only way to not lose the data is to save it as another file :(

**Comment by Rita-Bubnova** [comment]
@PauLuke Sorry for the long wait.
DesktopEditors v7.4.1 is released. Is this issue relevant?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
