### ISSUE TITLE
compile error tag ONLYOFFICE-DesktopEditors-4.4.1 on altlinux

### ISSUE THREAD

**Issue by p12** [ONLYOFFICE/DesktopEditors#123]
Error when build:

[errors.4.4.1.txt](https://github.com/ONLYOFFICE/DesktopEditors/files/2145620/errors.4.4.1.txt)

**Comment by ShockwaveNN** [comment]
Hi there, currently we have no working instruction for building DocumentEditors on AltLinux, you can monitor #4

**Comment by ShockwaveNN** [comment]
Closing this issue, since now we got building instruction for at least Ubuntu

All other question shold be discussed in [build_tools](https://github.com/ONLYOFFICE/build_tools/) repo
