### ISSUE TITLE
the dropper function is badly needed

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/DesktopEditors#1234]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

the dropper function is very necessary for the choice of colors on the screen
![Captura de pantalla 2023-03-05 202634](https://user-images.githubusercontent.com/126432941/223000326-cec2677f-40c4-4c38-aa5d-4075e7cd6202.png)
![Captura de pantalla 2023-03-05 202744](https://user-images.githubusercontent.com/126432941/223000348-325f90fa-3aa0-4683-ac55-01e9063be247.png)

**Comment by Rita-Bubnova** [comment]
This is a duplicate https://github.com/ONLYOFFICE/DesktopEditors/issues/184.
