### ISSUE TITLE
Copying an image into another presentation results in an empty image

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#1240]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.3.0

### Expected Behavior

It should be possible to copy the image in the attached presentation into another presentation.

[bug-OO-copy-image.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/10912889/bug-OO-copy-image.pptx)

### Actual Behavior

Copying the image of the attached presentation into another presentation results in an empty image.

### Reproduction Steps

Steps to reproduce:
- open the attached .pptx file
- select the image and type CTRL-C
- open an empty presentation
- copy the image with CTRL-V
- => the image is empty

**Comment by matveevms** [comment]
Hello, @parrenin 
I can confirm - this is bug, issue Bug 61808 in our issue tracker.
Thank you for report.

**Comment by parrenin** [comment]
I think this bug is now fixed in 7.4.0.

**Comment by matveevms** [comment]
Hi, @parrenin 
The problem is solved for local files, but unfortunately still present when working in the cloud. 
We'll let you know when the problem is fully fixed.

**Comment by Rita-Bubnova** [comment]
DesktopEditors v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
