### ISSUE TITLE
missing options when saving as

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/DesktopEditors#1243]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

When saving as, there are no options to customize the save, for example when saving as PDF, there are no options for quality, compression, dpi, security, password, page intervals, signatures, links, etc.
Also when saving in other formats, there are no options to customize the saving, this implementation is needed, which is very important.

example
![opciones-de-pdf-general](https://user-images.githubusercontent.com/126432941/224505572-aa3fbcfc-34da-4477-955c-d97ca21eb52e.jpg)

**Comment by MichaelFA7** [comment]
save as image or other formats.
When saving as, options are missing (choose single page, all pages, or which pages to export)

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
