### ISSUE TITLE
 The license warning box are presented,so I can't use it. 

### ISSUE THREAD

**Issue by jinjingyu** [ONLYOFFICE/DesktopEditors#125]
Hi, dear!

I am trying to build and execute OnlyOffice DesktopEditors 4.8.7.392 on windows 10 pro
I succeeded in building.
And  I run the program, The following warning box are presented, so I can't use it. 
![image](https://user-images.githubusercontent.com/40283634/42124191-06d69eb4-7c91-11e8-8cb4-cf258d539e68.png)

How do I run it with a 30-day free license?

**Comment by ShockwaveNN** [comment]
On `Build sdkjs` - step  2 did you correctly run `./build_desktop.bat` not any other script?

**Comment by jinjingyu** [comment]
I correctly run ./build_desktop.bat, why?

**Comment by ShockwaveNN** [comment]
@jinjingyu because according by our dev team this error may be cause by trying to build sdkjs for document server

**Comment by jinjingyu** [comment]
if I did not correctly run, What should I do?

**Comment by ShockwaveNN** [comment]
@jinjingyu cleanu up all builded files after that step and try to rebuild. But keep in mind that as I mention in #118 this instruction is not ready and this may be not enougth to correctly run

**Comment by jinjingyu** [comment]
sorry, Would you send me  build result of sdkjs-editors folder files?

**Comment by ShockwaveNN** [comment]
@jinjingyu you can find this folder in prebuildet deb or portable packages of `onlyoffice-desktopeditors`

**Comment by jinjingyu** [comment]
sorry, what is the url?

**Comment by ShockwaveNN** [comment]
@jinjingyu https://github.com/ONLYOFFICE/DesktopEditors/releases

**Comment by jinjingyu** [comment]
Oh, I see, thank you

**Comment by ShockwaveNN** [comment]
I think this problem is fixed since we moved to completely new build process involving [build_tool](https://github.com/ONLYOFFICE/build_tools)
