### ISSUE TITLE
Save as PDF does not report on flock etc.

### ISSUE THREAD

**Issue by paulf123b** [ONLYOFFICE/DesktopEditors#1250]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.3.3.50 (x64 exe)

### Expected Behavior

When attempting to save as and the target file cannot be written to (ie. is locked by another application,) a prompt should advise that the file cannot be written.

### Actual Behavior

It appears that the file has been saved but it is not.

### Additional information

Thanks devs for this awesome suite!

**Comment by LuckySpecialist** [comment]
Hi @paulf123b !
Issued a Bug 61780 on your request.
Thanks for the feedback!
