### ISSUE TITLE
Not working hyperlinks with &

### ISSUE THREAD

**Issue by mysoftd** [ONLYOFFICE/DesktopEditors#1253]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.3.3

### Expected Behavior

I have hyperlinks with the & symbol in my spreadsheet, e.g. "https://digi.archives.cz/da/permalink?xid=be8693d8-f13c-102f-8255-0050568c0263&scan=3009b24962eb4c5db8a340893d9d9cce". It should open normally in a web browser (I use Firefox).

### Actual Behavior

OnlyOffice opens a hyperlink with no & and no text after the & ("https://digi.archives.cz/da/permalink?xid=be8693d8-f13c-102f-8255-0050568c0263").

### Additional information

In LibreOffice and Microsoft Office (online version), opening hyperlinks works correctly. This problem is only in OnlyOffice. I use Ubuntu 22.10.

**Comment by mysoftd** [comment]
Can I ask when the next version is coming out? My Microsoft 365 license expires in 10 days and I would like to switch to OnlyOffice. The opening hyperlinks with & is very important for my work.

**Comment by LuckySpecialist** [comment]
The problem is fixed in version [7.4](https://github.com/ONLYOFFICE/DesktopEditors/releases/tag/v7.4.0)

**Comment by DenisDeeSign** [comment]
DesktopEditors v7.4.0 are released so I close this issue. Feel free to comment or reopen it if you got further questions.
