### ISSUE TITLE
"Text to columns" feature request

### ISSUE THREAD

**Issue by lexphor** [ONLYOFFICE/DesktopEditors#126]
Hello!

**Requesting a feature**

Desktop Editor Spreadsheet,  
Please allow the option to paste data in columns according to delimiters, something similar to the "text to columns" in MS office.
This is the only missing feature that prevents me from using ONLYOFFICE full time and ditching all other office suits.

Thanks and keep up the amazing work!

**Comment by HectorB-2020** [comment]
I believe it has been implemented. At least I can convert text to columns now.

![OO6](https://user-images.githubusercontent.com/64358003/103540886-830d6780-4eab-11eb-99b0-02d28e8ef955.png)

![OO7](https://user-images.githubusercontent.com/64358003/103540895-89034880-4eab-11eb-9e0b-4ce488e28b06.png)

![OO8](https://user-images.githubusercontent.com/64358003/103541168-0af37180-4eac-11eb-8e4e-85b8ac982ff4.png)

However I'd better prefer the way MS Word handles this, it permits selecting several options for decimeters: Tab, Semicolon, Comma, Space, and other.

And it allows treating several consecutive delimiters as one. This saves a lot of efforts in case of spaces or/and tabs.
I feel like submitting a separate enhancement for this.

**Comment by Rita-Bubnova** [comment]
@HectorB-2020, you are right. Function "Text to columns" implemented and we close this issue.

> However I'd better prefer the way MS Word handles this, it permits selecting several options for decimeters: Tab, Semicolon, Comma, Space, and other.
And it allows treating several consecutive delimiters as one. This saves a lot of efforts in case of spaces or/and tabs.
I feel like submitting a separate enhancement for this.

Please, create a new issue for this enhancement.

**Comment by ShockwaveNN** [comment]
Closed this issue since original enhancement was implemented
