### ISSUE TITLE
Unable to change settings in POP OS. 'APPLY' button is greyed out. 

### ISSUE THREAD

**Issue by ZephTheHungryLoli** [ONLYOFFICE/DesktopEditors#1262]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.3.3

### Expected Behavior

Changed settings should be applied. 

### Actual Behavior

Unable to apply settings.

**Comment by XDmitryK** [comment]
@ZephTheHungryLoli 
Hi, you can attach here short video where this problem repeated?

**Comment by Timur1337** [comment]
I think i figured it out:
If your user name have underscore in it, you can't apply settings. Remove underscores and everything will work as intended.

**Comment by ZephTheHungryLoli** [comment]
Thank you. Now it works. But unfortunately the Onlyoffice lacks proper
filling(fill as series, fill as formula etc) and copy and paste( paste as
text, paste as format etc)  features WHICH IS VERY IMPORTANT to me.

So as much I don't want, I'm switching to another desktop app.

**Comment by XDmitryK** [comment]
@ZephTheHungryLoli 
Sorry, our application does not support a formatted username. 
I can't share our plans, but some of the features you wrote above may be added in the future.
@Timur1337 Thanks for the help!
