### ISSUE TITLE
Incorrect scaling in 4k (everything so small)

### ISSUE THREAD

**Issue by worthant** [ONLYOFFICE/DesktopEditors#1264]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.3.3.50

### Expected Behavior

Expected to have much bigger interface, so that i can see everything properly.

### Actual Behavior

Right now with 27inch 4k monitor i can barely see anything, it is so hard to work.
![image](https://user-images.githubusercontent.com/43885024/231258266-b194d390-3c7e-471d-9220-cf7c4667021c.png)

### Reproduction Steps

1. Open ONLYOFFICE Desktop Editors

### Additional information

- GNOME Font scaling is set to 1.25/1.3/1.35 - doesn't change anything
- x64 Manjaro Linux with Gnome 43.4 X11
- Nvidia gtx 1070 graphics card

**Comment by Rita-Bubnova** [comment]
@worthant Sorry for late restonse, seems we missed this issue. 
DesktopEditors v7.4.1 is released. Please state is this problem still actual for you?

**Comment by worthant** [comment]
> @worthant Sorry for late response, seems we missed this issue. 
> DesktopEditors v7.4.1 is released. Please state is this problem still actual for you?

Sry for late response too :)

Since than i moved to Windows 10 primarily with debian virtual machine. There it seems fine, everything is ok.
On Windows 10 everything is fine too, good job :+1:

**Comment by Rita-Bubnova** [comment]
@worthant Thank you for response.
 Feel free to comment or reopen it if you got further questions.
