### ISSUE TITLE
Differences in margins between (Arch) Linux and Windows

### ISSUE THREAD

**Issue by Raj2032** [ONLYOFFICE/DesktopEditors#1265]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.3.3.50 (deb)

### Expected Behavior

I have noticed that with documents, I have noticed that when it is opened in onlyoffice, the margines are different on both Windows and (Arch) Linux distros. I am not too sure why this is.

on windows this is how it looks:

![image](https://user-images.githubusercontent.com/29293830/232223405-cfffe56b-9d56-4f6d-bf6d-31ce0ab9dce9.png)

### Actual Behavior

On Linux this is how it actually looks:

![image](https://user-images.githubusercontent.com/29293830/232223414-0e5b58f0-645c-4fea-88f4-dfdfd4a5229d.png)

and it should match what it does on Windows.

### Additional information

Here is the link to the sample document https://drive.proton.me/urls/CKK33V8S0C#lWDwP1ka4ajA

If you opened it on both windows and (Arch) Linux, you can compare the differences.

I noticed that when I opened the document on both Microsoft Office and on OnlyOffice on Windows the margins are the same, it is on Linux that does things a bit differently. I am not too sure why that is.

Open the document on libreoffice on both operating systems open's exactly the same with no differences.

**Comment by KirillovIlya** [comment]
Hello, thank you for your message.

This can happen when different font sets are used. Because the line height is depend on the font used.
Obviously, for different systems you have different font sets. 
Despite the fact that a specific font is specified in the application, if it is not present in the system, then we are looking for a substitution. Moreover, a given font may be present on both systems, but be physically different.

As a result, in order for you to have the same result, you need to use the same font sets.

**Comment by Raj2032** [comment]
@KirillovIlya 

> a given font may be present on both systems, but be physically different.

I am not too sure why I don't notice this issue on libreoffice, libreoffice works exactly the same on windows and Linux the entire document renders exactly the same. May I know how come onlyoffice does things differently?

> As a result, in order for you to have the same result, you need to use the same font sets.

![image](https://user-images.githubusercontent.com/29293830/232260686-a2d75580-e655-4703-88a9-586f1574156b.png)

This is the font that windows uses and I have installed the font on Linux by copying it from Windows to Linux and then running:

```bash
fc-cache -f
```

**Comment by KirillovIlya** [comment]
Can you share the file with this issue?

**Comment by Raj2032** [comment]
As provided in the "Additional Information" I have already provided a link to my sample document file which is this:

https://drive.proton.me/urls/CKK33V8S0C#lWDwP1ka4ajA
------- Original Message -------

**Comment by KirillovIlya** [comment]
Unfortunately, I can't download anything by the link you provided. 
Can you can attach the file right here please?

**Comment by Raj2032** [comment]
@KirillovIlya Strange,

I have attached the file over here then:
[Sample.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/11286369/Sample.docx)

**Comment by KirillovIlya** [comment]
I tested your file on a clean install of Ubuntu. 
The result was exactly the same on your screen. The problem, as I said, is in the font set. This file needs "symbol" font which is not found in the default font set for any Linux. I installed this font in the system and got the same result as on the Windows.

**Comment by Raj2032** [comment]
What exact font did you install @KirillovIlya to get the result as found on Windows?
