### ISSUE TITLE
Cell format not applied

### ISSUE THREAD

**Issue by guijusto** [ONLYOFFICE/DesktopEditors#1266]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.3.3.50 (x64 msi)

### Expected Behavior

Cell format is only actually changed after double click on it or after a replace.

### Actual Behavior

Cell format changes should be applied immediately.

### Reproduction Steps

1. Open a XLSX file containing number as text/general format.
2. Select one cell or cell range.
3. Right mouse click -> Number Format -> change from General to Number.
4. The cells are not recognized as numbers (content is still on the left side).
5. Double click on the cell + enter and now it is detected as number.

### Additional information

Interface language: English
Region: Português (Brasil)
If the content is copied to Notepad then pasted back it is detected as number.

**Comment by rsnegirev** [comment]
Hi @guijusto 

We cannot reproduce this behavior with the specified steps, in our cases everything works correctly.

Could you send a file with an error and make a screencast with your actions, please?

**Comment by guijusto** [comment]
Hello @rsnegirev 
Here's the link for the screencast and XLS file:
https://cloud.2vintens.com.br/index.php/s/eXxBjSfoWQkb7DZ

**Comment by rsnegirev** [comment]
We've compared the behavior with MS Excel and it's identical to the behavior in our editor.

So this behavior is considered as normal.
