### ISSUE TITLE
Paste as Plain Text hotkey (e.g., CTRL+SHIFT+V) missing

### ISSUE THREAD

**Issue by gmejzej** [ONLYOFFICE/DesktopEditors#1267]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows XP / Vista, Windows 10 / 8.1 / 7, Linux (DEB package), Linux (RPM package)

### Version information

v7.3.3.49

### Expected Behavior

Being able to paste content as Plain Text with a hotkey (e.g., CTRL+SHIFT+V) is critical need for a document editor. OnlyOffice is missing this. Please add ASAP.

### Actual Behavior

When user has content in the clipboard and presses CTRL+SHIFT+V, nothing happens.

### Reproduction Steps

1. With content in clipboard, press CTRL+SHIFT+V
3. see that content has been pasted in Plain Text
4.

**Comment by VladimirProkofiev52** [comment]
Hi! @gmejzej,
I find the bug, issue 42393 in our private issue tracker.
Our experts are still working on this issue.

Problem can be reproduced in DocumentServer.
Thank you for report.

**Comment by Rita-Bubnova** [comment]
This problem is discussed in https://github.com/ONLYOFFICE/DocumentServer/issues/1002 too.
