### ISSUE TITLE
[feature request] dark theme sheet viewer

### ISSUE THREAD

**Issue by gmankab** [ONLYOFFICE/DesktopEditors#1275]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

hello

i noticed that in onlyoffice you can view documents using a dark theme, but you cannot view sheets using a dark theme

please add this feature to sheets too

**Comment by Rita-Bubnova** [comment]
The issue actual in Document Server. 
I think, this is duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/1944.
