### ISSUE TITLE
Please publish Windows XP version in the assets as well

### ISSUE THREAD

**Issue by jeditobe** [ONLYOFFICE/DesktopEditors#1277]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows XP / Vista

### Version information

7.3.3

### Expected Behavior

Please publish Windows XP version in the assets as well

### Actual Behavior

there is no link on github with Windows XP version

**Comment by xmha97** [comment]
+1

**Comment by jeditobe** [comment]
hi! Any news?

**Comment by TatianaKirillova** [comment]
Hello, @jeditobe Thanks for your request!
I can confirm that the problem exists. 
I created issue #63692  with your proposal.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by jeditobe** [comment]
amazing! thanx

**Comment by xmha97** [comment]
Thanks
