### ISSUE TITLE
Fix Following OS theme on Ubuntu 23.04

### ISSUE THREAD

**Issue by xmha97** [ONLYOFFICE/DesktopEditors#1278]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (Snap package)

### Version information

7.3.3.50

### Expected Behavior

Follow OS theme.

# Light
![Screenshot from 2023-04-26 05-19-59](https://user-images.githubusercontent.com/23485114/234445628-a170478b-95bd-4523-8847-4fe8d2989e00.png)

# Dark
![Screenshot from 2023-04-26 05-20-38](https://user-images.githubusercontent.com/23485114/234445635-98eb27ad-06d5-4023-ab72-e97d4560a16d.png)

### Actual Behavior

![Screenshot from 2023-04-26 05-17-06](https://user-images.githubusercontent.com/23485114/234445648-1398e333-cab7-454c-8ff7-50e0947539a4.png)

**Comment by anton-borisov-d1** [comment]
same thing

**Comment by XDmitryK** [comment]
@xmha97 Hi
This is known as issue 59441 in our internal issue tracker.
Thank you for report.

**Comment by xmha97** [comment]
> @xmha97 Hi This is known as issue 59441 in our internal issue tracker. Thank you for report.

Please send me your internal issue tracker, is it public?

**Comment by XDmitryK** [comment]
@xmha97 Hi
Sorry for not replying for a while. We disabled this feature in version 7.4.0 for all UNIX systems.

**Comment by Rita-Bubnova** [comment]
DesktopEditors v7.4.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by Novantric** [comment]
Reopening cause this is still an issue, especially any time I try 24.10. Installed all the flatpak colour themes for GNOME 47 and nothing. They default to what I only know as the white default/placeholder theme. 
Honestly rather infuriating cause this isn't documented in the same way anywhere else, and I've had to use the system repos instead for theme support.
![image](https://github.com/user-attachments/assets/87c3b751-3f26-4903-97ce-9fcc70937399)
