### ISSUE TITLE
Tables pasted from speadsheet to document have incorrect colors

### ISSUE THREAD

**Issue by KayJay7** [ONLYOFFICE/DesktopEditors#1280]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.3.3.50 (flatpak)

### Expected Behavior

When a table is copied and pasted from a spreadsheet to a document, it should maintain its text colors.
The colors should not only be visible, but also be visible to other applications and printed documents.

### Actual Behavior

When a table is copied and pasted from a spreadsheet to a document, it shows correctly in the editor, but trying to print to pdf produces entirely black text on said table.

Opening the same file from a different app (libre office writer) doesn't show the colors, just like the print. Opening the original spreadsheet from a different app (libre office calc) shows the colors correctly, it's an issue only on copy-pasted tables.

Applying a style directly from the document editor doesn't cause this issue, the table is colored correctly.

Manually recoloring the table in the document fixes the issue, but it's tedious. That was the whole point of copy-paste

### Reproduction Steps

1. Write a table in a spreadsheet
2. Apply colors to some fields of the table
3. Copy paste the table in a document
4. Print to pdf

### Additional information

It's actually the flatpak version of desktopeditors, not the rpm one. There is no option for flatpak in the menu.

You should add the flatpak option

**Comment by KirillovIlya** [comment]
Hello, thank you for your report.

This issue was found by our team this week. And we have already fixed it, in version 7.4.0 everything should be fine.
