### ISSUE TITLE
Taslbar doesn't appear on top of desktop-editors window

### ISSUE THREAD

**Issue by Aceler** [ONLYOFFICE/DesktopEditors#129]
Windows 10. Desktop-editors 5.1.29.348.

If a user have a setup with his taskbar hidden, opening Desktop-editors window makes the taskbar inaccessible. User can move a mouse cursor to the edge of the screen, where the taskbar is located, with no effect.

I'm not sure, if it is a Windows bug, or a Desktop-editors.

**Comment by Rita-Bubnova** [comment]
Hello, @Aceler.
Thank you. I can confirm - this is a bug, issue 36992 in our internal issue tracker.

**Comment by maximushugus** [comment]
The problem is still here with the latest version on Windows 11...

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/desktop-apps/commit/4569d5a4bb5519955d0a4ca517e30f153b8aeb36, https://github.com/ONLYOFFICE/desktop-apps/commit/0bf32d67f218a6f716ca2d70ce9ccac5299e8c8c, https://github.com/ONLYOFFICE/desktop-apps/commit/2394c15d7ad6b8a03dec0f8fbbac7ed924441ccb, https://github.com/ONLYOFFICE/desktop-apps/commit/5ed3241fd6319268603f6a6f704d90959b977947, https://github.com/ONLYOFFICE/desktop-apps/commit/1d2cf7bb0ab942b2f0a667a27f04ef2829d0b21f) in future major release.

**Comment by DenisDeeSign** [comment]
DesktopEditors v7.3.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
