### ISSUE TITLE
how to comile an rpm with repositry of desktop-apps

### ISSUE THREAD

**Issue by wusuqin** [ONLYOFFICE/DesktopEditors#1300]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

mysteps:
git clone https://github.com/ONLYOFFICE/desktop-apps.git
cd /desktop-apps/win-linux/package/linux
make clean && make rpm

then an error occurs:
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/84169940/a0194c37-f251-4eca-8c24-cef9f79fda17)

**Comment by heatray** [comment]
first build binaries with https://github.com/ONLYOFFICE/build_tools#desktop-editors

or download tar https://github.com/ONLYOFFICE/DesktopEditors/releases and extract content to `build_tools/out/linux_64/onlyoffice/desktopeditors`

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
