### ISSUE TITLE
Presentation Editor :: Unable to change text color of a text containing Hyperlinks

### ISSUE THREAD

**Issue by vagner-dias** [ONLYOFFICE/DesktopEditors#1302]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.3.3.50 (x64 exe)

### Expected Behavior

When assigning a hyperlink to a text in presentation Editor the user should be able to change the text color (Like the document editor allows, for example)

### Actual Behavior

Using the Presentation Editor, After creating a text and assigning a Hyperlink to it, I am unable to change the text color.

![2023-06-07_07h49_07](https://github.com/ONLYOFFICE/DesktopEditors/assets/86367839/6e800579-9d7d-47c5-bab1-7fc5885d59ab)

**Comment by Rita-Bubnova** [comment]
This is duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/1666.
