### ISSUE TITLE
The latest release didn't include appimage form

### ISSUE THREAD

**Issue by HCY-ASLEEP** [ONLYOFFICE/DesktopEditors#1312]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Excuse me, only appimage works on my system. That's too hard for me .

**Comment by maruacat** [comment]
Hello, @HCY-ASLEEP 
Thank you for contacting us. We are still working on a new version of the editor for AppImage and will release it a bit later.
Have a good day!
