### ISSUE TITLE
Remember last scroll position when opening document 

### ISSUE THREAD

**Issue by ags1234** [ONLYOFFICE/DesktopEditors#1318]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

When closing documents, remember last scroll position and automatically scroll there when opening that document again.
This would greatly help when editing larger documents.

**Comment by Rita-Bubnova** [comment]
This is a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/277.

**Comment by hovereffect** [comment]
This issue is still a problem, why is it marked as Closed? @DenisDeeSign

**Comment by Rita-Bubnova** [comment]
@hovereffect, The issue is closed as it is a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2289.
