### ISSUE TITLE
Add British English as interface language

### ISSUE THREAD

**Issue by emes81** [ONLYOFFICE/DesktopEditors#1319]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

This is mainly important because when English is selected as the interface language and this defaults to US English, OnlyOffice uses spiral-formate US-style dates (MM/DD/YY), which is confusing or even misleading for non-US speakers of English, who always will read 07/01/23 as the 7th of January.

**Comment by ElenaMaaya** [comment]
Hello, @emes81.
Thank you for the enhancement!
I created ticket 63276  in our internal issue tracker.

**Comment by ElenaMaaya** [comment]
Hello, @emes81! I have a good news! This issue will be fixed in the next release. Please keep checking for updates.

**Comment by Rita-Bubnova** [comment]
DesktopEditors v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
