### ISSUE TITLE
Incorrect Bengali Font Rendering in the OnlyOffice Spreadsheet

### ISSUE THREAD

**Issue by 0xMehedi** [ONLYOFFICE/DesktopEditors#1322]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, Linux (DEB package), Linux (RPM package)

### Version information

7.3.3.50 (rpm)

### Expected Behavior

Bengali font rendering works as expected in the OO Document, OO Presentation, and Form templates, but NOT in the OO Spreadsheet.

_Vowel Diacritics_ and _Conjunct Consonants_ do NOT render correctly in **Spreadsheet Cells**. Interestingly, however, it DOES render correctly in the **Formula Bar**.

I tried several typefaces, but to no avail.

LibreOffice, WPS Office, Google Docs, MS Office etc. works fine.

Related Bugs: #131 #621

Resources:
    1. [Bengali_alphabet](https://en.wikipedia.org/wiki/Bengali_alphabet)
    2. [Lohit Bengali Font](https://www.fontsc.com/font/lohit-bengali)
    3. [Lohit Devanagari Font](https://www.fontsc.com/font/download/lohit-devanagari)

### Actual Behavior

Bengali font rendering should work fine across all of the OnlyOffice Suite.

### Reproduction Steps

1. Open the attached Spreadsheet in LibreOffice.
2. Open the attached Spreadsheet in OnlyOffice.
3. LibreOffice renders Bengali Fonts correctly, while OnlyOffice does not.

File: 
[Bug_Report.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/11983040/Bug_Report.xlsx)

Screenshot: 
![Bug_Report](https://github.com/ONLYOFFICE/DesktopEditors/assets/105382817/42e5c947-789c-4abe-b743-a0ff009acef8)

### Additional information

The Spreadsheet should look like the following:

| Serial No. | Country (EN_US) | Country (BN_BD) |
| ---------- | --------------- | --------------- |
| 1          | Bangladesh      | বাংলাদেশ        |
| 2          | Indonesia       | ইন্দোনেশিয়া     |
| 3          | Latvia          | লাটভিয়া         |
| 4          | Russia          | রাশিয়া          |
| 5          | Belarus         | বেলারুশ         |

**Comment by TatianaKirillova** [comment]
Hello, @0xMehedi 
Thanks for your request!
I can confirm that the problem exists. I created ticket 63331 in our internal  tracker with your  issue.
Problem reproduces in Document Server.

**Comment by 0xMehedi** [comment]
Hi team,
I'm hoping to get a gentle update on the status of this issue which I reported back in July.
I'm eager to see this issue addressed as it significantly impacts my ability to work effectively with Bengali text in spreadsheets. Any updates you can provide would be greatly appreciated.
Thanks!

**Comment by Rita-Bubnova** [comment]
@0xMehedi I'm just a QA specialist, I'm not in position to gurantee any dates. You better contact sales@onlyoffice.com.

**Comment by Tarek-Hasan** [comment]
Thanks OO devs for addressing the issue in latest version 8.1.

**Comment by TatianaKirillova** [comment]
@0xMehedi I'm happy to announce that the issue has been fixed and is now included in version 8.1.0. Don't miss updates)

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
