### ISSUE TITLE
macOS: File opened in browser (chrom), after waking up from sleep showing alert that file do not available

### ISSUE THREAD

**Issue by ogonchar** [ONLYOFFICE/DesktopEditors#133]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
macOS 10.13: High Sierra. File opened in browser (chrom), after waking up from sleep showing alert that file do not available
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
open file in online redactor in macOS 10.13: High Sierra, chrome. lullaby your mac, then wake it up. File would be unavailiable.
**What is the expected behavior?**
File still availiable.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
macOS 10.13: High Sierra.  chrome latest update.

**Comment by Rita-Bubnova** [comment]
Hello, @ogonchar.
This is DesktopEditors issue tracker, but you described problem with Chrome browser. Please duplicate issue in https://github.com/ONLYOFFICE/DocumentServer/issues

**Comment by ogonchar** [comment]
Really sorry for that one(
