### ISSUE TITLE
Weird Tab colors and pixelation

### ISSUE THREAD

**Issue by prashantjain25** [ONLYOFFICE/DesktopEditors#1334]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.4.1.36

### Expected Behavior

Tabs should be clear without distortion

### Actual Behavior

![Screenshot_20230806_222351](https://github.com/ONLYOFFICE/DesktopEditors/assets/5137282/82db4e92-c4a4-49de-a04f-2fab8032c61f)

**Comment by prashantjain25** [comment]
`.:/ossyyyysso/:.               dolphin@dolphin-UX310UQK 
        .:oyyyyyyyyyyyyyyyyyyo:`           ------------------------ 
      -oyyyyyyyodMMyyyyyyyysyyyyo-         OS: Kubuntu 23.04 x86_64 
    -syyyyyyyyyydMMyoyyyydmMMyyyyys-       Host: UX310UQK 1.0 
   oyyysdMysyyyydMMMMMMMMMMMMMyyyyyyyo     Kernel: 6.2.0-26-generic 
 `oyyyydMMMMysyysoooooodMMMMyyyyyyyyyo`    Uptime: 5 mins 
 oyyyyyydMMMMyyyyyyyyyyyysdMMysssssyyyo    Packages: 3359 (dpkg), 25 (flatpak), 9 (snap) 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   Shell: zsh 5.9 
oyyyysoodMyyyyyyyyyyyyyyyyyyydMMMMysyyyo   Resolution: 1920x1080 
yyysdMMMMMyyyyyyyyyyyyyyyyyyysosyyyyyyyy   DE: Plasma 5.27.4 
yyysdMMMMMyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy   WM: KWin 
oyyyyysosdyyyyyyyyyyyyyyyyyyydMMMMysyyyo   WM Theme: WhiteSur-dark 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   Theme: [Plasma], WhiteSur-Dark [GTK2/3] 
 oyyyyyydMMMysyyyyyyyyyyysdMMyoyyyoyyyo    Icons: [Plasma], WhiteSur-dark [GTK2/3] 
 `oyyyydMMMysyyyoooooodMMMMyoyyyyyyyyo     Terminal: konsole 
   oyyysyyoyyyysdMMMMMMMMMMMyyyyyyyyo      Terminal Font: MesloLGS NF 11 
    -syyyyyyyyydMMMysyyydMMMysyyyys-       CPU: Intel i5-7200U (4) @ 3.100GHz 
      -oyyyyyyydMMyyyyyyysosyyyyo-         GPU: Intel HD Graphics 620 
        ./oyyyyyyyyyyyyyyyyyyo/.           GPU: NVIDIA GeForce 940MX 
           `.:/oosyyyysso/:.`              Memory: 2546MiB / 23900MiB

**Comment by prashantjain25** [comment]
`        `.:/ossyyyysso/:.               dolphin@dolphin-UX310UQK 
        .:oyyyyyyyyyyyyyyyyyyo:`           ------------------------ 
      -oyyyyyyyodMMyyyyyyyysyyyyo-         OS: Kubuntu 23.04 x86_64 
    -syyyyyyyyyydMMyoyyyydmMMyyyyys-       Host: UX310UQK 1.0 
   oyyysdMysyyyydMMMMMMMMMMMMMyyyyyyyo     Kernel: 6.2.0-26-generic 
 `oyyyydMMMMysyysoooooodMMMMyyyyyyyyyo`    Uptime: 5 mins 
 oyyyyyydMMMMyyyyyyyyyyyysdMMysssssyyyo    Packages: 3359 (dpkg), 25 (flatpak), 9 (snap) 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   Shell: zsh 5.9 
oyyyysoodMyyyyyyyyyyyyyyyyyyydMMMMysyyyo   Resolution: 1920x1080 
yyysdMMMMMyyyyyyyyyyyyyyyyyyysosyyyyyyyy   DE: Plasma 5.27.4 
yyysdMMMMMyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy   WM: KWin 
oyyyyysosdyyyyyyyyyyyyyyyyyyydMMMMysyyyo   WM Theme: WhiteSur-dark 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   Theme: [Plasma], WhiteSur-Dark [GTK2/3] 
 oyyyyyydMMMysyyyyyyyyyyysdMMyoyyyoyyyo    Icons: [Plasma], WhiteSur-dark [GTK2/3] 
 `oyyyydMMMysyyyoooooodMMMMyoyyyyyyyyo     Terminal: konsole 
   oyyysyyoyyyysdMMMMMMMMMMMyyyyyyyyo      Terminal Font: MesloLGS NF 11 
    -syyyyyyyyydMMMysyyydMMMysyyyys-       CPU: Intel i5-7200U (4) @ 3.100GHz 
      -oyyyyyyydMMyyyyyyysosyyyyo-         GPU: Intel HD Graphics 620 
        ./oyyyyyyyyyyyyyyyyyyo/.           GPU: NVIDIA GeForce 940MX 
           `.:/oosyyyysso/:.`              Memory: 2546MiB / 23900MiB 
`

**Comment by prashantjain25** [comment]
OS: Kubuntu 23.04 x86_64 
Host: UX310UQK 1.0 
Kernel: 6.2.0-26-generic 
Uptime: 14 mins 
Packages: 3359 (dpkg), 25 (flatpak), 9 (snap) 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: Plasma 5.27.4 
WM: KWin 
WM Theme: WhiteSur-dark 
Theme: [Plasma], WhiteSur-Dark [GTK2/3] 
Icons: [Plasma], WhiteSur-dark [GTK2/3] 
Terminal: konsole 
Terminal Font: MesloLGS NF 11 
CPU: Intel i5-7200U (4) @ 3.100GHz 
GPU: Intel HD Graphics 620 
GPU: NVIDIA GeForce 940MX 
Memory: 2762MiB / 23900MiB

KDE/Gnome both Whitesur theme

**Comment by matveevms** [comment]
After installing the WhiteSur-Dark theme, I do not have the same problem with pixels. Please tell me if this problem occurs again when using other themes?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by Qianxilihulu** [comment]
> After installing the WhiteSur-Dark theme, I do not have the same problem with pixels. Please tell me if this problem occurs again when using other themes?

I have the same issue. And I can confirm this problem occurs no matter what themes I use. 

the output from terminal is:
```
% onlyoffice-desktopeditors 
QFont::fromString: Invalid description 'Sarasa UI SC,10,-1,5,600,0,0,0,0,0,0,0,0,0,0,1,SemiBold'
QFont::fromString: Invalid description 'Fira Code,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Sarasa UI SC,10,-1,5,600,0,0,0,0,0,0,0,0,0,0,1,SemiBold'
QFont::fromString: Invalid description 'Sarasa UI SC,10,-1,5,600,0,0,0,0,0,0,0,0,0,0,1,SemiBold'

(DesktopEditors:516254): Gtk-WARNING **: 17:20:33.549: gtk_disable_setlocale() must be called before gtk_init()
```

I'm using KDE plasma on Arch Linux. Here's my font configuration:
![image](https://github.com/user-attachments/assets/f7ef2e46-5ce4-455d-84ca-27a98e33db40)
