### ISSUE TITLE
 F12 does not open Developer Console for debugging Macros

### ISSUE THREAD

**Issue by KhalfaniW** [ONLYOFFICE/DesktopEditors#1341]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.4.1.36 (snap)

### Expected Behavior

The documentation here https://api.onlyoffice.com/plugin/debugging says 

F12 should open the developer console as described here

Maybe that is for debugging online version. If so, the documentation should be clearer.

### Actual Behavior

F12 does nothing

### Additional information

I opened developer console by following the instructions here

https://api.onlyoffice.com/desktop/debugging#linux

I ran open office with the `--ascdesktop-support-debug-info` flag and pressed F1

**Comment by l8556** [comment]
Hi, KhalfaniW !

To run DevTools in Desktop Editor to debug macros, you need:
— Open Desktop Editor with flag `---ascdesktop-support-debug-info`.
— Open plugin macros
— Press `F1`.

You can find more information about running DevTools in Desktop Editor here: https://api.onlyoffice.com/desktop/debugging#linux.

F12 – opens browser DevTools and can be used to debug macros in Document Server

**Comment by KhalfaniW** [comment]
The documentation here
 https://api.onlyoffice.com/plugin/debugging 

Should say you need to do that.to open devtools.

The documentation was very confusing fro me

**Comment by trofim24** [comment]
@KhalfaniW thanks for your additions. I add instructions for Desktop Editors in API
