### ISSUE TITLE
Selecting format from the toolbar overrides font typeface selection

### ISSUE THREAD

**Issue by Mr-Blue-Sky-Candy** [ONLYOFFICE/DesktopEditors#1342]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.4.1.36 (flatpak)

### Expected Behavior

After selecting a font, I expect the format to honour my preference for typeface selection. Boldness and size can change of course but typeface is not related to format

### Actual Behavior

Selecting format from the toolbar overrides font typeface selection

### Reproduction Steps

1. Change typeface to GNU free serif.
2. Click on the Heading 1 format
Observe the typeface is no longer GNU free serif.

**Comment by XDmitryK** [comment]
@Elshirak 
Can you attach a short video where the problem is reproduced?I can't reproduce the problem according to your steps, maybe I'm doing something wrong

https://github.com/ONLYOFFICE/DesktopEditors/assets/46962983/51bdd927-d2c1-405e-bca5-3ed7650d7277

**Comment by Mr-Blue-Sky-Candy** [comment]
Yes that is exactly the behaviour it should perform but I do not have it. Neither with native installation nor Flatpak.
[Kooha-2023-08-17-14-05-31.webm](https://github.com/ONLYOFFICE/DesktopEditors/assets/131680576/29e14417-67f6-47d5-b888-e6b902852d03)
[Kooha-2023-08-17-14-16-16.webm](https://github.com/ONLYOFFICE/DesktopEditors/assets/131680576/794d4ee8-bf58-46fb-ac76-4a83a15e60c2)

**Comment by XDmitryK** [comment]
@Mr-Blue-Sky-Candy
I understand you, but this behavior is conceived by our developers and there will be no change in the behavior scheme yet
For example, in MS Word and LibreOffice, when you click on the heading style, then all settings are taken from this preset, including the font
In our case, certain settings are first applied without changing the font, and when you click on the heading style again, the default settings for this style are already applied.

**Comment by Mr-Blue-Sky-Candy** [comment]
I reinstalled deleting every remaining file in .local/.config/.cache and this is resolved.
