### ISSUE TITLE
disable recover mode

### ISSUE THREAD

**Issue by cdx08222028** [ONLYOFFICE/DesktopEditors#1349]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

we don't want that our documents are copied to another place. Can we have methods to disable recover mode.

**Comment by LuckySpecialist** [comment]
Hi @cdx08222028, you can disable the `Autorecover` function in the menu `File` > `Advanced Settings` > `Editing and saving` for each editor independently.

**Comment by cdx08222028** [comment]
> Editing

Thanks a lot! I didnt checked the Autorecover option, but the app still copy the documents to the path ..\data\recover.  actually I don't want the recover mode at all (create, copy, read, write). I wanna change this behavior in the source code or cmd line.

**Comment by cdx08222028** [comment]
> Hi @cdx08222028, you can disable the `Autorecover` function in the menu `File` > `Advanced Settings` > `Editing and saving` for each editor independently.

Thanks a lot! I didnt checked the Autorecover option, but the app still copy the documents to the path ..\data\recover. actually I don't want the recover mode at all (create, copy, read, write). I wanna change this behavior in the source code or cmd line.

**Comment by LuckySpecialist** [comment]
The data in this directory is used while the application is working with documents. This cannot be changed.
If the `Autorecover` option is disabled, they are cleared after restarting the editors, even if the changes have not been saved.

**Comment by cdx08222028** [comment]
> The data in this directory is used while the application is working with documents. This cannot be changed. If the `Autorecover` option is disabled, they are cleared after restarting the editors, even if the changes have not been saved.

 I had changed a little code to change this behavior. thanks again.
