### ISSUE TITLE
[Aur] Traditional Chinese support in OnlyOffice DesktopEditors

### ISSUE THREAD

**Issue by kennethso168** [ONLYOFFICE/DesktopEditors#135]
I know Chinese display problems have been reported here, such as #82 . However, the behaviour on my system is different and I believe it has a different cause. Therefore I opened a new issue here.

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Chinese characters are shown as invisible characters, even when changed to a font with Chinese characters. Often, opening a document with Chinese characters makes OnlyOffice DesktopEditors hang at the loading screen.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I have two test documents here to demonstrate the issue.

***Document 1***
[test.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/2276978/test.docx)

This document was created by Microsoft Office 2016 with a single line of "這是一段測試文字。". However, under OnlyOffice, the characters are displayed as invisible characters, **not even boxes are shown**.
![screenshot_20180810_153413](https://user-images.githubusercontent.com/5262487/43944877-064714dc-9cb3-11e8-9c0d-66b714e3d23e.png)

I also tried to change the font from "Calibri" to some installed Chinese fonts such as Noto Sans CJK TC Regular. But the characters are still invisible. Unlike #82, in which the user can show the characters by changing to a Chinese font.
![screenshot_20180810_153622](https://user-images.githubusercontent.com/5262487/43945000-6f931102-9cb3-11e8-90f5-8cdfbcd147d1.png)

***Document 2***
[何謂二十四節氣.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/2276999/default.docx)

This document was created a long time ago, possibly by Microsoft Office 2007. It contains large paragraphs of Chinese text.

When opening the document from OnlyOffice DesktopEditors, OnlyOffice becomes stuck in the loading screen for over a minute:
![screenshot_20180810_154137](https://user-images.githubusercontent.com/5262487/43945233-1d7b8a60-9cb4-11e8-9191-3b5e508fecd8.png)

While LibreOffice opens the document successfully:
![screenshot_20180810_154526](https://user-images.githubusercontent.com/5262487/43945358-6e5fd1f2-9cb4-11e8-8c9d-f50b3d338bd6.png)

In fact, many of my Chinese documents failed to open under DesktopEditors

**What is the expected behavior?**

OnlyOffice DesktopEditors can open the documents successfully with Chinese characters visible.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

OnlyOffice DesktopEditors 5.1.29.350

Manjaro KDE ([System Info](https://gist.github.com/kennethso168/06f1201ebd81ddd48a838170302a5357))

I haven't tried previous versions.

Thank you.

**Comment by ShockwaveNN** [comment]
Seems this have something to do with your OS, we just tried both of your issues (this and #134)
And everything working fine on our Ubuntu-Kubuntu systems, I downloading manjaro now to try it, but I'm not sure it OS dependent, more like something in configs of your system.
Could you try to reproduce your issues on other PC's?

**Comment by ShockwaveNN** [comment]
@kennethso168 just notice that Manjaro is arch linux, and we have no Arch-specific package for it. Did you use `snap` of `AppImage` version of DesktopEditors

**Comment by kennethso168** [comment]
Oh I'm using the AUR version from here (https://aur.archlinux.org/packages/onlyoffice-bin)
I know this isn't supported. But any guidance for debugging the problem would be greatly appreciated (e.g. are there any logs? I only get the following output when running from the command line)
```
./DesktopEditors: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/libascdocumentscore.so)
/opt/onlyoffice/desktopeditors/DesktopEditors: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/libascdocumentscore.so)
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
/opt/onlyoffice/desktopeditors/converter/x2t: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/converter/x2t)
/opt/onlyoffice/desktopeditors/converter/x2t: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/converter/libdoctrenderer.so)
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/libascdocumentscore.so)
```
Off-topic:
By the way, after you've mentioned AppImage, I also tried running the AppImage version but I run into [this issue](https://github.com/ONLYOFFICE/appimage-desktopeditors/issues/3)

**Comment by kennethso168** [comment]
I tried this, but the same error still occurs and the problem isn't solved

**Comment by kennethso168** [comment]
I also tried the snap version and the same problems (including #134 and this one) still exist. Should I also open an issue there?

I may also test in a clean VM or ask other Manjaro users on the Manjaro forum to test this to see if this is a distro-specific problem, but this will take some time.

**Comment by ShockwaveNN** [comment]
@kennethso168 I just tried aur on  Archlinux image from Osboxes.Org and it just gelive me segmentation failt. I'm installing Manjaro by now and take a look at snap.

**Comment by ShockwaveNN** [comment]
@kennethso168 Ok, clean Manjaro install with https://aur.archlinux.org/packages/onlyoffice-bin opened your file without any troubles
![image](https://user-images.githubusercontent.com/668524/43959365-3b35ba6e-9cb7-11e8-835a-c2f52bfa3bce.png)

**Comment by ShockwaveNN** [comment]
@kennethso168 same with snap - a lot of warnings in console but file opened
![image](https://user-images.githubusercontent.com/668524/43959799-b41883fc-9cb8-11e8-849e-1130dfd1ff2b.png)

**Comment by kennethso168** [comment]
Thank you very much for testing that in a VM. It should be a problem of my system then.
Closing the issue.

**Comment by ShockwaveNN** [comment]
@kennethso168 if you will able detect what is the reason of such behaviour - it will be good.
I'm not sure - but probably some of fonts installed on your system
