### ISSUE TITLE
converted pdf display

### ISSUE THREAD

**Issue by cdx08222028** [ONLYOFFICE/DesktopEditors#1354]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I change fileconverter a little. the pdf were converted to the result files. and then the cef loaded these files to  display. I got a blank page.
Doesn't the app suppport that the converted pdf display in the cef?

I get  some hints:
sUrl: file:///D:\Program Files (x86)\ONLYOFFICE\DesktopEditors/editors/web-apps/apps/api/documents/index.html?

sParams: placement=desktop&filetype=pdf&mode=view&lang=en-US&username=h&location=CN&mode=view&title=6.pdf

![IMG_7066(20230823-162658)](https://github.com/ONLYOFFICE/DesktopEditors/assets/15779503/5028b627-9372-421f-88dd-817e8f360c63)

**Comment by LuckySpecialist** [comment]
Hi @cdx08222028, please describe your problem in detail, what specific modification are we talking about?
Attach the source file and the result.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
