### ISSUE TITLE
sharing mode OSX

### ISSUE THREAD

**Issue by julien71510** [ONLYOFFICE/DesktopEditors#1360]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.4.1

### Expected Behavior

How can i have the sharing mode?

<img width="654" alt="Capture d’écran 2023-09-02 à 00 22 02" src="https://github.com/ONLYOFFICE/DesktopEditors/assets/144050558/948cd58c-67f3-4038-9b24-f5867cf12cc4">

<img width="1061" alt="Capture d’écran 2023-09-04 à 18 44 37" src="https://github.com/ONLYOFFICE/DesktopEditors/assets/144050558/6182bac7-2018-43e6-8d13-750b5b535fb8">

<img width="1357" alt="Capture d’écran 2023-09-04 à 18 47 34" src="https://github.com/ONLYOFFICE/DesktopEditors/assets/144050558/aaa9ceb7-7cbf-42d2-adb5-31d1a831385e">

### Actual Behavior

XXX

### Reproduction Steps

<img width="654" alt="Capture d’écran 2023-09-02 à 00 22 02" src="https://github.com/ONLYOFFICE/DesktopEditors/assets/144050558/948cd58c-67f3-4038-9b24-f5867cf12cc4">

<img width="1061" alt="Capture d’écran 2023-09-04 à 18 44 37" src="https://github.com/ONLYOFFICE/DesktopEditors/assets/144050558/6182bac7-2018-43e6-8d13-750b5b535fb8">

### Additional information

XXX

**Comment by LuckySpecialist** [comment]
Hi @julien71510, advise you to first refer to the official help ([example](https://helpcenter.onlyoffice.com/userguides/groups-guides-documents-collaborative-editing.aspx)), and if you have any additional questions, describe in more detail what you want and what does not work in your opinion.
It's not very clear to me yet what your problem is.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
