### ISSUE TITLE
XLOOKUP not returning right output

### ISSUE THREAD

**Issue by oazadomer** [ONLYOFFICE/DesktopEditors#1361]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System
Arch linux 
Linux (DEB package)

### Version information

ONLYOFFICE Desktop Editors version 7.4.1.36 (deb)

### Expected Behavior

Not returning my all columns which they are 3  but its returning only the first column

### Actual Behavior

Not returning my all columns which they are 3  but its returning only the first column
![Formula](https://github.com/ONLYOFFICE/DesktopEditors/assets/110857012/48501ca7-a34b-4aff-80c9-5a09db216926)
![output](https://github.com/ONLYOFFICE/DesktopEditors/assets/110857012/182b8af0-2a7b-4799-ae15-430f4a7900b0)

**Comment by Rita-Bubnova** [comment]
Hello, @oazadomer.
Could you attach file with problem?

**Comment by oazadomer** [comment]
It's not accepting to upload xlsx file so I upload it as  jpg so please just change the extension to xlsx
![Formulas](https://github.com/ONLYOFFICE/DesktopEditors/assets/110857012/3e30dc36-f054-4a9f-924b-dd8116a14e59)

**Comment by rsnegirev** [comment]
Hi @oazadomer 

I see the difference between your screenshots and the XLSX file you sent.

In the spreadsheet the XLOOKUP formula has a different arguments and an additional columns:
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/65603548/579f2b76-40cc-4351-8822-1b5cc338018b)

And in the file formula works correctly:
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/65603548/a7454a40-18fa-47c0-b4b3-b4577b567d30)


If we're talking about your screenshots example - you should highlight cells array B3:D3, enter the formula and apply it by Ctrl+Shift+Enter shortcut (this is [how](https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Spreadsheet-Editor/UsageInstructions/InsertArrayFormulas.aspx) array formulas work in that moment):
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/65603548/406815b8-2e96-41ea-be6d-4838fc41a898)

Result:
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/65603548/2465e286-1d27-49d7-9df1-2d8f277d0078)

**Comment by oazadomer** [comment]
It's same I just copy paste it and delete a few column to make it easy for screenshot what is important the function is not working

**Comment by rsnegirev** [comment]
@oazadomer, the function is working.

As I said if you need an array for the result,  you should highlight cells array B3:D3, enter the formula and apply it by Ctrl+Shift+Enter shortcut.

**Comment by rsnegirev** [comment]
@oazadomer do you have any additional questions?

**Comment by oazadomer** [comment]
Thank you no more question, But about XLOOKUP didn't either the CTRL + SHIFT + ENTER worked same problem returning just the first column
Best regards

**Comment by rsnegirev** [comment]
You should highlight cells array first.

For example, you need a result from three columns, which should occupy three cells. You're highlighting three cells, inserting or typing a formula, and then applying it by the Ctrl+Shift+Enter shortcut.

If you need a result from four columns - you highlighting four cells, etc.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
