### ISSUE TITLE
Can't access Nextcloud which uses SSO/SAML

### ISSUE THREAD

**Issue by zeitue** [ONLYOFFICE/DesktopEditors#1368]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher, Linux (DEB package)

### Version information

7.4.1.36

### Expected Behavior

- Open ONLYOFFICE
- Click `Connect to cloud`
- Click `Nextcloud`
- Type in address of cloud.example.com
- Click `Connect now`
- See cloud interface and sign in

### Actual Behavior

- Open ONLYOFFICE
- Click `Connect to cloud`
- Click `Nextcloud`
- Type in address of cloud.example.com
- Click `Connect now`
- See no internet connection error

### Reproduction Steps

Try `connect to cloud` on a Nextcloud instance which uses SSO/SAML

### Additional information

I also tested using direct login and a even tried to do rewrites in the reverse proxy to make it work. Nothing tried worked, however, I found that in the Nextcloud documentation that setting HTTP header `OCS-APIREQUEST=true` and logging in via `/login/flow` should work. The interface for OnlyOffice Desktop Editors does not allow entering the URL or changing the HTTP headers.

**Comment by zeitue** [comment]
I've done further testing and modified the reverse proxy to try to emulate what the Nextcloud client on Android does. I set it up where if the user agent matches the Desktop OnlyOffice it will add the header `OCS-APIREQUEST=true` and redirect to `/login/flow`.  After doing this I am able to get the login screen and a place to enter a token, however, when I sign in this way I get the same no connection error after hitting the login button.

**Comment by LuckySpecialist** [comment]
Hi @zeitue, I apologize for the long answer.
I was unable to configure the environment to use SSO/SAML authorization to repeat your problem, since all NextCloud documentation for this is paid.
Is the problem still relevant to you when using the new version of the app?

**Comment by zeitue** [comment]
Would it help if I could give a docker-compose file that contains the whole environment?
Our setup consists of Nextcloud using Authentik with SAML. I have other instances which don't use SSO and they don't have this issue.

**Comment by LuckySpecialist** [comment]
> Would it help if I could give a docker-compose file that contains the whole environment?

If possible, we can try this option.

> Our setup consists of Nextcloud using Authentik with SAML. I have other instances which don't use SSO and they don't have this issue.

As far as I understand, in the new version 8.0 you still have the problem?

**Comment by zeitue** [comment]
In version 8.0 we get a no connection error
![Screenshot_20240220_150709-obfuscated](https://github.com/ONLYOFFICE/DesktopEditors/assets/7822272/9c82ebfe-fcdf-4768-951c-b7122f5e2ab7)

But there is internet connection and I'm able to connect to another Nextcloud instance without SSO and it works.

**Comment by zeitue** [comment]
I've set up a VPS with Nextcloud AIO + ONLYOFFICE  + Authentik for you to use in testing.

The hostnames are:
* https://cloud.zala.host
* https://id.zala.host

Here is a user for you:
username: LuckySpecialist
password: Lucky4Sure!

**Comment by zeitue** [comment]
Is there any update on this issue?

**Comment by zeitue** [comment]
I've tested this now with a Nextcloud instance using OpenID Connect instead of SAML and it results in the same issue.

**Comment by zeitue** [comment]
Based on what I can tell, this is due to ONLYOFFICE not being able to handle a redirect, which is needed when logging in with anything other than the built-in authentication of Nextcloud.

**Comment by LuckySpecialist** [comment]
Hi, @zeitue, I apologize for silence.
I handed over your stand to the developers, but I did not receive a specific response from them, so I did not write to you.
Now I see that your test server is no longer active to ask the developers about the problem again. Is it possible to turn it on or is it no longer available?

**Comment by zeitue** [comment]
It got messed up, and I saw no response, so I deleted it. The issue may be caused by the redirect, which occurs when you go through an SSO provider.

**Comment by LuckySpecialist** [comment]
I understood, in any case, this is not supported yet and is not included in the immediate plans, as I learned from the developers.
Maybe we'll come back to this later.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
