### ISSUE TITLE
OnlyOffice try save something, even there is nothing to save.

### ISSUE THREAD

**Issue by henadzi** [ONLYOFFICE/DesktopEditors#137]
feature

What is the current behavior?
Every time I push Ctrl+S on localy installed OnlyOffice - it try save something, even there is nothing to save.
What is the expected behavior?
MS Office do not save document if there is nothing to save.
Operating System:
Windows -10. Local installed OnlyOffice.

**Comment by henadzi** [comment]
Localy installed version 5.1.29.348.

**Comment by HellRoad** [comment]
Yes it is bug.
i'm posted this in local bugtracker
Thanks you feedback

**Comment by ShockwaveNN** [comment]
Version 5.2.4 of DesktopEditors was released and issue should be fixed.
