### ISSUE TITLE
Can’t change to fr-FR my whole document, always stays in en-US

### ISSUE THREAD

**Issue by TomBonnot** [ONLYOFFICE/DesktopEditors#1370]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.4.1.36 

### Expected Behavior

Select language "Français (France)" then start typing and the software automatically search for errors and typos in French. 

### Actual Behavior

Select language "Français (France)" then start typing and the software automatically search for errors and typos in English (US). 

### Reproduction Steps

1. Open a document 
2. Set the language in Français (France)
3. Start typing 
4. Software automatically changes it in English (US)

### Additional information

I am using a QWERTY (US) Keyboard because the layout United Stated International is one of the best out there, it SHOULDN’T be interfering in ANY WAY in which language I want to write in. 

I just tested and it is the keyboard layout that does this. It shouldn’t be.

**Comment by ElenaMaaya** [comment]
Hello @TomBonnot!
Thank you for report!
To work around this, switch to settings: Settings -> Spelling language detection -> Disabled.
This setting is current for Desktop Editors on Windows.
Waiting for your feedback. 
![spelling](https://github.com/ONLYOFFICE/DesktopEditors/assets/96118677/17976925-0609-4bbe-be61-36cbd7ca1b77)

**Comment by Bakaba** [comment]
Hello, I have the same issue. I've tested your workaround and it works. It solve another issue I've reported too (#1388)

**Comment by Rita-Bubnova** [comment]
@TomBonnot, This issue was closed due no response.
