### ISSUE TITLE
Form-fillable PDF support

### ISSUE THREAD

**Issue by FreshRoyal** [ONLYOFFICE/DesktopEditors#1376]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

OnlyOFFICE has really good support for reading PDFs, but there's pretty much no support for fillable aspects of them. I am unsure how complicated it would be, but it would be very appreciated.

**Comment by TatianaKirillova** [comment]
Hello @FreshRoyal! I apologize for the long response! Do you mean filling out objects in pdf such as form fields, for example?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
