### ISSUE TITLE
display problem - 显示问题

### ISSUE THREAD

**Issue by ryanzhaorx** [ONLYOFFICE/DesktopEditors#1380]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.4.1

### Expected Behavior

Normal font display
字体正常显示

### Actual Behavior

Font display thickness issues
字体显示粗细问题

### Reproduction Steps

Such as  "静" "陀" "院附"等字

**Comment by TatianaKirillova** [comment]
Hello, @ryanzhaorx 
Thanks for your request!
Please clarify the scenario. Can't reproduce the problem

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
