### ISSUE TITLE
Temporary files are not hidden on Linux

### ISSUE THREAD

**Issue by mikhailnov** [ONLYOFFICE/DesktopEditors#1384]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.3.3-201.p8

### Expected Behavior

I open a pptx file in DesktopEditors. A temporary file named `~$*` is created in the same directory (on the Desktop in my case):

![2023-10-12_08-06](https://github.com/ONLYOFFICE/DesktopEditors/assets/15802528/7a01ac82-2765-4bc2-8e85-5f9f55f99323)

This file should be hidden. "Hidden" is an attribute of file in Windows (NTFS), but, on GNU/Linux, hidden files must be named starting with dot. Such files are automatically considered hidden, and such file would not be shown on my XFCE desktop:

![2023-10-12_08-11](https://github.com/ONLYOFFICE/DesktopEditors/assets/15802528/e388ed7f-72a0-4cb0-9fc5-bc96820ddda5)

But, unfortunately, temporary junk from DesktopEditors is shown.

I suggest to name temporary files starting with dot.

**Comment by mikhailnov** [comment]
Other people also complain about this: https://t.me/c/1523335600/66724

**Comment by matveevms** [comment]
Hello, @mikhailnov 
Sorry for delay. 
Does the problem recur now on new versions of the desktop editor?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
