### ISSUE TITLE
Disable "Help" page in file menu to prevent Onlyoffice internet access

### ISSUE THREAD

**Issue by onny** [ONLYOFFICE/DesktopEditors#1395]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hey,
anytime I open the "File" tab in Onlyoffice Desktopeditors, the "editors_helper" application tries to connect to various IPs propably connected to onlyoffice.com.

![screenshot_2023-10-21-114045](https://github.com/ONLYOFFICE/DesktopEditors/assets/757752/97ecf94f-8127-403b-bcb0-764957102bb2)

For privacy reasons, this should be avoided because as long as I don't use the "Help" menu which propably loads the content from the Internet, I don't want to get tracked.

It would be even better if Onlyoffice ships the help files so no network connection is required at all.

Best regards
Jonas

**Comment by onny** [comment]
My package uses https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v${version}/onlyoffice-desktopeditors_amd64.deb as source

**Comment by LuckySpecialist** [comment]
> My package uses [https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v${version}/onlyoffice-desktopeditors_amd64.deb](https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v$%7Bversion%7D/onlyoffice-desktopeditors_amd64.deb) as source

Please update the app version to the [latest one](https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v7.5.1/onlyoffice-desktopeditors_amd64.deb), install [this](https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v7.5.1/onlyoffice-desktopeditors-help_all.deb) package additionally and check if your problem will be relevant?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
