### ISSUE TITLE
Update included vcredist 2013

### ISSUE THREAD

**Issue by o-l-a-v** [ONLYOFFICE/DesktopEditors#1396]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

7.5.0 installs VCRedist (Microsoft Visual C++ 2013 Redistributable) 2013 v12.0.30501.0, but it seems v12.0.40664.0 is the newest one according to:

* https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?#visual-studio-2013-vc-120

**Comment by LuckySpecialist** [comment]
Hi @o-l-a-v!
This component is no longer required for the application to work and [will be removed](https://github.com/ONLYOFFICE/desktop-apps/commit/28ecb71051c079eb265515a07ba06c9ed8fbde4d) in the next major release.
Thank you for contacting us.

**Comment by Rita-Bubnova** [comment]
Desktop Editors v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
