### ISSUE TITLE
ClearType is not used for text rendering in Table editor, so the text quality is much worse than in Excel and LibreOffice Calc

### ISSUE THREAD

**Issue by mobius217** [ONLYOFFICE/DesktopEditors#1397]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.5.0.127 (x64 exe)

### Expected Behavior

ClearType should be used for quality text rendering.

### Actual Behavior

ClearType is not used for text rendering in Table editor.

**Comment by ElenaMaaya** [comment]
Hello @mobius217! Thank you for report! Please If you have a specific example give it. Thank you!

**Comment by LuckySpecialist** [comment]
The explanation can be read [here](https://github.com/ONLYOFFICE/DesktopEditors/issues/1398#issuecomment-1849876429). Not planned.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
