### ISSUE TITLE
An error occurred while opening the file

### ISSUE THREAD

**Issue by lewis600** [ONLYOFFICE/DesktopEditors#1399]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.5.0 (541) x86_64

### Expected Behavior

An error occurred while open or new document file,screenshot：
![WX20231026-143559@2x](https://github.com/ONLYOFFICE/DesktopEditors/assets/3233316/f9974938-e510-431d-9660-5de8bf9892db)

### Actual Behavior

Open or new document file

**Comment by lewis600** [comment]
Crash report:
[x2t.log](https://github.com/ONLYOFFICE/DesktopEditors/files/13173782/x2t.log)

**Comment by Gingetsu** [comment]
Hello @lewis600! This is known issue Bug 64602 in our internal tracker. We will fix it in the hotfix. Thank you for report.

**Comment by lewis600** [comment]
Thank you for your support. It has been fixed. Great!

**Comment by Rita-Bubnova** [comment]
DesktopEditors v7.5.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
