### ISSUE TITLE
Updater version bug

### ISSUE THREAD

**Issue by SimoB** [ONLYOFFICE/DesktopEditors#140]
I've just downloaded and fresh installed latest version from https://github.com/ONLYOFFICE/DesktopEditors/releases/download/ONLYOFFICE-DesktopEditors-5.1.27/DesktopEditors_x64.exe

After the installation the updater is telling me I'm running 4.8.7.392

![cattura](https://user-images.githubusercontent.com/4073645/46203108-0331e380-c319-11e8-953c-843a9569d788.JPG)

**Comment by maxkadushkin** [comment]
fixed
