### ISSUE TITLE
Missing assets for the latest release (7.5.1)

### ISSUE THREAD

**Issue by Antiz96** [ONLYOFFICE/DesktopEditors#1404]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.5.1

### Expected Behavior

Having assets/artifacts for the latest release (7.5.1)

### Actual Behavior

There's no other assets than the `dmg` files in the latest release (7.5.1). Meaning there's no `rpm`, `exe`, `msi`, `deb`, ..., available.
 

### Additional information

Hi,

The latest release (7.5.1) do not have any other assets than the `dmg` files currently, meaning that every person/package that depends on other assets as a source (`rpm`, `exe`, `msi`, `deb`, ...,) cannot perform the update for now.

I wasn't sure if the GitHub issues are the right place to raise this. If not, I'm sorry.
Thanks for your wonderful work with ONLYOFFICE by the way! :slightly_smiling_face:

**Comment by Rita-Bubnova** [comment]
Hello, @Antiz96.
Thank you for the question.
Other packages will be available later. Stay tuned.

**Comment by TurboBlaze** [comment]
Hi @all,

+1 I am waiting othes packages too.

Thanks

**Comment by Antiz96** [comment]
I see the v7.5.1 has been re-made with all the missing packages.

Thanks!
