### ISSUE TITLE
OnlyOffice crashes and doesn't start

### ISSUE THREAD

**Issue by Korne127** [ONLYOFFICE/DesktopEditors#1409]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.5.1

### Expected Behavior

When opening OnlyOffice, it should start as usual.

### Actual Behavior

When opening OnlyOffice, it doesn't open and immediately crashes.
When opening it via the search bar, this error window opens after the crash:

<img width="409" alt="Bildschirmfoto 2023-11-02 um 16 16 13" src="https://github.com/ONLYOFFICE/DesktopEditors/assets/33464213/33d0c23d-12b2-4576-b195-971ccb02e789">

(The program ONLYOFFICE cannot be opened. 11)

The problem occurs on versions 7.5.0 and 7.5.1. 7.4.1 works as usual.

### Additional information

I'm using a MacBook Air with macOS 11.5.2 and an M1 chip.

**Comment by Gingetsu** [comment]
Hello, @Korne127! Could you please send crash log macOS?

**Comment by Korne127** [comment]
Here:
[OnlyOffice Crash.txt](https://github.com/ONLYOFFICE/DesktopEditors/files/13252033/OnlyOffice.Crash.txt)

**Comment by soumyaDghosh** [comment]
Kind of this happens in android also. In android 13 MIUI

**Comment by Rita-Bubnova** [comment]
@soumyaDghosh Could you write more about your problem  in a new issue?

**Comment by soumyaDghosh** [comment]
@Rita-Bubnova sorry for choosing the wrong issue tracker. This issue is already listed in the android one. 
https://github.com/ONLYOFFICE/documents-app-android/issues/303

I have made my comment there, and deleting my comment from here. But please help us fix it.

**Comment by Gingetsu** [comment]
Hello @Korne127! DesktopEditors v7.5.1 is released (11/14/2023). Could you tell me if your problem is recurring?

**Comment by Korne127** [comment]
Hey, I just downloaded the latest release and yeah, the problem still happens as I described it. :/

**Comment by Gingetsu** [comment]
@Korne127, Sorry, we're still working on it.

**Comment by Korne127** [comment]
This seems to be an issue with Big Sur (macOS 11).
I updated to Sonoma (macOS 14) and the new OnlyOffice version (8.0.0) now works. But then I tried the old non-working version (7.5.1) and it didn't crash anymore as well.

**Comment by Gingetsu** [comment]
Yes, the problem with Big Sur. 
Thank you for telling me that the OnlyOffice is working for you now.
