### ISSUE TITLE
The equation editor crashes if there is a space character at the beginning of an equation

### ISSUE THREAD

**Issue by ikulagin** [ONLYOFFICE/DesktopEditors#1414]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.5.0.127

### Expected Behavior

Onlyoffice does not crash.

### Actual Behavior

Onlyoffice crashes when try to auto-format an equation with a leading space character.

### Reproduction Steps

1. Open the Onlyoffice Document or Onlyoffice Presentation
2. Insert an equation
3. Type `f` (or other character)
4. Press `left arrow`
5. Press `space`
6. Press `right arrow`
7. Press `space`
8. Onlyoffice crashes with error:
```
An error occurred during the work with the document.
Use the 'Save as...' option to save the file backup copy to a drive.
```

**Comment by Rita-Bubnova** [comment]
Hello @ikulagin, thank you for report.
I can confirm - this is bug, issue #64737.

This has been fixed and will be released in the next release.

**Comment by Rita-Bubnova** [comment]
DesktopEditors v7.5.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
