### ISSUE TITLE
Suddenly text becomes hidden in Document editor

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#1417]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.5.0.127

### Expected Behavior

The content is preserved visible unless user intentionally drops or changes it.

### Actual Behavior

<img width="258" alt="OO-lost" src="https://github.com/ONLYOFFICE/DesktopEditors/assets/64358003/d18ac75d-575f-4db8-afdd-0d307def73d9">

### Reproduction Steps

That was observed on Windows 10.
Sadly I cannot surmise and hence report what exactly happened.
But having assumed that that was a rendering issue, I tried maximizing and minimizing the editor's window, changing font colour, highlight colour, undo things. No way, all in vain.
Thankfully copying the content was still possible. So I opened new editor windows and `Ctrl`-`V` pasted my text from the rotten window.

**Comment by XDmitryK** [comment]
@HectorB-2020 Hi
Does this problem reoccur or is it a one-time problem? If every time, can you send the broken file?
If you can’t send the file, then perhaps you remember a scenario in which this can be done.

**Comment by HectorB-2020** [comment]
@XDmitryK, I certainly shall keep looking into this. So far the scenario is described above, I cannot add anything else.

**Comment by XDmitryK** [comment]
@HectorB-2020 Hi
I believe that the problem has not recurred for you, if so then we will close this issue.
