### ISSUE TITLE
Implementation of slide master view for global slide template editing

### ISSUE THREAD

**Issue by mrosemeier** [ONLYOFFICE/DesktopEditors#1418]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Implementation of slide master view for global slide template editing

**Comment by Rita-Bubnova** [comment]
The issue is actual in DocumentServer.
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1551.

**Comment by candideu** [comment]
Now implemented:

![image](https://github.com/user-attachments/assets/25a5d563-61cf-4365-a26d-596861b7e63e)
