### ISSUE TITLE
Dekstop environment crashes upon moving OO window between screens

### ISSUE THREAD

**Issue by BanorHlaalu** [ONLYOFFICE/DesktopEditors#1419]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.4.0.163

### Expected Behavior

Separating out OO tab and moving it to different screen. Don't know if it worked in the past.

### Actual Behavior

Separating out OO tab and moving it to different screen causes desktop environment to crash.

### Reproduction Steps

1. Open OO
2. Open 2 tabs
3. Take one tab and move over to second screen

### Additional information

* I have a two screen setup (portrait and landscape, different resolutions)
* I'm running Gnome 44.6 with wayland

**Comment by XDmitryK** [comment]
@BanorHlaalu Hi
I need more information about your monitors as my two FullHD monitors do not have this issue.
And if there is such an opportunity, then please update to version 7.5.1. Also, if you can record a short video, this may speed up the search for the problem.

**Comment by BanorHlaalu** [comment]
@XDmitryK Hi,
The problem disappeared since I updated to Gnome 45. Was using [gnome tiling assistant](https://extensions.gnome.org/extension/3733/tiling-assistant/).
I'm rocking the following two monitors:
* DELL P2421D
* Fujitsu B24W-7

**Comment by XDmitryK** [comment]
@BanorHlaalu 
Glad to hear that, then we'll close this issue.
