### ISSUE TITLE
Selected column crashes when trying to move it.

### ISSUE THREAD

**Issue by saitam1** [ONLYOFFICE/DesktopEditors#142]
Does this bug also exist in DesktopEditors before 5.2 ?https://github.com/ONLYOFFICE/DocumentServer/issues/392

**Comment by ShockwaveNN** [comment]
This problem still actual since we do not released DesktopEditors with 5.2 version

**Comment by ShockwaveNN** [comment]
Version 5.2.4 of DesktopEditors was released today and issue should be fixed.
