### ISSUE TITLE
Draw.io Updated Plugin/Libraries

### ISSUE THREAD

**Issue by stondino00** [ONLYOFFICE/DesktopEditors#1426]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.5.1.23

### Expected Behavior

Updated draw.io libraries

### Actual Behavior

Outdated draw.io libraries

### Additional information

Path              : C:\Program Files\ONLYOFFICE\DesktopEditors\editors\sdkjs-plugins\{DB38923B-A8C0-4DE9-8AEE-A61BB5C901A5}\vendor\drawio\webapp\WEB-INF\lib\commons-text-1.9.jar
  Installed version : 1.9
  Fixed version     : 1.10.0

Nessus scan above finding

**Comment by VladimirProkofiev52** [comment]
Hello! @stondino00 
In the new version of the plugin, we have removed these libraries due to security issues.
Please tell me why you need updated libraries?

**Comment by stondino00** [comment]
If they have been removed that should work.  Was just noting they were bundled with old library verisons.
