### ISSUE TITLE
OnlyOffice hangs when inserting this .svg file

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#1431]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.5.0

### Expected Behavior

OnlyOffice writer should be able to insert this .svg file.

![scalability](https://github.com/ONLYOFFICE/DesktopEditors/assets/4678272/3cfc1ebd-ca2f-41ee-9844-33b9a9ae5cb3)

### Actual Behavior

OnlyOffice hangs when inserting this .svg file.
The following error message is displayed:

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/4678272/b15ba6a3-673e-42dd-9325-e1633d45a7f1)

### Reproduction Steps

Steps:
- Open OnlyOffice writer
- Try to insert this .svg file
- =>error message

**Comment by Gingetsu** [comment]
Hello, @parrenin! This case will be fixed in the next release.

**Comment by parrenin** [comment]
This bug seems to be fixed in 8.0.0.

**Comment by Rita-Bubnova** [comment]
DesktopEditors v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
