### ISSUE TITLE
Context menu function "Save as Picture" on an SVG image saves the whole UI HTML

### ISSUE THREAD

**Issue by brendonofficial** [ONLYOFFICE/DesktopEditors#1434]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.5.1 (543) Apple Silicon

### Expected Behavior

When using "Save as Picture" from the context menu against an inserted SVG object, I would expect that an image of the SVG is saved (either as SVG, PNG, JPG, etc).

### Actual Behavior

When using "Save as Picture" from the context menu against an inserted SVG object, the resulting file that is saved is an HTML document of the application UI itself.

### Reproduction Steps

1. Create a new Document or Presentation
2. Under the **Insert** ribbon, click **Image** dropdown and then **Image from File**
3. Select an SVG image
4. Right-click the imported SVG image and select **Save as Picture**
5. Click **Save** on the dialog that appears
6. Open the **Picture.html** file that has been saved

**Comment by Gingetsu** [comment]
Helle, @brendonofficial! Could you tell me the version of your system, please?

**Comment by brendonofficial** [comment]
Hey @Gingetsu, just tried again on the latest version (8.0.0) and I can no longer replicate this issue, so I'm guessing whatever was causing this behaviour has been fixed 👀

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
