### ISSUE TITLE
Pivot table that uses Named Range gets loaded wrong with = sign

### ISSUE THREAD

**Issue by twiggy** [ONLYOFFICE/DesktopEditors#1435]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.5.1.23

### Expected Behavior

Loading a pivot table that uses a named range as a data source from MS Excel should not have =NAMEDRANGE but simply NAMEDRANGE ... otherwise pivot table has an error. 

### Actual Behavior

Pivot tables datasource if a named range comes up as =NAMEDRANGE

Clearing the = (equal) sign fixes the pivot table. Slicers can still be messed up until switching sheets, but that might be another refresh/display issue when saving data sources.

### Additional information

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/905538/264fd905-e107-499e-a6fa-9cee6fba5103)

Hopefully this screenshot makes it clear.

**Comment by rsnegirev** [comment]
Hi @twiggy 

Can you please provide a file example?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
