### ISSUE TITLE
Text on the slide is displayed incorrectly

### ISSUE THREAD

**Issue by b09dan** [ONLYOFFICE/DesktopEditors#144]
*bug*

Text on the slide is displayed incorrectly.

Open a presentation, look at slide № 2: https://cloud.bogdan.co/index.php/s/7s7kiCgjZbbSmzP
Text no displays as this: https://cloud.bogdan.co/index.php/s/75N5DY3EKr3zA4i/download
![image](https://user-images.githubusercontent.com/668524/47651058-290a0c80-db93-11e8-9c33-0edf615d040f.png)

Text on the slide should be displayed correctly (LibreOffice): https://cloud.bogdan.co/index.php/s/AneDnTfocDNnxq4/download
![image](https://user-images.githubusercontent.com/668524/47651065-30c9b100-db93-11e8-832b-eee507447b83.png)

1. ONLYOFFICE Desktop Editors 5.1.29.350 (Appimage), 
Operating System: KDE neon 5.14
KDE Plasma Version: 5.14.2
Qt Version: 5.11.2
KDE Frameworks Version: 5.51.0
Kernel Version: 4.15.0-38-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-6200U CPU @ 2.30GHz
Memory: 11,6 GiB of RAM

2.  In 5.2.0 CE everything is ok

**Comment by HellRoad** [comment]
I reproduced this issue in 5.1.29.350 Onlyoffice Desktop Editors
this bug will be fixed in 5.2.0 and newest
Thanks for your feedback.

**Comment by ShockwaveNN** [comment]
Version 5.2.4 of DesktopEditors was released today and issue should be fixed.
