### ISSUE TITLE
Sort rows by column data

### ISSUE THREAD

**Issue by jozsefk9** [ONLYOFFICE/DesktopEditors#1445]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

If I select a range of cells, for example A4 till L124, Sort features are grayed out and I can't sort the rows based on let's say column A data. This is the first Spreadsheet editor I see where I am not able to do that. Is that a missing feature or I'm missing something?

**Comment by rsnegirev** [comment]
Hi @jozsefk9 

Can you please provide an example file to make the question more specified? For now it looks too abstract.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
