### ISSUE TITLE
Georgian font looks written in OnlyOffice Document looks unreadable in Microsoft Office Word

### ISSUE THREAD

**Issue by acdavit** [ONLYOFFICE/DesktopEditors#1448]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, Linux (DEB package)

### Version information

7.5.1.23

### Expected Behavior

Text with a Georgian font written in OnlyOffice Documents (Linux) should be readable when opened on a Windows machine with Microsoft Office Word

### Actual Behavior

Text with a Georgian font written in OnlyOffice Documents looks completely unreadable on a Windows machine with Microsoft Office Word

This is how it looks on Linux
![linuxlite](https://github.com/ONLYOFFICE/DesktopEditors/assets/107882602/ae77062b-aab6-4687-93ba-3018f324b55d)

This is how it looks on Windows 7 with MS Office 2010
![w7](https://github.com/ONLYOFFICE/DesktopEditors/assets/107882602/83cb53d0-bdf3-44d8-9cd7-722ac3261502)

This is how it looks on Windows 10 with MS Office 2016
![w10](https://github.com/ONLYOFFICE/DesktopEditors/assets/107882602/285d7df2-ec18-4e62-8ae3-d23f17c2f99d)

The document in question
[Document1.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/13728248/Document1.docx)

### Reproduction Steps

1. Create a document on Linux with OnlyOffice
2. Type in some Georgian fonts
3. Save it and transfer it to a Windows machine with MS Office
4. Open it up with MS Office Word

**Comment by rsnegirev** [comment]
Hi @acdavit 

The problem is only in the MS Office 2010 and 2016? Have you tried to open it in the Office 365 or OneDrive?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
