### ISSUE TITLE
Document language is not respected in new paragraphs.

### ISSUE THREAD

**Issue by erikhakansson** [ONLYOFFICE/DesktopEditors#1449]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

version 7.5.1.23 (x64 msi)

### Expected Behavior

New paragraphs get either the language of the preceding paragraph or the document language.

### Actual Behavior

New paragraphs always gets set to English (Keyboard layout language) rather than the document language or preceding paragraph language.

### Reproduction Steps

1. Set Windows Keyboard layout to language A
2. Set document language to language B
3. Write new parapraphs.

### Additional information

System and UI language is English, document language is Swedish. If I change the Windows keyboard layout to Swedish, it works, so it seems that the error comes from OO picking up the System keyboard layout rather than respecting user settings.

**Comment by HectorB-2020** [comment]
@erikhakansson, I regret to accede to your issue that Only Office has great potential of improving documents with multiple languages. Some of the issues below might resemble yours.
* https://github.com/ONLYOFFICE/DesktopEditors/issues/802
* https://github.com/ONLYOFFICE/DesktopEditors/issues/273
* https://github.com/ONLYOFFICE/DocumentServer/issues/2142
* https://github.com/ONLYOFFICE/DesktopEditors/issues/626
* https://github.com/ONLYOFFICE/DesktopEditors/issues/527
* https://github.com/ONLYOFFICE/DesktopEditors/issues/437
* https://github.com/ONLYOFFICE/DesktopEditors/issues/356
* https://github.com/ONLYOFFICE/DesktopEditors/issues/224
* https://github.com/ONLYOFFICE/DocumentServer/issues/576
* https://github.com/ONLYOFFICE/DocumentServer/issues/2326
* https://github.com/ONLYOFFICE/DesktopEditors/issues/1223
* https://github.com/ONLYOFFICE/DesktopEditors/issues/1124

For OO team: I certainly admit that some of the issues above are closed. But who knows, maybe it's worth checking them occasionally.

**Comment by TatianaKirillova** [comment]
Hello @erikhakansson!
Thank you for your request!
In the MS WORD editor the behavior is similar (as in the ONLYOFFICE editor). Which editor are you comparing with?

**Comment by erikhakansson** [comment]
Hi!

I am not comparing to any other editor.

I do this:
1. Set document language to Swedish
2. Set paragraph language to Swedish

Yet when I press enter to start a new paragraph, OnlyOffice automatically changes to English and I have to manually change to Swedish again. Every single time I press enter. Again, this happens *EVERY* time I press Enter to create a new paragraph, so several times per minute.

It doesn't matter how other editors do it, but I find it weird if the default behaviour is to automatically change language every time you press Enter despite the fact that the user has selected another language multiple times. That makes it impossible to use spelling control of a language that is not setup on the computer that you're using.

**Comment by TatianaKirillova** [comment]
Hello,  @erikhakansson 
 Sorry for the long wait
I can confirm that the problem exists, issue #50697 with your  proposal

**Comment by Rita-Bubnova** [comment]
The issue is actual in DocumentServer.

**Comment by TatianaKirillova** [comment]
@erikhakansson In the desktop editor settings, you can disable the text language from the keyboard language. Perhaps this will help your problem?

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/72191601/281c2298-128f-42fa-88e2-0617cd994ffb)

**Comment by erikhakansson** [comment]
@TatianaKirillova this makes no difference, unfortunately. I believe that option is for detecting language from text, right? In any case that options seems to be completely non-functional and the editor keeps picking up OS language settings.

**Comment by erikhakansson** [comment]
Recently the problem has gotten even worse. It doesn't even matter what keyboard layout I use, it seems to pick up the OS language instead.

**Comment by uc-ai2** [comment]
Hello,  @erikhakansson
Sorry for the long wait. 
The language of the input characters does not switch to the correct one even after entering characters in the language you need?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
