### ISSUE TITLE
[Windows] Every single run delays if start menu entry not created

### ISSUE THREAD

**Issue by Young-Lord** [ONLYOFFICE/DesktopEditors#1451]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.5.1.23 (x64 msi)

### Expected Behavior

When I open any document by double clicking it, OnlyOffice should open directly

### Actual Behavior

Every time, a `Please wait while windows configures ONLYOFFICE xxx` message box shows for 5 seconds, then OnlyOffice shows.
![2](https://github.com/ONLYOFFICE/DesktopEditors/assets/51789698/970e4ed6-9ba2-4279-a42d-13bcff0a9cfc)

### Reproduction Steps

1. Install the latest msi installer
2. Don't create start menu entry at install
3. Set OnlyOffice as default application for any file
4. Open the file by double clicking it

### Additional information

I found the issue might be connected with wrong registry entry.
(The Chinese text is: `Cannot detect production {D7...51}, feature MainFeature, component {CB...C0}. Resource C:\...\ONLYOFFICE\ does not exist.`)
![reg](https://github.com/ONLYOFFICE/DesktopEditors/assets/51789698/9e4bd9c9-8cc9-4b65-bfe7-033bebb125eb)
<https://stackoverflow.com/questions/1634699/please-wait-while-windows-configures-microsoft-visual-studio-2008>
<https://superuser.com/a/1486972>

**Comment by DAumkraft** [comment]
Hello, @Young-Lord!
I apologize for the long wait for an answer.
Thank you for reporting this issue!
Indeed, there was such a problem in the previous version of ONLYOFFICE, and this problem was fixed in the new version of ONLYOFFICE DesktopEditors 8.0.
You can check it yourself, and if the problem persists, please let me know.
Thank you!

**Comment by Young-Lord** [comment]
Confirmed fixed in 8.0.0. Thanks for your attention!❤️
