### ISSUE TITLE
Incorrect Spreadsheet autofill data

### ISSUE THREAD

**Issue by anfokaboom** [ONLYOFFICE/DesktopEditors#1464]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.5.1.23 (x64 exe)

### Expected Behavior

Selecting contiguous cells configured with a series of dates, then using the fill handler and dragging down, subsequent cells should continue the date series

### Actual Behavior

The autofilled cells do not continue the logical series, and appear to begin the series again

### Reproduction Steps

1. Open OnlyOffice Spreadsheet editor
2. Start a series of dates in column A. For example, 8/1/24, 9/1/24, 10/1/24 etc
3. Select all prefilled cells
4. Press and hold the fill handler and drag down column A another 4 or 5 rows
5. Examine resulting data for consistency

### Additional information

https://youtube.com/shorts/4jSSgj_Abk0

**Comment by rsnegirev** [comment]
Hi @anfokaboom 

I'm looking it now and can say that it depends of regional settings and date format. For example my regional is en-US and format is mm/dd/yyyy. So my dates are 1/8/2024, 1/9/2024, 1/10/2024, and in this case autofill works correctly.

And if I set custom date format dd/mm/yyyy:
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/65603548/3d747aea-a5e4-44e6-be52-72bcdf24c2ce)

autofill also works:
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/65603548/fafe837b-fb0d-4de9-8968-c5efad1cc179)


So can you recheck this? Maybe I missed something.

**Comment by anfokaboom** [comment]
PEBKAC 
I'm not sure if it was regional settings (I'm AU), formatting the cells or starting the range again, but it does work now. Sorry for the trouble.
