### ISSUE TITLE
pptx with jump to slides feature crashes desktop editor

### ISSUE THREAD

**Issue by shu0406** [ONLYOFFICE/DesktopEditors#1467]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

Version 7.5.1.23 (flatpak)

### Expected Behavior

use pptx in presentation mode without crash
[bug jump to slide.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/13887420/bug.jump.to.slide.pptx)

### Actual Behavior

pptx leads to crash when in presentation mode
![grafik](https://github.com/ONLYOFFICE/DesktopEditors/assets/76654412/6b678b43-ee77-404b-94af-61f1cc1b05c5)

**Comment by ElenaMaaya** [comment]
Hello @shu0406! Thank you for the report! This issue will be fixed in the next release. Please keep checking for updates.

**Comment by Rita-Bubnova** [comment]
Desktop Editors v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
