### ISSUE TITLE
Open the xlsx file, the Chinese content inside is garbled

### ISSUE THREAD

**Issue by muzhi9018** [ONLYOFFICE/DesktopEditors#1469]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.5.1

### Expected Behavior

I hope to be able to view and edit my xlsx files normally

### Actual Behavior

The Chinese content in the file is garbled. Below is a screenshot of the garbled content

<img width="661" alt="image" src="https://github.com/ONLYOFFICE/DesktopEditors/assets/38956027/3ee01405-0261-4d7d-ad82-91f18562bf82">

**Comment by rsnegirev** [comment]
Hi @muzhi9018 

Can you attach a problem file?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
