### ISSUE TITLE
command key referred to as "ctrl" on mac

### ISSUE THREAD

**Issue by lowlevelm** [ONLYOFFICE/DesktopEditors#147]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The software refers to the "ctrl" key on MacOS

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. insert a link into a spreadsheet cell
2. hover over link
3. the popup says: "Press CTRL and click link"

**What is the expected behavior?**
The popup should say: "Press command or CTRL and click link" only on MacOS.
Why both? Mac keyboards have both the ctrl key, and the command key, and both of them work to open a link.

**Which versions of DesktopEditors, and which OS are affected by this issue?**
I have only checked version 5.1 on MacOS.

**Comment by Rita-Bubnova** [comment]
Hello, @lowlevelm.
Thank you. I can confirm - this is a bug, issue 39898 in our internal issue tracker.

**Comment by aol-nnov** [comment]
This is still an issue.

More on this:

navigation shortcuts are wrong.
⌘ + arrow jumps word forward/back (expected behaviour: start of line/end of line)
⌥ + arrow does nothing (expected behaviour: jump word forward/back)

Any plans on fixing this any time soon? :)

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.

I close this issue. Feel free to comment or reopen it if you got further questions.
