### ISSUE TITLE
Presenter mode not synchronized with presentation

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#1475]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.5.1

### Expected Behavior

What is displayed in the presenter mode should be synchronized with what is displayed in the presentation

### Actual Behavior

The presenter mode is sometimes not synchronized with the presentation.

### Reproduction Steps

Steps to reproduce:
- open the attached .pptx file
- start presentation with presenter mode
- press several times the "space" key to advance the presentation
=> the presenter mode is not synchronized with the presentation.

[bug-presenter-mode.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/13961091/bug-presenter-mode.pptx)

**Comment by Rita-Bubnova** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1870.
