### ISSUE TITLE
Gtk-Message: Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by stanom** [ONLYOFFICE/DesktopEditors#148]
I want to request a bug.

The application doesn't start.

After the run of the script `/opt/onlyoffice/desktopeditors/onlyoffice-desktopeditors.sh` follow **WARNING** messages:
```
Gtk-Message: Failed to load module "canberra-gtk-module"
(DesktopEditors:8166): GdkGLExt-WARNING **: Window system doesn't support OpenGL.
```
### SYSTEM configuration:
**OS**: Debian 9.6 (amd64)
**Onlyoffice-desktopeditor**: 5.1.27-126 (amd64)
**Installed gtk canberra libs**:
- libcanberra-gtk3-0:i386
- libcanberra-gtk3-module:i386
- libcanberra-gtk3-0:amd64
- libcanberra-gtk3-module:amd64

**Comment by stanom** [comment]
Alternative way: onlyoffice-desktopeditors installed through snap

After the run of the script `snap run onlyoffice-desktopeditors` follow WARNING messages:
```
ln: failed to create symbolic link '/home/smotycka/snap/onlyoffice-desktopeditors/26/.local-5.1.27/share/glib-2.0/schemas/*.xml': File exists
ln: failed to create symbolic link '/home/smotycka/snap/onlyoffice-desktopeditors/26/.local-5.1.27/share/glib-2.0/schemas/*.xml': File exists
ln: failed to create symbolic link '/home/smotycka/snap/onlyoffice-desktopeditors/26/.local-5.1.27/share/glib-2.0/schemas/*.xml': File exists
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.onlyoffice-desktopeditors', please create it with 0700 permissions.
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.onlyoffice-desktopeditors', please create it with 0700 permissions.

(process:11684): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Qt: Session management error: None of the authentication protocols specified are supported

(DesktopEditors:11684): GdkGLExt-WARNING **: Window system doesn't support OpenGL.
```

**Comment by stanom** [comment]
SOLVED:
After upgrading NVIDIA driver in DEBIAN (using [sgfxi](https://smxi.org/docs/sgfxi-manual.htm) script with _adding/configuring ia32-libs-i386 before doing the driver install_) starts onlyoffice-desktopeditors (through [snap](https://snapcraft.io/)) successfully.

**Comment by ShockwaveNN** [comment]
Seems the reason is that your system `doesn't support OpenGL` as said in error.
Is that correct? what is `glxinfo | grep "OpenGL version"` output?
Seems we never checked systems without `OpenGL` support, I'll take a look at this
