### ISSUE TITLE
[Bug Report] OnlyOffice appears to be unable to overwrite files on my OneDrive

### ISSUE THREAD

**Issue by alba4k** [ONLYOFFICE/DesktopEditors#1503]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (AUR Package)

### Version information

8.0.0.99

### Expected Behavior

When saving a file (in my case, /home/alba4k/Documenti/OneDrive/FILE.xlxs) I would expect all changes to be written.

### Actual Behavior

The file remains unchanged and opening it again will show how it looked before editing it (the last time I opened it). Using "Save As" and overwriting it also has the same result, but Save As and creating a new file will work perfectly.

The file is not protected in any way, as using `cp [saved as another file].xlxs FILE.xlxs` will save the changes to the original. I have tried creating a completely new file, writing test in A1, reopening it ("test" is still there), editing "test" to "test1", saving, reopening: still shows "test".

What's weird is that files that are not on that onedrive drive (mounted by onedriver) work just fine.

### Reproduction Steps

1. Create a file (in my case, using the spreadsheets editor, the same happens using e.g. the document editor) and write something in it.
2. Save it to the onedriver-mounted drive
3. edit whatever you wrote in the file
4. press save, or save as > overwrite that same file
5. close the file, open it again
6. it won't have what was previously changed in it

### Additional information

Don't mind asking for anything that might be helpful :)

**Comment by XDmitryK** [comment]
@alba4k Hi
Unfortunely, i can't reproduce your issue on my Ubuntu 22.04. You can attach short video with problem?

https://github.com/ONLYOFFICE/DesktopEditors/assets/46962983/ae2a9087-1f3f-4ac0-b1d7-0adf918cc5bc

**Comment by alba4k** [comment]
@XDmitryK thanks for the quick response

What would you recommend doing to gather some extra data and hopefully help debug this?

**Comment by kabe-inc** [comment]
Not OP but I've been having the same issue for the past couple of OnlyOffice versions. Prior to that, overwriting files from my OneDrive worked fine.

However, as you can see from the attached video, in the most recent version (8.0.0.99), creating and saving an original file works fine, but no subsequent edits are saved, either when clicking `Save` or `Save As`.

I'm really hoping this is fixable because it makes OnlyOffice pretty much useless for me at the moment, as I am constantly working on files that are synced to my OneDrive folder.

[onlyoffice-onedrive-bug.webm](https://github.com/ONLYOFFICE/DesktopEditors/assets/72587902/24c5c5ac-638f-4bf3-8dd2-0eb8c214b5cf)

**Comment by kabe-inc** [comment]
Update: The problem still exists in v 8.0.1, FYI

**Comment by XDmitryK** [comment]
@kabe-inc Hi
Thank you for the video. I confirm this is bug, issue #66776

**Comment by alba4k** [comment]
This doesn't affect every file, by the way

![immagine](https://github.com/ONLYOFFICE/DesktopEditors/assets/84153269/7df12535-f777-4ba5-8f4d-00f4f939bfc7)

The files I marked didn't save the work I did yesterday (rip), the others did. I just wish I remembered about this issue before closing onlyoffice assuming that my work had been saved 😅

**Comment by alba4k** [comment]
closing as this is a duplicate od

https://github.com/ONLYOFFICE/DesktopEditors/issues/1436
