### ISSUE TITLE
Margin are not the same in documents

### ISSUE THREAD

**Issue by lorypelli** [ONLYOFFICE/DesktopEditors#1525]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

Latest

### Expected Behavior

It should have same margin left and right

### Actual Behavior

Margin left is greater than right

### Reproduction Steps

Open a document and see by yourself

### Additional information

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/87276663/ef80b0b2-7090-4b35-a8c1-b100a4b62f35)

**Comment by TatianaKirillova** [comment]
Hello @lorypelli 
Thank you for your request! In a standard document template, the left margin should be greater than the right one. If you want a document to immediately open with equal indentations, use your own document template.

**Comment by lorypelli** [comment]
> Hello @lorypelli 
> Thank you for your request! In a standard document template, the left margin should be greater than the right one. If you want a document to immediately open with equal indentations, use your own document template.

Really? How? It's so ugly...

**Comment by lorypelli** [comment]
> You can also use the selection of other fields
> 
> ![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/72191601/cc74039d-6eb0-44f4-a9c3-f725d27cfe5d)
> 

Why in other text editor there isn't this problem why in this one there is?

**Comment by lorypelli** [comment]
> @lorypelli I understood you. Need to select a default document field, issue #47180 with your suggestion.

How can I change default margins for every document instead of doing manually 1 by 1?

**Comment by TatianaKirillova** [comment]
@lorypelli For now, you can create a blank document with the required fields and open it when needed.

We are closing this issue. You can follow the progress of this issue at https://github.com/ONLYOFFICE/DesktopEditors/issues/746.

**Comment by lorypelli** [comment]
@TatianaKirillova I prefer the `Moderate` option, how can I set it as the default one (libreoffice uses that as default which I think it's better, but onlyoffice offers better support for docx documents and other good things that make me to prefer it)

**Comment by lorypelli** [comment]
Top and Bottom: 2.54 cm
Left and Right: 1.91 cm
