### ISSUE TITLE
Copy hyperlink option in right-click context menu

### ISSUE THREAD

**Issue by candideu** [ONLYOFFICE/DesktopEditors#1526]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Thank you for creating this excellent office suite! I would love to have the option to copy a hyperlink when I right-click on it.

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/55474996/695eebcd-b0e9-4df2-8d74-f718e84b49e7)

**Comment by maruacat** [comment]
Hello @candideu 
Thank you for the enhancement.
A similar suggestion for improvement already exists in our system - issue #63921. I have added information about your request.

**Comment by Rita-Bubnova** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2065.
