### ISSUE TITLE
.pptx presentation saved by OO needs repair in PowerPoint

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#1531]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

8.0.1

### Expected Behavior

The attached presentation does not open correctly in PowerPoint, it needs repair.
It was saved by OO.

[presentation-needs-repair.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/14633948/presentation-needs-repair.pptx)

### Actual Behavior

The attached .pptx file needs repair in PowerPoint.

### Reproduction Steps

Steps:
- open the attached .pptx file in OO and save it
- then open it in PowerPoint
- => the file needs repair

**Comment by parrenin** [comment]
This bug seems to be fixed in 8.1.0.

**Comment by TatianaKirillova** [comment]
@parrenin Yes, I'm happy to report that the issue is fixed in this [commit](https://github.com/ONLYOFFICE/sdkjs/commit/6cc9a963621438a189b67b0350a7cecb67b45e4c) and is already included in version 8.1.0!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
