### ISSUE TITLE
Discrepancy in Line Spacing Between OnlyOffice and Microsoft Word when Converting Docx 

### ISSUE THREAD

**Issue by PragmaticVBrault** [ONLYOFFICE/DesktopEditors#1533]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

**Issue Overview**
When using the desktop version of OnlyOffice to open a .docx file and subsequently converting it to a PDF format, a discrepancy in line spacing becomes evident compared to the same document opened in Microsoft Word. This inconsistency in line spacing can lead to formatting errors and visual discrepancies, impacting the overall quality and accuracy of documents.

**Steps to Reproduce**

1. Open a .docx file containing formatted text, including various line spacing configurations, in Microsoft Word.
2. Open the same .docx file in the desktop version of OnlyOffice. **Issue 1**
3. Convert the document to PDF format using OnlyOffice. **Issue 2**
4. Compare the line spacing in the resulting PDF document with the original document opened in Microsoft Word.

Expected result : 100% consistency between the original document as displayed in microsoft word, maintaining the intended formatting and layout. 

**Additional Information**

- This issue has been observed consistently across different documents and configurations.
- Users relying on OnlyOffice for document processing and conversion may encounter difficulties in maintaining consistent formatting standards, particularly when collaborating with others who primarily use Microsoft Word.
- It is essential to address this issue to ensure the reliability and accuracy of document conversion processes within OnlyOffice, enhancing user experience and facilitating seamless interoperability with other office productivity tools.

**Screenshots**

[Screenshot 1: OnlyOffice - Discrepancy in Line Spacing]
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/36156607/124e3cd0-37c3-42b6-9262-41b383e381ab)

[Screenshot 2: Microsoft Word - Original Document for Comparison]
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/36156607/58633c4b-e8c4-4f99-ac02-f97ead0da2c6)

Environment:
- Operating System: Windows 11 pro
- OnlyOffice Version: OnlyOffice Desktop version 8.0.1.31 (x64 exe)
- Microsoft Word Version: Microsoft 365 MSO (Version 2402 64bit)

Thank you for addressing this concern and working towards improving the functionality of OnlyOffice.

**Comment by HectorB-2020** [comment]
In 2022 I reported an issue for Line Spacing. Maybe there is something in common for them:
* https://github.com/ONLYOFFICE/DesktopEditors/issues/1050

**Comment by TatianaKirillova** [comment]
@PragmaticVBrault Thank you for your request! Could you attach a file to check the problems?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
