### ISSUE TITLE
Translating Bug Mac Version

### ISSUE THREAD

**Issue by JK85659** [ONLYOFFICE/DesktopEditors#1534]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

8.0.1

### Expected Behavior

In the Presentation module, the second tab in the insert dialog is in Russian, not in German or English.
![Translating issue](https://github.com/ONLYOFFICE/DesktopEditors/assets/164300615/bade4d23-5e46-49b3-a387-4ef0b7344a0e)

### Actual Behavior

Tab description in German or English

### Additional information

<img width="505" alt="image" src="https://github.com/ONLYOFFICE/DesktopEditors/assets/164300615/24f01eff-357b-43ae-9adf-4c6edda9ef28">

**Comment by LuckySpecialist** [comment]
Hi @JK85659!
The translation has already been corrected and will be released in the next major version of the application.
Thanks for the feedback.

**Comment by Rita-Bubnova** [comment]
DesktopEditors v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
