### ISSUE TITLE
Only office won't open

### ISSUE THREAD

**Issue by now-im** [ONLYOFFICE/DesktopEditors#154]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Software won't open.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Entering `onlyoffice-desktopeditors` in the terminal.
**What is the expected behavior?**
Total Crash.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
OS: Arch Linux
Ver: 5.2.4
Package: https://aur.archlinux.org/packages/onlyoffice-bin/
In this link you can see how the package is compiled and installed in the system: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=onlyoffice-bin
Error from terminal:
 ```
onlyoffice-desktopeditors                                                                                                 [130]
./DesktopEditors: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/converter/libkernel.so)
```

**Comment by ShockwaveNN** [comment]
Sorry, we do not support this package, it was made by someone else. You should contact them instead

**Comment by now-im** [comment]
Then kindly update the snap package. Otherwise, we can't use onlyoffice in Arch Linux and derivatives.

**Comment by ShockwaveNN** [comment]
@now-im we got some troubles updating snap package, we release update as soon it'll be ready

**Comment by now-im** [comment]
thanks a lot!
