### ISSUE TITLE
Text not importing correctly from CSV file

### ISSUE THREAD

**Issue by PJF-NZ** [ONLYOFFICE/DesktopEditors#1544]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

8.0.1.31

### Expected Behavior

Import/format the text in the CSV file correctly in OnlyOffice spreadsheet.
In earlier versions this worked correctly, but for a number of versions now it hasn't worked correctly.

### Actual Behavior

The following text in the CSV file (5 lines) -
11 March 2024: (See 7 March)
12 March 2024: (See 7 March)
13 March 2024: (See 7 March)
7, xx March 2024: Organise login access to Charities Services; Obtain information needed to complete 2022 & 2023 Annual Returns; File 2022 & 2023 Annual Returns at Charities Services; Associated email correspondence
8 March 2024: (See 7 March)

becomes in the CSV import -
1/01/7389
11/04/7389
20/07/7389
7, xx March 2024: Organise login access to Charities Services; Obtain information needed to complete 2022 & 2023 Annual Returns; File 2022 & 2023 Annual Returns at Charities Services; Associated email correspondence
8 March 2024: (See 7 March)

### Reproduction Steps

Select CSV file in Thunar file manager (opens by default in ONLYOFFICE Desktop Editors)
Select default encoding option: Unicode (UTF-8)
Select delimiter: Comma

### Additional information

Operating system:
Manjaro Linux rolling build, 64-bit
Xfce version 4.18
GTK 3.24.41
Kernel 6.6.19-1-MANJARO

**Comment by HectorB-2020** [comment]
Ain't these two issues similar?
* https://github.com/ONLYOFFICE/DesktopEditors/issues/1549

**Comment by HB9HIL** [comment]
same here..
