### ISSUE TITLE
Hope it can support aarch64 architecture

### ISSUE THREAD

**Issue by sjkhsl** [ONLYOFFICE/DesktopEditors#1546]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I want to use your software on aarch64 you can make a build for arm64 ?

**Comment by Rita-Bubnova** [comment]
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/988 or https://github.com/ONLYOFFICE/DesktopEditors/issues/270.

**Comment by sjkhsl** [comment]
> #988或#270的重复。

Although the request is repeated, we have been discussing ARM support since 20 years ago, and it has not been done yet~
