### ISSUE TITLE
Printer output is blurry

### ISSUE THREAD

**Issue by sojuo** [ONLYOFFICE/DesktopEditors#1547]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.4.1.36 (x64 msi)

### Expected Behavior

When selecting a page to print within Onlyoffice, the printer output should be as clear as when printing within Word.

### Actual Behavior

When selecting the appropriate page to print in Onlyoffice, the printer output is thick and fuzzy.

### Reproduction Steps

1. Open [高中英语词汇3500词（必背）.zip](https://github.com/ONLYOFFICE/DesktopEditors/files/14854245/3500.zip) with Onlyoffice
2. Print this document in Onlyoffice.

### Additional information

If you print this document using Word, you can get clearer results. The results are shown in the pictures in the zip file.
[Pictures.zip](https://github.com/ONLYOFFICE/DesktopEditors/files/14854421/Pictures.zip)

**Comment by VladimirProkofiev52** [comment]
Hello! 
@sojuo, I have reviewed your issue but was unable to reproduce it. Could you please clarify a few details:

1. You mentioned: "When selecting the appropriate page to print in Onlyoffice." Does the issue occur only on a specific page?
2. Are you printing the document to a physical printer or saving it to a file?
3. What is the model of your printer, or in what format are you saving the document?

We recently released an updated version of the editor. Please try updating to the latest version 8.1.1.26 and let us know if the issue persists.
