### ISSUE TITLE
Add underlining of double spaces to spell checker

### ISSUE THREAD

**Issue by Ciancy28** [ONLYOFFICE/DesktopEditors#1554]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

It would be handy to have something like Microsoft Office's double blue underline when accidentally typing two spaces instead of one
![ms_office](https://github.com/ONLYOFFICE/DesktopEditors/assets/77066322/6195d4f0-33dd-453d-94b6-440a4926fc08)
![onlyoffice](https://github.com/ONLYOFFICE/DesktopEditors/assets/77066322/c39281ed-2cd6-448d-9f57-380831723dfd)

**Comment by Rita-Bubnova** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1072.
