### ISSUE TITLE
SetValue with empty string produce zero value in cell

### ISSUE THREAD

**Issue by joselmm** [ONLYOFFICE/DesktopEditors#1565]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

version 8.0.1.31 (x64 exe)

### Expected Behavior

I expect the cell value to be "" (without any value) after executing the macro code

### Actual Behavior

The cell value is 0 after executing the code.
![Video_1714387721](https://github.com/ONLYOFFICE/DesktopEditors/assets/95531879/f71f2501-8079-4a0e-acae-660ab8d6f1ba)

### Reproduction Steps

Create a macro with the code:

`(function() 
{
    var range = Api.GetActiveSheet().GetSelection();
    range.SetValue("");
})();`

### Additional information

The same problem happens in docs space, i found this issue here too: https://forum.onlyoffice.com/t/setvalue-with-empty-string-produce-zero-value-in-cell/5224

**Comment by l8556** [comment]
Hello @joselmm

Version 8.1 of Document Server was released recently, please update your app and check the situation again.
This issue should be fixed in this version.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
