### ISSUE TITLE
Track changes does not remain active when a document is saved and re-opened

### ISSUE THREAD

**Issue by emes81** [ONLYOFFICE/DesktopEditors#1572]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

8.0.1.31

### Expected Behavior

(I'm not using the DEB or RPM; I'm using the Flatpak, installed via AUR)

When track changes is enabled, the documents is edited and saved, then re-opened, track changes should still be active

### Actual Behavior

Track changes must be re-activated

### Reproduction Steps

Open/create a doc, write some text, enable track changes, make some edits, save, then close and re-open; track changes will no longer be enabled

**Comment by XDmitryK** [comment]
@emes81 Hi
We have two options for dealing with patches.
The first is when it is turned on only for this session and the second, which is turned on for everyone, when the file is opened again.
![Review Mode](https://github.com/ONLYOFFICE/DesktopEditors/assets/46962983/d6c6fc5d-2245-459c-9c70-8c3cedfe0d7e)


Which option did you use? If you just click on the icon, the first option is enabled.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
