### ISSUE TITLE
providing a WebAssembly version to covert doc to pdf

### ISSUE THREAD

**Issue by lqzerogg** [ONLYOFFICE/DesktopEditors#1575]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I'm interested in leveraging OnlyOffice to generate PDF documents for my clients. While the overall experience has been excellent, I've encountered a challenge with the performance of converting .docx files to .pdf on my server, which is notably sluggish. To alleviate the significant server-side workload, could you offer a WebAssembly-based solution that enables my JavaScript code to invoke the API for docx-to-pdf conversion on the client-side, thus optimizing resource utilization and improving efficiency?

**Comment by K0R0L** [comment]
Hello. To convert on the server, use DocumentBuilder [().](https://www.onlyoffice.com/download-builder.aspx) It is not possible to write to PDF in js/webasm code at the moment.
