### ISSUE TITLE
providing a high performance executable file to convert doc to pdf

### ISSUE THREAD

**Issue by lqzerogg** [ONLYOFFICE/DesktopEditors#1576]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I am keen on harnessing the capabilities of OnlyOffice to produce PDF documents for my clients. Despite an overwhelmingly positive overall experience, I've stumbled upon a performance hurdle when converting .docx files to .pdf on my server, which is noticeably sluggish.
Could you offer a high-performance executable file specifically designed for this conversion process? Ideally, this executable should be capable of being invoked by other processes through Inter-Process Communication (IPC), eliminating the need to spawn a new process for every single conversion, thereby enhancing efficiency.

**Comment by K0R0L** [comment]
Please, use [DocumentBuilder](https://www.onlyoffice.com/download-builder.aspx) for this.

**Comment by lqzerogg** [comment]
> Please, use [DocumentBuilder](https://www.onlyoffice.com/download-builder.aspx) for this.

well, can u provide a guide to install document builder on my linux server? My server does not have any GUI, how to install it using command line?
