### ISSUE TITLE
Add new simple markup display mode in review

### ISSUE THREAD

**Issue by EchoPouet** [ONLYOFFICE/DesktopEditors#1577]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

When many contributors change a text document, the change marks no longer allow the document to be read correctly during editing.

The solution would be to add the same display mode as in MS Word, called Simple Markup. This would greatly facilitate readability when editing in collaborative mode.

**Comment by XDmitryK** [comment]
@EchoPouet Hi
This is known bug #47361

**Comment by EchoPouet** [comment]
Great, just for my curiosity, will it be released in version 8 or 9 ?

**Comment by EchoPouet** [comment]
Ok thank you.
