### ISSUE TITLE
OnlyOffice Editors fail to report inability to save as .xlsx if the .xlsx is open in another app

### ISSUE THREAD

**Issue by ericshreve** [ONLYOFFICE/DesktopEditors#1579]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

version 8.0.1.31 (x64 exe)

### Expected Behavior

When a spreadsheet is open in OnlyOffice, I save it as a .xlsx using the graphical option.  OnlyOffice appears to do this.  It's expected the OnlyOffice data was successfully exported to an .xlsx file.

### Actual Behavior

If there's a prior version of the .xlsx file that is open, say, in Pandas, the file is not saved and no notice is given.  It's expected if the file can't be saved, the user is made aware that the file can't be saved.  Even better would be 'why' it can't be saved, e.g. "File can't be saved because it is open in another app or locked". 

### Reproduction Steps

Create an spreadsheet in OnlyOffice editor.
Put some data in it.
Save it as an xlsx.
Open the saved file in Excel or Python/Pandas.
Change the data in OnlyOffice editor.
Save the OnlyOffice spreadsheet as .xlsx using the same file name.
Verify the local data in Excel or Python/Pandas didn't change and no notice was given that the action wasn't completed by OnlyOffice.

**Comment by LuckySpecialist** [comment]
Hi @ericshreve!
This problem is already known as Bug 45238 and i will add your request for fix there.
Thanks for the feedback.

**Comment by LuckySpecialist** [comment]
When you try to save changes to a file opened in another application, you should see this warning message:

> This file cannot be saved or created.
> Possible reasons are:
> 1. The file is read-only.
> 2. The file is being edited by other users.
> 3. The disk is full or corrupted.

The data is not written to the file after that.

**Comment by ericshreve** [comment]
Are you saying this is what it now does after a bug fix because this is not what it actually does in the version reported.

- Eric
     On Friday, May 31, 2024 at 08:33:42 AM MDT, Denis Myshaev ***@***.***> wrote:  
 
 


When you try to save changes to a file opened in another application, you should see this warning message:


This file cannot be saved or created.
Possible reasons are:
   
   - The file is read-only.
   - The file is being edited by other users.
   - The disk is full or corrupted.


The data is not written to the file after that.

**Comment by LuckySpecialist** [comment]
Hi, @ericshreve,
I want to say that I checked on the version you specified at the moment, I receive the correct error message and ask you to provide details of why in your case, with a similar environment, this does not work.
In other words, I don't see what needs to be fixed if the application is working correctly in the current version.

**Comment by ericshreve** [comment]
Hi, thanks for looking into this.  I tried this again.

In this case, I used Python to explicitly open three previously saved .xlsx files from OnlyOffice desktop editor.  I have Python in debug mode so I paused the program to keep the files open.  I verified I can view the ingested files' contents for all three of the .xlsx files in Python.

I then tried downloading these again using OnlyOffice desktop editor using Download As... and hitting the symbol for .xlsx and saving as the exact same file names.  Thus, my initial report was incorrect as I said "Save as..." instead of "Download as...".

OnlyOffice appears to do this; however, there is a spinning wheel in the top right of the editor indicating downloads are in progress.  Looking at this, you can see this in the attached pic.  Here, the wheel has been spinning for maybe five minutes on a small set of files.  It never completes the download which explains why I never saw the updates in the  downloaded files. 

OnlyOffice didn't give the message when "Download As" couldn't save.

Previously, and I don't know how, I somehow found a log and it mentioned something like "file was corrupt and couldn't be saved".  I can't find this now so I don't know where to look for this status - however, this indicated OnlyOffice was aware the file couldn't be saved but no dialog mentioned this yet it was in this log.  However the files are fine and not corrupted.

I hope this helps.

Thanks,

- Eric










***@***.***> wrote:














***@***.***,

I want to say that I checked on the version you specified at the moment, I receive the correct error message and ask you to provide details of why in your case, with a similar environment, this does not work.

In other words, I don't see what needs to be fixed if the application is working correctly in the current version.



—
Reply to this email directly, view it on GitHub, or unsubscribe.
***@***.***>

**Comment by LuckySpecialist** [comment]
Okay, then a few questions:
1. Where is the attached picture?
2. Are you using the application to work with files locally or is it connected to a cloud service?

**Comment by LuckySpecialist** [comment]
I still don't see the picture, can you attach it w/o using the reply via email?
I understand that you are using a Document Server, then what does Desktop Editors have to do with it?
Can you attach a video demonstrating the problem?
