### ISSUE TITLE
./DesktopEditors: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xXShadicXx11** [ONLYOFFICE/DesktopEditors#158]
Hello, I am currently using Fedora 29, but when installing Onlyoffice from the following repository, I get this error when executing it from the terminal.

`./DesktopEditors: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory` 

To add the repository I followed the instructions on this page. [https://helpcenter.onlyoffice.com/desktop/documents/linux/installation-rhel.aspx](url)

**Comment by Garbulix** [comment]
I've got the same, glad that I am not the only one using Fedora. 
I haven't tried snap yet, but that'd be great if I could prevent installing snapd, which I don't use.

**Comment by Garbulix** [comment]
I found a workaround - making a symlink. I made what **shiftkey** did and now it started (haven't fully tested yet): https://github.com/shiftkey/desktop/issues/21#issuecomment-357715905

But I think it shouldn't need that :( Everything should work out-of-the-box without doing stuff in CLI (think about home users).
I guess that DesktopEditors is optimized for Ubuntu without thinking about Fedora - I had the same error (about gnutls) when installing T7 DAW from RPM converted from DEB file. 
Is there a way to insert making symlink command to RPM installer?

**Comment by sorvani** [comment]
This is not new. I first encountered this error back in November. https://mangolassi.it/post/431462

I removed the Repo and tried the SNAP package. but that is also crappy with a lack of fonts.

Just tried it again today. Still broke.
![image](https://user-images.githubusercontent.com/3302372/51052105-5152b600-159b-11e9-9234-1888acd3b3d8.png)

**Comment by sorvani** [comment]
> I found a workaround - making a symlink. I made what **shiftkey** did and now it started (haven't fully tested yet): [shiftkey/desktop#21 (comment)](https://github.com/shiftkey/desktop/issues/21#issuecomment-357715905)

I did this on my laptop back in November and it does enable the desktop editors to load but still gives errors when doing so.
![image](https://user-images.githubusercontent.com/3302372/51052725-28cbbb80-159d-11e9-81b1-356f0a9e2ea6.png)

**Comment by Garbulix** [comment]
You are right, I also have these errors (didn't see them, because I was launching DesktopEditors from GUI).
I guess that these errors occur because of non-compatibility with Fedora's libcurl.

I hope that finally OnlyOffice will be released as Flatpak, what would probably cure our problems.

**Comment by tsunamaru** [comment]
Same error on Fedora 29. `sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4` resolved problem.

**Comment by bimagv** [comment]
> Hello, I am currently using Fedora 29, but when installing Onlyoffice from the following repository, I get this error when executing it from the terminal.
> 
> `./DesktopEditors: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory`
> 
> To add the repository I followed the instructions on this page. [https://helpcenter.onlyoffice.com/desktop/documents/linux/installation-rhel.aspx](url)

you 

> Same error on Fedora 29. `sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4` resolved the problem.

thanks.. this solved my problem

**Comment by Siryu6** [comment]
> Same error on Fedora 29. `sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4` resolved the problem.

Worked for me ! Thx tsunamaru

**Comment by Zackptg5** [comment]
Same here. Symlink workaround worked fine although I'm not getting these errors:
`./DesktopEditors: /lib64/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/converter/libkernel.so)
/opt/onlyoffice/desktopeditors/DesktopEditors: /lib64/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/converter/libkernel.so)
/opt/onlyoffice/desktopeditors/converter/x2t: /lib64/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/converter/libkernel.so)
/proc/self/exe: /lib64/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/converter/libkernel.so)
`

**Comment by jekeam** [comment]
> Same error on Fedora 29. `sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4` resolved the problem.

ln: failed to create symbolic link '/usr/lib64/libcurl-gnutls.so.4': No such file or directory

**Comment by 805bluebell** [comment]
> Same error on Fedora 29. `sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4` resolved the problem.

Worked for me as well.

**Comment by ShockwaveNN** [comment]
Hi, this issue is rather old and we made a lot of changes

Could you actualize if this problem is still actual for latest stable Fedora?

**Comment by ShockwaveNN** [comment]
In that case I'll close this issue but feel free to comment if someone has this issue actual on latest Fedora or create new issue
