### ISSUE TITLE
In Excel, I can still draw on the unprotected cells, but in OnlyOffice cannot

### ISSUE THREAD

**Issue by kuchaguangjie** [ONLYOFFICE/DesktopEditors#1581]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Expected Behavior

https://github.com/user-attachments/files/15542625/default.xlsx try this file, there is a male / female options which are protected cells, I can draw circle on them on windows, but can't draw anything anywhere with libreoffice calc, others tested with OnlyOffice, also can't.

### Actual Behavior

Can't draw anywhere on sheet with cells partly protected.

**Comment by kuchaguangjie** [comment]
Refer: https://askubuntu.com/questions/1516337/how-to-add-a-circle-around-a-text-in-a-spreadsheet-in-ubuntu-22-04

**Comment by Rita-Bubnova** [comment]
@kuchaguangjie, Does this issue actual in the current stable version of DesktopEditors (8.0)?

**Comment by kuchaguangjie** [comment]
> @kuchaguangjie, Does this issue actual in the current stable version of DesktopEditors (8.0)?

I don't know, from the askubuntu post above, 2 others tested it, and got the same issue.

**Comment by archisman-panigrahi** [comment]
I confirm that this issue is present in ONLYOFFICE 8.0.1.31 (deb) in Ubuntu 24.04.

(Clarification: OP reported version 7.3.7.2, which is his LibreOffice version according to his Ask Ubuntu, and perhaps he mistakenly wrote the LibreOffice version in this bug tracker).

**Comment by rsnegirev** [comment]
Hi @kuchaguangjie @archisman-panigrahi 

You both mean that you tried to insert Shape like this 
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/65603548/f425a3a7-6232-42bf-b4d2-d1f712492767)
but you can't. Right?

I just checked it on ONLYOFFICE 8.0.1.31 (deb) in Ubuntu 22.04 and it works.

**Comment by kuchaguangjie** [comment]
> Hi @kuchaguangjie @archisman-panigrahi
> 
> You both mean that you tried to insert Shape like this ![image](https://private-user-images.githubusercontent.com/65603548/336870522-f425a3a7-6232-42bf-b4d2-d1f712492767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTg0NTgsIm5iZiI6MTcxNzU5ODE1OCwicGF0aCI6Ii82NTYwMzU0OC8zMzY4NzA1MjItZjQyNWEzYTctNjIzMi00MmJmLWI0ZDItZDFmNzEyNDkyNzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE0MzU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYmU3ZGEyZDEwOGQwMGVmZThiMzBhNDY0NWVmOWJjODBhMGU2N2M5ZmRlMjNkYjAxYTlmMmMzOGY3M2ZmMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GrTz_F9dikUXAvGbipSNaKT-1Mv-MQmqKBMGtXeShXU) but you can't. Right?
> 
> I just checked it on ONLYOFFICE 8.0.1.31 (deb) in Ubuntu 22.04 and it works.

Yes, that's what I mean, I can't do it with libre office calc 7.x version.

**Comment by archisman-panigrahi** [comment]
I did not test OP's spreadsheet but tested with my own spreadsheet which has some protected and some unprotected cells, and all shapes are greyed out (see attached picture).

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/3063132/732bcf33-d8d2-4222-b13d-a8f4659e7fc0)

Here is my example spreadsheet (created with ONLYOFFICE) [Book1.xlsx](https://github.com/user-attachments/files/15592433/Book1.xlsx) . You can edit the contents of the unprotected cells, but there is no way to add shapes.

Interestingly, I can add shapes to OP's spreadsheet (the one written in Japanese), just like [this](https://github.com/ONLYOFFICE/DesktopEditors/issues/1581#issuecomment-2150079309).

**Comment by archisman-panigrahi** [comment]
@kuchaguangjie This is ONLYOFFICE bug tracker, please don't mention issues with Libreoffice here.

Although OP's spreadsheet does not have an issue with ONLYOFFICE, the issue seems to be present in ONLYOFFICE in some form, see my [comment above](https://github.com/ONLYOFFICE/DesktopEditors/issues/1581#issuecomment-2150252212).

**Comment by rsnegirev** [comment]
@archisman-panigrahi 

> Here is my example spreadsheet (created with ONLYOFFICE) [Book1.xlsx](https://github.com/user-attachments/files/15592433/Book1.xlsx) . You can edit the contents of the unprotected cells, but there is no way to add shapes.

Yes, that's right. It depends of the protection settings. In this case you should choose this one check-box:
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/65603548/6948f906-7c48-4075-a076-3e619d6ad28b)

In Excel it works the same.

Here is my file (from ONLYOFFICE) where you can add a shape, or a picture, or draw something: 
[adding_shapes.xlsx](https://github.com/user-attachments/files/15593584/adding_shapes.xlsx)

**Comment by rsnegirev** [comment]
So @kuchaguangjie do you have a problem with adding shapes in your file in the ONLYOFFICE or it's only the Libre Calc?

**Comment by archisman-panigrahi** [comment]
> Yes, that's right. It depends of the protection settings. In this case you should choose this one check-box:

Thank you for the clarification, and sorry about the confusion!

**Comment by kuchaguangjie** [comment]
> So @kuchaguangjie do you have a problem with adding shapes in your file in the ONLYOFFICE or it's only the Libre Calc?

I only tested on libre calc, don't have onlyoffice installed.

**Comment by archisman-panigrahi** [comment]
:facepalm: :facepalm: :facepalm: :facepalm: 
I guess we can close the issue.
