### ISSUE TITLE
Add new formulas for the Spreadsheet Editor

### ISSUE THREAD

**Issue by eSkry** [ONLYOFFICE/DesktopEditors#1582]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I suggest adding important functions for the table editor like:

1. [WEBSERVICE](https://support.microsoft.com/ru-ru/office/вебслужба-функция-вебслужба-0546a35a-ecc6-4739-aed7-c0b7ce1562c4) - The function allows you to make HTTP requests and receive the contents of the response;
2. [FILTERXML](https://support.microsoft.com/ru-ru/office/фильтр-xml-функция-фильтр-xml-4df72efc-11ec-4951-86f5-c1374812f5b7) - Allows you to get values from XML by specifying xpath;
3. FILTERJSON - Similar to FILTERXML for JSON only.

**Comment by rsnegirev** [comment]
Hi @eSkry 

Can you please create separate issues for FILTERXML and FILTERJSON?

And about last one formula (FILTERJSON). Where did you find it? I don't see any MS or Google documentation about it.

**Comment by eSkry** [comment]
Hi @rsnegirev 

Sure, I will create separate issues.

**About FILTERJSON**: There is no **FILTERJSON** formula in MS Excel. **However, many APIs now return JSON rather than XML**. It would be good to support JSON as well.

**Comment by eSkry** [comment]
Links:
[WEBSERVICE](https://github.com/ONLYOFFICE/DesktopEditors/issues/1585)
[FILTERXML](https://github.com/ONLYOFFICE/DesktopEditors/issues/1586)
[FILTERJSON](https://github.com/ONLYOFFICE/DesktopEditors/issues/1587)

**Comment by rsnegirev** [comment]
Great thanks. I'll discuss about that with devs and text in every issue.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
