### ISSUE TITLE
Proposal for Extending Spreadsheet Functionality with Custom User-Defined Formulas

### ISSUE THREAD

**Issue by eSkry** [ONLYOFFICE/DesktopEditors#1583]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

**Description**: The basic set of formulas is often insufficient. It would be beneficial to enable users to create custom plugins to extend the standard function set.

**Idea**: Add a `registerFormula` method to the Plugin API. This method should accept a formula name and a handler function. In the spreadsheet editor, users should be able to invoke the registered function just like any other formula: `=MY_CUSTOM_FUNC(A2, "arg2")`.

**Example**:

```js
window.Task.plugin.functions.registerFormula(
    "MY_FUNCTION_NAME",
    function(myarg1, myarg2, myarg3) {
        // Calculate
        return result;
    },
    "This function does..." // Description
);
```

**Usage in spreadsheet cells**: `=MY_FUNCTION_NAME(A4, "dsfa", 34)`

**Comment by askonev** [comment]
@eSkry On version 8.1, the functionality of adding custom functions based on js is implemented. It is also possible to use the functions of the [builder api](https://api.onlyoffice.com/docbuilder/gettingstarted) methods in the block
