### ISSUE TITLE
A detail about password protected files

### ISSUE THREAD

**Issue by wberga** [ONLYOFFICE/DesktopEditors#1597]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

When opening a password-protected document in OnlyOffice, the window that opens to enter the password is not in focus.

In this case, we need to click in the window, in the text field, so that the cursor blinks, and then add the file password.

The default behavior of other Office suites, such as Microsoft Office and LibreOffice, is to open the password window already in focus, with the cursor blinking, allowing you to enter the file's password immediately.

It's a small detail, but I wanted to request this fix because for someone who uses password protected files all day, it's a huge time saver at the end of the day.

To replicate the problem, simply open, for example, a password-protected spreadsheet in OnlyOffice, LibreOffice and Microsoft Excel to see the difference. The problem only occurs when opening a file directly from the operating system, such as a file on the desktop. The problem does not occur when opening the file within OnlyOffice, like recent files.

The system used was OnlyOffice 8.0.1 with Windows 11.

Thank you very much for your attention.

**Comment by ElenaMaaya** [comment]
Hello @wberga! Thank you for your attention to our product! 
I have a good news! This issue will be fixed in the next release. 
Please keep checking for updates.

**Comment by Rita-Bubnova** [comment]
DesktopEditors v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
