### ISSUE TITLE
Hard to find the autocomplete pointer on cell in spreadsheets

### ISSUE THREAD

**Issue by wberga** [ONLYOFFICE/DesktopEditors#1599]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

![excelpointer2](https://github.com/ONLYOFFICE/DesktopEditors/assets/172548835/f56d7685-6ff4-4f19-b9fa-b0b07102ebbd)

I would like to mention that it is very difficult to place the cursor in the exact place in the cell, so that the icon in the image above appears. It's the autocomplete cursor icon.

The impression it gives me is that it is necessary to place the mouse cursor in the exact place in the corner of the cell, for the icon to appear.

I don't really know how to say this, but it would be interesting to add more "pixel activation area" so that it is easier to find this function with the mouse cursor in the corner of the cell.

I compared this behavior in LibreOffice and Excel, and it is actually easier to place the cursor and activate this function in these programs.

That's all, and thank you very much for your attention.

**Comment by VladimirProkofiev52** [comment]
Hello! 
@wberga, I looked into your issue but couldn't replicate it.  
Could you provide more details such as: Which operating system are you using? 
What is your monitor's resolution?
What version of the editor do you have installed? 
What is the system scale on your computer and the scale set in the editor's settings?
Also, are you using the "Zoom" feature directly in the spreadsheet editor? If so, what percentage is it set to?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
