### ISSUE TITLE
Warning for entry in protected cells

### ISSUE THREAD

**Issue by Hedgehog61** [ONLYOFFICE/DesktopEditors#1602]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

If a user enters a value in a locked cell, a warning should be displayed. I had entered and saved values in a table. The next time I opened the table, all the values had disappeared. The search for the cause took some time, as I had not originally activated cell protection.

**Comment by rsnegirev** [comment]
Hi @Hedgehog61 

A warning appears when someone enters a value in a locked cell. What is your scenario? We need more details.

**Comment by Hedgehog61** [comment]
Hi

I try to explain more detailed
I enter daily values in two columns, adding them to a new row every day. However, from a certain row onwards, the two columns were suddenly marked as locked. My problem was that I could enter and save values in these locked cells without getting an error message and without recognizing that I had entered values in locked cells. The next time I opened the calculation document, the values had logically disappeared. It took me some time to find the cause, as I don't normally lock cells that I want to enter values in.
A message like "This cell is locked" would be useful, or when saving the document a warning message "Attention! Some changes will not be saved because they are in locked cells"

Regardings
Ralf

Gesendet von Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQU9BTVFaQUNPVFZHRVg1QUg2Qk9ORFdFUEFJTE5FVkJOSEhJWU9XN1JJQHJlcGx5LmdpdGh1Yi5jb20%3D), der besten kostenlosen E-Mail-App für die Arbeit

**Comment by rsnegirev** [comment]
Can you please send us a problem file?

**Comment by Hedgehog61** [comment]
Hello,

I can easily open the file with LibreOffice or Microsoft Excel, change fields, fill them in and save them. Only OnlyOffice does not work. Especially when I fill in and save several fields, an error occurs. The timestamp of the file has been changed, but the changes have not been saved and the fields are therefore empty.

Systeminformations:
OnlyOffice Flatpack Version 8.0.1.31
System:
Kernel: 5.15.0-112-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy

Gesendet von Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQU9BTVFaSEJORkVRTFFEQjNTR0tDNU9FUDdWWTVFVkJOSEhJWU9XN1JJQHJlcGx5LmdpdGh1Yi5jb20%3D), der besten kostenlosen E-Mail-App für die Arbeit

**Comment by rsnegirev** [comment]
@Hedgehog61 this isn't helping. I can't reproduce it. So please send us a file with problem.

**Comment by Hedgehog61** [comment]
Hello,

What kind of problem file do you mean? I have attached an xlsx file where the problem exists. If I fill more than 2 cells with a value, these are lost again when saving. As long as the file is open, you can see the values, but if you close it and then open it again, these values have disappeared. My workaround is to save the values after each entry. I cannot reproduce the error with other files. When I tried to edit the file copy with Libreoffice and MS-Excel, the behavior did not occur, but it did when I edited it with OnlyOffice. The columns B, H and I were always edited during the attempt.
Greetings Ralf
Gesendet von Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQU9BTVFaRFJIQkQ0V05aU0xXWkpaRk9FUVdOM1pFVkJOSEhJWU9XN1JJQHJlcGx5LmdpdGh1Yi5jb20%3D), der besten kostenlosen E-Mail-App für die Arbeit

**Comment by rsnegirev** [comment]
I don't see any files. But I see that you sending comments via email and probably attached a file this way too.
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/65603548/8688f6b9-e7e6-4db7-abbd-0bd97a46827f)

It isn't working, please attach a file in the Github comment directly.

**Comment by Hedgehog61** [comment]
[Energiekosten.xlsx](https://github.com/user-attachments/files/15992141/Energiekosten.xlsx)
Here is the File.

**Comment by rsnegirev** [comment]
Sorry for a long waiting.

I tried to reproduce this behavior, so I filled up with the some data columns B, H and I, closed the file, opened it again but all the data was saved. In your case as I understand you loosing the data, right?

And also version 8.1 was just released, is there the problem too?

**Comment by Hedgehog61** [comment]
Hi rsnegirev,
I use Linux Mint 21.3, Cinamon-Version 6.0.4, Linux Kernel 5.15.0-113-generic
OnlyOffice Version 8.1.0.169 (flatpak)

For e.g. i fill the field B191, H192 and I191  in the Worksheet 'Strom24', save the file and close OnlyOffice. After opening the file again these fields are empty.
If if enter the value in B191, save the file, enter value in H192, save the file,  enter a value in I191, save the file all the values are present when i'm opening the file again. So i must save the file after each value otherwise i lose data.

Greetings
Ralf

**Comment by rsnegirev** [comment]
I tried also on the same OS an version of OnlyOffice (Linux Mint 21.3, Cinamon-Version 6.0.4, Linux Kernel 5.15.0-113-generic OnlyOffice Version 8.1.0.169 (flatpak)) and with different types of saving (Ctrl+S, toolbar button, save as new file) but just really can't to repeat. 

Can you record a screencast? Or maybe this is the file after saving in Excel or Libre?

**Comment by Hedgehog61** [comment]
As of today, the error has suddenly disappeared. I can't say why. I think we can close this topic. Thank you for your patience and help.

**Comment by rsnegirev** [comment]
Glad to hear that. Feel free to comment here if the problem will appear (hope not:).
