### ISSUE TITLE
Spell checking errors?

### ISSUE THREAD

**Issue by Renen12** [ONLYOFFICE/DesktopEditors#1604]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

8.0.1.31

### Expected Behavior

I expected the spell checking to work like most other document editors.

### Actual Behavior

The spell checking suggested nonsensical corrections.
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/112264908/3e6fad90-f0a1-4a03-b1b7-69eb324ffb68)
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/112264908/cfa92016-39b0-4960-a7af-533a695c153f)

### Reproduction Steps

Can't really get the issue to be reproduced, sorry. The issue only occurs in this document for some reason.

**Comment by ElenaMaaya** [comment]
Hello @Renen12!
Thank you for report! 
 If you can, please attach test file for a more complete test.

**Comment by Renen12** [comment]
> Hello @Renen12! Thank you for report! If you can, please attach test file for a more complete test.
I can't really get the issue to occur anymore, so I don't really know what happened with the spell checking, sorry.

**Comment by ElenaMaaya** [comment]
@Renen12, thank you for your attention to our product! If the problem persists, please write here again. Have a good day!
