### ISSUE TITLE
OnlyOffice 8.1.0 crashes when saving on Ubuntu 24.04

### ISSUE THREAD

**Issue by yanier-dalmau** [ONLYOFFICE/DesktopEditors#1609]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

8.1.0.169

### Expected Behavior

I expect to save my files or open a local file

### Actual Behavior

OnlyOffice 8.1.0 crashes on Ubuntu 24.04 when I try to save or open a local file.

**Comment by XDmitryK** [comment]
@yanier-dalmau Hi
Can you attach your file or short video here? And if possible, see if there are errors in the terminal when opening the file

**Comment by yanier-dalmau** [comment]
Thanks for answering. Here a demo,
https://github.com/ONLYOFFICE/DesktopEditors/assets/45681889/5ab43a76-3096-4612-8e7e-63acdef7f292

The same does not happen with the snap version, the latter works well

**Comment by XDmitryK** [comment]
@yanier-dalmau 
Unfortunately, your problem does not reproduce on my PC. Can you write information about your PC?
Perhaps the problem is related to the video card and Vulcan technology.Perhaps driver updates can solve this problem, but not sure.

**Comment by yanier-dalmau** [comment]
@XDmitryK
I have to apologize for responding late.
I updated to the latest version 8.1.1.27 (deb) and the problem on my PC remains. PC properties with neofetch:
OS: Ubuntu 24.04 LTS x86_64 
Host: HP EliteBook 840 G1
Kernel: 6.8.0-38-generic 
Shell: bash 5.2.21 
Resolution: 1600x900 
DE: GNOME 46.0 
WM: Mutter 
CPU: Intel i7-4600U (4) @ 3.300GHz 
GPU: Intel Haswell-ULT 
Memory: 6301MiB / 15417MiB

There is no problem with the snap version, which is the one I have chosen to use

**Comment by XDmitryK** [comment]
@yanier-dalmau Thanks for info
But we are not yet reproducing the problem on our virtual machines (Ubuntu 22.04/24.04, Linux Mint 21.3)
It is possible that the problem is specifically with your system build.

**Comment by yanier-dalmau** [comment]
Ok, I will continue working with the snap version. There is no difference in the work experience. Thank you very much.

**Comment by TeamLinux01** [comment]
I just want to add that I am having the same problem with `version 8.1.1.27 (flatpak)` downloaded from flathub.

![image](https://github.com/user-attachments/assets/5165955c-b86a-4cd5-9c67-5eb5292fdb43)
