### ISSUE TITLE
Ctrl+Backspace not working

### ISSUE THREAD

**Issue by uncertainquark** [ONLYOFFICE/DesktopEditors#161]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Ctrl+Backspace doesn't delete the entire word as it should and does across all operating systems.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Write something, use "Ctrl+Backspace" to delete an entire word. It doesn't work, only a single character is deleted.

**What is the expected behavior?**
Should delete an entire word.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v5.2.4

**Comment by ShockwaveNN** [comment]
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/161

**Comment by uncertainquark** [comment]
You mean to say duplicate of #152? You have linked to bug #161, which is this same bug report.

**Comment by ShockwaveNN** [comment]
@uncertainquark yes, of course, sorry
