### ISSUE TITLE
Show comment indicator by default

### ISSUE THREAD

**Issue by uncertainquark** [ONLYOFFICE/DesktopEditors#162]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If there are comments in the document, the sidebar comments doesn't indicate if there are comments or the number of them.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open any documents with comments in it. You will not see any indicator on the comment icon to hint that there are comments in the document.

![01-oo-comments](https://user-images.githubusercontent.com/22585732/51168752-313f3180-18d0-11e9-8d1f-18a9b903127a.png)
![02-oo-comments](https://user-images.githubusercontent.com/22585732/51168753-31d7c800-18d0-11e9-8311-bc66fa0b6fad.png)

**What is the expected behavior?**
The comment icon in the sidebar should show an indicator bubble or a number indicating that there are comments.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v5.2.4

**Comment by Rita-Bubnova** [comment]
Hello, @uncertainquark.
The indicator on the Comments icon in the left toolbar appears only when another user adds a comment (the Comments panel must be hidden).
In the document depicted on your screenshot there are only comments added by you, that is, the indicator does not appear.
