### ISSUE TITLE
Bad print preview if header or footer was focused before

### ISSUE THREAD

**Issue by Norbert80** [ONLYOFFICE/DesktopEditors#1623]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

Version 8.1.0.169 (deb)

### Expected Behavior

Print preview should be correct.

### Actual Behavior

Print preview is bad:
- Header and footer indicators are displayed
- Document body content is gray instead of black

![Bildschirmfoto vom 2024-07-03 14-07-14](https://github.com/ONLYOFFICE/DesktopEditors/assets/6921696/0bf795b2-252e-454c-9a26-479259cd9770)

### Reproduction Steps

- Open any docx document
- Enter the header or footer
- Open the print preview (menu File / Print)

**Comment by LuckySpecialist** [comment]
Hi @Norbert80!
I have issued your request as Bug 68991.
Thank you for reporting the problem.

**Comment by Rita-Bubnova** [comment]
DesktopEditors v8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
