### ISSUE TITLE
Problems with the encoding of the .rtf file in the Belarusan language

### ISSUE THREAD

**Issue by Belarusan** [ONLYOFFICE/DesktopEditors#1625]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

8.1.0.169 (x64 exe)

### Expected Behavior

The file should open correctly. I have never used previous versions of DesktopEditors. But other .rtf files opened correctly now.

### Actual Behavior

All the text in the file had the wrong encoding. This file opens well in other editors. I did not find any way to change the encoding

### Reproduction Steps

1. Just open the file

### Additional information

The language of the document is Belarusan.

Here's a screenshot:
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/120222658/8831cd37-1ebe-4b68-9a1b-44e654ac4dc5)

I don't know if this is related, but if I select "Choose document language", it will be Polish, but changing to Belarusan will not change anything
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/120222658/d4155827-fdd1-471e-bdd5-da3eb745c7f8)
(Or is the Polish language just a suggested language? )

**Comment by TatianaKirillova** [comment]
Hello @Belarusan! 
Thank you for your request! Could you attach a file with this problem?

**Comment by Belarusan** [comment]
Greetings, @TatianaKirillova
Here is the file. I removed all the unnecessary text leaving only a few lines
[corrupted_file.zip](https://github.com/user-attachments/files/16115384/corrupted_file.zip)

**Comment by TatianaKirillova** [comment]
@Belarusan Thank you very much for your file! But this file opens with this encoding and in the MS Word 2019 editor.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
