### ISSUE TITLE
Incorrect grammatical gender in the name of the Belarusan language

### ISSUE THREAD

**Issue by Belarusan** [ONLYOFFICE/DesktopEditors#1626]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

The Belarusan language is called in its entirety as „Беларуская мова“. „Мова“ is feminine. It will be abbreviated simply as „Беларуская“, not „Беларускі“.

_„Беларускі“ is for masculine words, for example „Беларускі дух“ („Belarusan spirit“)._

Please fix this grammatical error. **Should be written „Беларуская (Беларусь)“**

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/120222658/ef780282-4865-4882-b980-acf34f16f1a2)

**Comment by TatianaKirillova** [comment]
Hello, @Belarusan 
Thank you for noticing, the problem really exists. Issue No. 69021 for your task
Problem reproduces in Document Server.

**Comment by piotra7r** [comment]
In fact, you can still write **па-беларуску** it means "in Belarusian"

**Comment by Rita-Bubnova** [comment]
DesktopEditors v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
