### ISSUE TITLE
Cursor changes color when selecting superscript text on dark theme

### ISSUE THREAD

**Issue by raulgrangeiro** [ONLYOFFICE/DesktopEditors#1632]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

8.1.0.169

### Expected Behavior

The cursor remains white when selecting all kinds of texts.

### Actual Behavior

The cursos becomes black and hard to detect when selecting superscript text.

### Reproduction Steps

1. Use black theme on OnlyOffice
2. Open an document and write sothing using normal writing and superscript writing.
3. See the cursor bugging.

### Additional information

My system: Ubuntu 23.10
Screen resolution: 1920x1080
CPU: Ryzen 7 5700U
RAM: 20GB 3200 MHz
SSD: 512GB M.2

I recorded a video showing the bug.

[Gravação de tela de 2024-07-09 09-51-23.webm](https://github.com/ONLYOFFICE/DesktopEditors/assets/10498152/b0d3692e-3c8b-48fe-a7a7-ae9e18b6a525)

**Comment by ElenaMaaya** [comment]
Hello, @raulgrangeiro! Thanks for your report! Unfortunately, I tried to reproduce this issue, but still unsuccessful on Windows 11 и Kubuntu 23.10 on Desktop Editors v. 8.1.0.169.  It would be great if you could attach this docx file for a more complete test.  Thank you!

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
