### ISSUE TITLE
Table of Content page number type doesn't change to other page number formats

### ISSUE THREAD

**Issue by Sanjay-Khadka** [ONLYOFFICE/DesktopEditors#1651]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package), Linux (RPM package)

### Version information

8.1.1.27

### Expected Behavior

When I changed the page number format to roman numbers it should also update the page numbers of those pages to roman numbers ? no this is the new feature.

### Actual Behavior

When I changed the page number format to roman numbers it change to roman numbers of the document pages but the number format still remains to be numbers in the Table of Content page number

### Reproduction Steps

From Header and footer Setting go to the bottom of the page and change to a number format option from the dropdown.
From references add Table of Content and check for page number, it should be numberic though the documents' page number is roman or in other formats.

### Additional information

I am on Fedora 39 workstation

**Comment by ElenaMaaya** [comment]
It's issue duplicate [#2811](https://github.com/ONLYOFFICE/DocumentServer/issues/2811). 
Problem reproduces in Document Server.
