### ISSUE TITLE
Table of content paragraph styles seem to be missing from 8.1.0

### ISSUE THREAD

**Issue by sokke90** [ONLYOFFICE/DesktopEditors#1652]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

8.1.1.27

### Expected Behavior

When inserting a TOC, you should be able to switch between different TOC styles and be able to edit the TOC styles manually with right click.

### Actual Behavior

As in 8.0.1, you should be able to switch between the styles and also have TOC paragraph styles assigned to the specific items.
All TOC items have the "Normal" paragraph style applied, which makes it impossible to differentiate between different TOC levels.

### Reproduction Steps

- Insert some headers, at least from level 1 to 3
- Insert Table of Content
- Click inside Table of content
- on the appearing border's header menu, click on "Table of Contents" -> "Settings"
- Change to any style on the lower right side, click ok.
- Nothing happens.

**Comment by matveevms** [comment]
Hello, @sokke90  
We are aware of this problem and have already fixed it for a future version. 
https://github.com/ONLYOFFICE/sdkjs/commit/e9559b2f138d476d29ea5e7b2d13d46d91f4848d
Thanks for feedback.
