### ISSUE TITLE
Pivot table filter rows does not filter blanks

### ISSUE THREAD

**Issue by gemorgan** [ONLYOFFICE/DesktopEditors#1665]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

8.1.1.27

### Expected Behavior

When unchecking (blank) and {Blanks} in the Row Labels filter, the row that is labeled (blank) with no values show no be shown. 

### Actual Behavior

The row shows no matter how I try to filter it. Unchecking the boxes in the filter, creating a new column and using it to filter. Nothing hides that (blank) row. When opening the same file in MS Excel, the "(blank)" row is indeed hidden. 

### Reproduction Steps

pivot a table that produces values for rows. Try to make the (blank) row go away.

**Comment by VladimirProkofiev52** [comment]
Hello! @gemorgan 
I have reviewed your issue but was unable to reproduce it. 
Could you please provide a more detailed description? 
If the problem occurs only with a specific file, kindly share that file with me.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
