### ISSUE TITLE
.docx  style problem

### ISSUE THREAD

**Issue by liulindong** [ONLYOFFICE/DesktopEditors#1667]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.3.3.49

### Expected Behavior

![image](https://github.com/user-attachments/assets/5612dc8e-bb39-4319-a212-6b6fa01d6487)

### Actual Behavior

![image](https://github.com/user-attachments/assets/f3bccabc-967f-4474-9c2f-8f4ea33ecf7f)

### Reproduction Steps

I used the pc side to view the document and it showed 9 pages, which is normal. But when I use the web side, it shows 11 pages, and the date is on the second page

### Additional information

This is the document in question，I opened it normally on ms office
![image](https://github.com/user-attachments/assets/b6026f34-0068-4df2-bd2f-035835592dc9)
[111.docx](https://github.com/user-attachments/files/16835424/111.docx)

**Comment by matveevms** [comment]
Hello, @liulindong 
Please tell me whether the font you are using is installed on your Document Server? If not, you need to install it. And I recommend you to use the latest version of the editor.

**Comment by liulindong** [comment]
> Hello, @liulindong Please tell me whether the font you are using is installed on your Document Server? If not, you need to install it. And I recommend you to use the latest version of the editor.

thanks，I tried to add some fonts and the problem was solved
