### ISSUE TITLE
Adding a new (left) column copies formatting

### ISSUE THREAD

**Issue by Korne127** [ONLYOFFICE/DesktopEditors#1673]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

8.1.1

### Expected Behavior

Let's say, you have two columns. In A, there is a lot of formatted text (e.g. dates with a yellow background). In B there is some other text. You want to add a new column between those. To do this, you right-click on B and Insert Left. This new column should have default formatting (transparent, general, etc.).

### Actual Behavior

If you actually right-click on B and then click on Insert Left in the described scenario, the new column copies the formatting of the column left to it (in this example A).
This means that the rows which have a coloured background in A have also a coloured background in the new column. Also the cell type (e.g. date) is copied onto the new cells:

<img width="208" alt="image" src="https://github.com/user-attachments/assets/0b0c44ad-49fe-4bca-a8d9-24ee6839a8d6">

### Reproduction Steps

1. Add formatting in column A
2. Right-click on column B and then click on Insert Left

### Additional information

I'm using macOS 14.3.

**Comment by rsnegirev** [comment]
Hi @Korne127 

It's not a bug, this is the same behavior as in LibreOffice or Excel. So this is kind of a standard.

Feel free to reopen this issue if you have more questions.
