### ISSUE TITLE
App freezes when exiting (Linux/Widnows)

### ISSUE THREAD

**Issue by muhammad-halimov** [ONLYOFFICE/DesktopEditors#1681]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, Linux (RPM package)

### Version information

version 8.1.1.27 (x64 msi)

### Expected Behavior

When click the close button, app should close and end the process

### Actual Behavior

But instead it just freezes until u shut it down with some special force units like task manager on windows and gnome

### Reproduction Steps

Investigate why it's crashing when closing the app

### Additional information

1080p60Hz
Intel 10210u
16/512
honor magicbook x15 2021

**Comment by Andrez092** [comment]
This might help:This file might fix it
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by LuckySpecialist** [comment]
Hi @muhammad-halimov!
Let's take a look at one system, for example windows
Can you record a video to show what the problem looks like?
After closing the application, is some error recorded in the system log?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
