### ISSUE TITLE
When searching in the spreadsheet - the default search should be by value, not formula

### ISSUE THREAD

**Issue by andrei93r** [ONLYOFFICE/DesktopEditors#1683]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

8.1.1.28

### Expected Behavior

When opening a spreadsheet and hitting ctrl + F , it searched in formula and not by value. 

### Actual Behavior

Unless otherwise specified, the default search should be by value. 

### Reproduction Steps

Open a spreadsheet
hit ctrl + f
type
should find any text values containing the text

**Comment by Dmitry-Kov** [comment]
Hi @andrei93r! This is the default behavior – we search through formulas. For example, MS Excel editor has the same behavior. If you need to search by values, you can change the search options in the advanced settings by doing the following:
  • Press Ctrl+F
  • In the search window, click ‘Open advanced settings’
  • On the ‘Find and replace’ panel, in the ‘Look in’ field, select -> ‘Values’
  Was I able to help, or do you have any further questions?

**Comment by andrei93r** [comment]
Hi @Dmitry-Kov 

As a user, when I search a partial or full string in a spreadsheet, I expect all references to be found. Maybe your right, that Excel searches by formula , however its finding the partial string. Even google drive does this. Maybe have an automatic fashion that searches for both.

EX: By formula
![Screenshot_20240920_201250](https://github.com/user-attachments/assets/e7540ead-83ed-48de-8591-cacb01cdb3b2)

Ex; By value
![Screenshot_20240920_201412](https://github.com/user-attachments/assets/87917990-b770-4d5a-85f9-b13da84115e9)

Maybe formula is broken, idk, but it does not find the searches for me

**Comment by Dmitry-Kov** [comment]
Hi @andrei93r 

I have looked into your issue but was unable to reproduce it.
Does the problem occur only with a specific file or with all files?
If the problem occurs only with a specific file, please send me that file.

**Comment by andrei93r** [comment]
@Dmitry-Kov 

I'm not 100% on this, however it seems to happen with protected sheets. I also cannot share the documents i'm working with, however it definately not just one file.

**Comment by Dmitry-Kov** [comment]
@andrei93r ,

Could you please describe step by step how the issue is reproduced? It would also be great if you could attach a screencast.
