### ISSUE TITLE
saving a document in HTML it duplicates the content

### ISSUE THREAD

**Issue by GuidoCamp** [ONLYOFFICE/DesktopEditors#1684]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

8.1.0

### Expected Behavior

saving a document in HTML it could be write only 1 time

### Actual Behavior

saving a document in HTML it duplicates the content

**Comment by XDmitryK** [comment]
@GuidoCamp Hi
Can you attach a file or a short video demonstrating the problem?

**Comment by GuidoCamp** [comment]
Good evening,
I attached a video in which I do an example of the situatione.
It appens only copyng a content from a docx, a odt or something like these. Pasting the content in a new file and saving the new file as html.
The result is that the content is duplicated. 
But it doesn't appens if a create a new file, i write somthing within and saving it as html.

thank you a lot.

Guido

https://github.com/user-attachments/assets/95b188ec-abcc-42cf-a297-701599284f3b

**Comment by XDmitryK** [comment]
Yes, this bug still exists in 8.1.0 but not reproduced in 8.1.1. Can you update Onlyoffice and check this case?

**Comment by GuidoCamp** [comment]
I update to version 8.1.1 and now it works well.
thank you so much

**Comment by GuidoCamp** [comment]
Now I update to version 8.1.1 and now it works well.
thank you so much
