### ISSUE TITLE
 DesktopEditors_x64.exe does not allow you to choose the installation folder

### ISSUE THREAD

**Issue by f242** [ONLYOFFICE/DesktopEditors#1698]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

8.2

### Expected Behavior

I expected to see the offer to choose the installation folder

### Actual Behavior

simply specify where the application will be installed without the "view" button or something similar
Here are all the steps that are when the installer is launched
![image](https://github.com/user-attachments/assets/c97a0717-7c7c-4eab-a2f4-f25edfb72ace)
![image](https://github.com/user-attachments/assets/d526e518-46e9-4b55-8058-197ea124e802)
![image](https://github.com/user-attachments/assets/0b927e3c-643a-4fbf-bfd8-582e9c271d22)
![image](https://github.com/user-attachments/assets/b16b6bd6-83f9-4411-b33b-9df7db9c3cb1)
![image](https://github.com/user-attachments/assets/60029b61-2f3f-46cf-bf15-e272f79755ea)
![image](https://github.com/user-attachments/assets/5fcd44fa-778d-4693-8480-6b7bd3b96c00)
![image](https://github.com/user-attachments/assets/4da470a9-92c5-428d-9e29-656e0ff8b235)

**Comment by Rita-Bubnova** [comment]
Hello, @f242. 

Please, when creating an issue, fill in all the fields of the form on English.

**Comment by LuckySpecialist** [comment]
Hi, @f242!
This is written in the [list of changes.](https://github.com/ONLYOFFICE/DesktopEditors/blob/master/CHANGELOG.md#820)
To display the installation directory selection page for the EXE package, use the `/enabledirpage` key or MSI package, where the installation directory page is not hidden by default.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
