### ISSUE TITLE
Date format isn't handled

### ISSUE THREAD

**Issue by Piscean** [ONLYOFFICE/DesktopEditors#17]
Bug: cells with dates in them show up as numbers.  No obvious way to format the cell as a date

To repro:
1. Create a spreadsheet in Excel or some other spreadsheet editor
2. Format a cell as Date format and enter the date.  (ie, 12/26/2016)
3. Safe the spreadsheet
4. Open that spreadsheet in DesktopEditors.  
--> The date you just entered shows up as "42730".  Expected it to match what we entered, which was "12/26/2016"

DesktopEditors version:
Linux using version 4.2.3.290
Windows 10 using version 4.2.3.296

Not sure if this worked in previous DesktopEditors versions.  This is the first version I've tried.

**Comment by trofim24** [comment]
Could you attach the saved file `.xlsx` to this issue ?
Thanks.

**Comment by Piscean** [comment]
As soon as I remove enough PII from the spreadsheet to share it, this problem is gone.  I would like to close the issue for now, until I can repro.  

When I opened the bug I thought it was a simple repro, but there is obviously something else going on here.

**Comment by chaos-prevails** [comment]
-) ONLYOFFICE Desktop Editors version 5.5.1.78
-) libreoffice fresh 6.4.3.2
-) Ubuntu 18.04 (locale is English United States)

I have this problem for many months now in a rather big ods file. As we are now rethinking our office platforms (and format), I replicated it in a fresh ods file (I didn't find this problem when using xlsx).

Problem description:
1) My initial problem was that onlyoffice did not recognize any date formatted cell at all in a ods file: for all dates (format YYYY-MM-DD), it would show numbers. I recently found out, that when I switched onlyoffice to swedish locale (which is the only one using YYYY-MM-DD by default), it would correctly show. However, today, it suddenly worked also with other locales in onlyoffice (I deleted ~/.config and ~/.local/share before trying again) for _MOST_ date fields (but not for all). The _same_ problem happens with a colleague using latest onlyoffice on Windows. 
2) The attached ods (I had to rename it to xlsx) file shows the inverse problem of my historical problem: a number is identified as date: **cell F3 (and also e.g. H3**)
3) It does not occur in a xlsx sheet (also enclosed)
[testdate1.ods.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/4898189/testdate1.ods.xlsx)

replication:
1) create a (big) spreadsheet in libreoffice
2) mark all cells (top left corner) and change format to date (and YYYY-MM-DD)
3) copy some fields with numbers somewhere into the sheet (into cells which have been formatted as date YYYY-MM-DD) -> numbers show correctly in libreoffice, also after reopening.
4) save as ods, and as xlsx.
**5) open ods in onlyoffice: cells show as date: wrong**
**6) open xlsx in onlyoffice: cells show as numbers: correct**

as I couldn't upload ods, I renamed it to testdate1.ods.xlsx (please remove the last extension)
[testdate1.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/4898188/testdate1.xlsx)
[testdate1.ods.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/4898190/testdate1.ods.xlsx)

**Comment by ShockwaveNN** [comment]
@chaos-prevails Hi, could you create a new isssue, since this one is pretty old

**Comment by chaos-prevails** [comment]
Hi Shockwave,

I did so: https://github.com/ONLYOFFICE/DesktopEditors/issues/424
