### ISSUE TITLE
Since 8.2 VLOOKUP function produces an array instead of a single value as it used to in 8.1 with range as a first argument.

### ISSUE THREAD

**Issue by nkolotov** [ONLYOFFICE/DesktopEditors#1704]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

8.2.0

### Expected Behavior

In v8.1 spreadsheet editor `VLOOKUP` function in a single cell produced output to this single cell even when first argument was a range of cells.
This behavior matched to Excel and LibreOffice.

### Actual Behavior

In v8.2 behavior suddenly changed. Now `VLOOKUP` function in a single cell produces an array as an output when first argument is a range of cells. For example `=VLOOKUP(A:A;List1;2;0)` becomes `{=VLOOKUP(A:A;List1;2;0)}` and editor turbofills the cells to show produced array. This breaks existing spreadsheets.

### Reproduction Steps

- select cell `D1`
- type formula `=VLOOKUP(A:A;List1;2;0)`
- press Enter
- with v8.2 editor starts filling `D` column (with v8.1 it would only fill `D1` cell)
- prompt appears for 10000 rows filled asking whether to stop or to continue filling remaining rows

**Comment by rsnegirev** [comment]
Hi @nkolotov 

We've changed behavior of Functions which may imply an array response. 

In this case an array A:A used as the first argument, that's why the result filled whole column D. You need just to change the first argue for A1:A25, for example.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by nkolotov** [comment]
@rsnegirev Well, changing `A:A` to `A1:A25` won't be of much help. Yes, it won't try to fill all the whole row, only 25 cells, however i'm expecting it to fill a just a single cell as it used to (and as it works in other editors) instead of producing an array.

**Comment by nkolotov** [comment]
@rsnegirev Excel 2016:
![msexcel2016](https://github.com/user-attachments/assets/878dbd52-f6d2-4ab3-b073-3d26254cd72a)
LibreOffice Calc:
![libreoffice](https://github.com/user-attachments/assets/9bad610e-0316-41a7-a986-232765b343d6)

Well, if this new behavior of OnlyOffice Spredsheet editor matches to newer MsOffice, then it is fine. It makes sense. However it would be helpful if such breaking changes were listed in Release notes (even better if they were accompanied with some sort of upgrade guide).

Also in this case fixing of broken documents after upgrade is complicated by inability to edit formula after it was transformed into array. Users have to delete entire column and then rewrite everything from scratch. Is this intended as well? Perhaps i should fill a new issue?

https://github.com/user-attachments/assets/4d9b6478-d5a9-4663-aff1-b26a23274317

**Comment by VladimirProkofiev52** [comment]
Hello @nkolotov 
I created ticket #71414 with your proposal.
Problem can be reproduced in DocumentServer.
Thank you for your report!
