### ISSUE TITLE
Error on Nextcloud loading

### ISSUE THREAD

**Issue by gregoriopellegrino** [ONLYOFFICE/DesktopEditors#171]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I try to add a NextCloud account, after the login, the webpage says "problem when loading the page" and it is refreshed in loop.

**What is the expected behavior?**
No error, on the browser everything is ok

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Version 5.2.1 on Mac, don't know previous versions

**Comment by Rita-Bubnova** [comment]
Hello, @gregoriopellegrino.
What is you Nextcloud connection url? Does it contain subdomain?

**Comment by Rita-Bubnova** [comment]
It known issue and will be fixed next releases.
Now you can remove your connection from the list and connect again without slash at the end of url (https://www.sportellodellosport.com/file-manager).

**Comment by gregoriopellegrino** [comment]
In this way I can't even login (with no error on webpage).

**Comment by Rita-Bubnova** [comment]
Unfortunately we can not reproduce the problem. After removing the portal from the list and reconnecting without the last slash, everything should work.
Could you provide us with a guest account at https://www.sportellodellosport.com/file-manager to reproduce the problem? You can share it with support@onlyoffice.com for security reasons.

**Comment by Rita-Bubnova** [comment]
We took a look at your Nexcloud and found out that there is no ONLYOFFICE Document Server connected to it. Furthermore you should install ONLYOFFICE App. 
You can learn more [here](https://api.onlyoffice.com/editors/nextcloud) and [here](https://www.onlyoffice.com/connectors-nextcloud.aspx).
