### ISSUE TITLE
old CheckBox types not clickable

### ISSUE THREAD

**Issue by urkos101** [ONLYOFFICE/DesktopEditors#1712]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

version 8.2.0.143 (flatpak)

### Expected Behavior

I have a document with dozen of old checkboxes. With this new update, I can finally see them, but nothing happen when I click on them.
I opened the document in other word processor to select the last two (in red in the image).
is that possible with onlyoffice? To use old checkboxes and select them?

![Pic](https://github.com/user-attachments/assets/46b9371d-1f86-4180-a87d-a50cf9dbd29f)

### Actual Behavior

When clicking on old checkbox, nothing happens.

**Comment by XDmitryK** [comment]
@urkos101 Hi
Can you attach the file here?

**Comment by urkos101** [comment]
Hi, 
Sure, I removed bunch of text and forms that are not important and only left the part where the checkboxes are.. ignore the text, as I just deleted what was written wrote something in english.
The original document is an application form to fill it, sign it and sends it back as the pdf to the administrative unit.
Hope it will help. 

[Testing-doc.docx](https://github.com/user-attachments/files/17834689/Testing-doc.docx)

**Comment by XDmitryK** [comment]
Thanks for file.
You can edit this field using the Protection tab. 

https://github.com/user-attachments/assets/a53ef8b1-92c3-4c79-ae59-6c161ce47cd7

**Comment by urkos101** [comment]
thank you for this.. 
Perhaps this could be enabled by default in future release?

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
