### ISSUE TITLE
Double-tap filename in tab to rename it

### ISSUE THREAD

**Issue by moonmehta** [ONLYOFFICE/DesktopEditors#173]
**Do you want to request a *feature* or report a *bug*?**
Feature
It would be cool if one could double tap a tab where the filename is shown and rename the file from there quickly. At present, there is no quick way to rename a file.

![screenshot from 2019-02-03 15-37-12](https://user-images.githubusercontent.com/22585732/52175423-a021f300-27c9-11e9-845c-c0772012827b.png)

**Comment by Rita-Bubnova** [comment]
Hello, @uncertainquark. 
Thank you for your enhancement.
I created a new issue 40450 in our private issue tracker.

**Comment by uncertainquark** [comment]
Any update on this?

**Comment by Rita-Bubnova** [comment]
Sorry, no update.
You can contact sales team sales@onlyoffice.com to speed up things.

**Comment by maruacat** [comment]
Hello, @moonmehta 
Thank you for your feedback and waiting.
At the moment, the functionality of renaming a file by double-clicking on the name is implemented in our editor for files located in the cloud, including when connected to the cloud in the desktop editor. Unfortunately, there is no technical possibility to implement this functionality for files opened in the desktop editor and stored locally.
Have a good day!
