### ISSUE TITLE
Pinch-to-Zoom Touchpad gesture isn't working on Windows

### ISSUE THREAD

**Issue by thisisartman** [ONLYOFFICE/DesktopEditors#1735]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

version 8.2.1.38 (x86 exe)

### Expected Behavior

When you use two-finger pinch to zoom gesture via touchpade, the document should zoom in.

### Actual Behavior

Does nothing.

### Reproduction Steps

1. Open any document, Spreadsheet or PDF.
2. Try zooming into document using touchpad.
3. Tada!

**Comment by Gingetsu** [comment]
Hello @thisisartman  !
This is the same problem as in this issue: #68812
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/1611.

**Comment by thisisartman** [comment]
Hi @Gingetsu, that issue is for Linux... I use it on Windows... Should I rename the issue to make it clear?

**Comment by Gingetsu** [comment]
Yes, you can rename it to make it clearer.

**Comment by thisisartman** [comment]
The name already mentions Windows. Similarly, I've mentioned it in the OS used.

**Comment by Ready-TP** [comment]
Same on Windows 11 an version 9.2.0.100
