### ISSUE TITLE
Dark Document mode for Spreadsheets

### ISSUE THREAD

**Issue by thisisartman** [ONLYOFFICE/DesktopEditors#1736]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Add a dark document mode similar to what is present in the Document, PDF Editors.

**Comment by Rita-Bubnova** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1944.
