### ISSUE TITLE
"Shapes" have incorrect, not at all useful tooltip/labels 

### ISSUE THREAD

**Issue by uncertainquark** [ONLYOFFICE/DesktopEditors#174]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Hovering over a shape gives not useful tooltips/labels.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Insert Shape > Hover over any shape > Read the tooltip that pops up

![screenshot from 2019-02-03 15-39-29](https://user-images.githubusercontent.com/22585732/52175465-6dc4c580-27ca-11e9-9f78-ee90f0560198.png)
![screenshot from 2019-02-03 15-39-41](https://user-images.githubusercontent.com/22585732/52175477-96e55600-27ca-11e9-98e1-e505e0688e70.png)

**What is the expected behavior?**
Tooltip should read what the shape it: Circle, Rounded rectangle, etc.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v 5.2.8

**Comment by Rita-Bubnova** [comment]
Hello, @uncertainquark.
Thank you for your enhancement.
We know about this problem, issues 17685 and 20091 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
This problem is fixed in https://github.com/ONLYOFFICE/web-apps-pro/commit/4b32576571d124df4c18a1e4f2c5c46f9039e2c4
We'll release this fix in version 5.3.
