### ISSUE TITLE
Allow downloading a slide as a PNG/JPG/SVG image

### ISSUE THREAD

**Issue by moonmehta** [ONLYOFFICE/DesktopEditors#175]
**Do you want to request a *feature* or report a *bug*?**
Feature (parity with competition)

**What is the current behavior?**
No download slide as PNG/JPG/SVG option present 

Google Drive, for instance has an option to download selected slide in all the above mentioned formats.

![screenshot from 2019-02-03 15-52-38](https://user-images.githubusercontent.com/22585732/52175610-3e16bd00-27cc-11e9-82d9-507ce2bc9d39.png)

For presentations, where one can be creative using features like shapes, images, text art,  etc. it is crucial to be able to download a slide in full resolution as a JPG/PNG/SVG. As a content creator who uses quick self created graphics to enhance my writings, I love this feature on MS Office and Google Slides. Would be really crucial to have it in OnlyOffice as well.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v 5.2.8

**Comment by Rita-Bubnova** [comment]
Hello, @uncertainquark.
Thank you for your enhancement.
I created a new issue 40447 in our private issue tracker.

**Comment by uncertainquark** [comment]
Any update on this? This is very useful for basic image making functions and the like. Currently having to use Google Docs and MS Office for this.

**Comment by Rita-Bubnova** [comment]
Sorry, no update.
You can contact sales team sales@onlyoffice.com to speed up things.

**Comment by trofim24** [comment]
Relesed in [version 7.0.0](https://github.com/ONLYOFFICE/DesktopEditors/blob/master/CHANGELOG.md#700)
