### ISSUE TITLE
Fixing multiple columns or rows OR fixing the first column and first row at once

### ISSUE THREAD

**Issue by SMHRambo** [ONLYOFFICE/DesktopEditors#1751]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

It would be nice if it were possible 
to fix several columns or rows at once.
Example: By selecting several columns or rows when fixing

Video of  two fixed columns in google docs:

https://github.com/user-attachments/assets/83bb3ec9-1f47-4aa5-9eeb-d6363ce3e3ec

to fix the first column and the first row at the same time.
Example: By selecting cell 1A when fixing.

Video of fixed frist column and row in google docs:

https://github.com/user-attachments/assets/0c3aa071-e73a-4349-a33e-6ad525b4e310

**Comment by Dmitry-Kov** [comment]
Hello @SMHRambo,

To freeze two columns (in this case, A and B), you need to select column C by left-clicking on it, then right-click and choose “Freeze Panels” from the dropdown menu. This will freeze the first two columns (you can also freeze two rows using the same method).

Additionally, you can freeze the first column and the first row: select cell B2, go to the “View” tab on the top panel, choose “Freeze Panels,” and then click “Freeze Panels” in the dropdown menu.

For more detailed information, you can visit this link: https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/Editors-User-Guides/SpreadsheetEditor/Freeze-rows-and-columns.aspx.

I hope this answers your question!
