### ISSUE TITLE
Right-click option to move slide to beginning/end 

### ISSUE THREAD

**Issue by moonmehta** [ONLYOFFICE/DesktopEditors#176]
**Do you want to request a *feature* or report a *bug*?**
Feature

Having an option to right-click a slide and move it to the beginning/end of a presentation is very convenient. Google Docs has it.

First slide:
![screenshot from 2019-02-03 17-18-56](https://user-images.githubusercontent.com/22585732/52176391-512f8a00-27d8-11e9-98f9-47d44043663c.png) 

Slide in between:
![screenshot from 2019-02-03 17-19-21](https://user-images.githubusercontent.com/22585732/52176392-51c82080-27d8-11e9-9e87-6a742195d35a.png)

Last slide:
![screenshot from 2019-02-03 17-19-36](https://user-images.githubusercontent.com/22585732/52176393-51c82080-27d8-11e9-842e-4408d19c1807.png)

OnlyOffice right-click menu is not as useful.
![screenshot from 2019-02-03 17-17-08](https://user-images.githubusercontent.com/22585732/52176410-84721900-27d8-11e9-8be3-5c381fed13c1.png)

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v 5.2.8

**Comment by Rita-Bubnova** [comment]
Hello, @uncertainquark.
Thank you for your enhancement.
I created a new issue 40453 in our private issue tracker.
We will discuss this with our team.

**Comment by uncertainquark** [comment]
Any update on this?

**Comment by Rita-Bubnova** [comment]
@uncertainquark, sorry, no update.

**Comment by trofim24** [comment]
It's added in 7.1 version
