### ISSUE TITLE
Start slideshow tooltip doesn't show keyboard shortcut

### ISSUE THREAD

**Issue by uncertainquark** [ONLYOFFICE/DesktopEditors#178]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Start slideshow tooltip is missing keyboard shortcut indicator

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Hover mouse over the "Start slideshow" button.
![screenshot from 2019-02-03 17-38-42](https://user-images.githubusercontent.com/22585732/52176598-e0d63800-27da-11e9-8754-c3c43593902d.png)

**What is the expected behavior?**
Tooltip should show keyboard shortcut

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v 5.2.8

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
