### ISSUE TITLE
Broken search icon Ubuntu 16.10

### ISSUE THREAD

**Issue by orschiro** [ONLYOFFICE/DesktopEditors#18]
Dear all, 

I wanted to report this.

Affected system:

Ubuntu 16.10
Version 4.2.1-43 

![image](https://cloud.githubusercontent.com/assets/170947/21504869/a9993b1a-cc62-11e6-9dec-09c08e08e9ae.png)

**Comment by maxkadushkin** [comment]
icon got broken after the package had been installed?

**Comment by orschiro** [comment]
Yes, after installation of the onlyoffice deb package.

**Comment by ShockwaveNN** [comment]
I think this issue should be resolved by now. Feel free to comment if not
