### ISSUE TITLE
Styles are not working correctly on RTF files

### ISSUE THREAD

**Issue by Hertony** [ONLYOFFICE/DesktopEditors#186]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Any styled RTF file will show a strange behavior when any style from the style bar is clicked. The selected text will get some properties from the style, but won't change font family or font size unless the style is clicked again. After the second click all styles start to work on that specific paragraph, but other 
 untouched paragraphs exhibit the same bug. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1 - Open any styled RTF, like the attached example: 
[formatting-submissions.zip](https://github.com/ONLYOFFICE/DesktopEditors/files/2857652/formatting-submissions.zip)
2 - Select the first paragraph.
3 - Click on any style that should change font size or family (like _Title_ or _Heading 1_). The style will not be completely applied.
4 - Try to apply the same style again. Now it will work for that paragraph only.

**What is the expected behavior?**
The expected behavior is the same presented when working on a new file. That is, styles are applied fully and correctly with a single click.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.2.83.480 and under. Ubuntu 16.

**Comment by Rita-Bubnova** [comment]
Hello, @Hertony.
This is correct behavior (issue 37155 in private bug tracker). To apply style you should click on style twice. First time will be to apply paragraph settings, second one to clean text run settings.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
