### ISSUE TITLE
Source packages of releases are empty

### ISSUE THREAD

**Issue by Germano0** [ONLYOFFICE/DesktopEditors#188]
In https://github.com/ONLYOFFICE/DesktopEditors/releases every source package (tar.gz or zip) of releases is empty and does not contain any source file, they do contain only the folder tree

**Comment by ShockwaveNN** [comment]
This is github limitation, github auto generated source-packages for projects with submodules are looks like that way

**Comment by Germano0** [comment]
Releasing complete source packages can help Linux distributions package maintainers

**Comment by ShockwaveNN** [comment]
You can perform `git clone`
