### ISSUE TITLE
Acute accent in Greek language broken

### ISSUE THREAD

**Issue by stavpup** [ONLYOFFICE/DesktopEditors#19]
Bug report

It is not possible to add https://en.wikipedia.org/wiki/Acute_accent in Greek language,
e.g. can not write Μόνος, can only write Μονος

Desktop editor, Ubuntu 16.10

**Comment by jsalatas** [comment]
Same here in KDE Neon (ubuntu 16.04 based).

**Comment by NunonuN** [comment]
Cannot write any accents in Portuguese words. Ubuntu 16.04 MATE.

**Comment by ChrisP4** [comment]
I'm having the same problem. Is this going to be fixed?

**Comment by agolybev** [comment]
Hi @ChrisP4, we are working on the problem now.

**Comment by K0R0L** [comment]
Fixed in 4.8.
