### ISSUE TITLE
./DesktopEditors  DesktopEditors: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.

### ISSUE THREAD

**Issue by noraj** [ONLYOFFICE/DesktopEditors#190]
**What is the current behavior?**

The tar.gz build crashed on Manjaro/ArchLinux.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```
./DesktopEditors 
DesktopEditors: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
[1]    29028 abort (core dumped)  ./DesktopEditors
```

**What is the expected behavior?**

Working instead of crashing I guess.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

I downloaded the 5.2.8 version here https://www.onlyoffice.com/download-desktop.aspx

OS : Manjaro Linux (very similar to Arch Linux on ArchLinux).

**Comment by tulasinandan** [comment]
Confirm the same behavior on Manjaro linux.

**Comment by kmrgo** [comment]
Same behavior on Debian Buster, with 5.2.8 OnlyOffice.

`./DesktopEditors or ./onlyoffice-desktopeditors.sh`

> DesktopEditors: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.

**Comment by joybhallaa** [comment]
Has anyone got a solution for this?

**Comment by ShockwaveNN** [comment]
@joybhallaa Hi, version of 5.2.8 is pretty old, and currently we are not working on support of `.tar.gz` version of DocumentEditors (and solution of this issue)
We advice you to move to AppImage, snap or flapak version of DocumentEditors

**Comment by XDmitryK** [comment]
@joybhallaa @noraj @ameisehaufen @tulasinandan 
Unfortunately we had to give up support for tar.gz but you can install  appimage or flatpak

**Comment by joybhallaa** [comment]
@XDmitryK thanks, will try flatpak!

**Comment by ShockwaveNN** [comment]
Closing this issue since we deprecated tar.gz archive and replaced it with snap, flatpak and AppImage installation method
