### ISSUE TITLE
Lacks basic image editing features like crop and rotate

### ISSUE THREAD

**Issue by uncertainquark** [ONLYOFFICE/DesktopEditors#193]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
No basic image editing options like crop and rotate!

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Insert and image and try to edit it. You will see no options to even crop or rotate. I know there is a photo editor plugin but that requires one to be online and it isn't an intuitive way to access the feature either.

**What is the expected behavior?**
Image cropping, rotating and other basic functions should be built in. 

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v5.2.8

**Comment by Rita-Bubnova** [comment]
Hello, @uncertainquark.

Thank you for your enhancement.
This is a known issue 36855 in our internal issue tracker. We are planning to implement some of this features on 5.3.

**Comment by uncertainquark** [comment]
Good to hear! When is 5.3 coming?

**Comment by Rita-Bubnova** [comment]
Currently we have no ETA.
