### ISSUE TITLE
Missing plugin button

### ISSUE THREAD

**Issue by 2ear** [ONLYOFFICE/DesktopEditors#196]
Do you want to request a *feature* or report a *bug*?
Bug

I like the older ui and i downloaded older from https://github.com/ONLYOFFICE/DesktopEditors/releases and https://sourceforge.net/projects/teamlab/files/ONLYOFFICE_DesktopEditors/ but after installation I can't found the plugin button at the side panel.

![Example](https://user-images.githubusercontent.com/48398683/54080383-d69ae280-4320-11e9-95e9-811d4cd6879e.jpg)

What wrong'? Its just bug or my insaller broken'? I use that on windows 7.

**Comment by ShockwaveNN** [comment]
@2ear could you sepcify which version you downloaded? But in general we do not support older versions of our product

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
