### ISSUE TITLE
Support "CTRL+DELETE" to delete whole word

### ISSUE THREAD

**Issue by EminYagmahan** [ONLYOFFICE/DesktopEditors#198]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The key combination only deletes one character. The behavior is identical to that of a single delete press.

**What is the expected behavior?**
Deleting the complete word

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
V. 5.2.83.480
Manjaro Linux 18.12
Didn't work on previous versions

**Comment by ShockwaveNN** [comment]
Related to https://github.com/ONLYOFFICE/DocumentServer/issues/436
