### ISSUE TITLE
open  document in own window

### ISSUE THREAD

**Issue by lhpitn** [ONLYOFFICE/DesktopEditors#199]
**Do you want to request a *feature* or report a *bug*?**
i guess its a feature but i consider it as a bug.
**What is the current behavior?**
i am unable to open two text documents side by side withing onlyoffice desctop on win 10
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
open one document, open another document, try to move one tab out to a new window by dragging and dropping or right clicking 
**What is the expected behavior?**
when moving the tab out of the window that it is dropped into an new one, when rightklicking a tab i would expect some context menu (both comparable to firefox or other browsers supporting tabbed browsing)
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Edition Version 5.2.83.480
(please make this copiable)
on windows 10 64bit (of cause with 64bit version of ONLYOFFICE)

in general its a good idea to invent tabbed document editing, makes my usual msofice/libreoffice workflow much more convenient, strg+tab and strg+w also work as expected, but to force users to work within a single window is not a good idea...

thanks in advance and keep up the good work

**Comment by Rita-Bubnova** [comment]
Duplicate #108

**Comment by lhpitn** [comment]
@Rita-Bubnova thanks for your quick reply, but not exactly what i meant, i dont want to run several independent applications on the same time (makes no sense for me because therefor i have a switch user feature (only maybe makes sense for developers) but i want to request the future to support multiple windows (and tab management between them) run within a single instance of the application. (less memory consumption, i dont want to save and load a document to open it into another window. Also i like the still perfectly working feature that when i open the onlyoffice desktop app again to show me hey, there i am still open...

**Comment by Rita-Bubnova** [comment]
This is the same task.
