### ISSUE TITLE
Can't run on arch linux with last updates

### ISSUE THREAD

**Issue by iddqdidkfa** [ONLYOFFICE/DesktopEditors#2]
Linux 4.7.6-1-ARCH 1 SMP PREEMPT Fri Sep 30 19:28:42 CEST 2016 x86_64 GNU/Linux

There was problems with installation and after start it can not open or create documents.

```
onlyoffice

/onlyoffice/DesktopEditors: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

sudo pacman -S libcurl-gnutls

onlyoffice

/onlyoffice/DesktopEditors: error while loading shared libraries: libgtkglext-x11-1.0.so.0: cannot open shared object file: No such file or directory

sudo pacman -S gtkglext

onlyoffice

/onlyoffice/DesktopEditors: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /onlyoffice/libascdocumentscore.so)
[1013/171147:ERROR:browser_main_loop.cc(219)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
/onlyoffice/DesktopEditors: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /onlyoffice/libascdocumentscore.so)
/onlyoffice/converter/x2t: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /onlyoffice/converter/x2t)
[1013/171159:ERROR:PlatformKeyboardEvent.cpp(117)] Not implemented reached in static PlatformEvent::Modifiers blink::PlatformKeyboardEvent::getCurrentModifierState()

```

![onlyoffice](https://cloud.githubusercontent.com/assets/1819727/19353540/5e43bef0-916c-11e6-8206-9b0f2747b62a.png)

**Comment by maxkadushkin** [comment]
could you try portal version? [link](http://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors-4.1.2-33-x64.tar.gz)

**Comment by iddqdidkfa** [comment]
```
./DesktopEditors 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
```

**Comment by iddqdidkfa** [comment]
@maxkadushkin this version works

**Comment by iddqdidkfa** [comment]
but it's not registered in system. I cant use it as default application to open documents and n oapplication icon in dock

**Comment by maxkadushkin** [comment]
yes, there are some disadvantages for portable version. unfortunately we have no another workaround for your distrib yet.

**Comment by iddqdidkfa** [comment]
@maxkadushkin Thanks. It would be awesome if someone from stuff can create [AUR](aur.archlinux.org) package. I'm sure community will create it soon anyway.

**Comment by samuelramox** [comment]
I had the same problem, but today it worked. (y)

**Comment by dbuch** [comment]
@samuelramox are you saying the non-portable now worked for you?

**Comment by samuelramox** [comment]
@dbuch exactly. And I did not install any additional packages.

**Comment by iddqdidkfa** [comment]
@samuelramox what is your Linux distributive?

**Comment by samuelramox** [comment]
@iddqdidkfa Arch Linux 64 bits with KDE Plasma 5.8.3, kernel 4.8.7.1.

**Comment by iddqdidkfa** [comment]
I confirm, new installer works with Arch Linux 64 bits with GNOME Shell 3.22.2, kernel 4.8.7-1

**Comment by dbuch** [comment]
@samuelramox is it the gui installer or? Care to provide a link?. Thanks - i'm trying to make a PKGBUILD and eventually put it in AUR

**Comment by iddqdidkfa** [comment]
@dbuch https://www.onlyoffice.com/download-desktop.aspx
I have used GUI-PACKAGE from "Linux" section

**Comment by dbuch** [comment]
@iddqdidkfa thanks :+1: I doubt i can make a pkgbuild from that.. guess we have to wait for build instructions to be publiched

**Comment by iddqdidkfa** [comment]
@dbuch you can make pkgbuild with portable version mentioned above if you know how to register desktopeditors in system applications

**Comment by mmetak** [comment]
@dbuch & @iddqdidkfa 
Yesterday I made a quick pkgbuild file for portable edition and if you, @dbuch, want you can improve it and maintain it in AUR?

**Comment by samuelramox** [comment]
I also used the gui-package. The AUR will be great!
