### ISSUE TITLE
MailMerge  missing

### ISSUE THREAD

**Issue by vinogradovnet** [ONLYOFFICE/DesktopEditors#20]
No MailMerge in Destop Editors 4.2.3.290

**Comment by maxkadushkin** [comment]
it doesn't tested for desktop version yet

**Comment by maxkadushkin** [comment]
added. for cloud documents

**Comment by nicolaslebrun** [comment]
Hi,

In our high schools we're trying to convert to onlyoffice and nextcloud, it is really necessary to have MailMerge in Desktop version.

Comment certainly useless on a closed issue ;-)
Regards,
