### ISSUE TITLE
write Durchsuchen instead of Browsen in german translation (button in open local files)

### ISSUE THREAD

**Issue by lhpitn** [ONLYOFFICE/DesktopEditors#202]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
to open files i can browse for them using the system file open Dialog behind this button, but in german its called Durchsuchen (or durchsuchen) and not Browsen... Compare with msoffice
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Edition Version 5.2.83.480
(please make this copiable)
on windows 10 64bit (of cause with 64bit version of ONLYOFFICE)

**Comment by alexandervnuchkov** [comment]
https://github.com/ONLYOFFICE/desktop-apps/commit/9870ee68da82b43e646bef69eca7a24765a11682

**Comment by ShockwaveNN** [comment]
DesktopEditors 5.3.3 was released. Issue should be fixed
