### ISSUE TITLE
feature request: remove connect to cloud button/screen

### ISSUE THREAD

**Issue by lhpitn** [ONLYOFFICE/DesktopEditors#203]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
there is no way to remove this connect to cloud screen, but it is not very beautifully to have that option there always if you dont want your users to use the cloud or if you want to use your cloud without the integration of onlyoffice (like dropbox/nexctcloud fiel syncing deamon that works by syncing local directories more efficiently (by only syncing changes) then alsways accessing webdav on load and save even if the file is already locally available) Maybe you could add some config file entry that i can add to its installation folder (or /etc/... under linux ) which disables this screen completely.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Edition Version 5.2.83.480
(please make this copiable)
on windows 10 64bit (of cause with 64bit version of ONLYOFFICE)

**Comment by maxkadushkin** [comment]
it's no so clear about "your users". do you mean users in some local network? do you need some admin's option to configure the app?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
