### ISSUE TITLE
dont use spellcheck dictonary only based on keyboard layout

### ISSUE THREAD

**Issue by lhpitn** [ONLYOFFICE/DesktopEditors#204]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
i like to use us international keyboard language to write in local language (german) by using alt gr for äöü. But onlyoffice detect it as english which forces me to switch to german on any new field. There is no way to set a language per whole ducument or a default language. Please add such a setting like in libreoffice:
![grafik](https://user-images.githubusercontent.com/45788285/55004798-26450380-4fdb-11e9-8ede-15305d6651ce.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
switch to us international and try to write some text in onlyoffice that is not english.
**What is the expected behavior?**
to let me set the language myself on a more global scale than per textfield/selection, additional a feature like in msoffice that detects the language itself after some words are typed (using statistics and search trough all dictionarys (but add a switch off feature, sometimes such things are annoying). 
Also something i miss much in other apps to is a way to select more than one active dictionary (like accept english and german words as correct spelled at the same time) 
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Edition Version 5.2.83.480
(please make this copiable)
on windows 10 64bit (of cause with 64bit version of ONLYOFFICE)

**Comment by Rita-Bubnova** [comment]
Hello, @lhpitn.

Firstly, the spell checker language really matches the keyboard layout language. This is the correct behavior (MS Office also behaves).

As for the second question - about the simultaneous use of several dictionaries for verification. Unfortunately, there is no possibility to implement this, since this feature is not provided by the ooxml format.
