### ISSUE TITLE
allow quick switching in and out plugin view withing the left hand panal

### ISSUE THREAD

**Issue by lhpitn** [ONLYOFFICE/DesktopEditors#205]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behaviour?**
if you are creating a presentation, and want to add some cliparts, everything is fine, but what if you want to add some new slide, afterwards and then add some more cliparts. quite a hazzle, so also you have to disable cliparts plugin view manually even if its got disabled by switching back to slide view. The plugin is unable to detect that its view has been closed by its own (which is not a convenient user interface as the state of it is not up to date...)
i would like that recent plugins are within that horizontal toolbar in the left hand side like in tabed browsing (with little x'es for all not plugin related icons)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
create a new presentation
go to plugins and cliparts type in some text, drag and drop some cliparts to the current slide
go to slide list to switch to another/add a new slide
try to go back to cliparts
**What is the expected behavior?**
wired back and forwarth clicking in enabling and disabling the clip arts view
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Edition Version 5.2.83.480
(please make this copiable)
on windows 10 64bit (of cause with 64bit version of ONLYOFFICE)

**Comment by Rita-Bubnova** [comment]
Hello, @lhpitn.
Thank you. I can confirm - this is a bug, issue 35682 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
This problem is fixed in documentserver (ONLYOFFICE/web-apps-pro@56967e2) and will be released as 5.3.0. And if everything goes well - will be included in next major release of DesktopEditors.

**Comment by ShockwaveNN** [comment]
DesktopEditors 5.3.3 was released. Issue should be fixed
