### ISSUE TITLE
feature request: speed up save and load

### ISSUE THREAD

**Issue by lhpitn** [ONLYOFFICE/DesktopEditors#207]
**Do you want to request a *feature* or report a *bug*?**
its quite slow to wait for save and loading (or even creating a new) document with this black half transparent loading screen (:)
![grafik](https://user-images.githubusercontent.com/45788285/55007033-044d8000-4fdf-11e9-841f-b58ccc25f345.png)
(screenshot of just creating a new document)
i know you are using javascript and not c/c++ like libreoffice/msoffice but maybe there is still a way to speed up things a little bit (for the beginning just for creating a new document maybe by preloading the template...)

thanks in advance and keep up teh good work!

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Edition Version 5.2.83.480
(please make this copiable)
on windows 10 64bit (of cause with 64bit version of ONLYOFFICE)

**Comment by ShockwaveNN** [comment]
Hi, thanks for our attention for our product. We constantly working on speeding up our application.
But since this issue is pretty general, without any exact problem - I think I'll close this issue
