### ISSUE TITLE
translate hinting der schriftarten correcly

### ISSUE THREAD

**Issue by lhpitn** [ONLYOFFICE/DesktopEditors#208]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
see :
![grafik](https://user-images.githubusercontent.com/45788285/55007293-74f49c80-4fdf-11e9-9d4c-6677a04f6793.png)

i guess what you mean is called "Schriftglättung" in german
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Edition Version 5.2.83.480
(please make this copiable)
on windows 10 64bit (of cause with 64bit version of ONLYOFFICE)

**Comment by alexandervnuchkov** [comment]
https://github.com/ONLYOFFICE/desktop-apps/commit/9870ee68da82b43e646bef69eca7a24765a11682

**Comment by ShockwaveNN** [comment]
DesktopEditors 5.3.3 was released. Issue should be fixed
