### ISSUE TITLE
In Debian/Ubuntu no option for change language

### ISSUE THREAD

**Issue by bigbruno** [ONLYOFFICE/DesktopEditors#21]
Using .deb instalation i'm not found how change interface for use Brazilian Portuguese language.

Version 4.2.3.290

**Comment by maxkadushkin** [comment]
unfortunately, we have no complete translation for Brazilian Portuguese language for app interface yet. app uses default language for local files. for files from a portal it depends on portal lang settings. app supports Brazilian Portuguese language for such files in particular editors

**Comment by bigbruno** [comment]
You have one address for send translantion contribution? My team help translation in open source programs.

**Comment by trofim24** [comment]
It would be great!
You can do pull request with changes files. Please name files br.json

https://github.com/ONLYOFFICE/web-apps/blob/master/apps/documenteditor/main/locale/en.json
https://github.com/ONLYOFFICE/web-apps/blob/master/apps/presentationeditor/main/locale/en.json
https://github.com/ONLYOFFICE/web-apps/blob/master/apps/spreadsheeteditor/main/locale/en.json

**Comment by bigbruno** [comment]
Localizations of this repositories using pt.json is Brazilian Portuguese, and not Portugal Portuguese.

But for test this i use this commands:

LANG=pt desktopeditors
LANGUAGE=pt desktopeditors

But not work, don't have any parameter for change language, like almost Linux applications?

**Comment by maxkadushkin** [comment]
there is some keys to launch the app
--lang:lang - apply the language for the current session
--keeplang:lang - keep the language
with that params certain editors will be translated, but not the whole app interface

**Comment by maxkadushkin** [comment]
you can use theese keys to launch the app
--lang:pt - apply language for current session
--keeplang:pt - keep language for next use
in this case, particular editors will be translated for local files, but not the whole app

**Comment by maxkadushkin** [comment]
we've prepared resources for translations for your team
in repo [desktop-apps](https://github.com/ONLYOFFICE/desktop-apps), branch develop:
[win-linux/langs/pt_BR.ts](https://github.com/ONLYOFFICE/desktop-apps/win-linux/langs/pt_BR.ts) - file consists translations for Qt's part of app
it's convenient to use [Qt Linguist](http://doc.qt.io/qt-5/linguist-translators.html)
second part - translation for 'start page'. pt_BR area in file
[common/loginpage/src/locale.js](https://github.com/ONLYOFFICE/desktop-apps/common/loginpage/src/locale.js)
thanks in advance

**Comment by bigbruno** [comment]
Thank you, we will start translation, but i'm suggest to OnlyOffice use one translation system like: https://www.transifex.com

This make very more simple maintain translations.

**Comment by Guilherme-Halal** [comment]
Hello there. I'm interested in helping on translation process. 
I just don't have any experience... How can I start?

**Comment by maxkadushkin** [comment]
Hello! thanks, we appreciate helping in app's internationalization. unfortunately, now the process a bit awkward, but we discuss how to make it easier. what language can you help with?

**Comment by ShockwaveNN** [comment]
Closing this issue, it's more a question than an issue. Feel free to comment through
