### ISSUE TITLE
add offline mode/state which operations/addons use online service under which law clearly

### ISSUE THREAD

**Issue by lhpitn** [ONLYOFFICE/DesktopEditors#210]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
i am not sure if all operations are done locally, which is sometimes important if you for example editing medical data of patients or are in the European union and dont have a aggrement from your clients to give the data out of your posession to some servers...

For example te ocr feature works quite nice, but i believe that it is using some online service to do its work... So if that is so, please add at least a hint (or even a warning when using from the EU) about the lokation where the data are processed and how long they are saved (i would guess that the service keeps all input for a certain time to improve its detection algorithm...)

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Edition Version 5.2.83.480
(please make this copiable)
on windows 10 64bit (of cause with 64bit version of ONLYOFFICE)

**Comment by lhpitn** [comment]
please add following text to that dialog:

![grafik](https://user-images.githubusercontent.com/45788285/55013845-403a1280-4fea-11e9-8611-e865b5a06674.png)
by uploading the image to a remote server located in ... under following privacy terms (link)

and here: (tested with windows firewall:)

![grafik](https://user-images.githubusercontent.com/45788285/55013953-69f33980-4fea-11e9-924e-2906259d4a27.png)

nothing happens, no error message or anything, if i block network access to the app.

please add some timeout or whatever way to generate an error message and write in that dialog also a privacy hint...

**Comment by Rita-Bubnova** [comment]
Hello, @lhpitn.
The OCR plugin works on client side only and all scripts are included in our Desktop Editors. 
Disabling internet connection help insure that.
