### ISSUE TITLE
OnlyOffice freezes when using certain fonts

### ISSUE THREAD

**Issue by prudentcircle** [ONLYOFFICE/DesktopEditors#219]
**Do you want to request a *feature* or report a *bug*?**
Reporting a bug

**What is the current behavior?**
OnlyOffice stutters if not freezes entirely when typing Korean characters using certain fonts. ( Noto Sans KR for my case)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Launch the program, Select the font "Noto Sans CJK KR", and start typing random Korean characters.

**What is the expected behavior?**
The characters won't input correctly, the program starts to stutter, or sometimes it just freezes entirely on me. 

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

I tested this on Ubuntu 19.04, directly installed with deb package. 
(Since your snap package does not work well with ibus-korean, I cannot enter Korean at all when using snap packages.  This is an issue entirely on its own. I may file it on GitHub at some later point :) )

The same behavior can be reproduced on CentOS 7.6, RHEL 7.6, and Fedora 29.

**Comment by Rita-Bubnova** [comment]
Hello, @prudentcircle.
Thank you. I can confirm - this is a bug, issue 41436 in our internal issue tracker.

**Comment by ShockwaveNN** [comment]
This issue is fixed for quite a long time, closing it
