### ISSUE TITLE
Chinese displays with error

### ISSUE THREAD

**Issue by Lazyjason** [ONLYOFFICE/DesktopEditors#22]
Chinese words in the editor display with error like this when `font` is selected with `arial`:
![image](https://cloud.githubusercontent.com/assets/7929582/22179617/f428a838-e093-11e6-98b9-929782cbd6cd.png)

Otherwise, when `font` is selected with `Heiti SC`, They are shown correctly like this:
![image](https://cloud.githubusercontent.com/assets/7929582/22179624/56fc244e-e094-11e6-8fa5-34046eeb477b.png)

I've tried most of fonts in my laptop and found that only in a few of fonts, Chinese can be shown correctly. When I change the font, they show with meaningless codes.

**Comment by maxkadushkin** [comment]
is it in opened document? or you have some experiments with fonts?
'arial' doesn't contain Chinese characters. see the [desription](https://www.microsoft.com/typography/fonts/font.aspx?FMID=1705)
lots of fonts have no Chinese characters, keep it in mind when typing a document

**Comment by Lazyjason** [comment]
sorry for my late reply😂
opened or new document meets the same problem.
I've tried some fonts, 'heiti sc' seems good, however most other chinese fonts don't work. about 2 or 3 of all my fonts display correctly.

**Comment by zaaack** [comment]
Hit this problem too, hope OnlyOffice could auto choose suitable font when user typing Non-English characters, like most office software, and add some default font options.

**Comment by JohnPerkin** [comment]
Hello!
Unfortunately we could not suggest a solution today but we are working on the issue. As soon as we solve it we will report on the solution.
Thank you for the interest in ONLYOFFICE.

**Comment by JohnPerkin** [comment]
Dear ONLYOFFICE users!
We are working hard on implementation of asian **fonts** in Document Server. So we need both standard and non-standard fonts to analyze their behaviour in our product. Please send us fonts via support@onlyoffice.com or attach them to your messages. We will appreciate your assistance.
Best regards
John
ONLYOFFICE support team

**Comment by KrasnayaPloshchad** [comment]
@Lazyjason @maxkadushkin I think this is due to bad font fallback mechanism.

**Comment by HighIO** [comment]
@JohnPerkin  
Here are MS-Fonts names you may ask, but no independent links available for download.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttf-ms-win10

Noto Fonts CJK or Adobe Source Han Pan family is a more appropriate choice for linux.
https://wiki.archlinux.org/index.php/Fonts#Chinese.2C_Japanese.2C_Korean.2C_Vietnamese

**Comment by ShockwaveNN** [comment]
Closing this issue. This issue should be resolved by now. If not feel free to comment
