### ISSUE TITLE
Pictures from clipboard get pasted in a square format

### ISSUE THREAD

**Issue by kojid0** [ONLYOFFICE/DesktopEditors#221]
**Do you want to request a feature or report a bug?**
I want to report a bug.

**What is the current behavior?**
When I insert a picture from clipboard via ctrl-v, the picture gets pasted in a square format (see attachment). After inserting it a second time it looks normal.

**What is the expected behavior?**
The format of the image should be kept.
As a workaround, I can paste it (oddly formatted), go back one step using ctrl-z and paste it again.

**Which versions of DesktopEditors, and which OS are affected by this issue?**
Using onlyoffice 5.2.83480 on zorinOS (Ubuntu 18.04.2).

![onlyoffice](https://user-images.githubusercontent.com/24477557/57040259-216d1280-6c5f-11e9-978c-c7622beb4354.jpg)

**Comment by Rita-Bubnova** [comment]
Hello, @jwsp1.
Thank you. I can confirm - this is a known error, problem 31484 in our internal tracker.

**Comment by Xyz00777** [comment]
bug still working, In presentation too

ONLYOFFICE Desktop Editors version 5.4.2.30 (windows 10 Pro 1909)

**Comment by asbl** [comment]
Is there progress here? I think this bug is pretty basic and could keep newcomers away from Onlyoffice.

**Comment by Rita-Bubnova** [comment]
> Is there progress here? I think this bug is pretty basic and could keep newcomers away from Onlyoffice.

Sorry, no news.

**Comment by lixaotec** [comment]
workaround works, although is anoying
