### ISSUE TITLE
Best spell check improvement suggestion is always the last one

### ISSUE THREAD

**Issue by jwsp1** [ONLYOFFICE/DesktopEditors#224]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug.

**What is the current behavior?**
The best spell check improvement option is always displayed as the last.
1) "absrakten" (actually "abstrakten") gives me options: "absteckten", "Abstraktoren", "abstrakten".
2) "individuelen" (actually "individuellen") gives me options: "Individuellzahlen", "individuell", "individuellen".

**What is the expected behavior?**
The suggestions order should be switched - from best to worst improvement suggestion.

**Which versions of DesktopEditors, and which OS are affected by this issue?**
Using onlyoffice 5.2.83480 on zorinOS (Ubuntu 18.04.2).

**Comment by ShockwaveNN** [comment]
DesktopEditors 5.3.3 was released. Issue should be fixed
