### ISSUE TITLE
Incorrect window size on 3200x1800 13.3 inch display

### ISSUE THREAD

**Issue by robjhyndman** [ONLYOFFICE/DesktopEditors#225]
The window sizing is incorrect using Ubuntu 18.04, KDE running plasma. Onlyoffice Desktop Editors version 5.2.83.480. See following screen image.

https://drive.google.com/file/d/15k1Ynfa_AcAfVQn-TrOCJLpAcCpXUg7m/view?usp=drivesdk
![image](https://user-images.githubusercontent.com/668524/57215404-727d5d80-6ff5-11e9-8084-e3953b2ebbe7.png)

My display settings have scaling set to 1.3.

**Comment by ShockwaveNN** [comment]
@robjhyndman Hi, could you specify your desktop resolution and display size.
But I think it's a known issue, we got troubles with display scale between 1 and 2

**Comment by robjhyndman** [comment]
Display resolution is 3200x1800. Screen scaling set to 1.3. Not sure what you mean by display size.

**Comment by ShockwaveNN** [comment]
@robjhyndman Actual display size of your notebook-monitor. We use this value to detect scaling factor and this may cause trouble

**Comment by robjhyndman** [comment]
It's a Dell XPS13 -- 13.3inch.

**Comment by ShockwaveNN** [comment]
@robjhyndman Thanks, we are  known about this problem and working on resolving this problem and hope in will be fixed in DesktopEditors 5.3, but currently have no exact date of release

**Comment by ddshore** [comment]
Hi, 

Just want to confirm this bug.  
- KDE running plasma. 
- resolution is 3200x1800.
- Running on Arch Linux
- Dell Inspiron 5530 / 15" laptop

I understand you're working on this, but meanwhile is there a workaround?  Even if I scale it to 2.2 by running  onlyoffice-desktopeditors --force-scale=2.2, the problem persists.  And if I try resizing my window, the Desktopeditor will shrink proportionally and will keep the huge grey area.

**Comment by ddshore** [comment]
Forgot to paste the images.  
![Screenshot_20190531_103243](https://user-images.githubusercontent.com/171169/58723914-dd297b00-83a0-11e9-82f8-0ab50a061b8a.png)
![Screenshot_20190531_102753](https://user-images.githubusercontent.com/171169/58723915-ddc21180-83a0-11e9-97d9-88d31b6deede.png)

**Comment by ShockwaveNN** [comment]
I think it's same issue as https://github.com/ONLYOFFICE/DesktopEditors/issues/136
so I'll close this
