### ISSUE TITLE
 Spreadsheets formulas i18n translation

### ISSUE THREAD

**Issue by q4a** [ONLYOFFICE/DesktopEditors#23]
**Do you want to request a *feature* or report a *bug*?**
It's translation feature.

**What is the current behavior?**
Formulas available without translation (only english).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
**What is the expected behavior?**
Example:
A1=1
A2=3
B1=SUM(A:A)= 4 - ok
But with russian translation should be another option with same funcrion (like in Excel):
B1=СУММ(A:A)= 4

I.e. "СУММ" is translation of "SUM" in russian.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I just installed DesktopEditors on Ubuntu 16.04.1 LTS x64 using this guide: 
http://helpcenter.onlyoffice.com/desktop/documents/linux/installation-ubuntu.aspx

**Comment by q4a** [comment]
Sorry, looks like default Formula Language was English (while all applications was Russian). After changing settings all works so good)

**Comment by trofim24** [comment]
Thanks for the bug.
We have fixed problem open file with Russian formula language by default.

This fix will in version 4.3

**Comment by q4a** [comment]
Bug was fixed more than 1,5 month ago. Is there development/daily build of DesktopEditors for Ubnutu and/or Windows?

**Comment by trofim24** [comment]
Yes, we have daily build of DesktopEditors, but it closed.
We'll figure out how to make it publicly available.
Thanks.
