### ISSUE TITLE
hyperlinks are not clickable in saved pdf files

### ISSUE THREAD

**Issue by deathtrip** [ONLYOFFICE/DesktopEditors#231]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Hyperlinks in exported pdf files are not clickable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a text document or a spreadsheet and save it as pdf.

**What is the expected behavior?**
Hyperlinks in exported pdf files should be clickable.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I use version 5.2.83.480 on Arch Linux. Haven't tried older versions.
This problem was also mentioned in a comment in #43, with an example pdf file.

**Comment by Rita-Bubnova** [comment]
Hello, @deathtrip.
Thank you. It is know issue 23458 in our private tracker.

**Comment by jxmallett** [comment]
Has any progress been made on this?

**Comment by Rita-Bubnova** [comment]
@jxmallett, unfortunately, the problem hasn't  fixed.

**Comment by Feuerhamster** [comment]
Same problem here. Any progress?

**Comment by Rita-Bubnova** [comment]
@Feuerhamster, sorry, the problem still not fixed.

**Comment by Amar-Gill** [comment]
I have a similar issue. When I save my .docx file as a PDF => the hyperlinks which are an actual URL in the document text work - but not the hyperlinks which are attached to arbitrary words e.g. "View Site" or "Source"

**Comment by ShockwaveNN** [comment]
This is same issue as 
https://github.com/ONLYOFFICE/DocumentServer/issues/189
Since DocumentServer is our base product I think we close this as duplicated
