### ISSUE TITLE
Surface Go interface scaling

### ISSUE THREAD

**Issue by u-alexey** [ONLYOFFICE/DesktopEditors#234]
Hi. I'm not sure is this a *feature* or a *bug*
Surface Go 10" screen. Windows 10 64. App version 5.2.83.480
Header of app too massive but tool panel too teeny compared of header. 
![onlyoffice](https://user-images.githubusercontent.com/50143425/60440810-47427380-9c1e-11e9-8c42-cc2b8a981cf9.jpg)

Need some scale function for small screen; tablet mode; or something similar.

**Comment by ShockwaveNN** [comment]
@u-alexey Hi, what is the resolution of your display?
It may be duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/217

**Comment by u-alexey** [comment]
Screen resolution is 1800 x 1200

**Comment by ShockwaveNN** [comment]
If so - it's duplicate of #217
