### ISSUE TITLE
[Feature request] temp folder/files 

### ISSUE THREAD

**Issue by udlch** [ONLYOFFICE/DesktopEditors#235]
Hi, Onlyoffice!  After saving documents at win10 onlyoffice creating temp folder for a second at the same directory. Seafile client try to sync this temp folder but cannot because it does not exist anymore. 

<img width="900" alt="onlyoffice" src="https://user-images.githubusercontent.com/50143425/60955289-37571d80-a309-11e9-806f-06ffec70b59b.png">

I can not find any settings about temp folders/files. Can client make hidden temp  folder or use custom directory for all temp files/folders?

**Comment by Rita-Bubnova** [comment]
Hello, @u-alexey.
Thank you. It is know issue 39663 in our private tracker.

**Comment by TatianaKirillova** [comment]
@udlch I'm happy to report that the issue has been fixed and is now included in version 8.1.1. Have a good day!

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
