### ISSUE TITLE
Change Linux Default Font

### ISSUE THREAD

**Issue by hypnomaki** [ONLYOFFICE/DesktopEditors#239]
When I freshly install the application, I would expect a font available on my system. Unfortunately, Calibri is selected as default Font even tough its not installed on any Linux Distro I know and also If I`m not totally wrong there is also no way to install it anyway.

Please set a default font (for Linux packages) which is available on most Linux Distros.

I use version 5.3.95.43 on Ubuntu 19.04

**Comment by ShockwaveNN** [comment]
@hypnomaki Hi, we got some process to use similar fonts if some default font are not installed on your system. So if Empty xlsx show `Calibri` in font picker - it use Carlito font, if you system has no Calibri installed. 
We did this system to support one solution on any platform and we thinks it's works pretty well

**Comment by hypnomaki** [comment]
Seems to work - thx for the info!

![image](https://user-images.githubusercontent.com/5446005/63588316-7afaa380-c5a6-11e9-98b0-b72d02ae72d6.png)

**Comment by ShockwaveNN** [comment]
@hypnomaki Good to hear, sorry for late responce
