### ISSUE TITLE
Can't open password-protected xlsx

### ISSUE THREAD

**Issue by q4a** [ONLYOFFICE/DesktopEditors#24]
**Do you want to request a *feature* or report a *bug*?**
It's very important feature.

**What is the current behavior?**
File don't open. Error like "Format does not support" (in Russian).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Ask password and open document, if password is correct.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I just installed DesktopEditors on Ubuntu 16.04.1 LTS x64 using this guide:
http://helpcenter.onlyoffice.com/desktop/documents/linux/installation-ubuntu.aspx

Example of password-protected xlsx. Password for file: 123
[pass123.zip](https://github.com/ONLYOFFICE/DesktopEditors/files/721702/pass123.zip)

**Comment by trofim24** [comment]
Thanks for the bug and file.
We have fixed this problem.

This fix will in version 4.3

**Comment by q4a** [comment]
Thx. I'll test new release.

**Comment by trofim24** [comment]
fix
https://github.com/ONLYOFFICE/DesktopEditors/releases/tag/ONLYOFFICE-DesktopEditors-4.3.2
