### ISSUE TITLE
Feature Request: Could you add a checksum for the release file?

### ISSUE THREAD

**Issue by linsui** [ONLYOFFICE/DesktopEditors#245]
**Do you want to request a *feature* or report a *bug*?**
Feature Request: Could you add a checksum for the release file or I can find it somewhere?

**Comment by LuckySpecialist** [comment]
Hi @linsui!
Do you mean the checksums for the various Desktop Editors installation packages?
Is this still relevant to you?

**Comment by linsui** [comment]
Not relavent to myself anymore but maybe useful to scoop.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
