### ISSUE TITLE
Can't drag and drop columns in Spreadsheets

### ISSUE THREAD

**Issue by moonmehta** [ONLYOFFICE/DesktopEditors#249]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
Can't drag and drop columns in Spreadsheets

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Make two columns. Try to interchange their positions using drag and drop. 

**What is the expected behavior?**
Should be able to drag and drop columns and change their orders like a breeze.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v5.3.3

**Comment by Rita-Bubnova** [comment]
Hello, @uncertainquark.
I'm not sure that I correctly understand the phrase "Should be able to drag and drop columns and change their orders like a breeze".
You can explain more?

I am attach a video with a demonstration of drag'n'drop columns into ONLYOFFICE Desktop Editors version 5.3.

![video](https://user-images.githubusercontent.com/25282241/62936913-abd31f80-bdd3-11e9-8e1f-58e08677f123.gif)

**Comment by uncertainquark** [comment]
Ah! It wasn't obvious to me because it turns out one needs to select the column, then mouse over the border for a while and then drag and drop. I think Google Docs has it far more intuitively. You can simply drag and drop from the column header itself! It is both easy to target with a mouse/touchpad and intuitive. Can you consider something like this?

**Comment by Rita-Bubnova** [comment]
@uncertainquark, in Google Sheets, dragging and dropping columns using a header is different from moving columns without grabbing the header.

I created a new issue 42406 in our private issue tracker.
We will discuss this with our team.

**Comment by VladimirProkofiev52** [comment]
Hello!
 @moonmehta, @Ampa 
 In the new version (7.5.1.23) of our editor, you can move columns using Drag-and-drop.

Just click on the column header, after which the cursor will turn into a hand icon and you will be able to move the columns using Drag-and-drop. 

The request is implemented, the behavior of our editor is similar with Google Sheets.

**Comment by Rita-Bubnova** [comment]
This has been [fixed in version 7.5 ](https://github.com/ONLYOFFICE/DesktopEditors/blob/master/CHANGELOG.md#spreadsheet-editor-1).
I close this issue. Feel free to comment or reopen it if you got further questions.
