### ISSUE TITLE
How to change where "docx_unpacked" is made

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/DesktopEditors#252]
**Do you want to request a *feature* or report a *bug*?**
This is a question

**What is the current behavior?**
A random folder named "docx_unpacked is made in the same folder as the .docx file.
I have an application installed that connects to my google drive cloud. Whenever i try to save the application creates a folder with a lot of files which all need to be uploaded and in the end removed for one save. 

This cumbersome and takes very long (each save takes over 5 minutes) 

Can i adjust the path where this disassembly happens? 

**What is the expected behavior?*
That the orginal .docx file is only changed once, or at least that i can change the path where this the "docx_unpacked" is made in. 

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Arch Linux, Version 5.3.3.35

**Comment by Rita-Bubnova** [comment]
Hello, @ArsalanAnwari.
Thank you. This issue should be resolved after fixed issue 39663 in our private tracker.

**Comment by TatianaKirillova** [comment]
I'm happy to report that the issue has been fixed and is now included in version 8.1.1. Have a good day!
