### ISSUE TITLE
Invalid rendering in Spreadsheets

### ISSUE THREAD

**Issue by rend3r** [ONLYOFFICE/DesktopEditors#253]
ONLYOFFICE Desktop Editors version 5.3.95.61
Windows 7 x64
[sample.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/3526457/sample.xlsx)
Number sign is occurred with small scales
![sc110](https://user-images.githubusercontent.com/12601181/63453185-bf742b00-c450-11e9-838b-7d10bbc92466.png)
![sc100](https://user-images.githubusercontent.com/12601181/63453186-bf742b00-c450-11e9-8a99-398b4979206f.png)

**Comment by Rita-Bubnova** [comment]
Hello, @rend3r.
Thank you. It is know issue 42134 in our private tracker.

**Comment by Rita-Bubnova** [comment]
Related https://github.com/ONLYOFFICE/DocumentServer/issues/618.

**Comment by rend3r** [comment]
solved to me (Desktop Editors 6.2.0)

**Comment by ShockwaveNN** [comment]
@rend3r Yeah, thanks, once again seems we forgot to close it 
This issue fixed in https://github.com/ONLYOFFICE/sdkjs/commit/ae7d4033bb32a57a0ed8fb66c9731b239c31996
