### ISSUE TITLE
Meaningless error description for opened file

### ISSUE THREAD

**Issue by rend3r** [ONLYOFFICE/DesktopEditors#254]
ONLYOFFICE Desktop Editors version 5.3.95.61
Windows 7 x64
![rw](https://user-images.githubusercontent.com/12601181/63453698-ed0da400-c451-11e9-9467-1a59525f3d4d.png)
Getting the error for file already opened in Excel in my case.

**Comment by Rita-Bubnova** [comment]
Hello, @rend3r.
Thank you. It is know issue 36839 in our private tracker.

**Comment by rend3r** [comment]
![ro](https://user-images.githubusercontent.com/12601181/111863510-19124380-896d-11eb-8169-6a934076fcae.png)

fixed for Desktop Editors 6.2 (translate buttons to russian).

**Comment by ShockwaveNN** [comment]
@rend3r Yeah, sorry seems we fixed this and forgot to notify it in issue
If I'm not mistaken - this fixed in v6.0
