### ISSUE TITLE
Bad font rendering for equations

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/DesktopEditors#256]
Hello,

**Do you want to request a *feature* or report a *bug*?**

I'm not sure if it is a bug or a problem with fonts configuration but I can't find any solution about it.  

**What is the current behavior?**

When typing letters and some others characters  (like greek letters as `\pi` )in equations, they appear as white rectangle.
The default font used by only office is Cambria Math.
The operating system is Debian 10

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Here an example with a simple formula:

On onlyoffice I see this: 

![image](https://user-images.githubusercontent.com/54131080/63754085-8b679280-c8b4-11e9-8e28-2f284f020adf.png)

When exporting as PDF everything is fine:

![image](https://user-images.githubusercontent.com/54131080/63754298-ebf6cf80-c8b4-11e9-96f2-fe0a8b2cd312.png)

**What is the expected behavior?**

See letters when typing equations.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

I'm using debian 10 and ONLYOFFICE Desktop Editors version 5.3.95.49.

I installed onlyoffice with the debian repository:
`deb https://download.onlyoffice.com/repo/debian squeeze main` 

For information, the debian package `ttf-mscorefonts-installer` is installed. 

I don't know if this work in previous versions, I began to use onlyoffice recently. 

The equation editor seem really nice to use, it would be perfect without this problem.
Thanks for your time !

**Comment by Rita-Bubnova** [comment]
Hello, @bergth1.
Can you attach file with problem?

**Comment by bergth1** [comment]
[math_test.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/3545833/math_test.docx)

You can find the file here.

I just see that apparently when you reopen the file after saving, everything is OK. This problem seem to happens only with new unsaved files.

**Comment by Rita-Bubnova** [comment]
While I can not reproduce your problem.
Please, attach a video with its demo.

**Comment by bergth1** [comment]
You can find the video here: https://drive.google.com/file/d/1L74yzhJ8v4dwTs39mEgivdr2bbuo0gRm/view

For information, I also tried on ubuntu 19.04 with onlyoffice installed with snap this time and there is the same problem.

**Comment by Rita-Bubnova** [comment]
Thanks for the attached video.
I can confirm - this is a bug, issue 42645 in our internal issue tracker. 
Problem reproduces in Document Server.

**Comment by sjollois** [comment]
Hello, any news about this bug ?

**Comment by ShockwaveNN** [comment]
@sjollois Sorry, no news and we cannot give estimates of this fix. If you really need it - better to contact sales@onlyoffice.com

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
