### ISSUE TITLE
Weired look (⍰) of non-breaking space

### ISSUE THREAD

**Issue by q4a** [ONLYOFFICE/DesktopEditors#26]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
I can see ⍰ instead of non-breaking space

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Check attached xlsx and png: screens from onlyoffice and excel

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I just installed DesktopEditors on Ubuntu 16.04.1 LTS x64 using this guide:
http://helpcenter.onlyoffice.com/desktop/documents/linux/installation-ubuntu.aspx

[Book1.zip](https://github.com/ONLYOFFICE/DesktopEditors/files/722265/Book1.zip)
![excel](https://cloud.githubusercontent.com/assets/1950719/22185972/d40778a6-e0ff-11e6-9774-75127e6ab562.png)
![onlyoffice](https://cloud.githubusercontent.com/assets/1950719/22185973/d40926ba-e0ff-11e6-995f-01bf80874a15.png)

**Comment by trofim24** [comment]
Thanks for the bug.
We have [fixed](https://github.com/ONLYOFFICE/sdkjs/commit/2f18b15e48fa525cca0721fdc695843f29a08feb) this problem.

This fix will in version 4.3

**Comment by trofim24** [comment]
fix
https://github.com/ONLYOFFICE/DesktopEditors/releases/tag/ONLYOFFICE-DesktopEditors-4.3.2
