### ISSUE TITLE
Problem with monitor high resolutions

### ISSUE THREAD

**Issue by vegansk** [ONLYOFFICE/DesktopEditors#260]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Both desktop editor and web version ignores text scale settings on Windows. Settings:

![image](https://user-images.githubusercontent.com/2908508/65213223-7f47ad00-dacf-11e9-9522-092012b07c84.png)

And see editor controls sizes compared to browser controls:

![image](https://user-images.githubusercontent.com/2908508/65212996-93d77580-dace-11e9-8edf-7829195fd0a1.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Just run it with high resolution monitor.

**What is the expected behavior?**

Scaled interface

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

DesktopEditors 5.3.95.84, Windows 10 Pro Version 10.0.18362 Build 18362

**Comment by ShockwaveNN** [comment]
I think I'll close this issue since we added support of 150% interface scaling a long time ago and this problem should be probably be fixed
