### ISSUE TITLE
Print Preview

### ISSUE THREAD

**Issue by PrzemekSkw** [ONLYOFFICE/DesktopEditors#263]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the expected behavior?**
Show document preview before printing.

Regards,
Przemek

**Comment by Rita-Bubnova** [comment]
Hello, @PrzemekSkw.
Thank you for your enhancement.
This is a known and requested feature - issue 40269 in our internal issue tracker.
But currently we have no ETA.

**Comment by PrzemekSkw** [comment]
@Rita-Bubnova Thanks for fast answer. You make a great job. Thank You.

Regards,
Przemek

**Comment by sinichi19** [comment]
> Hello, @PrzemekSkw.
> Thank you for your enhancement.
> This is a known and requested feature - issue 16000 in our internal issue tracker.
> But currently we have no ETA.

This feature (Print Preview) also we will wait to replace the libreoffice in our workstation and replace to OnlyOffice DesktopEditors,

This feature is important especially using spreedsheet to check the exact format before print the document.

Thank You

**Comment by sinichi19** [comment]
Still Waiting for this...

MOre Power OnlyOffice Nice Work

ThankYou

**Comment by maravento** [comment]
OnlyOffice desktop does not have "print preview dialog" and has serious problems with printing excel documents.

**Comment by lms91** [comment]
Please "Print preview".

**Comment by NoneRain** [comment]
This is a real issue IMO. Imagine printing 50 pages to then see how it went?

**Comment by dariopoz** [comment]
So still waiting for print preview? In my opinion, Onlyoffice is a great piece of software but still lacking very fundamental functionality: print preview! Please, add it!

**Comment by smarquespt** [comment]
@dariopoz I must agree with you. 2 years and still no print preview. At least in https://github.com/ONLYOFFICE/DocumentServer/blob/master/ROADMAP.md the told it will be added to sheets.

**Comment by NoneRain** [comment]
> @dariopoz I must agree with you. 2 years and still no print preview. At least in https://github.com/ONLYOFFICE/DocumentServer/blob/master/ROADMAP.md the told it will be added to sheets.

I just gave up at this point. Being using FreeOffice since.

**Comment by trofim24** [comment]
Fixed in 7.3.0
