### ISSUE TITLE
Allow customisation of charts' X- and Y-axes data ranges.

### ISSUE THREAD

**Issue by CodingEagle02** [ONLYOFFICE/DesktopEditors#265]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
If you create a chart in a document, there is no clear way to select what sets of data ranges should be used for the horizontal and vertical axes.

The only way seems to be to select "Data Range", select all the values, and hope OnlyOffice can discern what should be counted for the axes. 

That presents an issue, for example, when I was dealing with a line graph where the X-axis was composed of numeric values (1996, 1997, 1998, 1999). OnlyOffice refused to understand that the left column was supposed to be the X-axis values, _not_ an unnamed line.

Here is what OnlyOffice [thought I wanted.](https://imgur.com/a/uhsSluE)

**What is the expected behavior?**

[This.](https://imgur.com/a/7Uia35a)

I achieved what I was looking for by adding "Yr" to each year (such that OnlyOffice recognised they could not be another line), reselecting the column, and then removing it. Another way would be to use the [default template](https://imgur.com/a/jcuDDsS) and trying to extend it. However, I should not need to do either of these hacks around the problem.

**Comment by Rita-Bubnova** [comment]
Hello, @CodingEagle02.
Thank you. I can confirm - this is know issue 41769 in our private tracker.

**Comment by mcarpinter** [comment]
Is this problem solved or not yet? I am facing a similar situation, and I would like to know if by updating the onlyoffice it will fix it (I have the server version of it).
If this is not yet solved, I would like to better understand the "hack" used to accomplish what it is expected

**Comment by Rita-Bubnova** [comment]
Hello, @mcarpinter.
Unfortunately, the problem has not yet been fixed.
Currently we got no any ETA of implementing it, but you can always contact sales@onlyoffice.com to make this task more crucial.

**Comment by LucaAlimandi** [comment]
Hi,
I also faced this problem with a lot of datasheets, and I can't manage this by applying the workaround mentioned above.
I think this is a very annoying bug and should be quickly fixed.
Thank you very much.

Luca

**Comment by Rita-Bubnova** [comment]
This bug fixed (https://github.com/ONLYOFFICE/sdkjs/commit/20c98c50bedf0bf25941879b9a5d2c3c0011999b) and will be released in future major release.

**Comment by christian-nils** [comment]
Hi! Is this bug fixed in 5.6.0? I have 5.6.0 and still I cannot create a x-axis with numerical input. Thanks

**Comment by Rita-Bubnova** [comment]
Dates are taken into account when creating a diagram in ONLYOFFICE Desktop Editors version 5.6.0.21.

@christian-nils, сould you write more about your problem or attach a file in a new issue?

**Comment by christian-nils** [comment]
You are right sorry. I was not really interested in Dates per se, but a numerical list for the X-axis (and it does not work if the column that contains this numerical list has a header). I will open a new issue.

**Comment by ShockwaveNN** [comment]
So if original issue resolved and update is released - I think I'll close this issue.
Please feel free to comment if have any further questions
