### ISSUE TITLE
Feature request: ability to insert hyperlink to numbered item

### ISSUE THREAD

**Issue by rafjaf** [ONLYOFFICE/DesktopEditors#267]
Hello,

In OnlyOffice latest release, it is possible to insert a hyperlink to a heading, which is very useful.

However, it would be even better if it were possible to insert a hyperlink to any (automatically) numbered item in the document, not just to headings. This feature exists in Microsoft Word, see https://support.office.com/en-us/article/create-a-cross-reference-300b208c-e45a-487a-880b-a02767d9774b, and is necessary if you want to be able to edit complex documents in OnlyOffice.

Thank you for your help
Rafaël

**Comment by Rita-Bubnova** [comment]
Hello, @rafjaf.
Thank you for your enhancement.
I created a new issue 43057 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
"Create a cross-reference" feature added in Desktop Editors version 6.1.

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors v6.1 are released
I'm closing this issue
