### ISSUE TITLE
Text cursor will go to the beginning of the equation on multiple occasions

### ISSUE THREAD

**Issue by CodingEagle02** [ONLYOFFICE/DesktopEditors#269]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

While editing equations, on multiple occasions the text cursor will jump to the beginning of the equation - or at least move to locations that aren't where it's supposed to be, making equation-editing tiresome and frustrating.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I notice the issue easily by just making equations, but the easier way to reproduce it is as such:

1. Create an equation - I usually use the shortcut `alt` + `=`, but clicking on the button in the "insert" header.
2. Input seemingly any two characters. But, for a tried and tested example, input `=` and `4`.
3. You'll notice that the text cursors jumps to the beginning of the equation. If you continue typing, it'll now appear before `=4`.

**What is the expected behavior?**

The text cursor should behave in predictable, controllable ways.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

I'm using OnlyOffice 5.4.1.33. I do not know whether previous versions were affected.

**Comment by Rita-Bubnova** [comment]
Hello, @CodingEagle02.
Thank you. I can confirm - this is a bug, issue 43268 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/1ef3ac9ba38f706b3b7b94518ae36f8731d73ccc) in ONLYOFFICE Desktop Editors version 5.6.0.21.
