### ISSUE TITLE
Native window title bar flag (system-title-bar) no longer works

### ISSUE THREAD

**Issue by PJSingh5000** [ONLYOFFICE/DesktopEditors#271]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I launch ONLYOFFICE using `onlyoffice-desktopeditors --system-title-bar`.
I expect the application to use the native window title bars, but it doesn't.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Launch ONLYOFFICE from the terminal using

```
onlyoffice-desktopeditors --system-title-bar
```

**What is the expected behavior?**

I expect the application to use the native window title bars, but it doesn't.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Ubuntu 19.10 x64
Using Adwaita theme
Gtk version 3.24.12-1ubuntu1
Qt version 5.12.4+dfsg-4ubuntu1
GNOME Shell version 3.34.1

**Comment by Rita-Bubnova** [comment]
Hello, @PJSingh5000.
Thank you. I can confirm - this is known issue 43189 in our private tracker.

**Comment by sindex** [comment]
@Rita-Bubnova Any updates?

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/desktop-apps/commit/c80dc433a617d11eee768b51e4a5c89beae85656, https://github.com/ONLYOFFICE/desktop-apps/commit/8059906669cda97440841bbd307274d1b9c88725) and will be release in next major release.

**Comment by PJSingh5000** [comment]
Thanks! Looking forward to testing it!

**Comment by Rita-Bubnova** [comment]
This issue fixed and released in ONLYOFFICE Desktop Editors version 5.6.0.21.

**Comment by PJSingh5000** [comment]
I just tested this.
Thank yo
It looks great, with one small quirk: the 1st tab is truncated when system title bars are turned on. (See https://github.com/ONLYOFFICE/DesktopEditors/issues/438)
