### ISSUE TITLE
Feature request: Dark theme

### ISSUE THREAD

**Issue by Yorper** [ONLYOFFICE/DesktopEditors#272]
Just a simple request to have a toggle between either the current light theme and a new dark theme.

It would help some people with eye strain.

Thanks.

**Comment by Rita-Bubnova** [comment]
Hello, @Yorper.
Duplicate #215.

**Comment by Yorper** [comment]
Didnt realise, sorry. Closing.

**Comment by Rita-Bubnova** [comment]
All good, thanks for your request. Considering adding this.
