### ISSUE TITLE
Presentation: Selecting, Moving, Cropping has issues

### ISSUE THREAD

**Issue by baermathias** [ONLYOFFICE/DesktopEditors#274]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When clicking on an object (textbox, image, etc.) somtimes the mouse has to be next to the object to select it. Here is an example screenshot. On the left side is an image and on the right side is my mouse (changed its cursor to move/select). The cursor wouldn't change if it was exactly on the image.
![Screenshot from 2019-11-06 12-18-27](https://user-images.githubusercontent.com/45003352/68294580-d1995900-0090-11ea-941e-6cd908940b28.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Most of the time this behavior appears after working a few minutes with OnlyOffice

**What is the expected behavior?**
Select the object by clicking inside the object and not next to it

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v5.4.1.33

**Comment by Rita-Bubnova** [comment]
Hello, @baermathias.
Could you attach file with problem and and what OS do you use?

**Comment by baermathias** [comment]
I tried to create an example, it doesn't have exactly the same issue I have described here but the selection is also off the element. If I click on the elements left side I can't select it, I have to move the mouse far to the right side of the element:

[example.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/3819353/example.pptx)

**Comment by Rita-Bubnova** [comment]
In attached presentation there is placeholder with text 
"xxxxxxxxxx
xxxxxxxxx" 
and 4 empty paragraph. Placeholder placed is in front of image and cover big part of image. So to select image you should click on right part of image.
This is correct behavior.

To fix this situation - remove empty lines in placeholder with 
"xxxxxxxxxx
xxxxxxxxx"
or bring image to foreground.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
