### ISSUE TITLE
Export a Chart as a Picture

### ISSUE THREAD

**Issue by meckoboy** [ONLYOFFICE/DesktopEditors#276]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I can't download a Chart from Onlyoffice spreadsheet. Other office software such as WPS, LO & FO allow it to be done with just one click. I think it would be a good idea to integrate this feature.

**What is the expected behavior?**
Integrate this functionality into the image editor.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Onlyoffice 5.4.1
OSX Mojave

**Comment by Rita-Bubnova** [comment]
Hello, @meckoboy.
Thank you for your enhancement.
I created an issue 43611 to discuss it with our team.

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed (v7.5).
I close this issue. Feel free to comment or reopen it if you got further questions.
