### ISSUE TITLE
Khmer font and keyboard problem.

### ISSUE THREAD

**Issue by cambodiacoder** [ONLYOFFICE/DesktopEditors#279]
currently, I have a problem with the Khmer font and keyboard layout . Can you please add this feature which makes this software become the most used office in the world. I will encourage everyone in my country to try to use.

**Comment by Rita-Bubnova** [comment]
Hello, @cambodiacoder.
I installed the Khmer keyboard layout and I installed the Khmer Pailin font in the same place.
And it seems with no problems in ONLYOFFICE DesktopEditors.

Please fill in the template correctly and specify os and product versions so that I can understand your problem.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
