### ISSUE TITLE
Clicking on Save crashes the application on CENTOS 7

### ISSUE THREAD

**Issue by atishgoswami** [ONLYOFFICE/DesktopEditors#28]
I have install the desktopeditors application on my CENTOS 7 desktop using the instruction mentioned [here](http://helpcenter.onlyoffice.com/desktop/documents/linux/installation-rhel.aspx). When I try so save the a document the application crashes and closes off. This happening for all 3 excel, document and presentation. Also happens when I try to open a local file

# Preconditions
**Desktop Environment** 

OS: CentOS Linux 7
GNOME: Version 3.14.2
OS Type: 64-bit
Memory: 8 GB
Processor: Intel® Core™ i7-2600K CPU @ 3.40GHz × 8 

# Steps to reproduce

1. Get a Centos 7 desktop
2. Install DesktopEditors using the instruction mentioned [here](http://helpcenter.onlyoffice.com/desktop/documents/linux/installation-rhel.aspx)
3. After installing completes, launch DesktopEditors.
4. Click on "Create new" -> "Document"
5. Try saving the document
6. Click on "Open local file"

# Expected Result

Should prompt location path to save the document

# Actual Result
Application closes

Has anyone encountered such kind of issue ? Any way how I might be able to debug this issue ?

**Comment by ShockwaveNN** [comment]
I think issue should be resolved by now, if not - please create a new issue

**Comment by lalomouta** [comment]
I am facing same issue.

version: ONLYOFFICE Desktop Editors version 6.3.1.56
OS: Ubuntu 18.04 LTS

After working in a document, when I am going to save it to my local filesystem, after preshing "File > Save as", the application suddenly close the window, and the document couldn't be saved.

Before this week, I could working and saving documents without issues.

Log /var/log/onlyoffice/documentserver/docservice$ vi out.log-20210824

[2021-08-23T07:42:24.359] [WARN] nodeJS - Express server starting...
  1 [2021-08-23T07:42:24.361] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changin    g the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_av    ailability
  2 [2021-08-23T07:42:24.372] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
  3     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  4 [2021-08-23T07:42:25.389] [WARN] nodeJS - Express server listening on port 8000 in production-linux     mode. Version: 6.3.2. Build: 2
  5 [2021-08-23T13:42:19.882] [WARN] nodeJS - Express server starting...
  6 [2021-08-23T13:42:19.884] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changin    g the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_av    ailability
  7 [2021-08-23T13:42:19.891] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
  8     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  9 [2021-08-23T13:42:20.908] [WARN] nodeJS - Express server listening on port 8000 in production-linux     mode. Version: 6.3.2. Build: 2


/var/log/onlyoffice/documentserver/converter$ vi out.log-20210824

[2021-08-23T07:42:23.758] [WARN] nodeJS - update cluster with 1 workers
  1 [2021-08-23T07:42:23.764] [WARN] nodeJS - worker 2395 started.
  2 [2021-08-23T07:42:23.767] [WARN] nodeJS - update cluster with 1 workers
  3 [2021-08-23T07:42:24.361] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
  4     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  5 [2021-08-23T13:42:19.301] [WARN] nodeJS - update cluster with 1 workers
  6 [2021-08-23T13:42:19.314] [WARN] nodeJS - worker 2229 started.
  7 [2021-08-23T13:42:19.317] [WARN] nodeJS - update cluster with 1 workers
  8 [2021-08-23T13:42:19.839] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
  9     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

**Comment by ShockwaveNN** [comment]
I don't think this is same issue from 2017

Please create a new one, and describe in more details - you said that you using DesktopEditors version: ONLYOFFICE Desktop Editors version 6.3.1.56
But you got logs from DocumentServer? Are you opening document connected to some kind DMS?

**Comment by funnycubeguy** [comment]
> I am facing same issue.
> 
> version: ONLYOFFICE Desktop Editors version 6.3.1.56
> OS: Ubuntu 18.04 LTS
> 
> After working in a document, when I am going to save it to my local filesystem, after preshing "File > Save as", the application suddenly close the window, and the document couldn't be saved.
> 
> Before this week, I could working and saving documents without issues.
> 
> Log /var/log/onlyoffice/documentserver/docservice$ vi out.log-20210824
> 
> [2021-08-23T07:42:24.359] [WARN] nodeJS - Express server starting...
> 1 [2021-08-23T07:42:24.361] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changin g the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_av ailability
> 2 [2021-08-23T07:42:24.372] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
> 3 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
> 4 [2021-08-23T07:42:25.389] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 6.3.2. Build: 2
> 5 [2021-08-23T13:42:19.882] [WARN] nodeJS - Express server starting...
> 6 [2021-08-23T13:42:19.884] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changin g the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_av ailability
> 7 [2021-08-23T13:42:19.891] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
> 8 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
> 9 [2021-08-23T13:42:20.908] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 6.3.2. Build: 2
> 
> /var/log/onlyoffice/documentserver/converter$ vi out.log-20210824
> 
> [2021-08-23T07:42:23.758] [WARN] nodeJS - update cluster with 1 workers
> 1 [2021-08-23T07:42:23.764] [WARN] nodeJS - worker 2395 started.
> 2 [2021-08-23T07:42:23.767] [WARN] nodeJS - update cluster with 1 workers
> 3 [2021-08-23T07:42:24.361] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
> 4 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
> 5 [2021-08-23T13:42:19.301] [WARN] nodeJS - update cluster with 1 workers
> 6 [2021-08-23T13:42:19.314] [WARN] nodeJS - worker 2229 started.
> 7 [2021-08-23T13:42:19.317] [WARN] nodeJS - update cluster with 1 workers
> 8 [2021-08-23T13:42:19.839] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
> 9 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

I have the same version with the same issue Ubuntu 20.04

**Comment by ShockwaveNN** [comment]
> I have the same version with the same issue Ubuntu 20.04

Please create a new issue, do not hijack 5-year-old closed issue
