### ISSUE TITLE
Task bar doesn't shows

### ISSUE THREAD

**Issue by light-and-ray** [ONLYOFFICE/DesktopEditors#280]
Task bar doesn't shows, when I hover on the down of screen, in maximized window. It annoying me. Video: [https://youtu.be/RENtdvWXHzk](https://youtu.be/RENtdvWXHzk)

**Comment by Rita-Bubnova** [comment]
Hello, @light-and-ray.
This is  duplicate https://github.com/ONLYOFFICE/DesktopEditors/issues/129.
