### ISSUE TITLE
DesktopEditors fails to start the second run

### ISSUE THREAD

**Issue by VersuchUndIrrtum** [ONLYOFFICE/DesktopEditors#286]
[bug]

After closing OnlyOffice it fails to start the second time on a multi-user system. No error is reported but a process blogs deleting /AppData/Local/ONLYOFFICE. Even after logging out and logging in again.  

After deleting /AppData/Local/ONLYOFFICE it start again for exactly one time.

(This bug does not appear with the admin account with which it was installed!)

Tested with:
Windows 10 Education 64bit  1809,1909 
Desktopeditors   64bit  5.4.2.30

**Comment by Rita-Bubnova** [comment]
Hello, @VersuchUndIrrtum.
Sorry, I cannot reproduce your problem.
Could you describe the steps for playback in more detail?

**Comment by VersuchUndIrrtum** [comment]
Hello,
I cannot reproduce at either but at school it happens every time. (Machines are domain members. Documents-folder is a network drive.) 

I could break it down to the file  l\AppData\Local\ONLYOFFICE\DesktopEditors\data\cookie\user.data. [user.data.txt](https://github.com/ONLYOFFICE/DesktopEditors/files/3917819/user.data.txt) [.txt is added for upload only}

If  I delete it ONLYOFFICE starts immediately otherwise it fails to start. Today I needed to kill the DesktopEditor-task only the first time. After the second start it regulary dissappeared from the task manager after a moment and I could delete user.data.

By the way ONLYOFFICE needs long time to close and there are no other files in the cookie-folder (on my private machine there are two more.)

**Comment by Rita-Bubnova** [comment]
@VersuchUndIrrtum DesktopEditors v8.1is released. Please state is this problem still actual for you?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
