### ISSUE TITLE
Support Drop Down lists

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#287]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
OnlyOffice does not support Drop Down Lists in Spreadsheet
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v 5.4, Linux, but probably all versions are affected.
I attach a sample xlsx file.

[teste-menu.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/3908076/teste-menu.xlsx)

**Comment by Rita-Bubnova** [comment]
Hello, @parrenin.
Relate to https://github.com/ONLYOFFICE/DocumentServer/issues/252.

**Comment by Taste-IT** [comment]
Request from 20.March 2018 until now 06.02.2020 and the Feature is not implemented. I like OO, but there are elementary functions, which let me not recommend OO in any case, if i whould asked.

**Comment by trofim24** [comment]
We released Data Validation in [version 6.2.0](https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#620)
