### ISSUE TITLE
Accents and charset settings

### ISSUE THREAD

**Issue by ivannieto** [ONLYOFFICE/DesktopEditors#29]
**Do you want to request a *feature* or report a *bug*?**

Can't see nothing related in issues opened or closed. Also, I can't find options to manage this behaviour, so I guess it's a bug. If it's not, please, let me know how to manage this.

**What is the current behavior?**

Accents are not added by default when typed.

![bugonlyo](https://cloud.githubusercontent.com/assets/15637745/22784638/2b35d350-eed1-11e6-99b5-6fd060b46941.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See attached image.

It happens even when doc language is correct. Can't find more options to manage charsets or typing input in settings.

**What is the expected behavior?**

See attached image.

It's expected accents to be added when typed.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Ubuntu Desktop 16.10.

Not tested in previous versions.

**Comment by danielgomon** [comment]
I'm using Ubuntu 14.04 and I have the same problem. I think this is the same issue as this: https://github.com/ONLYOFFICE/DesktopEditors/issues/19

**Comment by Walker555** [comment]
Linux Mint 18.1 KDE, slovak keyboard, same issue.

**Comment by fabriciojardim** [comment]
Linux Mint 18, pt-br (brazilian portuguese) keyboard, same issue.

**Comment by selfus** [comment]
Kubuntu 16.04 LTS same issue, Portuguese (Portugal)

**Comment by leandropaz** [comment]
Ubuntu 17.04, pt-BR (brazilian portuguese), same issue.

**Comment by NunonuN** [comment]
Ubuntu 16.04 MATE, Portuguese-Portugal, ONLYOFFICE Desktop Editors version 4.2.5.312, same issue.

**Comment by carlosdededison** [comment]
ArchLinux, Portuguese-Brazil, ONLYOFFICE Desktop version 4.2.5.312 (from AUR), same issue.

**Comment by trinhno** [comment]
Does not work on my Ubuntu GNOME either (latest version). Doesn't take Vietnamese or Japanese input even after enabling hieroglyphs.
Works perfectly on Windows 10 though.

**Comment by edgardiniz** [comment]
Doesn't work on my Void Linux MATE, ONLYOFFICE 4.4.1.338 - Portuguese (Brazil). Works as expected on Windows 7.

**Comment by Floresigor1** [comment]
Same issue, Portuguese-Brazil (Pt-BR) Kubuntu (Ubuntu 17.04) + KDE Plasma.

**Comment by NathanMaia** [comment]
Same issue, Portuguese-Brazil (Pt-br), Kubuntu (Ubuntu 17.04) + KDE Plasma. OnlyOffice Latest Version (August 23, 2017).

**Comment by pciavald** [comment]
up to date Manjaro KDE, french keyboard

**Comment by lmagdiel** [comment]
Same Issue, pt-BR, Deepin 15.4.1, OnlyOffice 4.4.1.338

**Comment by K0R0L** [comment]
Fixed in 4.8
