### ISSUE TITLE
Update notification

### ISSUE THREAD

**Issue by sinichi19** [ONLYOFFICE/DesktopEditors#291]
Good Day,

To All,

nice work for Onlyoffice desktop editors thank you and more power.
Only for clarification if there a way to disable the update notification if there is new release version or fixed bugs.

We want is to manual update only and not prompt to every users that they need to update.

Thank you

**Comment by Rita-Bubnova** [comment]
Hello, @sinichi19.
At the moment, you can disable automatic update notifications only by changing the settings in the registry:
1. Go to the folder 
HKEY_CURRENT_USER\Software\ONLYOFFICE\DesktopEditors\CheckForUpdates
2. Set the CheckForUpdates parameter to 0.

I created a new issue 43736 in our private issue tracker.
We will discuss this with our team adding to the interface a parameter  to disable automatic notification updates.
Thank you for your enhancement.

**Comment by sinichi19** [comment]
Thank you for workaround and looking forward to disable auto update notification via GUI (DesktopEditor)

But overall nice work for the OnlyOffice 

More Power and God Bless

**Comment by Rita-Bubnova** [comment]
We added option "Check for updates automatically" in the "Settings" section. It will be released in future major release ONLYOFFICE Desktop Editors.

**Comment by trofim24** [comment]
Fixed
