### ISSUE TITLE
[Desktop Editors 5.4.2.30] Ctrl+Shift+V not working

### ISSUE THREAD

**Issue by TheFuzzStone** [ONLYOFFICE/DesktopEditors#292]
Hello.
I saw [this tweet](https://twitter.com/only_office/status/1200379031251816449) yesterday. I thought to myself, "Hooray!" and I updated my Desktop Editors. The first thing I did was to check if Ctrl + Shift + V was working, and I was surprised to see that it wasn't.

The official Twitter of Only Office [said](https://twitter.com/only_office/status/1201766247333011456) that it should be working (except for spreadsheets) and asked me to create an issue on Github. Here I'm.

* Desktop Editors 5.4.2.30
* Operating System: KDE neon 5.17
* KDE Plasma Version: 5.17.3
* KDE Frameworks Version: 5.64.0
* Qt Version: 5.13.2
* Kernel Version: 5.0.0-37-generic

**EDIT**.
In my case Ctrl + Shift + V does not work in the document editor.

**Comment by Rita-Bubnova** [comment]
Hello, @TheFuzzStone.
The keyboard shortcut Ctrl + Shift + C and Ctrl + Shift + V does not work in the spreadsheet editor (known issue 40907 in our private tracker).
In document and presentation editors, style copying (Ctrl + Shift + C / Ctrl + Shift + V) should work. If this is not your case, please describe the steps to reproduce the problem in more detail.

**Comment by TheFuzzStone** [comment]
@Rita-Bubnova, edited the issue.

In my case Ctrl + Shift + V does not work in the document editor.

> please describe the steps to reproduce the problem in more detail.

After I have copied the formatted text, I open the Document Desktop Editor, press Ctrl + Shift + V and nothing happens at all.

**Comment by Rita-Bubnova** [comment]
Sorry, I cannot reproduce your problem (Desktop Editors 5.4.2.30, Operating System: Kubuntu 18.04).
Could you attach a video demonstrating your problem?

**Comment by TheFuzzStone** [comment]
> Could you attach a video demonstrating your problem?

https://youtu.be/7fKi_aURikQ

---

I'll also leave a screenshot of my version of Only Office:

![](http://i.imgur.com/ZYjIpGk.png)

**Comment by KirillovIlya** [comment]
First of all you need to use Ctrl+Shift+C, but not just Ctrl+C or the Copy function, if you want to copy format of the text.
Also there is no reason to use Ctrl+Shift+C for the line of text in your viedo, because it has different text format for diffrerent parts of the text, as a result, the editor will not be able to understand what specific text format is required and nothing will happen on the Ctrl+Shift+V.

How this should work
1. Add text two lined of the text: 
 "Hello all"
 "Hello World"
2. Select the word "all". 
3. Make it bold.
4. Press Ctrl+Shift+C
5, Select the word "World"
6. Press Ctrl+Shift+V
7. Now the word "World" must be bold

**Comment by TheFuzzStone** [comment]
@KirillovIlya, that functionality that you described I don't need at all.
Either we don't understand each other, or this functionality is not yet available in the Only Office Document.

My question is: does Only Office Document contain such a simple function as "**paste as unformatted text**"?

**Comment by KirillovIlya** [comment]
> My question is: does Only Office Document contain such a simple function as "**paste as unformatted text**"?



1 Use the regular paste function (Ctrl+C)
2 You will see a special paste button
3 Choose the "Keep text only" flag

![ejtTCO 1](https://user-images.githubusercontent.com/17902914/70127905-ffbc8980-168c-11ea-8671-6f3b724add19.jpg)

**Comment by TheFuzzStone** [comment]
@KirillovIlya, Okay, great! I see we're starting to understand each other. 

And now the main thing is, is it possible to directly paste unformatted text?

**Comment by Rita-Bubnova** [comment]
Duplicate https://github.com/ONLYOFFICE/DesktopEditors/issues/248.

**Comment by TheFuzzStone** [comment]
> Duplicate #248.

Got ya.

It's a bit strange that this function isn't available...
