### ISSUE TITLE
How to set the default font the editor loads on startup from Arial to other (Desktop Editors)

### ISSUE THREAD

**Issue by itsjustarumour** [ONLYOFFICE/DesktopEditors#295]
Do you want to request a feature or report a bug?
Feature
What is the current behavior?
Creating new Document.  Sets Arial as default
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
Not a bug.

What is the expected behavior?
Config file or Api option to specify default font.

Did this work in previous versions of DocumentServer?
Not sure

DocumentServer version:
Not server version.
ONLYOFFICE Desktop Editors version 5.4.2.30

Operating System:
KDE Neon 18.04

Browser version:
70.0.1 (64-bit)

**Comment by ShockwaveNN** [comment]
You can replace files in `/opt/onlyoffice/desktopeditors/converter/empty` - those are new empty documents

**Comment by ds2atc** [comment]
Hello ShockwaveNN,
I have tried it, and it loads the file I saved as default. However, with spreadsheets, when I create a new sheet, it sets back to Calibri again.

**Comment by ShockwaveNN** [comment]
@ds2atc Could you attach file with which you replaced original empty document

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
