### ISSUE TITLE
Oversized Interface after Update

### ISSUE THREAD

**Issue by nickian** [ONLYOFFICE/DesktopEditors#296]
I just updated my Desktop Editor to version 5.4.2.30 on Windows and for some reason the interface is way oversized. Look at the comparison next to a word document. What is going on here? Why does everything have to be so huge?

I'm on a 3840x2160 monitor.  Changing the scaling percentage in display settings makes no difference.

![345345345](https://user-images.githubusercontent.com/590678/70399726-cdd85980-19e3-11ea-956a-e62256b94db3.jpg)

**Comment by Rita-Bubnova** [comment]
Hello, @nickian.
Could you report the version ONLYOFFICE Desktop Editor that was before update to  5.4.2.30?

**Comment by nickian** [comment]
I think it was 5.4.1

**Comment by Rita-Bubnova** [comment]
Was there a problem in version 5.4.1?
Please check is it scaling if the flag `--force-scale = 2`?

**Comment by nickian** [comment]
No, there was no problem. How do I run it with the flag on Windows? I know that works on the Linux command line, but how do I do this on Windows?

**Comment by LuckySpecialist** [comment]
@nickian 
1. Create new shortcut for launch ONLYOFFICE Editors
2. Right click on shortcut choose Properties
3. Put mouse cursor to the Target field
4. Go to the end of quotes (just hit the End key on keyboard)
5. Add Space and type/paste text "--force-scale=2" (w/o quotes)
You need to get a line like this:
"C:\Program Files\ONLYOFFICE\DesktopEditors\DesktopEditors.exe" --force-scale=2
6. Hit OK button on shurtcut properties window

Just launch ONLYOFFICE Editors with new shortcut.

**Comment by nickian** [comment]
Ok, thanks. Setting it to `--force-scale=1` worked for me.

**Comment by ShockwaveNN** [comment]
I will close this issue. Since auto-scaling interface on HiDPI display is our feature. If user prefer see small buttons on big display - it can be solved via command line flag
