### ISSUE TITLE
Pasting highlighted text fails.

### ISSUE THREAD

**Issue by yoasty** [ONLYOFFICE/DesktopEditors#297]
I report a *bug*?**

**What is the current behavior?**
I can paste highlighted text in the current document, if I copied from that document. But in a new or other document it pastes without the highlights.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Start only office and wps or libreoffice.
2. Go to onlyoffice and start a new document. Copy / paste in some text (I used ipsum lorem).
3. select a block of text and highlight it  (I tried yellow and green).,
4. select the block of text again and copy it.
5. start a second document in onlyoffice
6. paste the block. 
7. it pastes as black and white.
8. go to the other editor
9. paste, it pastes as highlighted.
10. go to onlyoffice's original document. 
11. Paste. It pastes as highlighted.
12. go to the second document in onlyoffice.
13. Paste, it pastes as black and white.

**What is the expected behavior?**
since the copied block has highlighted text in it, it should paste as highlighted in desktopeditors, but sometimes it doesn't
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
 I tried in the most recent appimage version 5..4.1 as well as in the most recent deb versions 5.4.2
As far as I know the issue has been around for months at least. But I use crostini linux on a chromebook and that had a known bug with rich text copy/pasting that was only recently solved. So I did not try it a lot. I had temporarily switched to WPS for a while and hope to get back to using desktopeditors.

**Comment by Rita-Bubnova** [comment]
Hello, @yoasty.
Sorry, I cannot reproduce your problem.
Could you attach video of this problem?

**Comment by yoasty** [comment]
Hi Rita, I started Manjaro Linux in Virtualbox and that works well. So it may be crostini linux that is causing the probllem. I did try again in Crostini and the behaviour is the same there. https://www.youtube.com/watch?v=_UAvZyGnPxo    with the comments. Not a very good video, sorry.

**Comment by XDmitryK** [comment]
Sorry but we don't have actual version for Crostini
We cheсked your case in other Linux OS and cannot reproduce.
I think what bug in Chrome OS

**Comment by yoasty** [comment]
Host: penguin Kernel: 4.19.69-06666-g6c4f8cbba24e x86_64 (64 bit) Desktop: N/A Distro: Debian GNU/Linux 9 (stretch)

It is not impossible there is still a bug in Crostini because rich text paste was not possible until recently. Having said that, how come WPS office and libreoffice paste the block with highlights and onlyoffice pastes with highlights as well, but only in the source document.  If I open a new document in onlyoffice it does not paste too that new document with highlights?

**Comment by XDmitryK** [comment]
Unfortunately but I can’t check your problem because I don’t have devices with Chrome OS
We will check this problem when we have the actual Chromebook at our disposal.

**Comment by yoasty** [comment]
I have struggled with this error. Other applications that use the clipboard like Libreoffice, wps-office, freeoffice all struggled with consistent and correct results and I tried looking at the x and wayland clipboards and various tools to manipulate and check them. 
Then I came across the sommelier command option --no-clipboard-manager in Crostini. 
That seems to solve the problem in Cloudready/ChromeOS V80.3.17 and probably before and after. 
For example: 
sommelier --no-clipboard-manager ~/appimages/LibreOffice-still.full-x86_64.AppImage
sommelier -X --no-clipboard-manager /usr/bin/desktopeditors
work and let the applications copy and paste correctly.
You can also simply edit the exec part of ".desktop" files so you do not always have to adjust the commandline.

**Comment by Rita-Bubnova** [comment]
@yoasty, DesktopEditors v8.1 is released. Please state is this problem still actual for you?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
