### ISSUE TITLE
ONLYOFFICE Scrolling Issue and Highlighting Problem

### ISSUE THREAD

**Issue by histoyrking** [ONLYOFFICE/DesktopEditors#298]
I have 2 bugs (all be it minor annoyances) that I would like fixed in the next update

1) When I click on the page up/down buttons, there is at times where it will act like it's scrolling up or down and go past multiple paragraphs.

2) When I try and highlight a word, sentence, or paragraph, it will have a tendency to somehow highlight something totally different and then at times try and "find" that whole word or paragraph

If you can resolve this in the next update that would be great.

**Comment by Rita-Bubnova** [comment]
Hello, @histoyrking.
Please fill in the template correctly (your OS, version  of DesktopEditors).
Could you attach video of this problem?

**Comment by histoyrking** [comment]
OS Name: Microsoft Windows 10 Home Version 10.0.18362 Build 18362
OPENOFFICE Version: ONLYOFFICE Desktop Editors version 5.4.2.30

And as far as recording it, that is kind of hard to to as it's one of those once in a thousand clicks if you will. So it's one of those occurrences where it happens enough to be annoying but not enough to fully say that it's there.

**Comment by Rita-Bubnova** [comment]
Sorry, I won’t be able to help you if you don't provide steps for reproduce or a video with a problem.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
