### ISSUE TITLE
Spreadsheet function CELL  CONTENTS no longer works.

### ISSUE THREAD

**Issue by yoasty** [ONLYOFFICE/DesktopEditors#299]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
The current behaviour is to just present the default "#NAME???" string. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
The bug was reported by a user in the online forum. https://cloud.onlyoffice.org/viewtopic.php?f=31&t=15771&sid=8e0ffab00b1c0d97e593c9ff1f7d97fc#p24758  but apparently not resolved.
The user left a link to an onlline sheet that is still available. https://personal.onlyoffice.com/products/files/doceditor.aspx?fileid=2814663&doc=ZkN1OUdNcTlxZWtUY21UWFI2djdqZW1wZlhkRElXQ3ZlOGt6dFFKREE3Zz0_IjI4MTQ2NjMi0
I can download the xslx and open it in libreoffice, wps office, gsuite and online ms office and it will work fine, but when opened in onlyoffice it does not work correctly. 

**What is the expected behavior?**
See in the other packages. It is supposedly meant to present a list of the numbers in the table at the top. 
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I have not opened the sheet in years so I do not know when it stopped working, but I am convinced I have used my sheet in onlyoffice.  My sheet contains financials, I'd rather not share and just use the other one available.

**Comment by Rita-Bubnova** [comment]
Hello, @yoasty.
Thank you. I can confirm - this is a bug, issue 43901 in our internal issue tracker.

**Comment by yoasty** [comment]
Thanks for confirming. Is there any idea about a timeframe of it getting picked up?

**Comment by Rita-Bubnova** [comment]
Sorry, currently we have no ETA.

**Comment by yoasty** [comment]
Resolved in the 5.5 version recently released. Thanks. Hopefully it will propagate to the desktop-editors soon.

**Comment by ShockwaveNN** [comment]
@yoasty I levae this issue opene util we release DesktopEditors, but yeah, we really hope to release them soon, but currently have no exact date

Also for infomration - this issue is fixed in 
https://github.com/ONLYOFFICE/sdkjs/commit/3af3a26169dcb0462669b23b395dfad66883143d
https://github.com/ONLYOFFICE/sdkjs/commit/e3c079eeddbf514fa7ff42f31d48b90b5369e3e6

**Comment by ShockwaveNN** [comment]
Oh, sorry, seems that this issue is not fixed in all cases.

@Rita-Bubnova please take a look and figure out is this issue really fixed?

**Comment by Rita-Bubnova** [comment]
@yoasty, I can confirm - this issue fixed and released as 5.5 DocumentServer.

**Comment by ShockwaveNN** [comment]
DesktopEditors 5.5.1 released. This issue should be fixed.
