### ISSUE TITLE
Garbage print output for dot matrix printer

### ISSUE THREAD

**Issue by sinichi19** [ONLYOFFICE/DesktopEditors#300]
**want to report a bug**

**What is the current behavior?**
Garbage print output for dot matirx printer
"With lines" blank letters

**What is the expected behavior?**
Good or readable print output for dot matrix printers

**Comment by Rita-Bubnova** [comment]
Hello, @sinichi19.
Please, fill out the form template ( version of Desktop Editors, and OS).
Could you attach file with problem and screenshot of printed sheet?
Is there a problem with printing through another printer?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
