### ISSUE TITLE
Does not open the taskbar in an unfolded window 

### ISSUE THREAD

**Issue by drkrol** [ONLYOFFICE/DesktopEditors#302]
Hello. I found a bug at Onlyoffice Dekstop 5.4.2.30. If your Windows system has "Automatically hide taskbar (startup) in desktop mode" enabled, you cannot open the taskbar (startup) when unfolding OnlyOffice. That is, as soon as the mouse is placed at the bottom of the screen, the start should appear, but this does not happen.

Здравствуйте. Я нашел баг в Onlyoffice Dekstop 5.4.2.30. Если в системе Windows включена функция "Автоматически скрывать панель задач (пуск) в режиме рабочего стола", то при разворачивании OnlyOffice нельзя открыть панель задач (пуск). То есть, как только мышь опустится в самый низ экрана - пуск должен появиться, но этого не происходит.

Windows 10

**Comment by Rita-Bubnova** [comment]
Hello, @drkrol.
This is duplicate #129.
