### ISSUE TITLE
Default font problem with Korean language

### ISSUE THREAD

**Issue by ds2atc** [ONLYOFFICE/DesktopEditors#304]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
Handwriting font is showing when English only fonts are set.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Type Korean letters while English only fonts are selected.

**What is the expected behavior?**
System default font needs to be used instead of the handwriting Korean font.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
DesktopEditors 5.4.2 for Linux
Running on Linux Mint 19.3
I have never tried previous versions.

![bug1](https://user-images.githubusercontent.com/25958633/72219553-aa786f80-358a-11ea-8ebd-807ec19caf11.png)

**Comment by Rita-Bubnova** [comment]
Hello, @ds2atc.
Could you attach the file that is displayed in the screenshot? What keyboard layout are you using? How was the Desktop Editors installed?

**Comment by ds2atc** [comment]
Hello Rita-Bubnova,
I have attached the doc file and the fonts.
I installed Desktop Editors from the deb file on the official website using gdebi, and current input method is "nimf"(fcitx has the same problem)

and below is the keyboard layout information.

`cat /etc/default/keyboard
# KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="pc105"
XKBLAYOUT="kr"
XKBVARIANT="kr104"
XKBOPTIONS=""

BACKSPACE="guess"
`


[kr_font_test.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/4053646/kr_font_test.docx)

Fonts : https://1drv.ms/u/s!AmefndeVrvpe6gGDbTMj5gLieYGH?e=W8HmeU

**Comment by Rita-Bubnova** [comment]
Thanks.
We will investigate this with our team.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
