### ISSUE TITLE
[FEATURE REQUEST] Add func "Remove duplicates" like in Excel 2007+

### ISSUE THREAD

**Issue by q4a** [ONLYOFFICE/DesktopEditors#306]
**Do you want to request a *feature* or report a *bug*?** Feature request

**What is the current behavior?** There is no such functionality

**What is the expected behavior?** Same behavior like in Excel 2007+: removing duplacates in rows

![remove-duplicates-excel](https://user-images.githubusercontent.com/1950719/72902259-32edd180-3d3c-11ea-8f87-73b954eeffba.png)

**Comment by q4a** [comment]
Same request was here: https://cloud.onlyoffice.org/ru/viewtopic.php?t=93211

**Comment by Rita-Bubnova** [comment]
Hello, @q4a.
Thank you for your enhancement. 
I can confirm - this is known issue 43621 in our private tracker.

**Comment by Rosmaninho** [comment]
Could someone point me to the file where the code for the Remove Duplicates in Only Office 6.0 is please?
I wanted to look at it.

**Comment by trofim24** [comment]
> Could someone point me to the file where the code for the Remove Duplicates in Only Office 6.0 is please?
> I wanted to look at it.

[RemoveDuplicates](https://github.com/ONLYOFFICE/sdkjs/blob/b05d71ddc07767939359b5a39f3fe1e44cdb2b3e/cell/api.js#L4768-L4773)

**Comment by Rita-Bubnova** [comment]
"Remove duplicates" option added in Document Server version 6.0 and ONLYOFFICE Desktop Editors version 6.0.2.10 (see screenshot).

![Удаление дубликатов](https://user-images.githubusercontent.com/25282241/99965863-8985cb00-2da6-11eb-9572-caf48aff0c44.png)
