### ISSUE TITLE
Feature: Remeber previous cloud connections and offer them in menu alongside "Open local files"

### ISSUE THREAD

**Issue by zyll71** [ONLYOFFICE/DesktopEditors#308]
**New feature request.**

**Current behavior:**
To open a cloud file, a new connection has to be established every time by pasting url. Connect to cloud does not show previously used cloud links (V 5.4.2.30).
As suggested in the official help, selecting "Connect to cloud" should bring up a list of previous connections. 
https://helpcenter.onlyoffice.com/it/desktop/documents/allplatforms/connect-nextcloud-owncloud.aspx
This does not happen. Instead the "Connect to your cloud" window is displayed with OO, NextCloud and OwnCloud logos. I have to click "Connect Now" to establish a new connection every time I want to open a file on the cloud.

**Reproduce:**
Open OnlyOffice for Windows.
Click on "Connect to cloud"
Establish a connection to a new cloud
Close OnlyOffice
Open OnlyOffice for Windows a second time
Click on "Connect to cloud"
-> The previously established connection is not shown

**Expected behavior?**
Open OnlyOffice for Windows.
Click on "Connect to cloud"
Establish a connection to a new cloud
Close OnlyOffice
Open OnlyOffice for Windows a second time
-> Between "Open local file" and "Connect to cloud" an Option "Open file in cloud" or "Open file in <name of cloud>" is offered.

**Versions**
Windows 10 (Version 10.0.18363 Build 18363)
ONLYOFFICE Desktop Editors version 5.4.2.30

**Comment by maxkadushkin** [comment]
app doesn't keep portals that you connect to after restast, does it? is there portal that you login to in "Connected clouds" list after connection? or "Connect to cloud" panel looks like before connection? with OO, NextCloud and OwnCloud logos
is there records on panel "Recent files" after you open local files or files from some portal? or "Recent files" list is empty?

**Comment by zyll71** [comment]
> app doesn't keep portals that you connect to after restart, does it?

Correct

> is there portal that you login to in "Connected clouds" list after connection?

There is no "Connected clouds visible

> or "Connect to cloud" panel looks like before connection?

Correct

> with OO, NextCloud and OwnCloud logos is there records on panel "Recent files" after you open local files or files from some portal? or "Recent files" list is empty?

No, I see previously opened files in the cloud in addition to the local ones. These links all work as to be expected.

**Comment by maxkadushkin** [comment]
what portal do you connect? nextcloud, owncloud or some portal on onlyoffice?

**Comment by zyll71** [comment]
Nextcloud

**Comment by LinneyS** [comment]
Hi @zyll71 
What version of Nextcloud and ONLYOFFICE connector for Nextcloud do you have?

**Comment by zyll71** [comment]
I'm using the Nextcloud provided by Infomaniak. Sorry, but I can't find a quick way to determine which version they are running.
Is the ONLYOFFICE connector something on my side or the side of the cloud provider?

**Comment by LinneyS** [comment]
The Nextcloud version can be viewed on page `~/index.php/settings/admin/overview`
and the connector version : `~/index.php/settings/apps/installed/onlyoffice`
you must be an administrator

**Comment by zyll71** [comment]
I'm not an administrator at the provider I use. I'm a customer... ;-)

**Comment by ibnpetr** [comment]
Hello 
Could you please contact us at support@onlyoffice.com (subject "Github issue Desktop/308")
We will provide you with the further instructions how to detect and fix (if that's possible) the issue.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
