### ISSUE TITLE
[Bug] Onlyoffice bad system ntegration.

### ISSUE THREAD

**Issue by hope-full** [ONLYOFFICE/DesktopEditors#309]
**Steps to reproduce:**
1.Try opening office files that were created in a different office program (microsoft office/wps office) from a file explorer on linux (didn't test on other platforms).

**Actual result:**
Onlyoffice opens a new window (even if one is already opened) without opening the file.

**Expected result:**
The file should open in a new tab of an existing window.

**Comment by XDmitryK** [comment]
@hope-full Hi 
Need information about your OS and how did you install Onlyoffice? Deb or Snap package?

**Comment by hope-full** [comment]
Hi, @XDmitryK 
Tested in the latest Linux Mint Cinnamon. Installed from Flathub.

**Comment by XDmitryK** [comment]
I agree it's bug
i posted this in our local bug tracker "44319"

**Comment by echanaron** [comment]
Maybe that's a consequence of Flatpak sandboxing, which prevents by default access to files outside Documents.

Same problem occurs with fonts: if you want to add one, you can put it in the /.local/share/fonts folder, which is not recognized by ONLYOFFICE. To bypass it, the user can type :
flatpak override org.onlyoffice.desktopeditors --filesystem=~/.local/share/fonts

As /usr/share/fonts is not readable either, I guess that is related to bug #294, which has been closed two times. ;)
Probably easy to fix with Flatpak portals.

**Comment by trofim24** [comment]
Fixed in 7.4.0
