### ISSUE TITLE
[Bug] Relative formulas in macros don't seem to work

### ISSUE THREAD

**Issue by hope-full** [ONLYOFFICE/DesktopEditors#316]
**Steps to reproduce:**
1.Enable RC range selection in settings (macros shouldn't ideally be dependent on this setting, but they are for some reason).
2.Create spreadsheet and add some numbers to rows 1-3 of 1 and 2 columns
3.Create macro:
`Api.GetActiveSheet().GetRange('R1C3:R3C3').SetValue('=RC[-2]*RC[-1]');`
or
`Api.GetActiveSheet().GetRange('R1C3:R3C3').ForEach(function(cell) {
cell.SetValue('=RC[-2]*RC[-1]');
});`

**Actual result:**
OnlyOffice shows error:
> Internal fatal error parsing the formula.

or something like that

**Expected result:**
The value of the 3 cells in the 3rd column should be equal to result of multiplication of the two cells from the previous columns on the same row.

**Comment by flaminestone** [comment]
Hello @hope-full. It problem is fixed on new version. We will release it soon

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.
