### ISSUE TITLE
macOS Desktop Editor not loading user installed fonts

### ISSUE THREAD

**Issue by prudentcircle** [ONLYOFFICE/DesktopEditors#318]
**Do you want to request a *feature* or report a *bug*?**
It is a BUG

**What is the current behavior?**
User-installed fonts are not showing on the latest version of Onlyoffice Desktop Editor. (5.4.2)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Just install the latest version and launch the program. You can only use system default fonts.
I cannot see any of the custom fonts that I installed on my system.
Other programs load these fonts just fine.

**What is the expected behavior?**
I should be able to use all fonts installed by me on this system.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

I am running on macOS Mojave (10.14.6)
up until 3 months ago, I used user-installed fonts on Onlyoffice just fine.  I was running on the same version of macOS. The problem is with the latest version of the desktop editor (5.4.2)

**Comment by abraha2d** [comment]
Same issue as https://github.com/ONLYOFFICE/DesktopEditors/issues/294?

**Comment by prudentcircle** [comment]
The same issue is gone on the latest release of Desktop Editor (v5.5)

My custom Korean fonts are all loaded back again.
And now I am able to edit Korean documents on OnlyOffice Desktop Editor once again.
