### ISSUE TITLE
Virus detected?

### ISSUE THREAD

**Issue by r3d9u11** [ONLYOFFICE/DesktopEditors#320]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?** Web browser attention

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Try to download .deb package for Ubuntu 18.04 in Firefox 72.0.2

**What is the expected behavior?** Downloading without attentions (like for a virtualbox on my screenshot)

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?** Latest

![Screenshot_20200203_212322](https://user-images.githubusercontent.com/15020827/73680050-a264a900-46cc-11ea-98b7-2953dc43bbaa.png)
![Screenshot_20200203_212121](https://user-images.githubusercontent.com/15020827/73680051-a264a900-46cc-11ea-8296-649fa6878544.png)

What is that? Check it, please.

Thanks!

**Comment by ShockwaveNN** [comment]
This issue should be fixed by now.

I'll close this issue, but feel free to comment or create new issue is problem still actual
