### ISSUE TITLE
Fonts installed under ~/.local/share/fonts are not detected by OnlyOffice

### ISSUE THREAD

**Issue by roydenyates** [ONLYOFFICE/DesktopEditors#321]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Fonts installed under ~/.local/share/fonts (Ubuntu Budgie 19.10) are not detected by OnlyOffice

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Locally install a font with font-manager - OnlyOffice is unaware of the font after reboot

**What is the expected behavior?**
Font visible and usable. LibreOffice sees such fonts and the install location is pretty standard.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
 5.4.2.30 in Ubuntu Budgie 19.10. Previous behaviour unknown but this bug is similar to the resolved issue [https://github.com/ONLYOFFICE/DesktopEditors/issues/134](https://github.com/ONLYOFFICE/DesktopEditors/issues/134)

**Comment by roydenyates** [comment]
Ok, this is a dupe but the observation is buried in a bug report about system fonts

_Originally posted by @terefang in https://github.com/ONLYOFFICE/DesktopEditors/issues/294#issuecomment-567324638_

Will leave this open to be closed by devs.

**Comment by XDmitryK** [comment]
@roydenyates Hi yes it's a bug
We fixed and this will be available in next update

**Comment by ShockwaveNN** [comment]
Issue still actual on release version and I leave it open until fix is released

**Comment by ShockwaveNN** [comment]
DesktopEditors 5.5.1 released. This issue should be fixed.
