### ISSUE TITLE
cell()  function absent from menu and always returns "#name"

### ISSUE THREAD

**Issue by yoasty** [ONLYOFFICE/DesktopEditors#323]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
If you try to select from the list of functions under "all" is is not present in the list. If you use cell(<correct parameters>) it always returns #name 
**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use the menu to try to insert a function (formula/function(x) then select to list all functions. ceiling, ceiling.math, ceiling,precise is followed by char there is no cell() function that can be selected.

Also in a new empty sheet. put something in cell E2.
Then use 

=CELL("type",E2) 
=CELL("width",E2)
=CELL("contents",E2)
in other cells and the answer is always "#name" while if you use libreoffice, gsuite, mso-online they will all give correct answers. 

**What is the expected behavior?**
The Cell function should be availabe in the slectable list of functions. In sheets cell should be available and work correctly. (identical to gsuite, o365 online, libreoffice etc. ) 
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I am convinced it worked in the past. But I have no evidence. 
It looks like someone simply removed the cell() function from onlyoffice.

**Comment by Rita-Bubnova** [comment]
Hello, @yoasty.
We have added support for the Cell function in version 5.5 (https://github.com/ONLYOFFICE/sdkjs/commit/3af3a26169dcb0462669b23b395dfad66883143d) which will be released soon. 
Unfortunately, while this function is partially implemented (issue 43901 in our private tracker).

**Comment by yoasty** [comment]
Great to hear. Thanks. I'll close the issue for now.

**Comment by ShockwaveNN** [comment]
I'll leave this issue opened until version 5.5 is released

**Comment by ShockwaveNN** [comment]
DesktopEditors 5.5.1 released. This issue should be fixed.

**Comment by yoasty** [comment]
Desktopeditors 5.5.1 released for desktop and fixes it, indeed. Thanks very much.
