### ISSUE TITLE
Problems of limits with the integral equation

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#325]
**Do you want to request a *feature* or report a *bug*?**
Bug.
**What is the current behavior?**
When inserting an simple integral equation, there are two options: one with the limits on the right, and one with the limits below and above.
But when I choose the limits below and above, I actually get the limits on the right.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Select insert>equation>integrals>simple integral with limits below and above
**What is the expected behavior?**
The limits should be below and above.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.4.2

**Comment by Rita-Bubnova** [comment]
Hello, @parrenin.
Please indicate your OS.
Could you attach video of this problem and file with problem?

**Comment by parrenin** [comment]
My OS is Debian Linux 10.

**Comment by parrenin** [comment]
I investigated a bit more the issue.
On a fresh document, inserting a large integral works.
But as soon as I insert a character after the equation, the integral becomes small.
I am not sure I like this behavior.
This is probably due to the notion of inline equation but I did not see a way to see if the equation was inline or not.

**Comment by Rita-Bubnova** [comment]
@parrenin, you are right the equation is changing, as it becomes inline.
This is the correct behavior.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
