### ISSUE TITLE
Locale defaults to Chinese on non-Chinese macOS

### ISSUE THREAD

**Issue by AkihiroSuda** [ONLYOFFICE/DesktopEditors#327]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**

The user interface is shown in Chinese though the system locale is Japanese.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Just launch `OnlyOffice.app` from Finder.

**What is the expected behavior?**

The user interface should be shown in English or in Japanese (if supported).

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

OnlyOffice 5.4.2 (367), macOS 10.15.3.
Haven't tried other versions.

**Comment by Rita-Bubnova** [comment]
Hello, @AkihiroSuda.
The ONLYOFFICE Desktop Editor language is selected from the list of preferred languages   (that is, it uses the first language that the application supports).

Is Chinese on your list of preferred languages? Does it stand higher than English?

**Comment by AkihiroSuda** [comment]
Thanks, adding English to the language list via System Preferences solved the issue.
