### ISSUE TITLE
[Feature Request] Table and Figure Captions

### ISSUE THREAD

**Issue by philipreimer** [ONLYOFFICE/DesktopEditors#329]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Table and Figure Captions do not exist

**What is the expected behavior?**
There should be a way to add a caption to an image or a table - like it is possible in LibreOffice and MS Word - e.g. "Figure 5 - OnlyOffice Desktop Editor Sreenshot".

The numberings should be automatically updated, when adding / removing / moving a figure or table in the text.

It should be possible to reference / link to this caption from the text, e.g. "see Figure 5"

The references in the text should be automatically updated, if the captions or numberings change.

It should be possible to create a "Table of Figures" and "Table of Tables" from the existing captions, like you can do with the Table of Contents.

see https://dev.onlyoffice.org/viewtopic.php?f=44&t=24572&sid=707ee37e7652b59e5281e2daf7c3718b

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Editors version 5.4.2.30
Linux, Mac, Windows

**Comment by Rita-Bubnova** [comment]
Hello, @philipreimer.
This feature is implemented in https://github.com/ONLYOFFICE/web-apps/commit/a4a2bdcf461510383b0e010d0bd7e4fe9cc22067#diff-03a8ffcaaaf43cebada40f4b619a7292 and will be release in v5.5.0.

Thank you for your enhancement.

**Comment by parrenin** [comment]
I just tested this feature in OnlyOffice 5.5.
I see that I can insert a legend to, e.g., a figure, and the numbering is automatic.
But I don't see how I can make a reference to this legend (e.g., "see Figure 2").
Is there a guide on how to do it?
Thanks.

**Comment by XDmitryK** [comment]
@parrenin Unfortunately this functionality is currently in development
I mean reference for Tables or Images

**Comment by philipreimer** [comment]
@XDmitryK that's great to hear. Is there a github issue we can follow?

**Comment by XDmitryK** [comment]
@philipreimer I don't have no release information in the near future
But you can create a new issue

**Comment by philipreimer** [comment]
@ShockwaveNN what does the Label `fixed` mean? 

I see that web editor v5.5.0 now supports adding captions to tables and figures. But there is no version 5.5.0 of DesktopEditors available yet.

Also it is not possible to reference captions from the text yet (e.g. "see Figure 5).

Does `fixed` mean that it is implemented and we just need to wait for the release of DesktopEditors 5.5.0?

**Comment by ShockwaveNN** [comment]
> Does fixed mean that it is implemented and we just need to wait for the release of DesktopEditors 5.5.0?

Yes, you're right.
`Fixed` mean that issue should be fixed in next release. We didn't release DesktopEditors in quite a long time, but currently working on releasing DesktopEditors 5.5.1 (skipping 5.5.0)

**Comment by ShockwaveNN** [comment]
DesktopEditors 5.5.1 released. This issue should be fixed.

**Comment by philipreimer** [comment]
@ShockwaveNN  please re-open. This is only partly fixed with DesktopEditors 5.5.1.

I can now add captions to figures and tables.

However, the numbering of captions is not automatically updated when inserting more images or moving images in the text, e.g.:

1. insert image_1
1. add caption to image_1
1. insert image_2 *before* image_1 in the document
1. add caption to image_2

Result
both images have caption "Figure 1:"

Expected result
image_2 should have caption "Figure 1"
image_1 should have caption "Figure 2"

See attached [test.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/4464635/test.docx)

Also, as @parrenin already mentioned, there is no way to reference figures or tables in the text.

It is also not possible to create a table of figures or table of tables.

**Comment by XDmitryK** [comment]
@philipreimer 
please create a new issue for your scenario
Also if you find new problems with "Caption" then create a new issue 
for a specific issue, create a new issue so it will be easier for us to tell you what is fixed and what is not

**Comment by philipreimer** [comment]
@XDmitryK done, please see #357 and #358
