### ISSUE TITLE
Comments removed in OnlyOffice still appear in Word

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#330]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.
**What is the current behavior?**
When opening the attached document in OnlyOffice, no comment appear.
But if it is opening in MS-Word, comments appear.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the attached document in OnlyOffice and Word and compare.
**What is the expected behavior?**
When removing a comment in OnlyOffice, it should be really removed from the document.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.4.2.
[Document2.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/4237287/Document2.docx)

**Comment by Rita-Bubnova** [comment]
Hello, @parrenin.
Sorry, I cannot reproduce your problem.
Could you describe the steps for playback in more detail or сan you attach video of this problem?
Which version of MS Word are you using?

**Comment by parrenin** [comment]
I tried with both Word 2010 and Word 2016.
Comments appear in Word, but not in OnlyOffice.
You said you cannot reproduce.
Does that mean that comments appear in your version of OnlyOffice?

**Comment by parrenin** [comment]
I attach the screenshots of the document in OnlyOffice and Word.
![screenshot-Word](https://user-images.githubusercontent.com/4678272/75234609-2c2f0000-57bb-11ea-99de-967201a09202.png)
![screenshot-OnlyOffice](https://user-images.githubusercontent.com/4678272/75234610-2d602d00-57bb-11ea-894b-aa1900de2035.png)

**Comment by Rita-Bubnova** [comment]
I think I understand your problem.
Go to the "File" -> "Additional Settings..." -> section and check the box "Turn on display of the resolved comments", and then click the "Apply" button.
A comments should appear on the page.

**Comment by parrenin** [comment]
Yes, that is it, thanks.
I did not know comments could be resolved but still in the document.

**Comment by ShockwaveNN** [comment]
I'll close issue. Feel free to comment or create another issue if something happens
