### ISSUE TITLE
Equation editor: guide for shortcuts

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#335]
**Do you want to request a *feature* or report a *bug*?**
Request a feature.
**What is the current behavior?**
The equation editor of OnlyOffice generally uses LaTex shortcuts, which is good.
But the \frac shortcut for creating fractions does not work.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Entering \frac should create a fraction.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.4.2

**Comment by Rita-Bubnova** [comment]
Hello, @parrenin.

> The equation editor of OnlyOffice generally uses LaTex shortcuts, which is good.

Could you explain in more details what do you mean by that phrase?

**Comment by parrenin** [comment]
I mean that you can insert α by typing \alpha, you can insert a subscript by typing _, etc.

**Comment by parrenin** [comment]
I just discovered that typing 'a/b' and then 'space' in an equation insert the a/b fraction.
So I think it answers my comment.
It would be nice to have a guide of the shortcuts available in the equation editor.

**Comment by Rita-Bubnova** [comment]
> It would be nice to have a guide of the shortcuts available in the equation editor.

Thank you for your enhancement.
I created a new issue 44659 in our private issue tracker.

**Comment by HectorB-2020** [comment]
@parrenin , I guess that your requirements for symbols like 'α' were addressed by AutoCorrect:
![OO10](https://user-images.githubusercontent.com/64358003/103566588-4a818400-4ed3-11eb-8acf-916462246643.png)


> I just discovered that typing 'a/b' and then 'space' in an equation insert the a/b fraction.

@parrenin, but can you please be more specific how you turn 1/2 or 3/4 into real fractions as you type? Any specific configuration?

**Comment by ElenaMaaya** [comment]
Hello, parrenin! This is [fixed](https://github.com/ONLYOFFICE/web-apps/commit/2d3441bcf3f525cc9434753aa50adb1c112aeb3a) in DocumentServer and DesktopEditors v. 8.0. Information is available in the File tab -> Help -> AutoCorrect Features section. 
Thanks for contacting us!

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
