### ISSUE TITLE
Cell References Different Web/Mac Client

### ISSUE THREAD

**Issue by wuast94** [ONLYOFFICE/DesktopEditors#337]
when I have something like "=RC2*R1C3/100" in an excel sheet its different from MacOS Client to Cloud Instance. 

On the Left Site the MacOS Client. There I Edited and saved the sheet. looks all fine as it should.
On there right site I opened in Nextcloud and see that the Formular was saved Different and of course I get Errors in my sheet. 

<img width="724" alt="Bildschirmfoto" src="https://user-images.githubusercontent.com/16965460/75747625-bd532900-5d1d-11ea-8b03-90a9144d60ae.png">

Why is this Happening ?

**Comment by Rita-Bubnova** [comment]
Hello, @wuast94.
Which version of DesktopEditors you use? What product (and version) is used in Nextcloud?

**Comment by wuast94** [comment]
I downloaded the latest version from desktop client today... And my nextcloud server is up to date too..when there was no big change last week the community server should up to date too.

**Comment by ShockwaveNN** [comment]
@wuast94 To be clear - on nextcloud are you using Community Document Server?

**Comment by wuast94** [comment]
> @wuast94 To be clear - on nextcloud are you using Nextcloud's Community Document Server?

That's true :)

**Comment by ShockwaveNN** [comment]
@wuast94 , please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
