### ISSUE TITLE
presentation video is not working

### ISSUE THREAD

**Issue by Xyz00777** [ONLYOFFICE/DesktopEditors#338]
**BUG**

**What is the current behavior?**
I inserted a downloaded YouTube video into the presentation (pptx file growed to the size of the video) but i can't start the video. When i hover over the video (in presentation mode) with my mouse than i can see that i can click there but nothing happens... it would be extrem awesome when that can get fixed until next week 13.3. Because i need it then... when i insert the video its only creation a black box.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Insert a mp4 video into the presentation over the video plugin. than a black box appears and the pptx grow at the file size of the video. than start the presentation and you cant play the video but you can see that when you hover with your mouse over the black box that the box is clickable.

**What is the expected behavior?**
It should start when i click it

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Editors version 5.4.2.30 (windows 10 Pro 1909) i dont have other platforms to check if its happen there too

**Comment by XDmitryK** [comment]
@Xyz00777 
Hi you need install K-Lite Kodec Pack for watching video in our app

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
