### ISSUE TITLE
German Language correction

### ISSUE THREAD

**Issue by Xyz00777** [ONLYOFFICE/DesktopEditors#340]
**Do you want to request a *feature* or report a *bug*?**
Language correction

**What is the current behavior?**
In German when you want to search for new updates there stand "Prüfen Sie Updates"

**What is the expected behavior?**
There should stand "Nach Updates suchen"

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Editors version 5.4.2.30 (windows 10 Pro 1909) i dont have other platforms to check if its happen there too

**Comment by ShockwaveNN** [comment]
@svetlana81 please take a look

**Comment by hellonadya** [comment]
Thanks for the correction, we fixed that. The fix will be released with the next update.

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.
