### ISSUE TITLE
pptx: Incorrect rendering of bullets

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#341]
**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**
In the attached pptx file, the bullets are not displayed correctly
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
  ** open the file in OnlyOffice
  ** open the file in PowerPoint
  ** compare
**What is the expected behavior?**
bullets should be displayed a plain circles
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.4.2 on Debian Linux 10.
[test.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/4313349/test.pptx)

**Comment by ShockwaveNN** [comment]
@Rita-Bubnova please take a look

**Comment by parrenin** [comment]
This is probably the same as: https://github.com/ONLYOFFICE/DocumentServer/issues/718.
The file was created using LibreOffice 6.4.
I used the standard template of LO.
OnlyOffice is probably missing some font to display the bullets.

**Comment by parrenin** [comment]
I cannot reproduce on Windows 10.
This really seems to be a font issue.
Arial is present on Windows 10 but not on Debian 10.
Maybe the fix in this issue will solve the problem: https://github.com/ONLYOFFICE/DesktopEditors/issues/321

**Comment by Rita-Bubnova** [comment]
Hello, @parrenin.
Thank you. I can confirm - this is a bug, issue 44907 in our internal issue tracker.

**Comment by kbauer** [comment]
For reference, I experienced the same issue on Linux, until I installed `webcore-fonts-vista` (Open Suse, Zypper).

**Comment by parrenin** [comment]
I cannot reproduce anymore on Debian 11 with OnlyOffice 6.3.
This issue is fixed for me.

**Comment by parrenin** [comment]
I will close this issue since it is fixed for me now.

**Comment by Rita-Bubnova** [comment]
@parrenin, the problem don't reproduce in "test.pptx" file in ONLYOFFICE Desktop Editors version 7.0.1.
Another problem ("Presentation Template (2).pptx" file) fixed (https://github.com/ONLYOFFICE/sdkjs/commit/9171d0817d832485c8d05264a84c148f8e0e44df) in future major release.

@parrenin, I think the problem is fixed for you, because you have necessary fonts installed in the OS.
