### ISSUE TITLE
Low quality exporting to the PDF

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/DesktopEditors#345]
**Do you want to request a feature or report a bug?**
Request a feature or repost a bug

**What is the current behavior?**
When I save my docx as PDF, the result looks low quality - images ~~and certain parts of text~~ blurry
The table of content also doesn't work properly and doesn't redirect me to page after clicking it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a docx > insert content > file > save as PDF

What is the expected behavior?
Table of content that redirects me to pages. ~~Clear text.~~
Ability to export file as PDF properly.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

I didn't try previous versions

Latest Windows 10

Latest stable OnlyOffice Document editor

**Attaching file**
[file.pdf](https://github.com/ONLYOFFICE/DesktopEditors/files/4361423/file.pdf)

**Comment by ShockwaveNN** [comment]
@Rita-Bubnova please take a look, as far as I remember look like pretty old bug

**Comment by Rita-Bubnova** [comment]
Hello, @ghost.
Can't follow the links in a PDF or DOCX file?
Can you attach the original DOCX file?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
