### ISSUE TITLE
ppt: incorrect vertical spacing of text

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#351]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.
**What is the current behavior?**
In the linked ppt file, the vertical spacing of text is incorrect.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
To reproduce, open the file in OnlyOffice and PowerPoint and compare.
**What is the expected behavior?**
The appearance of the slide should be the same in both softwares.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.4.2
https://cloud.univ-grenoble-alpes.fr/index.php/s/BeBJT7DAXYLx6Wd

**Comment by Rita-Bubnova** [comment]
Duplicate https://github.com/ONLYOFFICE/DesktopEditors/issues/347.
