### ISSUE TITLE
[Bug] - Default Templates in Nautilus

### ISSUE THREAD

**Issue by Dvlnst** [ONLYOFFICE/DesktopEditors#355]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
Every time I open Onlyoffice, some default templates are created in Nautilus Templates directory. I already have my custom templates, I don't need/want them.

**What is the expected behavior?**
Prevent those templates from being created. They should be created during installation or just the first time Onlyoffice is opened.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Debian 10 (Buster).
ONLYOFFICE Desktop Editors version 5.5.1.78.

Kind regards.

**Comment by XDmitryK** [comment]
@Dvlnst 
We are currently thinking about how to solve this problem.

**Comment by XDmitryK** [comment]
@Dvlnst  Also you can run command:
sudo nano /usr/bin/desktopeditors
comment lines from 82 till 95

**Comment by Dvlnst** [comment]
Thanks for the workaround, I though /usr/bin/desktopeditors was a binary file so I didn't bother to try to edit it. I had two workarounds: one monitoring the Templates folder with inotify-tools and removing unwanted templates. Another is to edit the desktop file and remove those templates after run Onlyoffice. Yours is definitely better.

Thank you, I appreciate the support.

Kind regards.

**Comment by XDmitryK** [comment]
Sorry for the long delay, this issue has been fixed in a commit
https://github.com/ONLYOFFICE/desktop-apps/commit/c3be73c0090816a0bcb06ed9426ca0c20ffe79ef
