### ISSUE TITLE
[Feature Request] Reference Figure and Table Captions from Text

### ISSUE THREAD

**Issue by philipreimer** [ONLYOFFICE/DesktopEditors#357]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
It is not possible to reference (link to) figures or tables from the text.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
It should be possible to reference (link to) figures and tables from the text, e.g. "see Figure 5", "see Table 2", etc.

This should work like referencing headings from the text. The references in the text should be clickable. Clicking the reference should put the cursor at the referenced figure's or table's caption.

When the figure / table captions are updated the reference's text should also be updated. For example:
1. I add a reference to Figure 5 in the text: "see Figure 5"
1. I insert another figure before Figure 5.

Result: Figure 5 is now Figure 6 and the reference in the text should be automatically changed to say "see Figure 6".

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
All DesktopEditors up to version 5.5.1.78
All operating systems

**Comment by XDmitryK** [comment]
Thank for your feedback
I created new issue 45174 in our local bugtracker

**Comment by solarjoe** [comment]
Any news on this? I am using Desktop Editors Version 5.6.4.20
This is really an important to have to create larger reports.
Without it I would not start a large report in Onlyoffice as you have to tons of overhead with
renumbering when adding or moving images or tables.

**Comment by matveevms** [comment]
Hello, @philipreimer, @solarjoe 
Cross-references implemented in version 6.1
