### ISSUE TITLE
[Feature Request] Automatically create List of Figures  / Tables from Figure / Table Captions

### ISSUE THREAD

**Issue by philipreimer** [ONLYOFFICE/DesktopEditors#358]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
It is not possible to automatically create a list of figures or list of tables

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
It should be possible to create a list of figures and list of tables based on figure / table captions in the document.

This should work like adding a table of contents based on headings existing in the document.

The list of figures / tables should contain the figure / table number, the caption's text and the page number.
Each entry in the list of figures / tables should be clickable. Clicking on an entry would put the cursor at the referenced figure's (or table's) caption.

It should be possible to update the list of figures / tables like it is possible with the table of contents, i.e. only update page numbers or update entire list.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
All DesktopEditors up to version 5.5.1.78
All operating systems

**Comment by XDmitryK** [comment]
Thank for your feedback
I created new issue 45175 in our local bugtracker

**Comment by trofim24** [comment]
We've released this feature in [version 6.2.0](https://github.com/ONLYOFFICE/DesktopEditors/blob/master/CHANGELOG.md#620)
