### ISSUE TITLE
Use gtk3 save as window, instead of the gtk2 one.

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/DesktopEditors#36]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
DesktopEditors uses GTK2 to render the "Save as" window, this cause problems with custom GTK3 themes, also, gtk2 is legacy, with GTK3 being the stable release.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
4.2.5.312. Arch Linux, updated. I assume it was like this in previous versions of DesktopEditors.
PD: Kickass software, fellows, I replaced Libreoffice with it. Kudos for this Office suite!

**Comment by JohnPerkin** [comment]
Hello @Ufeldraku!
Thank you for your positive feedback on ONLYOFFICE. We will take this issue into consideration.

**Comment by xmbwd** [comment]
Can I second this?  The current "Save as" or "Open document" windows look like, well, Windows.  

![opendocument](https://user-images.githubusercontent.com/12945044/52169318-e6eceb80-26ea-11e9-9e8e-b77f3f8d9d8c.png)

**Comment by paulocoghi** [comment]
This is really important, because it can compromise the first impression for new users.

**Comment by paulocoghi** [comment]
I believe this issue is solved. Tested on both Ubuntu Mate 18.04 and 20.04 and now the dialogs are using GTK3 *or, if not,* they are following the theme completely (if not using gtk3).

**Comment by keybreak** [comment]
on Arch Linux still looks kinda like GTK2 above posted by @xmbwd  :frowning_face: 
I'd really like more modern dialog too :+1:

**Comment by XDmitryK** [comment]
Native window support was added in version 7.4.0
