### ISSUE TITLE
[Bug] Multiple-window support does not work on macOS (v5.5.1)

### ISSUE THREAD

**Issue by leoaltmann** [ONLYOFFICE/DesktopEditors#363]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
When multiple files are open in OnlyOffice, dragging the tab for each file only allows it to move within the window, it does not pop out into a new window.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Open OnlyOffice on macOS
- Open two or more documents
- Grab document tab in top bar, drag up and out of window
- Observe tab does not leave window and spawn new editor

**What is the expected behavior?**
- Dragging document tabs out of top bar spawns new editor with that document

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
macOS  - version 5.5.1.  Have only tried this version, per the blog this feature was introduced in 5.5.

**Comment by Rita-Bubnova** [comment]
Hello, @leoaltmann.
This is known problem. @ayuzhin take a look, please.

**Comment by Raph33** [comment]
I experience the same issue

**Comment by ayuzhin** [comment]
It's not a bug. Multiple windows support was not announced for the macOS. Please read the announcement carefully. At the moment, this function is at the design stage.
