### ISSUE TITLE
Drop-down menu bug

### ISSUE THREAD

**Issue by macmiranda** [ONLYOFFICE/DesktopEditors#365]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When you insert a row above a line that contains a drop-down menu, the inserted row has a dropdown menu in the column where the original row had the drop-down menu, which is working as expected. The original row though loses its drop-down menu.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Insert a row above a row that contains a drop-down menu. 
**What is the expected behavior?**
Both rows, new and original should have drop-down menus.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Using DocumentServer 5.5.1 (but core is hosted here)

**Comment by Rita-Bubnova** [comment]
Hello, @macmiranda.
Thank you.
This is a known issue 44854in our internal issue tracker.

**Comment by ShockwaveNN** [comment]
Yeah, thanks for noticing, seems we've fixed this issue some time ago and forgot to close this issue
