### ISSUE TITLE
Text doesn't show properly in qt dialogs

### ISSUE THREAD

**Issue by codic12** [ONLYOFFICE/DesktopEditors#366]
For example save dialog
![image](https://user-images.githubusercontent.com/48339289/79781163-eb062880-82f1-11ea-913b-8f4790780863.png)
unsaved document dialog
![image](https://user-images.githubusercontent.com/48339289/79781199-f8231780-82f1-11ea-8628-b1dfe65619d9.png)

**Comment by Rita-Bubnova** [comment]
Hello, @gsbhasin123.
Please, fill in the template correctly and specify OS and product versions.

**Comment by gsbhasin123** [comment]
OS version: Manjaro KDE 19
Product version: Latest at https://aur.archlinux.org/packages/onlyoffice-bin/ (if the aur is up to date)

**Comment by Rita-Bubnova** [comment]
Thank you. I can confirm - this is a bug, issue 31995 in our internal issue tracker.

**Comment by gsbhasin123** [comment]
okay-thanks

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
