### ISSUE TITLE
Double clicked items open the desktop editor, but not the document itself. Flatpak install.

### ISSUE THREAD

**Issue by jwshive** [ONLYOFFICE/DesktopEditors#369]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When double clicking a file that would open in OnlyOffice (xlsx, docx, etc), the only office desktop editor opens but the document that was double clicked does not open. It does not matter if the desktop editor has been previously started or not. Also, it appears only certain folders show up in the "Open Local File" menu. [Desktop, Documents, Downloads, Pictures, Videos]

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
With OnlyOffice open or closed, double click a Microsoft Word Document (docx).
The desktop editor will open, but the document will not.

**What is the expected behavior?**
The desktop editor opens with a new table for the file I've just double-clicked.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
This is the first version of DesktopEditors I've used. It is installed as a flatpak.
org.onlyoffice.desktopeditors                                     5.4.1

**Comment by klainn** [comment]
The AppImage version will allow me to open a document from any folder, not just the ones listed above. The installed deb package (running on Pop_OS 19.10), everything works as expected. I suppose this is a limitation or bug of the flatpak install only.

**Comment by liquidiert** [comment]
Had the same problem and it really seems to be related to the flatpak version. deb package also worked for me, though running Pop_OS 20.04.

**Comment by XDmitryK** [comment]
This is known for us problem
Issue 44321 in our local bug tracker

**Comment by parijke** [comment]
Same here, .deb install on Ubuntu 21.10 with ONLYOFFICE Desktop Editors versie 7.0.2.5

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
