### ISSUE TITLE
[Q] Bringing Developer Inspector, if is this a Chromium based app?

### ISSUE THREAD

**Issue by ebraminio** [ONLYOFFICE/DesktopEditors#37]
Is OnlyOffice a Chromium based like the popular Atom editor and Visual Studio Code, as the appearance of "ChromiumBasedEditors" on https://github.com/ONLYOFFICE/desktop-sdk suggests? If so, how can I bring Chromium Developer Inspector on it? Is that just not supported or I've got the technology used on the project incorrectly? Thanks

**Comment by K0R0L** [comment]
run with flag --ascdesktop-support-debug-info

**Comment by ebraminio** [comment]
It didn't help or it seems I don't know how to bring inspector afterward,

`➜  ~ /Applications/ONLYOFFICE.app/Contents/MacOS/ONLYOFFICE --ascdesktop-support-debug-info 
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
May 10 17:01:10  ONLYOFFICE Helper[3005] <Error>: CGAffineTransformInvert: singular matrix.`

**Comment by K0R0L** [comment]
mouse right click on start view / editable field (for example font list combo) in editor tab

**Comment by ebraminio** [comment]
Very nice, thanks. However I can not open DevTools while a document is opened, is Chromium just used for homepage and not documents editors themselves?

**Comment by ebraminio** [comment]
Works great. Thank you very much
