### ISSUE TITLE
.emf image is not saved in text document

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#375]
**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**
When inserting an .emf image in the attached document and saving, the image is not saved properly.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
open the attached .docx file
insert an .emf image. Observe that the image appears normally.
save the file
re-open the file
now the image appears as a red rectangle with a cross
**What is the expected behavior?**
The .emf image should be saved normally.
This was the case before, but then I edited the document with Word 2016 and the images disappeared.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.5.1
[test2.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/4535186/test2.docx)

**Comment by Rita-Bubnova** [comment]
Hello, @parrenin.
Can you attach EMF image?

**Comment by parrenin** [comment]
Unfortunately, it is not possible to attach an .emf file in Gitub.
I think any .emf image can be used to reproduce, but I put one here for which I tested:
https://mycore.core-cloud.net/index.php/s/mYa4gPdYvzkA2YX

**Comment by Rita-Bubnova** [comment]
Thank you for attach image.
I can confirm - this is a bug, issue 45290 in our internal issue tracker.

**Comment by parrenin** [comment]
Still present in 7.0.2.

**Comment by parrenin** [comment]
This bug is still present in 7.2.0, although the support for .emf images has been improved in this version.

**Comment by TatianaKirillova** [comment]
@parrenin Yes, indeed, we are happy to announce that the problem has been resolved in version 8.0.0

**Comment by Rita-Bubnova** [comment]
DesktopEditors v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
