### ISSUE TITLE
Question: How can I customize locale/ format in Desktop Editors?

### ISSUE THREAD

**Issue by AkihaTohno** [ONLYOFFICE/DesktopEditors#376]
**Do you want to request a *feature* or report a *bug*?**
This is request for feature.
Desktop Editor does not have Japanese locale /format settings,
I want to add them. 
So, I want to know where it has locale/format settings,
and how to add them.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

5.5.1

**Comment by Rita-Bubnova** [comment]
Hello, @AkihaTohno.
For full Japanese support, we need interface support. Unfortunately we do not have enough translators for this. 
But you can help translate the app into your language or proofread an existing translation by contacting us at documentation@onlyoffice.com.

**Comment by AkihaTohno** [comment]
Hello, @Rita-Bubnova .
Thank you for your message and I think sorry to replay your message too late.
Well, I will contact at documentation@onlyoffice.com.

**Comment by zilexa** [comment]
With a big workaround that suprisingly no one from the OnlyOffice team wants to provide us, you _**can**_ change the default document language/spell check language, but it requires you to modify/create new templates and move/overwrite existing ones. 

I love OnlyOffice, but the fact I had to spend hours figuring this out myself even though it has been asked numerous times on github and the forum is just insulting. There are more languages in the world! And OnlyOffice actually supports a lot of document languages and even has a spellchecker for many languages.

I have written a guide on how to change the default document language as it cost me so much time doing trial/err to figure this out, I hope it helps others: 
https://github.com/zilexa/Ubuntu-Budgie-Post-Install-Script/blob/master/onlyoffice/README.md

**Comment by ElenaMaaya** [comment]
Hello, @AkihaTohno! I have a good news! The interface, regional settings, and formula language are in Japanese in the latest versions of the desktop editor. Please update ONLYOFFICE Desktop Editors to version 7.4.1.
Have a good day!

**Comment by zilexa** [comment]
You responding on my comment from 2 years old. Your expectations a strange. 
Is this resolved, then provide documentation and close this issue, if not, then provide an up to date work around.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by ElenaMaaya** [comment]
@zilexa, Since your problem is not related to the first problem, Please create a new issue. Thanks for understanding!

**Comment by zilexa** [comment]
@ElenaMaaya could you please clarify why you expect me to contribute again, after 2 years? I don't even know if that workaround that I suggested, that solved the original issue in this ticket 2 years ago, is still valid. 
Why would I validate that after 2 years. Makes zero sense. 
You should have just closed this without involving me.
