### ISSUE TITLE
libcef.dll error, windows 7 32bit

### ISSUE THREAD

**Issue by hitman72ita** [ONLYOFFICE/DesktopEditors#377]
**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**
Every time I exit OnlyOffice 5.5.1 on Windows 7 32bit, the program crashes
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Firma problema:
  Nome evento problema:	APPCRASH
  Nome applicazione:	editors.exe
  Versione applicazione:	5.5.1.78
  Timestamp applicazione:	5e8d1c04
  Nome modulo con errori:	libcef.dll
  Versione modulo con errori:	75.1.14.0
  Timestamp modulo con errori:	5d071e50
  Codice eccezione:	80000003
  Offset eccezione:	01bf825e
  Versione SO:	6.1.7601.2.1.0.256.48
  ID impostazioni locali:	1040
  Informazioni aggiuntive 1:	0a9e
  Ulteriori informazioni 2:	0a9e372d3b4ad19135b953a78882e789
  Ulteriori informazioni 3:	0a9e
  Ulteriori informazioni 4:	0a9e372d3b4ad19135b953a78882e789
**What is the expected behavior?**
it should exit without error codes
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.5.1

**Comment by Rita-Bubnova** [comment]
Hello, @hitman72ita.
Please describe how you exit the application?
You are closing window ONLYOFFICE Desktop Editors or shut down the operating system and then an error appears?

**Comment by hitman72ita** [comment]
yes, when I close OnlyOffice Destop window. the suite works well, it's just annoying to have this error on exit
