### ISSUE TITLE
Cannot access files on WSL 2 file system

### ISSUE THREAD

**Issue by wilbowma** [ONLYOFFICE/DesktopEditors#378]
**Do you want to request a *feature* or report a *bug*?**
This may be a feature request, but could be a bug.

**What is the current behavior?**
When trying to open a file from the Windows Subsystem for Linux (WSL) 2 filesystem, ONLYOFFICE silently fails returning no error message, and opening no files.

WSL 2 mounts the guest filesystem as a Windows network file system named `\\wsl$\<wsl-instance-name>\path\to\file`. Other networked files seem to open correctly, so it may be something specific to WSL.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Setup a WSL 2 instance
2. Attempt to open a .csv file located under `\\wsl$` using the ONLYOFFICE dialog "Open local file" dialog.
3. The file will not open, and no error is raised.

Interestingly, we can work-around the issue by re-mounting `\\wsl$\<wsl-instance-name>` as a networked drive.
1. Navigate to `\\wsl$` in Explorer.
2. Right click on `<wsl-instance-name>` and click "Map network drive ..."
3. Mount the folder as a drive, such as `Z:`.
4. Attempt to open a .csv file from `Z:` using the ONLYOFFICE "Open local file" dialog.
5. The file will open correctly.

**What is the expected behavior?**
The file is opened correctly.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

ONLYOFFICE Desktop Editors version 5.5.1.78
Licensed under GNU AGPL v3
Windows 10 Enterprise Build 19041.21

**Comment by Rita-Bubnova** [comment]
Sorry for the long response, seems we missed this issue.
DesktopEditors v7.4.1 is released. Please state is this problem still actual for you?
