### ISSUE TITLE
/opt/onlyoffice/desktopeditors/dictionaries/ should not be a git repository

### ISSUE THREAD

**Issue by vstoykov** [ONLYOFFICE/DesktopEditors#38]
**Do you want to request a *feature* or report a *bug*?**
I think that is a bug.

**What is the current behavior?**
When rpm package is installed it creates the following folder `/opt/onlyoffice/desktopeditors/dictionaries/` which is a git repository.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
You can check by installing the rpm package and navigate to `/opt/onlyoffice/desktopeditors/dictionaries/` and execute `git status`. Git will report bunch of modified files.
You can also see that there is a `/opt/onlyoffice/desktopeditors/dictionaries/.git` folder which is not empty (35MB).

**What is the expected behavior?**
There should be no git repository installed. Only files needed for the application to work need plus license files and documentation should be included in the package. Everyone who want to contribute to the project can clone the repo from github.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Latest version at this time 4.2.2-45 rpm build. I don't know how it was in previous versions because I try OnlyOffice for the first time.

**Comment by ibnpetr** [comment]
Thanks a lot, 
Will be fixed in the next version (will be available next week)
