### ISSUE TITLE
Flatpak version on Flathub is outdated

### ISSUE THREAD

**Issue by veyselerden** [ONLYOFFICE/DesktopEditors#380]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
It's outdated than the other versions of it
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The current version is 5.5.1 but on Flathub it's 5.4.1.
**What is the expected behavior?**
To be updated like the other versions
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

**Comment by ShockwaveNN** [comment]
Yeah, thank for noticing. We are working on flatpak release right now and hope it will be released very soon
