### ISSUE TITLE
DesktopEditor crashing while launching on windows 10

### ISSUE THREAD

**Issue by linuxqtcppexamples** [ONLYOFFICE/DesktopEditors#384]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Crash

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

-----------------------------CRASH DUMP ANALYSIS--------------------------------------
Microsoft (R) Windows Debugger Version 10.0.17134.1 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\Users\ernds\AppData\Local\CrashDumps\DesktopEditors.exe.18064.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available

Symbol search path is: srv*
Executable search path is: 
Windows 10 Version 18362 MP (4 procs) Free x64
Product: WinNt, suite: SingleUserTS
18362.1.amd64fre.19h1_release.190318-1202
Machine Name:
Debug session time: Fri May 15 11:28:31.000 2020 (UTC + 5:30)
System Uptime: not available
Process Uptime: 0 days 0:00:03.000
................................................................
.........................................
This dump file has a breakpoint exception stored in it.
The stored exception information can be accessed via .ecxr.
ntdll!NtWaitForMultipleObjects+0x14:
00007ffb`5363cbc4 c3              ret
0:000> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

*** WARNING: Unable to verify checksum for ascdocumentscore.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ascdocumentscore.dll - 
*** WARNING: Unable to verify checksum for DesktopEditors.exe
*** ERROR: Module load completed but symbols could not be loaded for DesktopEditors.exe
GetUrlPageData2 (WinHttp) failed: 12002.

KEY_VALUES_STRING: 1

TIMELINE_ANALYSIS: 1

Timeline: !analyze.Start
    Name: <blank>
    Time: 2020-05-15T06:09:33.681Z
    Diff: 662681 mSec

Timeline: Dump.Current
    Name: <blank>
    Time: 2020-05-15T05:58:31.0Z
    Diff: 0 mSec

Timeline: Process.Start
    Name: <blank>
    Time: 2020-05-15T05:58:28.0Z
    Diff: 3000 mSec

DUMP_CLASS: 2

DUMP_QUALIFIER: 400

CONTEXT:  (.ecxr)
rax=0000000000000000 rbx=0000000000000000 rcx=000000ceb7cfecf0
rdx=00000000000000b9 rsi=000000ceb7cfecf0 rdi=0000000000000000
rip=00007ffad0a26563 rsp=000000ceb7cfea60 rbp=000000ceb7cfeae0
 r8=00007f2c1d3f42e0  r9=000000ceb7cfed88 r10=000002c521970000
r11=000000ceb7cfecf0 r12=000002c521974d38 r13=000002c5219746c0
r14=000002c521974040 r15=000000ceb7cfefa0
iopl=0         nv up ei pl zr na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000246
libcef!cef_string_utf16_to_upper+0xe9969:
00007ffa`d0a26563 cc              int     3
Resetting default scope

FAULTING_IP: 
libcef!cef_string_utf16_to_upper+e9969
00007ffa`d0a26563 cc              int     3

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ffad0a26563 (libcef!cef_string_utf16_to_upper+0x00000000000e9969)
   ExceptionCode: 80000003 (Break instruction exception)
  ExceptionFlags: 00000000
NumberParameters: 1
   Parameter[0]: 0000000000000000

BUGCHECK_STR:  BREAKPOINT

DEFAULT_BUCKET_ID:  BREAKPOINT

PROCESS_NAME:  DesktopEditors.exe

ERROR_CODE: (NTSTATUS) 0x80000003 - {EXCEPTION}  Breakpoint  A breakpoint has been reached.

EXCEPTION_CODE: (HRESULT) 0x80000003 (2147483651) - One or more arguments are invalid

EXCEPTION_CODE_STR:  80000003

EXCEPTION_PARAMETER1:  0000000000000000

WATSON_BKT_PROCSTAMP:  5ebd5fe5

WATSON_BKT_PROCVER:  5.3.95.508

PROCESS_VER_PRODUCT:  ONLYOFFICE Desktop Editors

WATSON_BKT_MODULE:  libcef.dll

WATSON_BKT_MODSTAMP:  5d071e50

WATSON_BKT_MODOFFSET:  1e46563

WATSON_BKT_MODVER:  75.1.14.0

MODULE_VER_PRODUCT:  Chromium Embedded Framework (CEF) Dynamic Link Library

BUILD_VERSION_STRING:  18362.1.amd64fre.19h1_release.190318-1202

MODLIST_WITH_TSCHKSUM_HASH:  c1cc2d64050ff777a7f556a7af0d10475e2ecad1

MODLIST_SHA1_HASH:  3af9a9a936987fd4bf1ff74fd090290e4b6fc977

NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

DUMP_FLAGS:  94

DUMP_TYPE:  1

ANALYSIS_SESSION_HOST:  DESKTOP-K07RD37

ANALYSIS_SESSION_TIME:  05-15-2020 11:39:33.0681

ANALYSIS_VERSION: 10.0.17134.1 amd64fre

THREAD_ATTRIBUTES: 
OS_LOCALE:  ENN

PROBLEM_CLASSES: 

    ID:     [0n317]
    Type:   [@APPLICATION_FAULT_STRING]
    Class:  Primary
    Scope:  DEFAULT_BUCKET_ID (Failure Bucket ID prefix)
            BUCKET_ID
    Name:   Omit
    Data:   Add
            String: [BREAKPOINT]
    PID:    [Unspecified]
    TID:    [Unspecified]
    Frame:  [0]

PRIMARY_PROBLEM_CLASS:  BREAKPOINT

LAST_CONTROL_TRANSFER:  from 00007ffad074977b to 00007ffad0a26563

STACK_TEXT:  
000000ce`b7cfea60 00007ffa`d074977b : 000000ce`b7cfefb0 00007ffa`d1518486 00004208`e31288af 000002c5`21973970 : libcef!cef_string_utf16_to_upper+0xe9969
000000ce`b7cfef30 00007ffa`d1018c45 : 00000000`00000001 00000000`00000010 000002c5`21970000 00007ffb`535dba3b : libcef!cef_string_map_size+0x19031eb
000000ce`b7cff020 00007ffa`d091128c : 00000000`00000000 000002c5`21970000 000000ce`b7cff4a9 00007ffb`535e60b9 : libcef!IsSandboxedProcess+0x1f9d5d
000000ce`b7cff1c0 00007ffa`d0910ecc : 000002c5`88000088 000002c5`21973e80 000000ce`b7cff388 00007ffa`cebe11b6 : libcef!cef_string_map_size+0x1acacfc
000000ce`b7cff2f0 00007ffa`cebe1293 : 00000000`00000000 000002c5`1fc51500 00000000`00000080 000002c5`1fc50000 : libcef!cef_string_map_size+0x1aca93c
000000ce`b7cff360 00007ffb`043e7f8a : 000000ce`b7cff5c0 000002c5`1fd3ae40 000000ce`b7cff610 000002c5`21973c30 : libcef!cef_initialize+0xc4
000000ce`b7cff5a0 00007ffb`04404d6c : 000002c5`1fd2ce00 000000ce`b7cff700 000000ce`b7cff610 000000ce`b7cff720 : ascdocumentscore+0x57f8a
000000ce`b7cff5f0 00007ffb`0446fd71 : 000002c5`1fcd09d0 000000ce`b7cff730 000000ce`b7cff9b0 000000ce`b7cff668 : ascdocumentscore+0x74d6c
000000ce`b7cff630 00007ff6`b2323476 : 000002c5`1fd30020 000002c5`00000000 000002c5`1fcd7ee0 000002c5`00000000 : ascdocumentscore!CApplicationCEF::Init_CEF+0x9f1
000000ce`b7cffc20 00007ff6`b2366c14 : 00000000`00000001 00000000`00000000 000002c5`1fcd7110 000002c5`1fd2a4e0 : DesktopEditors+0x3476
000000ce`b7cffdf0 00007ff6`b23662ab : 00000000`0000000a 00000000`00000000 00000000`00000000 00000000`00000000 : DesktopEditors+0x46c14
000000ce`b7cffe80 00007ffb`53267bd4 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : DesktopEditors+0x462ab
000000ce`b7cffec0 00007ffb`5360ce51 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
000000ce`b7cffef0 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21

THREAD_SHA1_HASH_MOD_FUNC:  38b51138b9ee96ac7ee911a4f63713ac9cf045c4

THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  5d21005733c794f13b079d4a6f4bcb8e49d18be3

THREAD_SHA1_HASH_MOD:  9b947f2da4adedc08a65de9b7723c30e39fcb0ae

FOLLOWUP_IP: 
libcef!cef_string_utf16_to_upper+e9969
00007ffa`d0a26563 cc              int     3

FAULT_INSTR_CODE:  6a0b0fcc

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  libcef!cef_string_utf16_to_upper+e9969

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: libcef

IMAGE_NAME:  libcef.dll

DEBUG_FLR_IMAGE_TIMESTAMP:  5d071e50

STACK_COMMAND:  ~0s ; .ecxr ; kb

BUCKET_ID:  BREAKPOINT_libcef!cef_string_utf16_to_upper+e9969

FAILURE_EXCEPTION_CODE:  80000003

FAILURE_IMAGE_NAME:  libcef.dll

BUCKET_ID_IMAGE_STR:  libcef.dll

FAILURE_MODULE_NAME:  libcef

BUCKET_ID_MODULE_STR:  libcef

FAILURE_FUNCTION_NAME:  cef_string_utf16_to_upper

BUCKET_ID_FUNCTION_STR:  cef_string_utf16_to_upper

BUCKET_ID_OFFSET:  e9969

BUCKET_ID_MODTIMEDATESTAMP:  5d071e50

BUCKET_ID_MODCHECKSUM:  0

BUCKET_ID_MODVER_STR:  75.1.14.0

BUCKET_ID_PREFIX_STR:  BREAKPOINT_

FAILURE_PROBLEM_CLASS:  BREAKPOINT

FAILURE_SYMBOL_NAME:  libcef.dll!cef_string_utf16_to_upper

FAILURE_BUCKET_ID:  BREAKPOINT_80000003_libcef.dll!cef_string_utf16_to_upper

WATSON_STAGEONE_URL:  http://watson.microsoft.com/StageOne/DesktopEditors.exe/5.3.95.508/5ebd5fe5/libcef.dll/75.1.14.0/5d071e50/80000003/01e46563.htm?Retriage=1

TARGET_TIME:  2020-05-15T05:58:31.000Z

OSBUILD:  18362

OSSERVICEPACK:  778

SERVICEPACK_NUMBER: 0

OS_REVISION: 0

SUITE_MASK:  256

PRODUCT_TYPE:  1

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

OSEDITION:  Windows 10 WinNt SingleUserTS

USER_LCID:  0

OSBUILD_TIMESTAMP:  1987-11-30 01:37:31

BUILDDATESTAMP_STR:  190318-1202

BUILDLAB_STR:  19h1_release

BUILDOSVER_STR:  10.0.18362.1.amd64fre.19h1_release.190318-1202

ANALYSIS_SESSION_ELAPSED_TIME:  11c00

ANALYSIS_SOURCE:  UM

FAILURE_ID_HASH_STRING:  um:breakpoint_80000003_libcef.dll!cef_string_utf16_to_upper

FAILURE_ID_HASH:  {19642e16-6992-d7f9-6807-8a53534b08e7}

Followup:     MachineOwner
---------

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
OK                                             C:\Devlopment\DesktopEditors\desktop-apps\win-linux\build\win_64

**What is the expected behavior?**

Without application should launch

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Windows 10 MSVC 2015 64 bit and Qt 5.9.9
and below mentioned version are used for to compil Desktop Ediotor Code.
 icu version   : icu4c-60_1-Win64-MSVC2015.zip
 boost version : boost_1_59_0.tar.bz2
cef version   : cef_binary_75.1.14+gc81164e+chromium-75.0.3770.100_windows64.tar.bz2

**Comment by ShockwaveNN** [comment]
How it's different from https://github.com/ONLYOFFICE/DesktopEditors/issues/383 ?

**Comment by linuxqtcppexamples** [comment]
This contains crashdump information, the content is the same.
We can mark as duplicate. 
Are you aware about libcef!cef_string_utf16_to_upper+e9969
 error?
The following 3rdparty version are right, Can you please confirm?
icu version : icu4c-60_1-Win64-MSVC2015.zip
boost version : boost_1_59_0.tar.bz2
cef version : cef_binary_75.1.14+gc81164e+chromium-75.0.3770.100_windows64.tar.bz2

Is this known issue?

**Comment by ShockwaveNN** [comment]
You should continue discussion in #383, since it has more details

And since we current have no correct guid on compilation on windows I don't think I can provide more details

**Comment by linuxqtcppexamples** [comment]
Okay.
