### ISSUE TITLE
Avoidance of two following capital LEtters

### ISSUE THREAD

**Issue by fewaltix** [ONLYOFFICE/DesktopEditors#387]
**Do you want to request a *feature* or report a *bug*?**
A feature.

Especially in languages like German, where many words have to be written with capital letters, _an option to automatically correct words with two CApital LEtters_ in the beginning is very handy and already implemented in MS Word, Textmaker & etc.

Thank you so much for your work!

**Comment by linuxqtcppexamples** [comment]
Is in on windows, Are you able to compile manually based on github code?

**Comment by Rita-Bubnova** [comment]
Hello, @FeWa-zu.
Thank you. I can confirm - this is know issue 38873 in our private issue tracker.
Problems reproduces in Document Server (https://github.com/ONLYOFFICE/DocumentServer/issues/388).

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
