### ISSUE TITLE
Feature Request: Goal Seek & Detective

### ISSUE THREAD

**Issue by JayVii** [ONLYOFFICE/DesktopEditors#392]
Using `ONLYOFFICE Desktop Editors Version 5.5.1.78` & `ONLYOFFICE Online Spreadsheet Editor Version 5.5.1`

We've been using OnlyOffice for a while now and stumbled about this a fair bit in the spreadsheet application, where we would need the "[Goal Seek](https://support.office.com/en-us/article/Use-Goal-Seek-to-find-the-result-you-want-by-adjusting-an-input-value-320cb99e-f4a4-417f-b1c3-4f369d6e66c7)" and the "[Detective](https://support.office.com/en-us/article/display-the-relationships-between-formulas-and-cells-a59bef2b-3701-46bf-8ff1-d3518771d507)" (sometimes referred to as "Precedent & Decedent Cells") features. However we could neither find these in the DesktopEditors, nor the online client (or the manual for that matter).

As reference, these features do not only exist in MS Excel, but also in LibreOffice Calc ([Goal Seek](https://help.libreoffice.org/Calc/Goal_Seek), [Detective](https://help.libreoffice.org/Calc/Detective)) and therefore also Collabora Office.

**Comment by Rita-Bubnova** [comment]
Hello, @JayVii.
Thank you. I can confirm:
"Goal Seek" - this is know issue 42541 in our private issue tracker,
"Detective" - this is know issue 41398 in our private issue tracker.

**Comment by Batwam** [comment]
Hello,

Has there been any progress with the implementation of Goal Seek?

**Comment by Rita-Bubnova** [comment]
@Batwam, sorry, no news.

**Comment by Batwam** [comment]
thanks for the response Rita. Is there a timeline for implementation?

**Comment by Rita-Bubnova** [comment]
Sorry for late response, seems we missed this issue.

"Goal Seek" added [version 8.0](https://github.com/ONLYOFFICE/DesktopEditors/blob/master/CHANGELOG.md#spreadsheet-editor-1). 
"Detective"added [version 7.5](https://github.com/ONLYOFFICE/web-apps/commit/77f74bce4254bd02283908335c74c76ded4cdf22).

 I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by Batwam** [comment]
That's great to hear. Thanks for the update!

**Comment by 8grin4** [comment]
If the target value during goal seek is not an integer, a nan error occurs. Does not accept comma or period as separator. Probably something with the localization setting. I use the Russian version.

**Comment by VladimirProkofiev52** [comment]
Hello! @8grin4 
Thank you for your report. Could you please create a separate issue for your message? We will continue our discussion there.
