### ISSUE TITLE
Incorrect scaling on HiDPI Display [Linux, KDE Plasma, X11]

### ISSUE THREAD

**Issue by athdesk** [ONLYOFFICE/DesktopEditors#393]
**Current behaviour**
DesktopEditors' windows is correctly sized according to the set scaling, but the content remains at 100% size

![Screenshot 1](https://user-images.githubusercontent.com/47639916/82606862-1497c580-9bb8-11ea-8ab1-78d69396e09a.png)
![Screenshot 2](https://user-images.githubusercontent.com/47639916/82606906-24afa500-9bb8-11ea-8a91-2eea349ce51a.png)

**How to reproduce**
Using KDE Plasma, and an HiDPI display (In my case 3840x2160, but I don't think resolution is relevant), set the scaling >100%
Reboot
Open DesktopEditors

**Affected versions**
The problem affects both the latest AppImage version, and the Arch User Repositories version, which I assume to be the same.

**Comment by ShockwaveNN** [comment]
Could you try to run it with `--force-scale=2` argument?

**Comment by athdesk** [comment]
I actually did that, but forgot to mention in my first comment.
It seems that this scales everything, including the white space:
![Screenshot 1](https://user-images.githubusercontent.com/47639916/82644424-9536e000-9c11-11ea-921d-5d384627bdf0.png)

This might me unrelated, but clicking on the window, when using the `--force-scale` argument, makes it automatically shrink to default size. The window frame gets smaller (as it was with 1x scale), and the content remains scaled 2x.
![Screenshot 2](https://user-images.githubusercontent.com/47639916/82644835-42a9f380-9c12-11ea-8c22-03746b360be0.png)

**Comment by ShockwaveNN** [comment]
In that case seems like duplicate of #53
Also there is possible workaround at https://github.com/ONLYOFFICE/DesktopEditors/issues/53#issuecomment-526973965

**Comment by athdesk** [comment]
Of course it is, i don't know how i missed that thread.
I'll close this issue
