### ISSUE TITLE
The icon in the menu and dock panel is not displayed *bug*

### ISSUE THREAD

**Issue by Finist992** [ONLYOFFICE/DesktopEditors#397]
*bug*

The icon in the menu and dock panel is not displayed. Icon only appears when you start desktop-editors. Before the starting only title can be seen.
I use it on the manjaro 19 operating system. 
But If I try to use snap version of this office, I can see the icon

**Comment by ShockwaveNN** [comment]
We are not officially support arch\manjaro operation system. If you use 3d party aur like this https://aur.archlinux.org/packages/onlyoffice-bin/ - please report issues to their authors, or use snap (we do support snap and flatpak and AppImage )

**Comment by Finist992** [comment]
> We are not officially support arch\manjaro operation system. If you use 3d party aur like this https://aur.archlinux.org/packages/onlyoffice-bin/ - please report issues to their authors, or use snap (we do support snap and flatpak and AppImage )

Thank you, then going to use snap

**Comment by ShockwaveNN** [comment]
I'll close this issue, if you got any troubles with snap - please create new issue
