### ISSUE TITLE
Inserting em dash in OnlyOffice *feature*

### ISSUE THREAD

**Issue by Finist992** [ONLYOFFICE/DesktopEditors#398]
Can I insert em dash symbol when I am working in OnlyOffice?
If I use other office suites, I can insert em dash with keybord combinaions (ctrl + -, etc.) but It doesnt work in OnlyOffice

**Comment by Rita-Bubnova** [comment]
Hello, @Finist992.
Can you give a link to the documentation that describes the purpose of the `ctrl` + `-` shortcut in text editors (like LibreOffice or MS Office)?

**Comment by Finist992** [comment]
Cannot find.the documentation.
But it is working now in SoftMaker Office 2019 beta on my PC:
ctrl + - en dash
ctrl + shift + - em dash

**Comment by Finist992** [comment]
> Hello, @Finist992.
> Can you give a link to the documentation that describes the purpose of the `ctrl` + `-` shortcut in text editors (like LibreOffice or MS Office)?

Cannot find.the documentation.
But it is working now in SoftMaker Office 2019 beta on my PC:
ctrl + - en dash
ctrl + shift + - em dash

**Comment by Finist992** [comment]
> Hello, @Finist992.
> Can you give a link to the documentation that describes the purpose of the `ctrl` + `-` shortcut in text editors (like LibreOffice or MS Office)?
Moreover I have already tried to use alt + 0151 to insert emdash but as a result the program changes the style of text formatting

**Comment by Finist992** [comment]
> Hello, @Finist992.
> Can you give a link to the documentation that describes the purpose of the `ctrl` + `-` shortcut in text editors (like LibreOffice or MS Office)?

Moreover I have already tried to use alt + 0151 to insert emdash but as a result the program changes the style of text formatting

**Comment by Rita-Bubnova** [comment]
I'm not sure I understand you correctly. I need some documentation, we do not use  SoftMaker Office 2019, could you try to find docs for LibreOffice or MS Office?

**Comment by Finist992** [comment]
> I'm not sure I understand you correctly. I need some documentation, we do not use SoftMaker Office 2019, could you try to find docs for LibreOffice or MS Office?

Here is it
https://answers.microsoft.com/en-us/office/forum/office_2003-word/en-dash/61731ec5-d0dd-4cf0-8092-2f7185f265d6

**Comment by Rita-Bubnova** [comment]
I tested the work "hold down the Alt key while typing 0150 on the number pad to get an en dash, or while typing 0151 to get an em dash" on ONLYOFFICE Desktop Editors version 5.5.1.78 (OS Windows 10). These combinations work correctly.

> Moreover I have already tried to use alt + 0151 to insert emdash but as a result the program changes the style of text formatting

Which version of Desktop Editors, and which OS are you use?

**Comment by Finist992** [comment]
> > Here is it
> > https://answers.microsoft.com/en-us/office/forum/office_2003-word/en-dash/61731ec5-d0dd-4cf0-8092-2f7185f265d6
> 
> I tested the work "hold down the Alt key while typing 0150 on the number pad to get an en dash, or while typing 0151 to get an em dash" on ONLYOFFICE Desktop Editors version 5.5.1.78 (OS Windows 10). These combinations work correctly.
> 
> > Moreover I have already tried to use alt + 0151 to insert emdash but as a result the program changes the style of text formatting
> 
> Which version of Desktop Editors, and which OS are you use?

I have the latest snap version of Desktop Editors - 5.5.1, using it on Manjaro OS

**Comment by Rita-Bubnova** [comment]
@Finist992, can you check the operation of the keyboard shortcut (hold down the Alt key while typing 0150 on the number pad to get an en dash, or while typing 0151 to get an em dash) in other text editors on your OS (not in  for SoftMaker Office 2019 beta)?

**Comment by Finist992** [comment]
> @Finist992, can you check the operation of the keyboard shortcut (hold down the Alt key while typing 0150 on the number pad to get an en dash, or while typing 0151 to get an em dash) in other text editors on your OS (not in for SoftMaker Office 2019 beta)?

It doesn't work in WPS Office too. Can it depend on my keyboard? I use xiaomi mi notebook pro.

**Comment by Rita-Bubnova** [comment]
I don’t know if it depends on your keyboard. It seems that these keyboard shortcuts may be OS dependent.
You can try using a symbol table (tab "Insert") to insert em dash.

**Comment by Finist992** [comment]
> I don’t know if it depends on your keyboard. It seems that these keyboard shortcuts may be OS dependent.
> You can try using a symbol table (tab "Insert") to insert em dash.

Yes, It works! Insert + double dash. Thank you!

**Comment by ShockwaveNN** [comment]
Seems your problem is resolved, I'll close this issue, feel free to comment if got any question
