### ISSUE TITLE
4.3.2.318 Update issue, not launching 2nd+ time

### ISSUE THREAD

**Issue by efimov90** [ONLYOFFICE/DesktopEditors#40]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
4.3.2.318
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Update, launch, close, launch.
**What is the expected behavior?**
It open document.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
4.3.2.318, windows 10 (1703, 15063.138), it works on previous versions. It just loads CPU for 50% and do absoluttely nothing. Reboot helps, but it's ridicolous reboot each time after 1 launch and closing.

**Comment by ShockwaveNN** [comment]
I think issue should be resolved by now, if not - please create a new issue
