### ISSUE TITLE
Crushed on copy-paste big amount of content

### ISSUE THREAD

**Issue by kpstsp** [ONLYOFFICE/DesktopEditors#400]
**bug**

**Word processor crushed on copy past big amount of text: > 400 pages with error:
Something has gone wrong. Work with. file has been cancelled..**

**Create new doc with up to 400 pages with text and media content. Cmd+A , Cmd+v**

**Copy and paste successfully or show notification about app limits**

**Which versions of DesktopEditors, and which OS are affected by this issue?
5.4.2 (367)
Mac OS X Mojave 10.14.6
 Did this work in previous versions of DesktopEditors?:
Don't know**

**Comment by ShockwaveNN** [comment]
Could you try to update to latest version of DesktopEditors (5.5) and reproduce bug again

**Comment by kpstsp** [comment]
With ver. 5.5.1 works great. Tested up to 1000 pages, all ok.
Thanks!
