### ISSUE TITLE
Application crashes on start in Win8.1

### ISSUE THREAD

**Issue by andreaschizzali** [ONLYOFFICE/DesktopEditors#401]
**Do you want to request a *feature* or report a *bug*?**
report a bug
**What is the current behavior?**
Starting the freshly installed application DesktopEditors_x64.exe  downloaded from https://www.onlyoffice.com/de/webinars.aspx gives a crash
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Start the program,  message widow appears with title "editors.exe  Einsprungpunkt nicht gefunden" and content "Der Prozedureispungpunkt 
"?put_Height@CBgraFrame@@QEAAXAEBH@Z" wurde in der DLL
"C:\Program
Files\ONLYOFFICE\DesktopEditors\converter\HtmlRenderer.dll" nicht 
gefuden.  
![2020-05-29 17_23_49-editors exe - Einsprungpunkt nicht gefunden](https://user-images.githubusercontent.com/49131541/83277052-cdba5900-a1d1-11ea-8599-01824e129320.png)
**What is the expected behavior?**
The program should start
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Last version of DesktopEditors for 64 bit Windows downloaded today, Version 5.5.1.78.
Installed on a Windows 8.1.
It is my first download, I wished to try the program.

**Comment by Rita-Bubnova** [comment]
Hello, @andreaschizzali.
Can you attach a screenshot of the applications installed on your computer (Control Panel\Programs\Programs and Features)?
If you want to do this private send a screenshot to support@onlyoffice.com marked "DesktopEditors / # 401".

**Comment by maxkadushkin** [comment]
it seems there is some issue with lib's search path. could you launch the app from cmd?
> cd "c:/Program Files/ONLYOFFICE/DesktopEditors"
> set PATH=./converter;%PATH%
> DesktopEditors.exe

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
