### ISSUE TITLE
Request feature copy formula to whole column

### ISSUE THREAD

**Issue by xjrcode** [ONLYOFFICE/DesktopEditors#403]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
The only way to apply a formula to whole column is drag the bottom right cell and drop the column way down to the end of the table.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Double click on bottom cell corner (or shift + double click) should apply the formula to all the empty cells below.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Desktop Editor (at least on macOS)

**Comment by Rita-Bubnova** [comment]
Hello, @xavi-dev.
Do I understand correctly that the specified area should be formatted as tables?

**Comment by xavi-dev** [comment]
Sorry, my explanation was too poor.

In the Excel Desktop App, usually in all editors you can double click a cell to copy the formula to the whole column. I made a video of the feature:

![doubleclick](https://user-images.githubusercontent.com/3817677/83612097-39117b80-a582-11ea-84f5-0f170c18e234.gif)

In ONLYOFFICE this is not possible and it's difficult to apply a formula in a document with thousands of rows:

![ONLYOFFICE](https://user-images.githubusercontent.com/3817677/83612494-c48b0c80-a582-11ea-9029-4ff1cccb6b1b.gif)

**Comment by Rita-Bubnova** [comment]
@xavi-dev, thanks for the detailed explanation)
I can confirm - this is known issue 42972 in our private issue tracker.

**Comment by HectorB-2020** [comment]
I guess we have [another very much the same request (or bug?)](https://github.com/ONLYOFFICE/DesktopEditors/issues/510#issue-743782132).

Hopefully this is going to be implemented some day.

**Comment by HectorB-2020** [comment]
May I follow up on this request?
Can you please update if you are going to implement this any time in future?

**Comment by alinasafonova** [comment]
Hello, @xjrcode, @HectorB-2020

This feature is implemented in https://github.com/ONLYOFFICE/sdkjs/commit/f3519ccfe2e4f1a852ade999ca0de9b5197f834c

It will be released as v7.2.0

**Comment by ShockwaveNN** [comment]
DesktopEditors v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions
