### ISSUE TITLE
Sticky edges feature

### ISSUE THREAD

**Issue by qdouasbin** [ONLYOFFICE/DesktopEditors#408]
First things first: you guys are doing a great job!

I am using onlyoffice on ubuntu20.04 LTS.

I noticed that the "sticky edges" feature was implemented in the top-center (maximizes the window).
However, the feature does not seem to be implemented for the left and right sides. Most ubuntu apps (and windows) use the sides sticky efges to resize the window to half of the screen (horizontally). 

This feature could improve the "feel" associated with the app that will be loved by users.

**Comment by XDmitryK** [comment]
Yes it's bug
Issue 44915 in our local bugtracker

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
