### ISSUE TITLE
[Feature Request] Please can we have a proper in text referencing system like on MSOffice

### ISSUE THREAD

**Issue by joehfearon** [ONLYOFFICE/DesktopEditors#409]
This is a plea for a feature that would make ONLYOFFICE immensely useful for uni students.
University essays require in-text citations and a bibliography, typically in Harvard style referencing. 

This is a massive pain in the ass to do manually, and in MSOffice there is a tool that lets you add in text citations and then compiles a bibliography at the end your document.
This would be an incredibly useful feature to have in the referencing tab,as I could use this to write my university essays. 

Many Thanks.

**Comment by VladimirProkofiev52** [comment]
Hello! @joehfearon,
Our editor has the Zotero plugin. Try to use it, it should suit your needs.

The Zotero plugin can be installed using the Plugin Manager.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
