### ISSUE TITLE
Open file menu does not list all directories

### ISSUE THREAD

**Issue by Flygrounder** [ONLYOFFICE/DesktopEditors#411]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I open local file, explorer does not list all directories in my home.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open local file

![Снимок экрана от 2020-06-16 15-33-21](https://user-images.githubusercontent.com/16033061/84774707-e656ab80-afe6-11ea-97eb-a340537f3f3a.png)

**What is the expected behavior?**
Explorer should list all directories in my home directory.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
OS: Pop!_OS 20.04
DesktopEditors v. 5.5.1 installed via flatpak

**Comment by hanny00** [comment]
I have the same issue. I want to open some files on my second ssd located in /mnt/ 
but i cannot not open the location, is not there.

![Screenshot_20200616_152313](https://user-images.githubusercontent.com/50232823/84780249-a642f900-afe5-11ea-8d99-fafccd907df6.png)

**Comment by ShockwaveNN** [comment]
Hi. Could you try to reproduce this problem with AppImage, deb or other installation method.
Is this actual for any of them, or only for flatpak?

**Comment by hanny00** [comment]
Hello, i will try it.

⁣BlueMail for Android herunterladen ​

**Comment by Flygrounder** [comment]
Tried .deb on the same system - works fine

**Comment by ShockwaveNN** [comment]
So, seems this issuea actual only for flatpaks
Please duplicate issue at, we cannot move issues between organization
https://github.com/flathub/org.onlyoffice.desktopeditors/issues

**Comment by Flygrounder** [comment]
It seems that this issue already exists there for a while.

[OnlyOffice only show only few selected folders in Open Document dialog](https://github.com/flathub/org.onlyoffice.desktopeditors/issues/6)

**Comment by ShockwaveNN** [comment]
@Flygrounder Yeah, i've seen one, but not sure it's the same, ok, in that case I'll close this issue here and leave issue at flatpak repo
