### ISSUE TITLE
Starting Onlyoffice always Creating Standard Templates

### ISSUE THREAD

**Issue by Axel-G** [ONLYOFFICE/DesktopEditors#416]
I have no template directory in my home directory.

When starting onlyoffice, the three standard templates for writer, calc and presentation are always created in the home directory.

Thats not nice ;)

**Comment by ShockwaveNN** [comment]
Seems like duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/355

**Comment by Axel-G** [comment]
duplicate of #355
