### ISSUE TITLE
ENH: Plugins store

### ISSUE THREAD

**Issue by gczark** [ONLYOFFICE/DesktopEditors#421]
One-stop place searching for plugins; showcase the "plugins available" and the "ability" of the app itself. Can also indicate if there are "existing" community of developers working on plugins.

**Comment by Rita-Bubnova** [comment]
Hello, @gczark.
It seems that [there ](https://www.onlyoffice.com/ru/app-directory.aspx) is what you need.

**Comment by gczark** [comment]
Nice and its quite few 👎, yet, its hard to find. Somehow its not indexed in the google search maybe because you need to search for "ONLYOFFICE App Directory" instead of  "ONLYOFFICE Plugins".

**Comment by Rita-Bubnova** [comment]
@gczark, thanks for your suggestions. We will work on making our store easier to find and maybe even easily accessed from the editors interface in future releases.

**Comment by ShockwaveNN** [comment]
I'm closing this issue, since plugin store exists, and this product is not related to DocumentEditors, it's a separate product and currently not finished
