### ISSUE TITLE
Show OnlyOffice Flatpak Version in "Open With" application list (Nautilus)

### ISSUE THREAD

**Issue by eganonoa** [ONLYOFFICE/DesktopEditors#425]
Hello,

I am using the latest flatpak version on OnlyOffice in Debian 10 Buster (Gnome). OnlyOffice is not presented in the list of applications when right-click to "open with" a file in Nautilus/Gnome Files. This does not happen in the .deb or snap versions.

To fix you need to add %f at the end of the Exec line in /var/lib/flatpak/exports/share/applications/org.onlyoffice.desktopeditors.desktop

After that everything works as expected. 

Thanks

**Comment by ShockwaveNN** [comment]
Hi, please report all flatpak issues at [official repo](https://github.com/flathub/org.onlyoffice.desktopeditors/issues)
I cannot move this issue to those repo

**Comment by eganonoa** [comment]
Done.
