### ISSUE TITLE
Arabic support

### ISSUE THREAD

**Issue by Ahmed-E-86** [ONLYOFFICE/DesktopEditors#433]
Arabic letters appear in your document editor as scrambled letters, so I don't think that this application supports Arabic language at all, so are you going to support Arabic?

### There are some points about Arabic that are important to know first:
- Arabic letters are written from the right to the left.
- Arabic letters are connected together, not separated like this word: اللغة العربية
- The Arabic numerals' system are 2 different systems: **western Arabic** which is used in **English**, and [Eastern Arabic numerals](https://en.wikipedia.org/wiki/Eastern_Arabic_numerals).
- **Special characters** can be added above the letters like in **French** to give a different pronunciation like this word: اَلْعَرَبِيَّةُ‎
More information can be found in this link >> https://en.wikipedia.org/wiki/Arabic_chat_alphabet

**Comment by ShockwaveNN** [comment]
Hi, thanks for your report 
There is alrady an issue of general support of RTL
https://github.com/ONLYOFFICE/DocumentServer/issues/19

I'll close this issue since any news or request of about Arabic should be posted at these issue
