### ISSUE TITLE
Column with numerical inputs as Chart X-axis.

### ISSUE THREAD

**Issue by christian-nils** [ONLYOFFICE/DesktopEditors#434]
**Do you want to request a *feature* or report a *bug*?**
Bug (but it might be seen as a feature request..)
**What is the current behavior?**
When you have a header for the X-axis values list, it is not possible to select that column as the x-axis (https://imgur.com/nrR7czc)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Have two columns of values

| Time | Value|
|---|---|
| 0 | 0|
|10|12|
|20 | 2|
2. Select the whole table and insert a Chart
3. You get https://imgur.com/nrR7czc

**What is the expected behavior?**
I would expect something like this https://imgur.com/HHe6Dwo (with the possibility to get the header as X-axis label, here it would be "Time")

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.6 (Linux)

Maybe there is actually a way to do it, sorry if it is already the case.

**Comment by Rita-Bubnova** [comment]
Hello, @christian-nils.

If I understand you correctly, you need to use a " XY (Scatter)" chart. 
Then change the chart settings: "Chart - Advanced Settings" window - > "Layout" section -> "Lines" - Straight -> button OK.

![Chart - Advanced Settings](https://user-images.githubusercontent.com/25282241/89792290-01e4bb00-db2d-11ea-86c9-c506f2871c51.png)

The chart is displayed as in the screenshot:

![XY (Scatter) chart](https://user-images.githubusercontent.com/25282241/89792208-e679b000-db2c-11ea-83fc-58af4a56ee24.png)

**Comment by christian-nils** [comment]
Hi @Rita-Bubnova 

Yes, this sounds very much like the right way! I guess I did not look properly in the documentation. Is there any way to have the Column header automatically set as the x-axis label? (Here "Time")

**Comment by Rita-Bubnova** [comment]
> Is there any way to have the Column header automatically set as the x-axis label? (Here "Time")

No, automatically displayed label "Y Axis".

**Comment by christian-nils** [comment]
Alright, thanks!
