### ISSUE TITLE
Cannot connect to nextcloud documentserver

### ISSUE THREAD

**Issue by kernie** [ONLYOFFICE/DesktopEditors#435]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
cannot connect to nextcloud documentserver
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Have a Nextcloud server v19.0.1 with a working documentserver (separate install) v5.6.2. When I want to connect the desktop editor to the cloud I get a time out (see image).
**What is the expected behavior?**
Connection to cloud service
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
DesktopEditor: 5.6 (403), MacOS latest

![Bildschirmfoto 2020-08-10 um 18 09 42](https://user-images.githubusercontent.com/23321751/89804608-b0402e80-db34-11ea-9c48-d187adc16a90.png)

**Comment by DenisDeeSign** [comment]
Hi, @kernie. Is your Nextcloud Server run with SSL without FQDN? If it so, you usually get an error when you try to open it from browser. ONLYOFFICE DesktopEditors is facing with the same error. You should run an application from Terminal with the flag below to avoid this error.
`/Applications/ONLYOFFICE.app/Contents/MacOS/ONLYOFFICE --ignore-certificate-errors`

**Comment by kernie** [comment]
@DenisDeeSign exactly. Thanks for pointing that out. I can connect now, but have another issue that I will describe in a new issue.

Thanks!
