### ISSUE TITLE
First tab is truncated when using system title bars.

### ISSUE THREAD

**Issue by PJSingh5000** [ONLYOFFICE/DesktopEditors#438]
**Do you want to request a *feature* or report a *bug*?**
Bug Report

**What is the current behavior?**
This bug occurs when using system title bars.
The text in the first tab, after the "ONLYOFFICE" tab, is always truncated.
This occurs for all document types (*.docx, *.xlsx, *.pptx)
For example, instead of "Document1.docx", only "ument1.docx" is visible in the tab.
Subsequent tabs appear fine and are not truncated.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Launch OnyOffice using `onlyoffice-desktopeditors --system-title-bar`

**What is the expected behavior?**
The first tab, after the "ONLYOFFICE" tab should not be truncated when using system title bars.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Version = 5.6.0-21
OS = Ubuntu 20.04
Display: HDPI 3840x2160px with 200% scaling
(Previous version of onlyoffice desktopeditors did not support system title bars; reference https://github.com/ONLYOFFICE/DesktopEditors/issues/271).

**Comment by Rita-Bubnova** [comment]
Hello, @PJSingh5000.
Thank you for report.
I can confirm - this is bug, issue 46103 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/desktop-apps/commit/40760e6905044838d62e1fde49bfc61bd51e3479, https://github.com/ONLYOFFICE/desktop-apps/commit/9e5d6f4d56695e74e87d27250348f5ec7b03d9db) in future major release.

**Comment by PJSingh5000** [comment]
Thank you.
I will test it once the release comes out.

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.

**Comment by PJSingh5000** [comment]
Fix confirmed.
Looks great.
Thank you!

**Comment by nauq302** [comment]
How can I turn off system title bar?

**Comment by ShockwaveNN** [comment]
@nauq302 System title bar disabled by default and enabled only by running `onlyoffice-desktopeditors --system-title-bar`

If you got some troubles - better create new issue
