### ISSUE TITLE
Namespace prefix new on cell is not defined

### ISSUE THREAD

**Issue by PJSingh5000** [ONLYOFFICE/DesktopEditors#439]
**Do you want to request a *feature* or report a *bug*?**
Bug Report

**What is the current behavior?**
Launching onlyoffice-desktopeditors from the command line outputs the following error:

    /usr/bin/onlyoffice-desktopeditors: 71: [: !=: unexpected operator
    namespace error : Namespace prefix new on cell is not defined
    <Settings><custom-title-bar></custom-title-bar><new:cell></new:cell><system-titl
                                                            ^

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Launch OnyOffice using `onlyoffice-desktopeditors`

**What is the expected behavior?**
The `namespace error` should not occur.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Version = 5.6.0-21
OS = Ubuntu 20.04

**Comment by PJSingh5000** [comment]
Issue not present in ONLYOFFICE Desktop Editors ver. 6.3.1.56 on Ubuntu 21.04.

**Comment by ShockwaveNN** [comment]
Sorry, seems we somehow missed your issue but fixed it )
