### ISSUE TITLE
Spell checking is falsely marking possessive nouns

### ISSUE THREAD

**Issue by redranamber** [ONLYOFFICE/DesktopEditors#44]
**Do you want to request a *feature* or report a *bug*?**
 Bug
**What is the current behavior?**
Many possessive nouns are being marked as spelled incorrectly with your English dictionary. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
For example, I wrote the word William's and it was highlighted with the suggestion to change to William.
**What is the expected behavior?**
It should recognize that adding "'s" to the end of a noun is a valid spelling.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I am using 4.3.2.320 on Windows 10 and haven't tried with any other version.

**Comment by ShockwaveNN** [comment]
This issue is closed, since seems issue is not actual. If not please comment at this issue
