### ISSUE TITLE
ONLYOFFICE doesn't display all typed text!

### ISSUE THREAD

**Issue by dlalinsp** [ONLYOFFICE/DesktopEditors#441]
**Do you want to request a *feature* or report a *bug*?** Bug.

**What is the current behavior?** It doesn't display the text that is being typed from time to time.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
While typing a document, ONLYOFFICE suddenly stops displaying the text that is being typed. It seems to happen randomly. I tested my keyboard in other applications and there was no issue with it.

**What is the expected behavior?**  It displays all that is typed.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

I am on Linux Mint 19.3. I only recently installed ONLYOFFICE v5.6.0 through Flathub.

**Comment by ShockwaveNN** [comment]
Hi, could you try to reproduce this problem on deb installation, not flatpak version

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
