### ISSUE TITLE
System fonts aren't accessible!

### ISSUE THREAD

**Issue by dlalinsp** [ONLYOFFICE/DesktopEditors#442]
**Do you want to request a *feature* or report a *bug*?** Bug.

**What is the current behavior?** I am able to use fonts that I have manually installed on the system but most of the system fonts don't show up under ONLYOFFICE.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Install ONLYOFFICE via Flathub.
2. Type some text and try to change its font to a known system font.
3. It doesn't show up in the drop-down menu for fonts.

**What is the expected behavior?**
ONLYOFFICE detects and is able to use all the fonts installed on a system.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I am on Linux Mint 19.3. I only recently installed ONLYOFFICE v5.6.0 through Flathub.

**Comment by ShockwaveNN** [comment]
Hi, this is flatpak specific issue
Duplicat of https://github.com/flathub/org.onlyoffice.desktopeditors/issues/2
