### ISSUE TITLE
Vertical alignment doesn't work as intended!

### ISSUE THREAD

**Issue by dlalinsp** [ONLYOFFICE/DesktopEditors#443]
**Do you want to request a *feature* or report a *bug*?** Bug.

**What is the current behavior?** When trying to change the vertical alignment of text in a table cell, the text is not aligned as intended.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create a document with a table in it.
2. Type some text in the table.
3. Attempt to change the vertical alignment.
4. The change doesn't occur or it doesn't occur as intended. (Eg. When trying to make the text align at the center of cell, it remains at the top or bottom.)

**What is the expected behavior?** ONLYOFFICE aligns the text as specified.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I am on Linux Mint 19.3. I only recently installed ONLYOFFICE v5.6.0 through Flathub.

**Comment by Rita-Bubnova** [comment]
Hello, @dlalinsp.
Could you attach file with problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by pat-githubber** [comment]
I think @ghost was looking for this feature to make the cells vertically centered:

<img width="793" height="656" alt="Image" src="https://github.com/user-attachments/assets/7a825ac4-3f90-46e0-b6f6-c6db92f0f6c8" />
