### ISSUE TITLE
Are there any restrictions on the use of "ONLYOFFICE Desktop Editors" in an organization?

### ISSUE THREAD

**Issue by mrkaban** [ONLYOFFICE/DesktopEditors#446]
Hello, are there any restrictions on the use of "ONLYOFFICE Desktop Editors" in an organization? For example, prohibiting commercial use? or a limit on the number of workstations?

I apologize for such a question, but one persistent site visitor persistently proves that there are such restrictions, so a developer's response is needed.

**Comment by ShockwaveNN** [comment]
Hi

We do not have any limits for using DesktopEditors in an organization.
Not for commercial use, nor for limit on the number of workstations

**Comment by mrkaban** [comment]
Thank you very much for your answer!

**Comment by ShockwaveNN** [comment]
> persistent site visitor persistently proves that there are such restrictions, so a developer's response is needed.

Maybe there is a confusion with DocumentServer, since we have some limits in this product p, you can see them [here](https://github.com/ONLYOFFICE/DocumentServer#onlyoffice-document-server-editions)
