### ISSUE TITLE
Debian 10 XFCE, 1920x1080, large interface

### ISSUE THREAD

**Issue by SCratORS** [ONLYOFFICE/DesktopEditors#449]
Interface onlyoffice default scaled 2x on 1080p in debian 10 xfce. it's very large
use --forced-scale=1 fix it.

**Comment by ShockwaveNN** [comment]
Hi, could you provide information about real screen size of your display, if it's not very big, this issue may be duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/217

**Comment by SCratORS** [comment]
14" 1920х1080.
Yes, it's duplicate #217

**Comment by ShockwaveNN** [comment]
In that case I close this issue
