### ISSUE TITLE
[Feature request] Collaborative editing over LAN

### ISSUE THREAD

**Issue by Darthagnon** [ONLYOFFICE/DesktopEditors#456]
Seeing as server components do exist for OnlyOffice, I was wondering if a simplified version could be integrated into the desktop editors, allowing users to open editing to other users on the LAN?

**Comment by LuckySpecialist** [comment]
Hi @Darthagnon,
Collaboration with documents requires a shared document server that manages file access and collaborative editing. You can install a [ONLYOFFICE Docs](https://github.com/ONLYOFFICE/DocumentServer) in your LAN and connect to this portal using [Desktop  Editors](https://github.com/ONLYOFFICE/DesktopEditors).
There is no other option for collaboration in the documents.
