### ISSUE TITLE
The .deb and appimage versions are not updated on Ubuntu 20.04

### ISSUE THREAD

**Issue by maravento** [ONLYOFFICE/DesktopEditors#458]
Possible BUG
I have version 5.6.0.21 (.deb and appimage) on Ubuntu 20.04. Version 5.6.4.20 has already been released and the app does not request an update
In windows 10 it does, but not in Ubuntu 20.04

Proposed Solution:
The least for the .deb version could create a PPA for Ubuntu 20.04 LTS.

**Comment by ShockwaveNN** [comment]
Moved this issue to corresponding repo

1. Just checked ONLYOFFICE default debian repo and there is 5.6.4-20
![image](https://user-images.githubusercontent.com/668524/92748188-90976280-f38d-11ea-898a-4db6189aed43.png)

Which repo are you using?

2. We always release AppImage version some time later, after main release, so just wait for it

**Comment by maravento** [comment]
> Moved this issue to corresponding repo
> 
> 1. Just checked ONLYOFFICE default debian repo and there is 5.6.4-20
>    ![image](https://user-images.githubusercontent.com/668524/92748188-90976280-f38d-11ea-898a-4db6189aed43.png)
> 
> Which repo are you using?
> 
> 1. We always release AppImage version some time later, after main release, so just wait for it

No. This command doesn't work in ubuntu mate 20.04.2
![Captura de pantalla -2020-09-10 09-59-00](https://user-images.githubusercontent.com/14880802/92750104-5c4f8200-f34c-11ea-9dbb-c4d51bcd14e6.png)

**Comment by ShockwaveNN** [comment]
Are you run `sudo apt -y update` before that?

What is content of 

`cat /etc/apt/sources.list | grep onlyoffice`

![image](https://user-images.githubusercontent.com/668524/92752101-4a440280-f391-11ea-87d2-8a161ddc7e34.png)

**Comment by maravento** [comment]
According to https://helpcenter.onlyoffice.com/desktop/documents/linux/installation-ubuntu.aspx
This repo `deb https://download.onlyoffice.com/repo/debian squeeze main` is for debian, Nowhere in this document does it say that this repo is compatible with Ubuntu. That's why i didn't include it

**Comment by ShockwaveNN** [comment]
> ok fix it

Sorry, what?

**Comment by maravento** [comment]
Solved
![Captura de pantalla -2020-09-10 10-19-02](https://user-images.githubusercontent.com/14880802/92753017-147e2a00-f34f-11ea-94cc-1037ceca0c41.png)
