### ISSUE TITLE
functions not working properly?

### ISSUE THREAD

**Issue by PedroMarquetti** [ONLYOFFICE/DesktopEditors#460]
**Do you want to request a *feature* or report a *bug*?**
BUG REPORT 
(also a want a feature. I have low vision, and the UI is soooo small, not even changing the OS' scaling factor changes)

**What is the current behavior?**
i've created a function (IF statement) on my sheet, every time I close it and reopen the function brakes and says "!VALUE" 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

i created an if statement 
=IF(F6>=126,"diabete",IF(F6<=60,"hipo","normal"))
it works, but when i close and reopen the doc, it appears as !VALUE

**What is the expected behavior?**
showing "diabetes","normal" or "hipo"
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

version 5.6.0.21 running on windows 10

**Comment by Rita-Bubnova** [comment]
Hello, @PedroMarquetti.
What regional settings are you using?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
