### ISSUE TITLE
[Bug] Custom font colors are not saved in styles (Normal/Header/etc)

### ISSUE THREAD

**Issue by Fmstrat** [ONLYOFFICE/DesktopEditors#461]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Style colors are not saved when updated to a custom font color.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Start a new document
- Type "Test Header"
- Make "Test Header" a `Header 1` style
- Highlight "Test Header" and change the color to a custom color not already defined in the theme or default color set  via `Add new custom color`
- Right click on `Header 1` style and choose `Update from selection`
- The `Header 1` style will reflect the color change
- Save the document
- Close the document
- Reopen the document
- The color of `Header 1` is back to black

**What is the expected behavior?**
When reopening the document, `Header 1` would retain the specified color just like if a standard or theme color was used.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Linux, ONLYOFFICE Desktop Editors version 5.6.0.21

**Comment by Fmstrat** [comment]
Demo:
![obug](https://user-images.githubusercontent.com/971474/93249306-17b65300-f75f-11ea-86c3-d7e27eb9da24.gif)

**Comment by Rita-Bubnova** [comment]
Hello, @Fmstrat.
Thank you for detailed report.
I can confirm - this is bug, issue 46579 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/2cadd82348a83e994a3f75a875ea4ad0bc9ceb5c, https://github.com/ONLYOFFICE/sdkjs/commit/3096283a2435a26990361c80290b476e1dec8790) in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.
