### ISSUE TITLE
OnlyOffice does not exit correctly from SlideShow

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#462]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
On Linux, OnlyOffice Presentation stays in FullScreen after a SlideShow

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- On Linux, play a slidehow and exit
=> OnlyOffice stays in FullScreen, there is no button to close or minimize the window

**What is the expected behavior?**
OnlyOffice should come back in a window mode, where you can resize your window or minimize it

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.6.4 on Debian 11 Bullseye

**Comment by Rita-Bubnova** [comment]
Duplicate #463.
