### ISSUE TITLE
x86 linux binary request

### ISSUE THREAD

**Issue by Askmewho** [ONLYOFFICE/DesktopEditors#464]
Hi, sorry to utilize this channel for my request. the thing is than Onlyoffice doesnt support ARM Linux but we have a very decent linux x86 emulator, could you supply a linux x86 binary to test it?

thanks anyway. and hope there is an armhf/aarch64 appimage sooner or later :)

**Comment by ShockwaveNN** [comment]
Hi, I don't think we are planning to add x86 binary.
But you could try to compile it by yourself using our [build_tools](https://github.com/ONLYOFFICE/build_tools/)
But newer tested this variant

> and hope there is an armhf/aarch64 appimage sooner or later :)

Yeah, we hope to make this in future, but I cannot give any estimates

**Comment by Askmewho** [comment]
Thanks. Closing
