### ISSUE TITLE
No Paste Special

### ISSUE THREAD

**Issue by wd5gnr** [ONLYOFFICE/DesktopEditors#468]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Paste takes formatted text no matter what. Need a paste special or paste plain text. Workaround: open editor (e.g., emacs, Kate), paste into there. Copy again. Then paste into OnlyOffice.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

**Comment by Rita-Bubnova** [comment]
Duplicate https://github.com/ONLYOFFICE/DesktopEditors/issues/248.
