### ISSUE TITLE
When using ods file format, division formula =cell1/cell2 becames =#NAME\? when you reopen the file

### ISSUE THREAD

**Issue by marekmarecki** [ONLYOFFICE/DesktopEditors#472]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

ODS version of file seems to break division formula. Problem occurs when you try to reopen the file (at the moment of creating and saving the file, everything seems ok).

Picture 1 (1. create xlsx file, 2. put simple formula, 3. save and close the editor 4. open the file again):
![image](https://user-images.githubusercontent.com/776138/94923582-5fa5db80-04bc-11eb-9ff4-62121435777d.png)

Picture 2 (1. create ods file, 2. put the same formula, 3. save and close the editor 4. open the file again):
![image](https://user-images.githubusercontent.com/776138/94923600-67fe1680-04bc-11eb-93fd-467a1968ac06.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open the xlsx file that I attached (or create simple file where you put some value in two cells and divide them in third cell with _=cell1/cell2_ formula),
2. Save it as ods file and close the editor,
3. Open the ods file and observe the result in formula field. Formula became corrupted: _=#NAME\?_

**What is the expected behavior?**

Formula _=cell1/cell2_ should not be corrupted after reopening the ods file format. **Xlsx format behaves ok.**

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

OS: Ubuntu 20.04.1 (confirmed on a fresh VM in addition to my main system)
snap version of DesktopEditors: 5.6.4 (revision 46)
I do not know if it worked OK in the past since I did not use the software for that long.

**Comment by marekmarecki** [comment]
[Book1.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/5318097/Book1.xlsx)

**Comment by Rita-Bubnova** [comment]
Hello, @marekmarecki.
Thank you  for detailed report.
This issue fixed in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.
