### ISSUE TITLE
/usr/bin/desktopeditors typo

### ISSUE THREAD

**Issue by wd5gnr** [ONLYOFFICE/DesktopEditors#474]
70   │ check_templates() {
  71   │   if [ $1 != "--new-document-templates" ]; then

Needs to be:

  70   │ check_templates() {
  71   │   if [ "$1" != "--new-document-templates" ]; then

**Comment by ShockwaveNN** [comment]
Hi, thank you

This issue is already fixed via https://github.com/ONLYOFFICE/desktop-apps/pull/165 and waiting to be released as v6.0

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.
