### ISSUE TITLE
[feature] Support Seafile cloud connection

### ISSUE THREAD

**Issue by Ealhad** [ONLYOFFICE/DesktopEditors#477]
[Seafile](https://www.seafile.com) supports online editing with OnlyOffice, is there any plan to add it to the list of connectable clouds alongside OwnCloud and NextCloud?

Nice work in any case.

**Comment by maxkadushkin** [comment]
we have some talks with Seafile conterpats by now. i think it'll be available in closest releases

**Comment by JeanLouPtflbx** [comment]
Hi, 
Seafile connector works fine with 6.2, I just miss a kind of bookmark feature for cloud connection as I used to connect to many seafile / nextCloud servers.

**Comment by ShockwaveNN** [comment]
Sorry, seems we forgot to close this issue - we implemented Seafile support in DesktopEditors v6.2

But for @JeanLouPtflbx 

I think it's better to create a new issue and describe your problem in little bit more details
