### ISSUE TITLE
How to export image from document?

### ISSUE THREAD

**Issue by zaaack** [ONLYOFFICE/DesktopEditors#48]

**Comment by vatterspun** [comment]
Could you give a little more detail on what you're looking for?  Do you want to save an image present in a document?  Export your document to an image?

From what I can tell, OnlyOffice doesn't currently have the ability to save an individual image.  I have a few workarounds but they require other programs:

* Almost any document format can be opened in LibreOffice.  From there you should be able to right-click on the image and click Save
* RLVision has an excellent Windows program for exporting all images from Microsoft Office files
* If it's a DOCX file, rename it to end with .ZIP and use an unzip program to extract all files.  Then navigate to _word\media\_ folder

**Comment by zaaack** [comment]
Yes, I mean save images present in document, just like right click on libreoffice. And I hope this feature could be add to only office.

**Comment by maxkadushkin** [comment]
there are no options for that in current version

**Comment by listenerri** [comment]
I would also like to be able to right click to save images locally ; )

It would be nice to be able to copy images directly to the clipboard in the usual way, instead of copying some image data in text format.

**Comment by Rita-Bubnova** [comment]
Thank you for enhancement.
This is know bug 19262 in our private issue tracker. 

> It would be nice to be able to copy images directly to the clipboard in the usual way, instead of copying some image data in text format.

@listenerri, can you create separate issue and describe in more detail?

**Comment by listenerri** [comment]
> Thank you for enhancement.
> This is know bug 19262 in our private issue tracker.
> 
> > It would be nice to be able to copy images directly to the clipboard in the usual way, instead of copying some image data in text format.
> 
> @listenerri, can you create separate issue and describe in more detail?

I will do this.

**Comment by listenerri** [comment]
@Rita-Bubnova 
Oh, I may have made a mistake.
The problem with copying images to the clipboard occurs in my NextCloud service, where I use the OnlyOffice plugin.
Sorry about this.

**Comment by unclev** [comment]
An image copied within Desktop Editors app can be pasted into an OnlyOffice document, even into new one, but this picture does not go to the system clipboard. The same for OnlyOffice on Nextcloud.
Having no capability for exporting embedded images into system is frustrating.
I can imaging security restrictions of interacting with the system clipboard, so adding "Export" option (acting as "Download") could probably be a straightforward solution.

**Comment by danielebrox** [comment]
Is there still no such option? It would be very useful!

**Comment by Rita-Bubnova** [comment]
This issue is fixed, I check it in version 7.4.0.

**Comment by DenisDeeSign** [comment]
I'm close this issue since the feature is implemented. Feel free to create a new one if you got further questions.

**Comment by CorneliusCornbread** [comment]
How _does_ one actually extract an image from a document, there seems to be no documentation or help on how this feature works.
