### ISSUE TITLE
Files with diacritics (such as `ě š č ř ž ý á í é ú ů ...`) in the file name won't open 

### ISSUE THREAD

**Issue by jiriks74** [ONLYOFFICE/DesktopEditors#480]
**Do you want to request a *feature* or report a *bug*?**
* Report a bug

**What is the current behavior?**
* When I open file which name includes diacritics the onlyoffice window flashes a few times and won't open anything

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Save a office file that includes some lettert with diacritics (you can copypaste: `ě š č ř ž ý á í é ú ů`) and then try to open it

**What is the expected behavior?**
* Program opens the document file

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
* I use `archlinux` and `ONLYOFFICE Desktop Editors version 5.6.4.20`

**Comment by matveevms** [comment]
Hi, @jiriks74 
Please clarify which package? snap or appimage?

**Comment by jiriks74** [comment]
> Hi, @jiriks74 
> Please clarify which package? snap or appimage?

Bin package from aur, appimage, flatpak

**Comment by matveevms** [comment]
You using kde shell?

**Comment by jiriks74** [comment]
> You using kde shell?
I'm running awesome window manager and I have kde desktop installed

**Comment by jiriks74** [comment]
> > You using kde shell?

I'm running awesome window manager and I have kde desktop installed

**Comment by jiriks74** [comment]
> You using kde shell?
I'm running awesome window manager and I have kde desktop installed
