### ISSUE TITLE
Bug: Huge PDF file as a output

### ISSUE THREAD

**Issue by pktiuk** [ONLYOFFICE/DesktopEditors#481]
**What is the current behavior?**
I wanted to generate PDF from file:
[2020 09 23_zal_05_Wniosek_Stypendium Rektora_2020.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/5378774/2020.09.23_zal_05_Wniosek_Stypendium.Rektora_2020.docx) (approx 40kB)
To do it I used print to file option.  
And I got huge (about 20 MB) PDF file.

**What is the expected behavior?**
Generate PDS in reasonable size.

**Version**
Ubuntu 20.04
ONLYOFFICE Desktop Editors ver. 5.6.4.20

**Comment by Rita-Bubnova** [comment]
Hello, @pktiuk.
We know about this, but so far it will remain as is.
We are thinking about a solution to this problem, but we have no ETA.

**Comment by pktiuk** [comment]
I don't know how, but you have fixed this.

With `ONLYOFFICE Desktop Editors ver. 6.0.2.10` output file is now only 125.2 kB

**Comment by levirs565** [comment]
You can use Save As PDF instead of using Print. It result smaller PDF file size than using Print.

**Comment by Rita-Bubnova** [comment]
I create issue 48584 in our private issue tracker for discuss with our dev team.

**Comment by eldelacajita** [comment]
Just to add to the arguments, using Save As PDF does work well for text documents, but _not_ for spreadsheets, as it ignores the format and pagination settings.

**Comment by Rita-Bubnova** [comment]
> Just to add to the arguments, using Save As PDF does work well for text documents, but _not_ for spreadsheets, as it ignores the format and pagination settings.

Sorry, this is issue about when printing to PDF, we use a raster and the file size increases.

The issue with ignoring settings when save in PFD is discuses in https://github.com/ONLYOFFICE/DesktopEditors/issues/560.

**Comment by eldelacajita** [comment]
Totally understood. Just pointing out that Save As PDF is not always a feasible workaround as others are suggesting.

**Comment by Haabda** [comment]
If **Save as PDF** would allow me to save only the current worksheet, then it might be a viable workaround. However, **Save as PDF** is not a workaround for me at this time because it saves every worksheet.

I am having a very hard time getting my staff to accept ONLYOFFICE as a replacement to Excel because of the way is rasterizes printing to PDF.

**Comment by Rita-Bubnova** [comment]
@Haabda, thank you for the details.

> If Save as PDF would allow me to save only the current worksheet, then it might be a viable workaround. However, Save as PDF is not a workaround for me at this time because it saves every worksheet.

But this is another problem - issue 34914 in our private issue tracker.

**Comment by jbergengh** [comment]
Printing a document also sends a huge amount of data to the printer (the same 20 MB) resulting in over a minute and a half to print just two pages on my printer.  The workaround is to save to a PDF and print the PDF which is ridiculous.  Any chance this 2 year old bug will be fixed?

**Comment by ShockwaveNN** [comment]
Sorry, but fix of this bug is complicated and we cannot provide any specific time frame

**Comment by matveevms** [comment]
This issue should be fixed in version 7.2.

Feel free to comment or reopen it if you got further questions
