### ISSUE TITLE
Incorrect display on Manjaro GNOME

### ISSUE THREAD

**Issue by baptiste0928** [ONLYOFFICE/DesktopEditors#487]
Hello ! I recently installed Manjaro 20.1 GNOME Edition on a laptop, and I want to use OnlyOffice on it. I downloaded it from the official Manjaro repositories (version 5.6.4-1). Unfortunately, **the application displays badly**, and is therefore unusable.

![Capture d’écran de 2020-10-15 20-50-17](https://user-images.githubusercontent.com/22115890/96173829-b5e93480-0f28-11eb-8772-a6432365aad0.png)

Here is more precise information about my system: 

![Capture d’écran de 2020-10-15 20-50-44](https://user-images.githubusercontent.com/22115890/96173955-e7620000-0f28-11eb-99e7-5fbd435311f8.png)

I hope you can help me solve this problem, I would really like to be able to use OnlyOffice on this machine. 😄 
*Feel free to ask me more details about the problem if needed.*

**Comment by ShockwaveNN** [comment]
Hi, could you check snap, flatpak or AppImage version is the problem is same?

We got similar issue, but it's for hidpi screens, but your is just FullHD

**Comment by baptiste0928** [comment]
Same problem using the Flatpak version :confused:

**Comment by ShockwaveNN** [comment]
@matveevms Could you take a look at this problem?

**Comment by baptiste0928** [comment]
Any updates on that?

**Comment by matveevms** [comment]
Hello @baptiste0928
I'm sorry for the wait. Which version of flatpak are you using? On my machine, with flatpak version 5.6.4.20, this problem does not recur

**Comment by baptiste0928** [comment]
Hello @matveevms
I have just tested again with the version 6.0.0 from Flatpak, and the display works normally! Thank you for your time on this problem.
