### ISSUE TITLE
OnlyOffice 6.0 crashes when you try add an unfamiliar word to a dictionary

### ISSUE THREAD

**Issue by kompilainenn** [ONLYOFFICE/DesktopEditors#490]
Create a new text document
Enter some strange word, for example "охуеть"
OO will underline it with a red line
Right click on that word
Select Add to dictionary
OO crashes

**Comment by ShockwaveNN** [comment]
Works fine for me on Ubuntu 20.04 and deb

Which OS and distribution method are you using?

**Comment by kompilainenn** [comment]
> Works fine for me on Ubuntu 20.04 and deb
> 
> Which OS and distribution method are you using?

Windows 7 and latest exe from github

**Comment by DenisDeeSign** [comment]
Hi @kompilainenn.
Could you specify what OS version you are using? A simple way to do that make a request "winver".
Also please attach a screenshot of error at Computer Management > System Tools > Event viever > Windows Log > Application.

**Comment by kompilainenn** [comment]
![изображение](https://user-images.githubusercontent.com/9006514/96248953-1de55c80-0fb5-11eb-9523-290eeaa846e6.png)

![изображение](https://user-images.githubusercontent.com/9006514/96249022-36ee0d80-0fb5-11eb-8209-629d0153b5a1.png)

**Comment by K0R0L** [comment]
Don't use such words in bugs. This is not a place for super humor.

**Comment by kompilainenn** [comment]
> Don't use such words in bugs. This is not a place for super humor.

You can use any another word for repro the crash. I don't think if you just close the issue, then the crash will disappeare itself by some magic.
I wrote in first post that word just because I found the problem with it.

**Comment by kompilainenn** [comment]
Just for your info: I can't repor it in ONLYOFFICE Desktop Editors версия 6.3.1.56

PS: I hope your crown is still on your head, man
