### ISSUE TITLE
Core dumped at launch in prebuild binary from .tar.gz archive and .rpm package

### ISSUE THREAD

**Issue by AngryPenguinPL** [ONLYOFFICE/DesktopEditors#492]
I have not been able to start OnlyOffice Desktop editior for a long time. I used to run an application from the .tar.gz package, but for some time (several months or a year) I can't do it.
The same happens with the .rpm package - I can install it, but when I start I have the same error as with onlyoffice-desktopeditors-x64.tar.gz

```
desktopeditors/DesktopEditors 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
Aborted (Core dumped)
```
Of course, Qt is installed.
I am using Linux OpenMandriva Cooker with:
RPM / DNF
QT: 5.15.1
Plasma: 5.20.0
K Frameworks: 5.75.0

Worth to add, only way to use OnlyOffice is Appimage package - and this packkage work fine for me, but unfortunately latest version 6.0.0 was not released as Appimage.

**Comment by ShockwaveNN** [comment]
@matveevms Please take a look

**Comment by maxkadushkin** [comment]
@AngryPenguinPL try to launch the app like
desktopeditors/LD_LIBRARY_PATH=./ ./DesktopEditors

**Comment by AngryPenguinPL** [comment]
> @AngryPenguinPL try to launch the app like
> desktopeditors/LD_LIBRARY_PATH=./ ./DesktopEditors

Still same issue.

**Comment by matveevms** [comment]
Hi, @AngryPenguinPL 
I'm sorry for waiting so long. Appimage version 6.0.0 is now available. You can use on your system. Unfortunately, we do not guarantee stable operation of the rpm version on the OpenMandriva Cooker system, as it is a unstable version

**Comment by AngryPenguinPL** [comment]
@matveevms Hi.
Appimage is still at version 5.6.4.

Anyway, I know what issues can cause .rpm especially when it's built for another system (I think you're building for Fedora / RedHat). But .tar.gz should works fine or at least start complaining about missing libraries.
In this case, it looks like a problem with some QT compatibility - or something like that.

As for the system, I also tried on stable versions, the same problem everywhere.

**Comment by matveevms** [comment]
Appimage is currently the only portable version of the OnlyOffice application. In this case, I think we can close this issue.
