### ISSUE TITLE
OnlyOffice doesn't work on MacBook (early 2016) says “ONLYOFFICE” is damaged and can’t be opened.

### ISSUE THREAD

**Issue by timemaster5** [ONLYOFFICE/DesktopEditors#495]
**Do you want to request a *feature* or report a *bug*?**
Seems like a bug

**What is the current behavior?**
Can't run OnlyOffice at all. When I open the app, mac says:
"ONLYOFFICE" is damaged and can't be opened. You should move it to the Bin.

When I try to turn run the binary from a terminal:
cd /Applications/ONLYOFFICE.app/Contents/MacOS
./ONLYOFFICE

it does the same thing, in the console I get only this line:
zsh: killed     ./ONLYOFFICE

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Described above

**What is the expected behavior?**
The application should start instead:)

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

On this mac, I tried version 5.6 and 6 with the same result. It is a fresh installation of MacOS Catalina, no hardware issues, all other software work ok.

**Comment by ShockwaveNN** [comment]
@DenisDeeSign please, take a look

**Comment by timemaster5** [comment]
It may be a compiler issue or something like that. I use homebrew to install OnlyOffice and have multiple Macs so I can compare. I tried another machine, which is Intel Core i7, and there everything works. An OS version is the same, and the only difference is architecture. This bug report is for Intel Core m7.

**Comment by ShockwaveNN** [comment]
Sorry, we got no macs with Core m7 at out access

> I use homebrew to install OnlyOffice

Could you describe this in more details? You are not using our official DMG? I far as I know we do not provide homebrew version for mac

**Comment by timemaster5** [comment]
Oh great, we have a progress. I tried to download a dmg manually, and it works well!

Homebrew is just an automatic installer. It currently uses this package http://download.onlyoffice.com/install/desktop/editors/mac/updates/onlyoffice/ONLYOFFICE-6.0.zip
referenced from this file
https://download.onlyoffice.com/install/desktop/editors/mac/onlyoffice.xml

And this doesn't work on my MacBook, it works on the other machines.
As a workaround I can use DMG version, that's perfectly fine. 

I would expect the same binaries released in this .zip and in .dmg, which might be the only problem then.

**Comment by ShockwaveNN** [comment]
As far as I know (I do not not have a mac at all, so just assuming) this package is 
http://download.onlyoffice.com/install/desktop/editors/mac/updates/onlyoffice/ONLYOFFICE-6.0.zip
for autoupdater, not for direct use

Is there any public link for homebrew installer script? I think it was made from someone else and it's better to contact them

**Comment by timemaster5** [comment]
Here is the link: https://formulae.brew.sh/cask/onlyoffice

I will reference this issue there, so they know.

**Comment by ShockwaveNN** [comment]
I've just asked our Mac Dev team and they said that 

> homebrew is not our official way to distribute our product. And we do not support homebrew scripts

So we glad to help you if you got any trouble with dmg version, but for homebrew you better contact authors of this script

**Comment by timemaster5** [comment]
Will do, thank you
