### ISSUE TITLE
Desktop Editor v6.0 on macOS slow

### ISSUE THREAD

**Issue by maghog** [ONLYOFFICE/DesktopEditors#498]
Hi,

Upgraded to Desktop Editor v6.0 on macOS Catalina v10.15.7.

After upgrade OO is extremely slow. It takes approx 1 min to create an empty local document. Is this an known problem?

Regards,
Magnus

**Comment by ShockwaveNN** [comment]
Sorry, seems that we missed this issue

And I think since 2 years are passed this issue should be resolved, I'll close it
But feel free to comment if this issue is still actual
