### ISSUE TITLE
[Feature request] Use column as data-label in scatter and line chart.

### ISSUE THREAD

**Issue by asaaditya8** [ONLYOFFICE/DesktopEditors#499]
**Do you want to request a *feature* or report a *bug*?**
Request a feature.
**What is the current behavior?**
If the column for labels is not selected then the graph is correct. But if it is then the values are plotted against row numbers.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not a bug.
**What is the expected behavior?**
To be able to use separate column for data labels.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Editors version 6.0.0.110, Ubuntu 18.04. I don't know.

**Comment by VladimirProkofiev52** [comment]
Hello! @asaaditya8 
I noticed that you are using the editor version: 6.0.0.110.
The requested function is present in the new editor version 7.4.1.36.

1) Update the editor to version: 7.4.1.36.
2) Enter the data in the table (column with labels and column with data).
3) Select both columns and create a pie chart.
4) In the "Charts - advanced settings" menu in the "layout" section, you can select the location of the data label.

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/86404945/a2b83b97-a500-4ac7-a2cf-54ec86aa585f)

Is this what you expected to see?

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
