### ISSUE TITLE
FR: Allow individual/custom number formats (e.g. m²)

### ISSUE THREAD

**Issue by totti4ever** [ONLYOFFICE/DesktopEditors#503]
**Do you want to request a *feature* or report a *bug*?**
*Feature*

**What is the current behavior?**
There is a long list of available custom formats, and when opening an excel file it even reads other custom formats - but I cannot define one myself.

**What is the expected behavior?**
Extend the list or overwrite the content of the custom number format setting

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
macOS 6.0 (412)

**Comment by Rita-Bubnova** [comment]
Hello, @totti4ever.
Do I understand correctly that you want to set your custom format (see screenshot)?
![image](https://user-images.githubusercontent.com/25282241/98519755-43971600-2282-11eb-8a4b-112d4117b4c4.png)

**Comment by totti4ever** [comment]
Yes, I'd like to extend that list or just enter an own syntax like `###m²`

**Comment by Rita-Bubnova** [comment]
This problem reproduces in Document Server.

Duplicate of #https://github.com/ONLYOFFICE/DocumentServer/issues/385.

**Comment by totti4ever** [comment]
oooups, thanks!
