### ISSUE TITLE
[feature request] option for logarithmic scale 

### ISSUE THREAD

**Issue by dabos1** [ONLYOFFICE/DesktopEditors#507]
**Do you want to request a *feature* or report a *bug*?**
feature request 

**What is the current behavior?**

For now its only possible to scale a XY-shart in linear scale. But I would like to have an option to scale it in logarithmic scale too.  

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Not a bug.

**What is the expected behavior?**

An option to choose between linear and logarithmic scale. 

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

I use Ubuntu 20.10 and with Onlyoffice version 6.0.0.110

**Comment by VladimirProkofiev52** [comment]
Hello @dabos1
We have released a new version of the editor 7.4.1. You can select the Logarithmic Scale setting in the "Charts - Advanced Settings" menu.
Thanks for your report.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
