### ISSUE TITLE
Right click not working

### ISSUE THREAD

**Issue by memesforlife1** [ONLYOFFICE/DesktopEditors#508]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Right click context menu not working
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just right click in onlyoffice
**What is the expected behavior?**
that it shows the context menu
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Linux Version 6.0.1.32

**Comment by Rita-Bubnova** [comment]
Hello, @memesforlife1.
Which OS are you using? 
I checked for Kubuntu 18.04, ONLYOFFICE Desktop Editors version 6.0.1.32 and it works.

**Comment by memesforlife1** [comment]
Fedora 33

**Comment by XDmitryK** [comment]
I checked it on the pre-release version(6.1.0-90) the problem does not recur

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
