### ISSUE TITLE
Images in presentations saved as PDFs render incorrectly

### ISSUE THREAD

**Issue by alexburlton-sonocent** [ONLYOFFICE/DesktopEditors#509]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When saving a presentation as a PDF, images are saved in a way which makes them render strangely in other software.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Replication steps:

1) Create a presentation in OnlyOffice, and add a JPG image. 
2) Save the presentation as a PDF.
3) Observe that viewing the PDF in various other pieces of software only shows the bottom corner of the image. This includes file preview in Slack, and rendering in a browser via [pdf-js](https://github.com/mozilla/pdf.js). 

I believe this to be an OnlyOffice bug, because exporting the PDF from something else like LibreOffice works fine, and the rendering problem is showing up in multiple pieces of software. 

I've uploaded a minimal example, including:

 - A single-slide presentation file, created in OnlyOffice
 - A broken PDF file, generated by saving as PDF from OnlyOffice
 - An alternate PDF file, generated by saving as PDF from LibreOffice
 - A screenshot from Slack, showing how the OnlyOffice PDF is rendered incorrectly (LibreOffice one works fine)

[cookie.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/5545794/cookie.pptx)
[cookie.pdf](https://github.com/ONLYOFFICE/DesktopEditors/files/5545793/cookie.pdf)
[cookie-libre-office.pdf](https://github.com/ONLYOFFICE/DesktopEditors/files/5545827/cookie-libre-office.pdf)
![slack preview](https://user-images.githubusercontent.com/57534485/99245108-f58e8f00-27fa-11eb-948f-a857233a7cc4.png)

**What is the expected behavior?**

The image renders as in the LibreOffice example.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

ONLYOFFICE Desktop Editors version 6.0.0.110 on Ubuntu 18.04

**Comment by Rita-Bubnova** [comment]
Hello, @alexburlton-sonocent.
For understanding: I open the cookie.pptx file in the ONLYOFFICE Desktop Editors -> Save as PDF -> open PDF file [here](https://mozilla.github.io/pdf.js/web/viewer.html). 
The image is displayed correctly.
Is that correct?

Also I tried to open your files (`cookie.pdf` and `cookie-libre-office.pdf`) [here](https://mozilla.github.io/pdf.js/web/viewer.html) (browsers Chrome 87.0.4280.66 and Firefox 81.0.1). Images are displayed correctly.

I am using Windows 10, ONLYOFFICE Desktop Editors version 6.0.1.32.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
