### ISSUE TITLE
Launch Issues

### ISSUE THREAD

**Issue by JGH1000** [ONLYOFFICE/DesktopEditors#51]
I have noticed several small issues when launching OnlyOffice on Elementary OS (which I have also seen on other OS). Would be great if they could be addressed!

1) Then I launch a new document, no matter if half or full size, the page is not centered or visible in full. The only way to fix it is by maximizing since the bottom panel is missing.

2) The bottom panel is missing and can only be recover by maximizing and then changing the size of the panel.

![screenshot from 2017-06-27 14 34 48](https://user-images.githubusercontent.com/27884805/27572338-53f5d272-5b46-11e7-97fe-11fec6ac24f9.png)

3) The top panel items are not visible when the editor is taking half screen, and there is no way to scroll to them (heading styles, view setting buttons etc).

4) The side panel with Line Spacing and Paragraph Spacing cannot be turned off and in a half screen mode this takes too much screen space.

![screenshot from 2017-06-27 14 36 49](https://user-images.githubusercontent.com/27884805/27572342-57dbe1a6-5b46-11e7-9998-57727661078c.png)

Small issues and the suite is otherwise fantastic so many thanks for all your work.

**Comment by JGH1000** [comment]
Guess I will close it, no reply after a month. Hope it will be addressed at some point!

**Comment by ShockwaveNN** [comment]
@JGH1000 Hi there, sorry we missed your issue. Can you tell version of DekstopEditors and Resolution of each of your display.

**Comment by JGH1000** [comment]
No worries! The bug is still there with 4.4.1.338 and I have a 4K 27 inch display. FYI point 4 is solved in the new version. Not sure if related but those are the errors I get while launching OnlyOffice.

Gtk-Message: Failed to load module "pantheon-filechooser-module"

(DesktopEditors:31915): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(DesktopEditors:31915): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(DesktopEditors:31915): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(DesktopEditors:31915): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
[0810/174602:ERROR:browser_main_loop.cc(219)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

Thanks for looking into this!

**Comment by ShockwaveNN** [comment]
@JGH1000 Thank. We aware of issues with 4K, but currently have no perfect solution for your problems. You can try force scale 1x (as metions in [this](https://github.com/ONLYOFFICE/DesktopEditors/issues/53#issuecomment-318654393) comment, but interface will be smaller

**Comment by JGH1000** [comment]
Ah I see, other tickets are open regarding the HiDPI issues so I will follow them. Thanks for replying and keep up the great work!
