### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by bphd** [ONLYOFFICE/DesktopEditors#514]
**Do you want to request a *feature* or report a bug?**

**What is the current behavior?**

White, all white, eyes strain everywhere

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Open a document, or even the software and BAM, light at profusion

**What is the expected behavior?**

An option in the parameters to set the UI in dark and to invert text/BG colors of the document (only for the purpose or using in through ONLYOFFICE, the exported/saved document still in original defined colors, not the dark adaptation)

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Latest, Linux, no

**Comment by ShockwaveNN** [comment]
@bphd Hi, this is duplciate of https://github.com/ONLYOFFICE/DocumentServer/issues/1008

**Comment by bphd** [comment]
Not precisely
Because I'm more precise about what I want, the other case just talk about a vague dark mode
And the second part of my wish is not mentioned in the case too

**Comment by ShockwaveNN** [comment]
@bphd Currently our dev team is not finished working on dark mode, so it's better to have all user requests in one place
So it's better to comment out same info in that issue as comment

But after we implement dark mode we'll close that issue and if it will not meet your requirements separate issue for any changes in it will be threated as separate issue
