### ISSUE TITLE
[Feature Request] Native support for Apple M1

### ISSUE THREAD

**Issue by Marc66** [ONLYOFFICE/DesktopEditors#520]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
ONLYOffice does not run natively on Apple's new M1 chip. Not sure if it runs under Rosetta2

**What is the expected behavior?**
Having a native support of Apple M1 (by compiling a Universal binary) would make ONLYOffice one of the first Office suite to run natively on the new Apple platform and could help increase adoption of the Desktop editors

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
All macOS versions up to 6.0.2 do not support the Apple M1 chip

If/when ONLYOffice supports Apple M1, you can report it here >> https://github.com/ThatGuySam/doesitarm or by creating a pull request from this template >> https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md

**Comment by ShockwaveNN** [comment]
@Marc66 Hi, we already working on it and got working prototype, which currently in testing stage, but I cannot guarantee any exact date to be released, since we may found some serious troubles. Or not. 
It's pretty new to us to support several architectures

**Comment by johnblommers** [comment]
Efforts to ship a universal binary for Intel/ARM for macOS Big Sur is hugely important given the anticipated performance gains. I'm happy to test any release candidates for the Desktop Editor.

**Comment by nulled06** [comment]
Hello, any news?

**Comment by ShockwaveNN** [comment]
@nulled06 Sorry, no news

We got fully working version of DesktopEditors and they work well on M1 devices, but this is not native version as far as I'm aware
Seems making native version is little bit complicated

I'll make some announcements as soon as it will be ready

**Comment by nulled06** [comment]
@ShockwaveNN thanks for reply.

**Comment by DroneZzZko** [comment]
You guys [wrote](https://www.onlyoffice.com/blog/2020/12/onlyoffice-desktop-editors-6-1-goes-to-arm-based-apple-silicon-macs/) in your blog last year for version 6.1 that the native version will be available in the next release. But I'm on 6.3 and it's not native. Where can I download it native version?

**Comment by ShockwaveNN** [comment]
@DroneZzZko Sorry it's a very complicated process for our architecture  and took more time than we originally expected

It's currently in the works

**Comment by johnblommers** [comment]
Yes indeed I'm looking at an Apple Silicon application here in my Application folder. Well done and many thanks!
