### ISSUE TITLE
Problem (Ubuntu): In the web browser (Chrome, Firefox) screencast for Desktop Editors window is not possible.

### ISSUE THREAD

**Issue by vladikoles** [ONLYOFFICE/DesktopEditors#530]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
In the web browser (Chrome, Firefox) when using the "open access to the screen" function, dialog does not display the Desktop Editors application window for window selection. Screencast for Desktop Editors window is not possible.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
In the web browser (Chrome, Firefox) when using the "open access to the screen" function, dialog the Desktop Editors application window  for window selection displayed. Screencast for Desktop Editors window is possible.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Ubuntu 18.04.5 LTS (Gnome Shell 3.28.4).
ONLYOFFICE Desktop Editors 6.0.0.110 (6.0.1 appimage), 6.0.2 snap, 6.1.0 deb.
Google Chrome 87.0.4280.88
Mozilla Firefox 83.0

This did not work in any previous versions.

**Comment by rtsisyk** [comment]
I have the same problem.

**Comment by matveevms** [comment]
Hi, @vladikoles 
Could you record a video with this problem?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
