### ISSUE TITLE
[Bug] Onlyoffice hanging at opening new or existing file

### ISSUE THREAD

**Issue by Akrai** [ONLYOFFICE/DesktopEditors#534]
So I installed onlyoffice from the AUR ( https://aur.archlinux.org/packages/onlyoffice-bin/ ) but I have never been able to run it properly. This is the behaviour:

[untitled.zip](https://github.com/ONLYOFFICE/DesktopEditors/files/5721222/untitled.zip)

I have tried the appimage release too. I have also tried running in a guest user account, which has a home folder in a tmpfs, to discard issues from config files, and still the same problem. And also tried in a live iso of kde manjaro, running the appimage release, and it does work.

This is my system:

Operating System: Arch Linux
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.77.0
Qt Version: 5.15.2
Kernel Version: 5.9.14-zen1-1-zen
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-3570K CPU @ 3.40GHz
Memory: 15.6 GiB of RAM
Graphics Processor: Radeon RX 590 Series

**Comment by matveevms** [comment]
Hi, @Akrai 
Onlyoffice from the AUR is not our official build. Your appimage problem on other systems doesn't repeat.
Could you try the snap or flatpak version of our editor?

**Comment by Akrai** [comment]
So flatpak does work, and the onlyoffice package in manjaro repo does work too in a manjaro system. How can I find the issue with this AUR package? I don't want to use flatpak or snap

**Comment by ShockwaveNN** [comment]
@Akrai We, as ONLYOFFICE, do not provide any aur for our products, you should contact team who developed it
I closed this issue, since our flatpak works
