### ISSUE TITLE
Docs claim XP support but executable can't run

### ISSUE THREAD

**Issue by tumagonx** [ONLYOFFICE/DesktopEditors#539]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
can't run onlyoffice on Windows XP SP3 after version 4.4.1 while docs claim it still list XP as supported OS https://helpcenter.onlyoffice.com/installation/desktop-install-windows.aspx
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
install and run
**What is the expected behavior?**
docs need to remove XP as supported OS
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
4.4.1 is the last working version on Windows XP
error is caused by recent CEF (chromium) asking NT6 API

**Comment by DenisDeeSign** [comment]
Hi @tumagonx,
we have special build for Windows XP with last supported CEF. Please check a section For Windows XP / Vista on our [site](https://www.onlyoffice.com/download-desktop.aspx). 
The installation article will be fixed soon. Thank you for your note.

**Comment by tumagonx** [comment]
ah didn't saw that before, I just went to github to download.
thanks for still supporting XP!
