### ISSUE TITLE
[Feature request] Make it possible to change display name for comments

### ISSUE THREAD

**Issue by poVoq** [ONLYOFFICE/DesktopEditors#54]
Referencing this:
https://github.com/ONLYOFFICE/DesktopEditors/issues/50

Would be good if you could actually write the name you want to appear in the advanced settings.

Thanks!

**Comment by maxkadushkin** [comment]
for cloud documents is used user name from portal and app is'not allowed to change that name
for local files it's planed for next release

**Comment by tetrakos** [comment]
Hi @maxkadushkin

Do you have any update on that enhancement? I use OnlyOffice 5.1.29.350 and I still can't edit the name which is used in the comments. 

Otherwise, great work, please go on!

**Comment by maxkadushkin** [comment]
it's testing. and will be available with next update. sorry for continuous waiting

**Comment by samir-s** [comment]
Feature seems available on Onlyoffice 6.2.0.148.

**Comment by ShockwaveNN** [comment]
@samir-s Oh, thanks, seems we forgot to close this issue

**Comment by DesertCookie** [comment]
Where can this option be found? I am unable to.

**Comment by ShockwaveNN** [comment]
@DesertCookie In settings of DesktopEditors

![image](https://user-images.githubusercontent.com/668524/188394378-be761047-7812-4461-96e1-0fd48be839fb.png)

If you didn't find those please state version of DesktopEditors and installation type

**Comment by DesertCookie** [comment]
@ShockwaveNN Thanks, I found it. I was looking in `File > Advanced Settings` and forgot about the general settings (we use the client with Nextcloud mostly but here I had an offline document).

Thank you.
