### ISSUE TITLE
Feature: implement Shift-F3

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#541]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Looks Shift-F3 is not handled

**What is the expected behavior?**
Like it's explained on the [Microsoft official page](https://support.microsoft.com/en-us/office/keyboard-shortcuts-in-word-95ef89dd-7142-4b50-afb2-f762f663ceb2):

 | Shift+F3: switches the selected text between upper case, lower case, and title case.

This extremely handy keyboard shortcut to correct entered text. It works similarly well both for a single word or entire phrase.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Windows 10 20H2
Only Office 6.1.0.90

**Comment by Rita-Bubnova** [comment]
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/395.
