### ISSUE TITLE
Feature: add keyboard shortcuts for "Superscript" and "Subscript" formatting

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#544]
**Do you want to request a *feature* or report a *bug*?**
Feature or enhancement

**What is the current behavior?**
Didn't find how I can format text with keyboard instead of clicking on 
![OO11](https://user-images.githubusercontent.com/64358003/103567210-6b96a480-4ed4-11eb-9781-534a61a73be0.png)
And I'm afraid these keyboard shortcuts are partially assigned for zoom in and zoom out.

**What is the expected behavior?**
MS Office applications and even Skype support well-known shortcuts:

Ctrl-Shift-'+/='  for superscript
Ctrl-'+/='      for subscript

This significantly simplifies entering text without distracting from keyboard to mouse. This is essential when one types something not very sophisticated but what includes text like "x squared" or "chemical formula of water".
I'm guessing if this functionality can be somehow combined with [another request for math equations](https://github.com/ONLYOFFICE/DesktopEditors/issues/335#issue-571416524).

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Windows 10 20H2
Only Office  6.1.0.90

**Comment by Rita-Bubnova** [comment]
Hello, @HectorB-2020.
You're right - we use keyboard shortcut `Ctrl-'+/='` for zoom in. 

But we have keyboard shortcuts for "Subscript" and "Superscript":
`Ctrl+.` - for subscript,
`Ctrl+,` - for  superscript.
More information about Keyboard Shortcuts [here](https://helpcenter.onlyoffice.com/onlyoffice-editors/onlyoffice-document-editor/helpfulhints/keyboardshortcuts.aspx).

**Comment by HectorB-2020** [comment]
@Rita-Bubnova, good to know, I truly appreciate! 

BTW, do you have plans to show shortcut tips to these menu items like you already have for `Ctrl-B`, `Ctrl-U`, `Ctrl-[` or `Ctrl-J` like on the screenshot below?

![OO18](https://user-images.githubusercontent.com/64358003/104203089-ca13d380-543c-11eb-875e-9959e92fb7e8.png)

Maybe I could re-qualify this case to a different feature request - show keyboard tips for Superscript and Subscript?

**Comment by Rita-Bubnova** [comment]
> BTW, do you have plans to show shortcut tips to these menu items like you already have for `Ctrl-B`, `Ctrl-U`, `Ctrl-[` or `Ctrl-J` like on the screenshot below?
> 
> ![OO18](https://user-images.githubusercontent.com/64358003/104203089-ca13d380-543c-11eb-875e-9959e92fb7e8.png)
> 
> Maybe I could re-qualify this case to a different feature request - show keyboard tips for Superscript and Subscript?

This enhancement is discussed in https://github.com/ONLYOFFICE/DesktopEditors/issues/169.

**Comment by HectorB-2020** [comment]
well, then I can only hope that you'll add "Superscript" and "Subscript" formatting to that feature. Though that feature request is pretty old already you know... :worried:

**Comment by Rita-Bubnova** [comment]
@HectorB-2020, you can follow the news about keyboard shortcuts in popups at https://github.com/ONLYOFFICE/DocumentServer/issues/1123.

I think, this issue can be closed?

**Comment by HectorB-2020** [comment]
certainly!
