### ISSUE TITLE
Please help me to see why I can't compile this code, Thank you

### ISSUE THREAD

**Issue by allenyufan** [ONLYOFFICE/DesktopEditors#549]
![1111](https://user-images.githubusercontent.com/18259100/104166407-b9139400-5435-11eb-9b1e-038cb7b70086.png)

7z
Git for Windows
Microsoft Visual Studio 2015 Community
Microsoft Windows SDK 10 (10.0.14393)
Qt 5.8
PowerShell 4
Node.js

After everything is installed, you can continue to the next step.

https://github.com/ONLYOFFICE/DesktopEditors.git

**Comment by ShockwaveNN** [comment]
Hi, we still got not instruction for compiling project on Windows

Any progress will be here https://github.com/ONLYOFFICE/build_tools/issues/105#issuecomment-628510621
