### ISSUE TITLE
libgconf-2.so.4 not found on Ubuntu 17.04

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DesktopEditors#55]
1. Install `onlyoffice-desktopeditors` (4.4.1-53) on Ubuntu 17.04
2. Run it by `desktopeditors`

Result:
There is error:
```
./DesktopEditors: error while loading shared libraries: libgconf-2.so.4: 
cannot open shared object file: No such file or directory
```

Seems since Ubuntu 17.04 packaged `libgconf2-4` is not installed by default.

Error can be fixed by 
`sudo apt install libgconf2-4`

Need to add this packages to dependencies

**Comment by ShockwaveNN** [comment]
Errors only happend on Ubuntu 17.04 (and possible later)
Clean installation on Ubunut 16.10 is working fine

**Comment by agolybev** [comment]
Fixed by  https://github.com/ONLYOFFICE/desktop-apps/pull/12

**Comment by ShockwaveNN** [comment]
Need to recheck on newer build

**Comment by ShockwaveNN** [comment]
`libgconf2-4` correctly installed with
`onlyoffice-desktopeditors 5.0.3-54`

**Comment by georgy7** [comment]
This helped me to run Game Dev Tycoon on Ubuntu 18.04 😄

**Comment by davidsolorzano20** [comment]
Solved my problem https://www.ubuntuupdates.org/package/core/bionic/universe/base/libgconf-2-4
