### ISSUE TITLE
Windows: "Recent Folders" does not open correct folder

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DesktopEditors#550]
**Do you want to request a *feature* or report a *bug*?**
Bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Open local file -> Recent folder

actually contains list of recently accessed folders.

However regardless on what you click on in this list, only the recently opened folder will open.

Assume now you have "Desktop" and "Documents" in the list of recent folders.
Click "Browse" and find a file let's say among "Downloads". "Downloads" will duly appear in the list of recent folders.

Since this moment whatever you click on in the list of recent folder will always open the folder "Downloads"

**What is the expected behavior?**

The program must correctly track the "recent" folder.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Windows 10 20H2
Only Office 6.1.0.90
 
This could be related to similar issue reproduced on Ubuntu.
# https://github.com/ONLYOFFICE/DesktopEditors/issues/528#issue-761406210

**Comment by Rita-Bubnova** [comment]
Hello, @HectorB-2020.
I can confirm - this is bug, issue 48197 in our private issue tracker.

**Comment by HectorB-2020** [comment]
@Rita-Bubnova, since I hit this issuer again, I purposefully decided to copy additional details from other issue.

Recently the document editor crashed. 
I started the application again and found the need file name among recent ones and clicked to open it.
I was shocked to find that it opened a file with changes dated probably yesterday. I attempted to recover this file; yes, its name was in the list of files that application believed could be recovered.
But it opened that same old file. 

As a last resort I opened the document folder through Windows explorer. Thankfully the needed file was there.

Looks like Only Office tries folder with old recoveries. It's only a guess.

**Comment by Rita-Bubnova** [comment]
@HectorB-2020 I see that the original problem has been fixed (https://github.com/ONLYOFFICE/desktop-apps/commit/2df104a3ae539755e14b1560a781276b06539775, https://github.com/ONLYOFFICE/desktop-apps/commit/1d53fde946a40ad441fdaf3d270ccf56212e24c8).
Could you create a separate issue with the new steps to reproduce?

**Comment by HectorB-2020** [comment]
@Rita-Bubnova, can you please tell in which version it was fixed? Mine is 7.2.1.36.
I see this issue hasn't been closed yet.

**Comment by LuckySpecialist** [comment]
Hi, @HectorB-2020!
This problem has been fixed in the version 6.1.1 and is also not reproducible on the current release 7.2.1.
Can you attach a video demonstrating the problem on your system?
