### ISSUE TITLE
Only Office doesn't write with virtual keyboard

### ISSUE THREAD

**Issue by gaetan1903** [ONLYOFFICE/DesktopEditors#552]
**Do you want to request a *feature* or report a *bug*?**
Report A Bug

Only Office doesn't write with virtual keyboard 

OS: Linux
Version:  5.6.4.20

Virtual keyboard: Florence

**Comment by ShockwaveNN** [comment]
Hi, sorry for late response
Could you'll try to update to latest stable version, version 5.6.4 is pretty old
And if problem is still exists on latest version - please record a video and attach it here

**Comment by gaetan1903** [comment]
Hi, yes, this bug is not  hear in ONLYOFFICE Desktop Editors version 6.1.0.90.

Thank you 👍🏾
