### ISSUE TITLE
Cancels session logs out but stills close itself

### ISSUE THREAD

**Issue by bphd** [ONLYOFFICE/DesktopEditors#559]
Which is very smart indeed

____________

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Log out of session with opened documents

**What is the expected behavior?**

Cancels the session log out and pops a message about the risk of losing unsaved files (worst case)

Doesn't cancels the session log out but ask to restore docs from cache files at next opening (middle case)

Doesn't cancels the session log out, save continuously modification and application state to restore it automatically at next opening exactly as it was (without replacing non saved docs or what, just as it was before log out, all from cache) (best case)

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Latest stable, Arch KDE

**Comment by matveevms** [comment]
Hi, @bphd 
Do you have a snap version of the editor installed?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
