### ISSUE TITLE
Change document save behavior

### ISSUE THREAD

**Issue by RIS2000** [ONLYOFFICE/DesktopEditors#56]
Change behavior when saving previously opened xls or doc file:

Currently:
OnlyOffice can't save to xls or doc, instead it saves to xlsX or docX and as a result there is file duplicates and confusion of which is which.

Change to:
Modify through plugin or directly in code that when saving xls to xlsx the old xls file will be deleted and alert appears.

Thank you!

**Comment by maruacat** [comment]
Hello, @RIS2000!
Sorry for the long wait. In the last released version of the editor (version 8.1.0), when saving files doc and xls formats, a file manager window appears in which the user can change the name of the files to avoid confusion with the original file.

Deleting the source files doc and xls seems very risky, as the user will lose them and will not be able to use them for further work, for example in another application that only works with these formats. Therefore, there are currently no plans to implement this behavior in our editor and I think we can close this issue.

Feel free to comment or reopen issue if you got further questions. Thank you for your feedback!

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
