### ISSUE TITLE
Window size automatically increases - after reducing it

### ISSUE THREAD

**Issue by ludberg** [ONLYOFFICE/DesktopEditors#562]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After I reduce the size of the window - it automatically increases again to a size larger than my screen resolution. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Video here: https://youtu.be/Z95xDuTQ2WE

1) Start application
2) Reduce the size my grabbing hold to the lower right corner

**What is the expected behavior?**
The window size should remain as I set it

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
6.1.0.90
Linux Mint

`System:    Kernel: 5.6.0-1042-oem x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.8.6 
           Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Dell product: XPS 13 9310 v: N/A serial: <filter> 
           Mobo: Dell model: 0THX8P v: A00 serial: <filter> UEFI: Dell v: 1.1.4 date: 11/23/2020 
Battery:   ID-1: BAT0 charge: 45.1 Wh condition: 51.0/51.0 Wh (100%) model: BYD DELL FP86V0A status: Discharging 
CPU:       Topology: Quad Core model: 11th Gen Intel Core i5-1135G7 bits: 64 type: MT MCP arch: Tiger Lake rev: 1 
           L2 cache: 8192 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 38707 
           Speed: 1067 MHz min/max: 400/4200 MHz Core speeds (MHz): 1: 1100 2: 1095 3: 1100 4: 1100 5: 1101 6: 1088 
           7: 1070 8: 1100 
Graphics:  Device-1: Intel vendor: Dell driver: i915 v: kernel bus ID: 0000:00:02.0 
           Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1200~60Hz 
           OpenGL: renderer: Mesa Intel Xe Graphics (TGL GT2) v: 4.6 Mesa 20.2.6 direct render: Yes 
Audio:     Device-1: Intel vendor: Dell driver: sof-audio-pci bus ID: 0000:00:1f.3 
           Sound Server: ALSA v: k5.6.0-1042-oem 
Network:   Device-1: Intel vendor: Bigfoot Networks driver: iwlwifi v: kernel port: 3000 bus ID: 0000:00:14.3 
           IF: wlp0s20f3 state: up mac: <filter> 
           IF-ID-1: tun0 state: unknown speed: 10 Mbps duplex: full mac: N/A 
Drives:    Local Storage: total: 476.94 GiB used: 48.42 GiB (10.2%) 
           ID-1: /dev/nvme0n1 model: KXG60ZNV512G NVMe KIOXIA 512GB size: 476.94 GiB 
RAID:      Hardware-1: Intel Volume Management Device NVMe RAID Controller driver: vmd v: 0.6 bus ID: 0000:00:0e.0 
Partition: ID-1: / size: 28.78 GiB used: 17.13 GiB (59.5%) fs: ext4 dev: /dev/nvme0n1p7 
           ID-2: /home size: 107.40 GiB used: 31.20 GiB (29.0%) fs: ext4 dev: /dev/nvme0n1p9 
           ID-3: swap-1 size: 7.81 GiB used: 5.0 MiB (0.1%) fs: swap dev: /dev/nvme0n1p8 
Sensors:   System Temperatures: cpu: 40.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Info:      Processes: 301 Uptime: 1d 25m Memory: 15.37 GiB used: 4.74 GiB (30.8%) Init: systemd runlevel: 5 
           Compilers: gcc: 9.3.0 Shell: bash v: 5.0.17 inxi: 3.0.38 
`

**Comment by ludberg** [comment]
Hi @matveevms 
I downloaded it from the Software Manager in Linux Mint. 
It was a flatpak.

See this screenshot for details: https://i.imgur.com/9VelRug.png

**Comment by matveevms** [comment]
@ludberg 
Thanks for waiting.
I have checked the flatpak version on this system, but your problem is not reproduced. Could you try installing the deb version or snap and try to reproduce your problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
