### ISSUE TITLE
Unable to launch editor after installation

### ISSUE THREAD

**Issue by johannessennahoj** [ONLYOFFICE/DesktopEditors#563]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When trying to launch the editor after installation, the following error message appears:
![image](https://user-images.githubusercontent.com/61589008/107144378-1ddde380-693b-11eb-83bc-78522bd9ce4b.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Install the desktop editor, launch directly after installation or afterwards.

**What is the expected behavior?**
editor launches

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
OnlyOffice Desktop editor x64
Version 6.1.0
Windows 10 Home 20H2
Surface Pro 7

**installed applications**
![image](https://user-images.githubusercontent.com/61589008/107340918-9f11b380-6abe-11eb-9ca8-6543a9ffcd2f.png)

**Comment by Rita-Bubnova** [comment]
Hello, @johannessennahoj.
Can you attach a screenshot of the applications installed on your computer (Control Panel\Programs\Programs and Features)?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
