### ISSUE TITLE
Is there a way to make the OnlyOffice Desktop Editor Installer for Windows 10 an self-extracting archive?

### ISSUE THREAD

**Issue by DUOLabs333** [ONLYOFFICE/DesktopEditors#569]
I like to make my software as portable as possible, so I often extract installers as archives and just use them regularly (most time this works fine). But when I tried it for the installer for Windows, I didn't see any relevant files (maybe it's an online installer). So, is there a version of the installer that can be extracted?

**Comment by DenisDeeSign** [comment]
Hi @DUOLabs333,
the proper folder structure builds after installation. An application is portable, so you just can zip ONLYOFFICE or DesktopEditor folder and make self-extracted archive on you own.

**Comment by DUOLabs333** [comment]
@DenisDeeSign Yeah, that's what I thought at first, but whenever I run the application, it creates a data folder in the local data folder. Is there a way to change the location?

**Comment by necros2k7** [comment]
imho should be merged with 2017 portable feat.req. issue
