### ISSUE TITLE
Shapes are not matched with cursor

### ISSUE THREAD

**Issue by KillingSpark** [ONLYOFFICE/DesktopEditors#57]
This is a bug i think:   
Shapes are not picked up correctly by the cursor. If i want to resize a shape, i have to aim slightly to the right and top, approximatly one cursor width in each direction. Makes it pretty hard if the shape is a line.  
  
I hope this explains what I wanted to describe.  
  
I'm on Windows 10 64x, using the latest download from you webiste.

**Comment by K0R0L** [comment]
Do you have a high-resolution monitor or not?

**Comment by KillingSpark** [comment]
I have a Laptop, with the standard weird laptop-hd resolution 1366x768

**Comment by ShockwaveNN** [comment]
I think this issue should be resolved by now. Feel free to comment if not
