### ISSUE TITLE
Spell check does not work in flatpak on manjaro kde

### ISSUE THREAD

**Issue by shivanshsinghx365** [ONLYOFFICE/DesktopEditors#574]
I recently installed OnlyOffice on my manjaro kde which has kernel 5.9.16, and noticed that the spell check won't work for default settings it self, I mean  for default language english-us
the spell check doesn't work at all even though it seems to be enabled.

**Comment by ShockwaveNN** [comment]
Hi, could you try to install snap\appimage on same system and check if spellchecker works there and this is flatpak related issue?

**Comment by risacher** [comment]
FWIW, I'm running ONLYOFFICE DE 6.1.0.90 on Ubuntu Groovy from the apt repo and spell check is not working for me either.

**Comment by ShockwaveNN** [comment]
@risacher I think you got separate issue, please create a new one, see for errors in `/var/log/onlyoffice`

**Comment by risacher** [comment]
I tried the AppImage and no spell chek there either.

**Comment by ShockwaveNN** [comment]
@risacher Once again please create a new issue, original topic may be unrelated of your problem and original author is not answered my question

**Comment by risacher** [comment]
FWIW - my "offtopic" issue was related to a specific file.  I.e. spellcheck was working in general, but not for a specific file; if I cut-n-paste the content from that file to a new document, it was okay.    I'll report a new issue after I explore it a bit more to see if I can narrow it down.

**Comment by shivanshsinghx365** [comment]
The issue got solved with upgrading from flatpak to official repository
