### ISSUE TITLE
Bug : Can't save xlsx sheets

### ISSUE THREAD

**Issue by ImaCrea** [ONLYOFFICE/DesktopEditors#576]
Hello, I'm encountering a bug with xlsx sheets on my local computer

 **What is the current behavior?**
- When I want to save my document, an alert box is displayed and I can't save my modifications.
- I tried with already existing xlsx document and even when trying with a new one from fresh.
- The dialog box I see :
![Capture d’écran 2021-03-09 à 09 28 37](https://user-images.githubusercontent.com/764332/110442535-3a487980-80bb-11eb-9a10-0a919558f2ee.png)

- My disk has enough space, the file has proper permission to be edited and no other apps is working on the file (I'm on local mode here)

**This makes OnlyOffice unusable for me with spreadsheets. Saving docx files is working fine.**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Open or create new xlsx
- Make some edit
- Try to save

**What is the expected behavior?**
- Document should be saved
- The alert box shouldn't be displayed

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
- I'm on OnlyOffice 6.1 (443)
- Mac OS X El Capitan 10.11.6

Thanks for your help!

**Comment by DenisDeeSign** [comment]
Hi @ImaCrea,
this is known issue 47984 in our private issue tracker. The issue has already fixed and will be included in next major relase.

**Comment by ImaCrea** [comment]
ok

**Comment by ShockwaveNN** [comment]
I'll leave this issue opened until we release a fix

**Comment by PiecePaperCode** [comment]
Saving as docx fails on Ubuntu

**Comment by ShockwaveNN** [comment]
@PiecePaperCode Original issue was for Macos, please do not hijack this issue, I think your problem is completly separated, create new issue and describe it in more details that 6 words

**Comment by DenisDeeSign** [comment]
@ImaCrea, new version was released yesterday. We had to separate package to the two different ones because of critical fixes. So you can download the correct version using direct direct [link].(https://download.onlyoffice.com/install/desktop/editors/mac/x86/distrib/ONLYOFFICE.dmg).

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors v6.2.0 are released.
This issue should be fixed.
Feel free to comment or open new issue if got any troubles.

**Comment by ImaCrea** [comment]
Thank you all and for taking the time to notify me about this update! 🤗
