### ISSUE TITLE
Bug in Fedora 26 when opening or saving files

### ISSUE THREAD

**Issue by bkmgit** [ONLYOFFICE/DesktopEditors#58]
![screenshotdemonstratingbugonfedora26](https://user-images.githubusercontent.com/1679477/29031175-fef9bb92-7b95-11e7-8dca-7f73ba383999.png)

Opening and closing files in the current desktop version on Fedora 26 available through rpm installer does not display icons, file paths and file names correctly. A screenshot follows.

**Comment by n1441** [comment]
Second that. Can provide an 8GB KVM raw image in reproducible state.

**Comment by ShockwaveNN** [comment]
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/52
