### ISSUE TITLE
(Spreadsheet) Touchpad horizontal scrolling gesture scrolls diagonally

### ISSUE THREAD

**Issue by PrefixCoder** [ONLYOFFICE/DesktopEditors#582]
**Do you want to request a *feature* or report a *bug*?** 
bug

When using a touchpad in spreadsheet, vertical scrolling works as intended, but horizontal vector of scrolling is turned -45 degrees for some reason, e.g. ↘ instead of ➡️, ↖️ instead of ⬅️.

**Which versions of DesktopEditors, and which OS are affected by this issue?** 
version 6.2.0.148, Win 10
**Did this work in previous versions of DesktopEditors?** 
Bug was there before

**Comment by Rita-Bubnova** [comment]
Hello, @PrefixCoder.
Our dev team associates this issue with https://github.com/ONLYOFFICE/DocumentServer/issues/536.
