### ISSUE TITLE
Add Snap support?

### ISSUE THREAD

**Issue by BearzRobotics** [ONLYOFFICE/DesktopEditors#59]
**Feature:** add support for Ubuntu's snap package, to create a cross distro one command install. The server edition could also be packaged as a snap as well.

**current behavior?**
Having to go and download it and figure out if my distro has all required dependencies then having to manual update it.

**Comment by now-im** [comment]
I also think this is more necessary than ever. Version 4.4.8 is out but the tar.gz version doesn't contain the install script files so, arch linux distro voluntary developers have not updated it yet. Creating a snap can solve this problem. Really hope developers make this a priority and eventually reduces their workload.

**Comment by BearzRobotics** [comment]
I havn't been here since I made the comment, it looks like there is another issue asking for snap that has more people communicating. So I'm going to close this and hope on the other issue.
