### ISSUE TITLE
MacOS: It is not possible to change the editor width significantly

### ISSUE THREAD

**Issue by inovikov78** [ONLYOFFICE/DesktopEditors#590]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
I'm trying to reduce the editor window width but on some certain width it stops reducing and only possible to expand it.
https://drive.google.com/file/d/19eVwMwRL9LU-khyBS8weXgaV_XgTX_SR/view?usp=drivesdk

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Try to reduce the size of the editor window to 1/3 screen size, for example.
I suppose the reason for that - that toolbar not able to change the look to more compact.

**What is the expected behavior?**
Screen width reduces.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
MacOS 10.13.6 (17G14042)
OnlyOffice 6.2 (492)

**Comment by Rita-Bubnova** [comment]
Hello, @inovikov1978.
We know about this behavior. We discuss this issue with our development team (issue 40055 in our internal issue tracker).

**Comment by inovikov1978** [comment]
Okay. Thank you for your quick reply. 
Looking forward to the resolution of that case.

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
