### ISSUE TITLE
Missing Polish translations.

### ISSUE THREAD

**Issue by RDKRACZ** [ONLYOFFICE/DesktopEditors#593]
Seems like some parts are not yet translated:
![image](https://user-images.githubusercontent.com/43277609/113064456-51105680-91b7-11eb-90ee-5d5658024fb4.png)
![image](https://user-images.githubusercontent.com/43277609/113064500-64bbbd00-91b7-11eb-8f44-298d0d2560ce.png)
![image](https://user-images.githubusercontent.com/43277609/113064521-6dac8e80-91b7-11eb-97fc-d086373b6f99.png)

v6.1.0-90

I can translate these but where? Do You have stings on sites like poeditor?

**Comment by hellonadya** [comment]
Hello! Thanks for reporting! Please contact us at documentation@onlyoffice.com, we'll give you access to our translation system.

We would really appreciate your help with the Polish translation.

**Comment by ShockwaveNN** [comment]
I'll close this issue, since translation question are discussed outside of GitHub
