### ISSUE TITLE
[Feature request] Custom tabulators.

### ISSUE THREAD

**Issue by RDKRACZ** [ONLYOFFICE/DesktopEditors#594]
v6.1.0-90
Is there an option to make tab insert dots under the text line? [It's not described here](https://helpcenter.onlyoffice.com/onlyoffice-editors/onlyoffice-document-editor/usageinstructions/settabstops.aspx)

![image](https://user-images.githubusercontent.com/43277609/113064867-270b6400-91b8-11eb-8632-e833c3d2c2fc.png)
![image](https://user-images.githubusercontent.com/43277609/113064964-5326e500-91b8-11eb-9b2e-838398bd3597.png)

**Comment by Rita-Bubnova** [comment]
Hello, @RDKRACZ.
I attach the video to show how it works.

https://user-images.githubusercontent.com/25282241/113113726-47b4d780-9213-11eb-98ec-02cfbcebb29a.mp4

It's also described on [this page](https://helpcenter.onlyoffice.com/onlyoffice-editors/onlyoffice-document-editor/usageinstructions/settabstops.aspx) by `Leader` title.

**Comment by RDKRACZ** [comment]
Thank You! I think I was even looking there but Polish translations were misleading, gonna improve them too.

**Comment by Rita-Bubnova** [comment]
@RDKRACZ, I glad to help :)
