### ISSUE TITLE
libcurl-gnutls.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by KAMiKAZOW** [ONLYOFFICE/DesktopEditors#6]
OS: Fedora 24
Installed from RPM download which claims to be for Fedora 24.

./DesktopEditors: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

**Comment by maxkadushkin** [comment]
yes, there is such trouble with deployment on some linux distros

**Comment by K0R0L** [comment]
please download the new version and report the results

**Comment by dbuch** [comment]
@K0R0L Where is the new version? Is it ported away from the old curl open ssl version 3 protocol?

**Comment by K0R0L** [comment]
new version on site
http://www.onlyoffice.com/ru/download-desktop.aspx

**Comment by fchicout** [comment]
problem persists on Fedora 25... but with 

cd /opt/onlyoffice/desktopeditors
sudo ln -s /usr/lib64/libcurl.so.4 libcurl-gnutls.so.4


it opens, but with some warnings,..

./DesktopEditors: ./libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/libascdocumentscore.so)

(DesktopEditors:15058): GdkPixbuf-WARNING **: Bug! gdk-pixbuf loader 'png' didn't set an error on failure.

** (DesktopEditors:15058): WARNING **: Pixbuf theme: Cannot load pixmap file /usr/share/themes/Adwaita-dark/gtk-2.0/assets/progressbar-horz-trough.png: Failed to load image '/usr/share/themes/Adwaita-dark/gtk-2.0/assets/progressbar-horz-trough.png': reason not known, probably a corrupt image file


(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

** (DesktopEditors:15058): WARNING **: Invalid borders specified for theme pixmap:
        /usr/share/themes/Adwaita-dark/gtk-2.0/assets/progressbar-horz-trough.png,
borders don't fit within the image

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(DesktopEditors:15058): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
[1229/235100:ERROR:browser_main_loop.cc(219)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
/opt/onlyoffice/desktopeditors/DesktopEditors: ./libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/libascdocumentscore.so)
[1229/235132:ERROR:PlatformKeyboardEvent.cpp(84)] Not implemented reached in static bool blink::PlatformKeyboardEvent::currentCapsLockState()
[1229/235154:ERROR:PlatformKeyboardEvent.cpp(84)] Not implemented reached in static bool blink::PlatformKeyboardEvent::currentCapsLockState()
[1229/235154:ERROR:PlatformKeyboardEvent.cpp(84)] Not implemented reached in static bool blink::PlatformKeyboardEvent::currentCapsLockState()
/opt/onlyoffice/desktopeditors/converter/x2t: /lib64/libcurl.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/converter/x2t)

**Comment by fchicout** [comment]
Update: the related above had happen with the direct rpm package download. With the rpm on the repository, (misteriously) the link wasn't needed. Different versions, maybe?

**Comment by NeroMorto** [comment]
Same on Fedora 26.

**Comment by jonnjonzzn** [comment]
Works on F26 as per @fchicout suggestion above.

**Comment by naktu** [comment]
Has this problem. FIx like @fchicout

**Comment by jonathan-91** [comment]
Had this problem on F28. Fixed as per @fchicout.

**Comment by Nindaleth** [comment]
OnlyOffice crashed for me on Fedora 29 even with the [workaround](https://github.com/ONLYOFFICE/DesktopEditors/issues/6#issuecomment-269725720) applied, but after the December 2018 update v5.2.4 it finally starts and runs.

**Comment by xmbwd** [comment]
OO crashes without ever starting with a fresh install (downloaded today, 02.02.2019) on Fedora 29.  

Error:
`./DesktopEditors: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory`

**Comment by noraj** [comment]
OS : ArchLinux
Product : ONLYOFFICE Desktop Editors version 5.2.83.480

When I try to connect to a ONLYOFFICE cloud using HTTPS:

```
./DesktopEditors: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/converter/libkernel.so)
/opt/onlyoffice/desktopeditors/DesktopEditors: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/onlyoffice/desktopeditors/converter/libkernel.so)
[0215/172809.095028:ERROR:cert_verify_proc_nss.cc(921)] CERT_PKIXVerifyCert for 192.168.2.107 failed err=-8187
```

But I have the lib:

```
ls -l /usr/lib/libcurl-gnutls.so.4
lrwxrwxrwx 1 root root 23 13 janv. 22:03 /usr/lib/libcurl-gnutls.so.4 -> libcurl-gnutls.so.4.5.0
```

**Comment by Germano0** [comment]
Fedora libcurl uses openssl not gnutls. Could you please provide the RPM spec file you are using so that I could fix it together with other Fedora developers?
Thank you

**Comment by TheRoarkster** [comment]
Need to figure out how to extract the spec file from the built rpm, but here is additional information in the interim:
```
$rpm -qi onlyoffice-desktopeditors.x86_64
Name        : onlyoffice-desktopeditors
Version     : 5.2.8
Release     : 9
Architecture: x86_64
Install Date: Sat 02 Feb 2019 03:19:09 PM PST
Group       : Applications/Office
Size        : 676492046
License     : AGPLv3
Signature   : (none)
Source RPM  : onlyoffice-desktopeditors-5.2.8-9.src.rpm
Build Date  : Mon 28 Jan 2019 08:10:24 AM PST
Build Host  : buildslave-linux-64.onlyoffice.info
Relocations : (not relocatable)
Packager    : Ascensio System SIA <support@onlyoffice.com>
Vendor      : Ascensio System SIA
URL         : http://onlyoffice.com/
Summary     : Desktop editors for text, spreadsheet and presentation files
Description :
ONLYOFFICE DesktopEditors installation package
 ONLYOFFICE DesktopEditors is an application for editing office documents (text documents, spreadsheets and presentations) from onlyoffice cloud portal on local computer without browser using.
```

**Comment by Germano0** [comment]
@TheRoarkster you cannot retrieve it from the binary RPM. You need the SRPM (source RPM)

**Comment by TheRoarkster** [comment]
Right.  Any idea where I can get that?

**Comment by sergiomb2** [comment]
Still happens in Fedora and Centos 7

**Comment by ShockwaveNN** [comment]
DesktopEditors 5.3.3 was released. Issue should be fixed
I checked on Fedora 30 - and everything seems fine
