### ISSUE TITLE
FEATURE, PDF EDITING

### ISSUE THREAD

**Issue by Rmdhn1** [ONLYOFFICE/DesktopEditors#601]
can't find a way to edit a PDF, it says it can edit them but for me it justs views them

**Comment by ShockwaveNN** [comment]
> it says it can edit them

Seems this is incorrect info, could you show where is you see this?

Currently we cannot edit PDF

**Comment by PiecePaperCode** [comment]
people pay good money to edit PDF. Its quite hard to do anywhay because it wasent designed thet way

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
