### ISSUE TITLE
Onlyoffice opens only a partial amount of document

### ISSUE THREAD

**Issue by gitgrubhub** [ONLYOFFICE/DesktopEditors#604]
I am still unclear what produces this bug. I have repeatedly had a document fail to open entirely. The text will cut off at the same spot in the document. Strangely I can open the file fine in Libreoffice and Microsoft Word.

**Comment by ShockwaveNN** [comment]
Hi, could you attach this document? We defenetly need one

And also please note your DesktopEditor version and OS. We got similar bug but I think we already released a fix for it

**Comment by gitgrubhub** [comment]
The document is a bit confidential. Could privately email if helpful. 

running Ubuntu 20.04 and OO 6.2.0.148.

**Comment by ShockwaveNN** [comment]
You can send it to files@onlyoffice.com

**Comment by Rita-Bubnova** [comment]
This issue fixed in future major release, but currently we have no ETA.

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors v6.3.1 is released. This issue should be fixed
