### ISSUE TITLE
Spell check language switches back automatically to the default language

### ISSUE THREAD

**Issue by biva** [ONLYOFFICE/DesktopEditors#607]
As reported by @rataman098 in https://github.com/ONLYOFFICE/DesktopEditors/issues/143#issuecomment-661776855, after changing the document language to Spanish, whenever typing a character, it changes back to English (on a different computer setup, it's the same with different languages: after changing the document language to English UK, whenever I type a character, it changes back to French).

The document should keep the language chosen for the spell check

**Which versions of DesktopEditors, and which OS are affected by this issue?**
Windows 10 
Desktop editor 6.2.0.148

**Comment by jochepr** [comment]
### Experiencing the same issue. 

Default language on my computer is English, and the currently opened document is set to Spanish. Whenever I type a character, it changes back to English.

Document language should persist regardless of text modification. 

```
Windows 10 Pro (Version 2004, Build 19041.572)
Desktop Application **6.2.0.148** 
```

**Comment by zilexa** [comment]
With a big workaround that surprisingly no one from the OnlyOffice team wants to provide us, you _**can**_ change the default document language/spell check language, but it requires you to modify/create new templates and move/overwrite existing ones. 

I love OnlyOffice, but the fact I had to spend hours figuring this out myself even though it has been asked numerous times on Github and the forum is just insulting. There are more languages in the world! And OnlyOffice actually supports a lot of document languages and even has a spellchecker for many languages.

I have written a guide on how to change the default document language as it cost me so much time doing trial/err to figure this out, I hope it helps others: 
https://github.com/zilexa/Ubuntu-Budgie-Post-Install-Script/blob/master/onlyoffice

**Comment by biva** [comment]
@zilexa Thanks for your support! OnlyOffice team suggested a similar solution (I guess?) but no support was available in https://github.com/ONLYOFFICE/DesktopEditors/issues/143#issuecomment-826689472.

@ShockwaveNN maybe you could add that in the official documentation?

**Comment by ShockwaveNN** [comment]
@zilexa Thanks for your detailed guide

@biva Yeah, I send it to our documentation team, see that whey can do with it

**Comment by biva** [comment]
Hello, I think this issue is a duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/273, so I close this one.
