### ISSUE TITLE
VLOOKUP returns incorrect results when data table is in another sheet

### ISSUE THREAD

**Issue by IGBC** [ONLYOFFICE/DesktopEditors#608]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
VLOOKUP function (spreadsheet module) returns the incorrect row of data when the data table field referenced is in another sheet, and the sheet has been renamed

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Create a table of data on Sheet1
| Mark  | 1 |
|-------|---|
| Ringo | 2 |
| Paul  | 3 |
| Jon   | 4 |
| James | 5 |
| Phil  | 6 |

Rename sheet 1 to Overview

into Sheet2 enter

| Ringo | =VLOOKUP(A1,Overview!A1:B6,2) |
|-------|---|

VLOOKUP should resolve to 2, on my system I get 6

**What is the expected behavior?**
VLOOKUP should follow the behavior set by Microsoft Excel, see https://support.microsoft.com/en-us/office/vlookup-function-0bbc8083-26fe-4963-8ab8-93a18ad188a1 for details.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Issue reported in:  6.2.0.148
Running on ArchLinux 

Due to how binaries are packaged on Arch it is not possible to try other versions.

**Comment by Rita-Bubnova** [comment]
Hello, @IGBC.
I checked your problem in ONLYOFFICE and MS Excel and got the same result - 6.
Could you attach file with problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
