### ISSUE TITLE
Wish to provide a document about compile from source code

### ISSUE THREAD

**Issue by Sraw** [ONLYOFFICE/DesktopEditors#62]
We modified sdkjs submodule and want to compile from source code in order to use modified sdkjs. But there is not a document about how to compile it from source code.

Please consider provide at least a simple document to introduce how to compile.

We have noticed that linux version was built with qt, but we still need to know the requirements.

**Comment by agolybev** [comment]
Hello @Sraw 
You could find sdkjs compile instructions in [this](http://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx) guide.
If you wouldn't  like to compile web-app project you can just run `grunt` command in `build` directory:
`cd build && grunt`
But before it you should install grunt with `sudo npm install -g grunt-cli` command and install npm modules with `cd build && npm install` command.

**Comment by Sraw** [comment]
@agolybev Hello, what I really want to compile is "DesktopEditors". I didn't find anything about how to compile it.

**Comment by agolybev** [comment]
Hello @Sraw, [this](http://helpcenter.onlyoffice.com/desktop/documents/linux/compile-desktop-ubuntu.aspx) instruction describes how to compile  Desktop Editors.

**Comment by Sraw** [comment]
@agolybev Thanks a lot, best wish to you.
