### ISSUE TITLE
Dark Mode support

### ISSUE THREAD

**Issue by rafadesign** [ONLYOFFICE/DesktopEditors#620]
Onlyoffice could support dark mode, in linux I use dark mode and it is uncomfortable to use onlyoffice in light mode

**Comment by ShockwaveNN** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1008

**Comment by cipricus** [comment]
This is a dark GUI theme but note a full-dark mode with dark/custom page background like MSOffice and LO have.
