### ISSUE TITLE
Equations in calc

### ISSUE THREAD

**Issue by asbl** [ONLYOFFICE/DesktopEditors#622]
I use the Desktop Editor 6.2.0.148.

When I use calc and want to edit an equation with the equation editor (Inside a cell or inside a Textfield) onlyoffice crashes (very often but not every time...) and promts me to save my documents. After restarting onlyoffice I can edit the equation.

**Comment by Rita-Bubnova** [comment]
Hello, @asbl.
Could you attach file with problem and original file?
Could you describe the steps to reproduce the problem?

**Comment by asbl** [comment]
Unfortunatly i can't. 

I got the error multiple times on working with several Documents with sensible Data.

I tried reproducing the problem but i'm not sure when exactly the problem occurs...

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
