### ISSUE TITLE
[BUG] ShellNew registry keys doesn't work.

### ISSUE THREAD

**Issue by the4anoni** [ONLYOFFICE/DesktopEditors#623]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I can't create .docx/.xlsx/.pptx file from right click on Desktop.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Right Click on Desktop -> New

![image](https://user-images.githubusercontent.com/13403084/118355063-5f9bad00-b56e-11eb-88ad-9b3a9e07cb12.png)

**What is the expected behavior?**
I can create .docx/.xlsx/.pptx file from right click.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Windows 10 21H1 Insider and 1809 LTSC, ONLYOFFICE Desktop Editors 6.2.0.148
This is first time I am using OnlyOffice.

This is how it looks in regedit
![image](https://user-images.githubusercontent.com/13403084/118355020-24997980-b56e-11eb-8dd2-056583c1c6d3.png)

**Comment by LuckySpecialist** [comment]
Hi @the4anoni 
This is a known issue 37924 in our private tracker and we are working on a solution.
Thank you for your feedback.

**Comment by Loki-L1130** [comment]
Is there any news or improvements on this ?

**Comment by LuckySpecialist** [comment]
Sorry, there is no news yet. But I reminded the developers about this issue in issue 37924.

**Comment by YanceyChiew** [comment]
Encountered the same problem, here is my registry changes for reference.

```reg
Windows Registry Editor Version 5.00

[-HKEY_CLASSES_ROOT\.DOCX]
[HKEY_CLASSES_ROOT\.DOCX]
@="ASC.Document.12"

[HKEY_CLASSES_ROOT\.DOCX\ShellNew]
"FileName"="D:\\Program Files\\ONLYOFFICE\\DesktopEditors\\converter\\empty\\en-US\\new.docx"
"IconPath"="D:\\Program Files\\ONLYOFFICE\\DesktopEditors\\DesktopEditors.exe,7"
@=""

[-HKEY_CLASSES_ROOT\.PPTX]
[HKEY_CLASSES_ROOT\.PPTX]
@="ASC.Show.12"

[HKEY_CLASSES_ROOT\.PPTX\ShellNew]
"FileName"="D:\\Program Files\\ONLYOFFICE\\DesktopEditors\\converter\\empty\\en-US\\new.pptx"
"IconPath"="D:\\Program Files\\ONLYOFFICE\\DesktopEditors\\DesktopEditors.exe,9"
@=""

[-HKEY_CLASSES_ROOT\.XLSX]
[HKEY_CLASSES_ROOT\.XLSX]
@="ASC.Sheet.12"

[HKEY_CLASSES_ROOT\.XLSX\ShellNew]
"FileName"="D:\\Program Files\\ONLYOFFICE\\DesktopEditors\\converter\\empty\\en-US\\new.xlsx"
"IconPath"="D:\\Program Files\\ONLYOFFICE\\DesktopEditors\\DesktopEditors.exe,10"
@=""


```

After importing the above registry, you can use ShellNew to create a new file correctly. It is especially important to note that the subkeys that onlyoffice automatically adds to `[HKEY_CLASSES_ROOT\.docx]` etc. should be removed, or at least not have the same name as `[HKEY_CLASSES_ROOT\ASC.Document.12]`.

**Comment by Rita-Bubnova** [comment]
DesktopEditors v7.5.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
