### ISSUE TITLE
[Feature request] Smooth scrolling for sheets

### ISSUE THREAD

**Issue by liferooter** [ONLYOFFICE/DesktopEditors#625]
## Do you want to request a *feature* or report a *bug*?
I want to request **feature**

## Current behavior
ONLYOFFICE sheet editor doesn't have smooth scrolling.

## Expected behavior
ONLYOFFICE sheet editor should have smooth scrolling for better usability.

## Software versions
**ONLYOFFICE:** 6.2.0.148
**OS:** Fedora Linux 34

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
