### ISSUE TITLE
Deleting a selection of space/text next to or including commented text deletes the comment

### ISSUE THREAD

**Issue by gitgrubhub** [ONLYOFFICE/DesktopEditors#628]
Running Ubuntu 20.04 and OO 6.2.0.148

**Comment by Rita-Bubnova** [comment]
Hello, @gitgrubhub.
Can you please describe your actions step by step or include gif/video of what's happening?

**Comment by gitgrubhub** [comment]
Sure. If a text string is highlighted (using the actual highlighter tool), then if I highlight (with my cursor) any text adjacent to or including the highlighter tool highlighted text, then the entire comment is deleted.

Take the following sentence for example, "I eat rocks. Don't you?" If I highlighter tool highlighted rocks, but then I highlighted any letter of rocks or even the empty space before it or the period after it and then hit delete, the entire comment is deleted. This isn't intuitive to me and I don't believe this behavior happens in Word or LibreOffice.

**Comment by matveevms** [comment]
Hello, @gitgrubhub. 
In which part of the sentence was the comment added? How was the selection made? Double click or cursor? The video would help us a lot to solve your problem faster.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
