### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by mcanepa** [ONLYOFFICE/DesktopEditors#629]
I think that an autoupdate feature would be nice to have. Or at least a notification about a new version available

**Comment by ShockwaveNN** [comment]
Are you talking about windows version of DesktopEditors? I think we got autoupdate there

**Comment by mcanepa** [comment]
Linux (Debian 9)

I've installed 6.0.0.110 and never get an autoupdate or a notification to download a new version

**Comment by ShockwaveNN** [comment]
On debian update should be received via `apt-get update` as any other deb
based application, I don't think adding our own update system instead of
default option for Debian is a good idea

Maybe you forgot to add our repo to sources.list?

**Comment by mcanepa** [comment]
I've installed via .deb file

I see now there's a repo option to install the package

As soon as debian 11 is released I will install that way (new installation, os and packages)

Thanks!

**Comment by ShockwaveNN** [comment]
In our basic [installation instruction](https://helpcenter.onlyoffice.com/installation/desktop-install-ubuntu.aspx) of DesktopEditors we installing them via adding repo

In that case all updates will be provided same way as any other updates on Debian

I'll close this issue, but please comment if you got any troubles/ideas regarding this issue
