### ISSUE TITLE
snap support for Solus OS

### ISSUE THREAD

**Issue by radomir-lilic** [ONLYOFFICE/DesktopEditors#63]
I like to request a snap support for Solus OS for DesktopEditors. 

Thanks!

**Comment by ShockwaveNN** [comment]
@HellRoad look into this

**Comment by radomir-lilic** [comment]
Thank you for looking into.

**Comment by HellRoad** [comment]
@radomir-lilic 
Hi. We currently have some plan, about using snap package system for desktopeditors, but it's in early stage, so we have not ETA

But you can youse portable version, I checked it - and it worked fine https://www.onlyoffice.com/download-desktop.aspx

**Comment by radomir-lilic** [comment]
Thank you for the update... I will eagerly wait for snap support for Solus OS. The portable version is ok but I do prefer full fledged installation or snap install. Do you think that I can get updated when full installation or snap support is ready?

**Comment by charlesjt** [comment]
@radomir-lilic The best way to request a native package for Solus OS is to follow [this guide](https://solus-project.com/articles/packaging/request-a-package/en/), on the other hand the currently offered portable package is sufficient for most distros. I think it's an independent discussion choosing one of the new formats available for gnu/linux (I think Flatpak is more universal and independent IMHO).

**Comment by radomir-lilic** [comment]
Solus team won't add this to their repository as according to them it is responsibility of the maker. Stuck there...

**Comment by charlesjt** [comment]
@radomir-lilic I don't see what you say in [Solus phabricator](https://dev.solus-project.com/T1374)... Basically the arguments are that there are already two alternatives to handle office documents, a native option (LibreOffice) and a third party alternative (WPS Office) that extends support to a specific group of Chinese language users, so there is no real (priority) need to add other software that does the same, plus there is a version provided by the authors that works perfectly in Solus OS.

I suppose adding better arguments to the discussion would help to better consider the inclusion of OnlyOffice, as an equal or better support to OOXML or that is maintained more actively than WPS Office, etc. Anyway I dont see the need to pressure OnlyOffice authors when they have a portable version that works really well.

**Comment by radomir-lilic** [comment]
I asked about OnlyOffice while I was able to handle complex excel files and open them without formatting errors (same for word docs) and the response I got was this: 

_All I can tell is that only office wasn't accepted for inclusion in the main repository, so it should go in the 3rd party repo. This means a snap package should be available. Anyone willing to package it can do it but ideally the vendor should do it. I see someone made a request, I would advise to comment it to show others users would like to have it published as a snap package too.

Regarding the choice, it's a complex question. There are already a few offices suites available on Solus. It doesn't make sense to offer many different applications that do the same thing (even if each of them have their own strengths) while there are still many other priorities. It would result in outdated packages or very long delays to solve issues, not enough time/resources to handle core functionalities or toluso add much needed features.
The good news is that the Solus team is currently investing lot of energy in the tool and infrastructure to allow more contributions and faster packages delivery and also in the replacement of the 3rd party repository by snaps which will improve the user experience. This also brings many new applications to Solus.

Regarding your particular issue, although it is not what you want, a possible workaround would be to use ms-office with wine/playonlinux. You would not face compatibility issues anymore and you won't have to switch to windows._

**Comment by radomir-lilic** [comment]
BTW that thread you linked too, is marked as closed... That's the reason I did not post anything there.

**Comment by charlesjt** [comment]
@radomir-lilic There is no licensing problem with OnlyOffice Desktop Editors so that it is sidelined to the third-party repository (Flatpak or Snap) and many of the apps in the third-party repository have been created by the same solus team, in addition to recommending ms-office in wine more seems a response of a volunteer in a social network.

On the ticket in phabricator is marked as "Wontfix" and in some ways still active receiving comments and duplicate ticket, since OnlyOffice is becoming popular (with the next version 5 and its new UI there will be more reasons to include it).

**Comment by radomir-lilic** [comment]
That was response from <b>kyrios<b/> if you are curious about it.

**Comment by radomir-lilic** [comment]
I really like onlyoffice as when using it on Ubuntu or Mint I was able to open all complex documents without formatting errors but also the interface was very intuitive... the only thing that I didn't like is on my high DPI display it didn't quite look good. I guess they need to work on it to optimize interface for 4K/5K displays.

**Comment by BearzRobotics** [comment]
#59 This issue already existed and I'm going to close it so as not to have a duplicate.

**Comment by agolybev** [comment]
Hi all, I'm working on snap for Desktop Editor now, but I don't sure about it on Solus OS.

**Comment by BearzRobotics** [comment]
Why wouldn't it work on Sous OS. The point of snaps are to be cross distribution. So if you actually put all of your dependencies in the snap it should work fine.

**Comment by radomir-lilic** [comment]
My impression was also that the point of snaps are to be cross compatible...

**Comment by now-im** [comment]
@agolybev Visit the page and you will see all the distribution that supports snap.
https://snapcraft.io/

**Comment by liberodark** [comment]
Solus OS have same possibility of arch for install software .deb is good or appimage or flatpak

**Comment by BearzRobotics** [comment]
Solus has snap support out of the box. I personally use it for Nextcloud, gnucash and freecad.

**Comment by ShockwaveNN** [comment]
Guys, we currently have in testing snap version of DesktopEditors and it working fine on Solus OS. So just wait for final release.

**Comment by radomir-lilic** [comment]
Amazing! Thanks.

**Comment by agolybev** [comment]
Hi, we've got a release candidate snap of DesktopEditors.
Install it with 'snap install --candidate onlyoffice-desktopeditors'
Please report any issues you find out while testing this snap on [GitHub issue tracker](https://github.com/ONLYOFFICE/snap-desktopeditors/issues).

**Comment by charlesjt** [comment]
@now-im Look [here](https://docs.snapcraft.io/core/install) for real support of snapd

@BearzRobotics As @liberodark  says, Solus OS offers official repositories for Flatpak packages in addition to Snap, on the other hand the support for snapd integration on software store was [delayed a bit](https://solus-project.com/2018/02/14/plasma-and-solus-4-updates/#solus-4).

I like the initiative to offer more portable distribution systems, however, it would be a good idea to consider the [adoption](https://kamikazow.wordpress.com/2017/02/09/adoption-of-flatpak-vs-snap/) of these new technologies. In practice, software that offered a *.deb package for Ubuntu and derivatives doesn't get as broad a scope as expected, since snap is still difficult to use for distros where it is now easy to use a Flatpak or AppImage package.

**Comment by agolybev** [comment]
Hi @charlesjt .
We’ll definitely think it over.

**Comment by Juankz** [comment]
We should close this issue as snap is already available (https://snapcraft.io/onlyoffice-desktopeditors)

**Comment by ShockwaveNN** [comment]
@Juankz yep, you're right, closing
