### ISSUE TITLE
Change Case Option is Missing

### ISSUE THREAD

**Issue by gelatinbomb** [ONLYOFFICE/DesktopEditors#631]
Hi! I'm new using your software and I have to say its really cool. I'm a basic user so almost all the tools I need are here except for one and its important.

**Bug Report**

**What is the current behavior?**
The option to change the case on text words and paragraphs is missing. The documentation says it should be on the format options. 
Take a look on the documentation: https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Document-Editor/UsageInstructions/FontTypeSizeColor.aspx

![2021-05-30 17_33_22-Window](https://user-images.githubusercontent.com/31792239/120261102-715e9f00-c254-11eb-9c8f-b9d7b045ad1e.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Check the text formatting options in the ribbon tab. 

**What is the expected behavior?**
The button should be there

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
6.2.0.148

Thanks for reading!

**Comment by Iangh59** [comment]
Available in v6.3, https://www.onlyoffice.com/blog/2021/05/onlyoffice-docs-v6-3-dark-theme-150-scaling-protecting-files-with-passwords-updated-reviewing/, which is not yet released for DesktopEditors.

**Comment by gelatinbomb** [comment]
Got it! I will wait then :D
