### ISSUE TITLE
Change "DesktopEditors" to "OnlyOffice" in application title

### ISSUE THREAD

**Issue by CHJ85** [ONLYOFFICE/DesktopEditors#632]
**Do you want to request a *feature* or report a *bug*?**
Not really a bug but sorta.

**What is the current behavior?**
App title says "DesktopEditors".

**What is the expected behavior?**
Should say "OnlyOffice".

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Stable channel from Flathub

This is not a huge deal. But for the sake of professionalism, I think that the application title should say OnlyOffice rather than DesktopEditors

![see image](https://user-images.githubusercontent.com/12821304/120345209-cbf60a80-c2e9-11eb-917a-564058d7140f.png)

**Comment by matveevms** [comment]
Hello, @CHJ85 
Thank you for report.
I can confirm - this is bug, issue 50685 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue fixwd (https://github.com/ONLYOFFICE/desktop-apps/commit/5082f0f2457207d934d8321aed53370d4239ff8c, https://github.com/ONLYOFFICE/desktop-apps/commit/6b710ea45befc640c8fb272d6ea08b8b9a70397d).
@matveevms @CHJ85 please state is this problem still actual for you?

**Comment by CHJ85** [comment]
Yup, the issue is fixed.
I'll go head and close this issue.
Thanks, @Rita-Bubnova

**Comment by Rita-Bubnova** [comment]
@CHJ85, thank you for fast response. 
Feel free to comment or reopen it if you got further questions.
