### ISSUE TITLE
Images with gradients in powerpoint documents dont work

### ISSUE THREAD

**Issue by kylagit** [ONLYOFFICE/DesktopEditors#636]
Heres a screenshot
https://imgur.com/a/GwGd7Ox
Heres the intended behavior
https://binaries.templates.cdn.office.net/support/templates/en-gb/lt22977542_quantized.png

**Comment by ShockwaveNN** [comment]
@Freddie-Green Hi, we need original file and to be clear - state versoins of your system and product

**Comment by Freddie-Green** [comment]
Im using Linux Mint Xfce 20.1 and use the Debian 8/Ubuntu 14.04 version from your website, i have version 6.2.0.148, you can donwload the original file at https://templates.office.com/en-gb/outdoors-presentation-tm22977542, the direct download link is https://binaries.templates.cdn.office.net/support/templates/en-gb/tf22977542_win32.potx

**Comment by ShockwaveNN** [comment]
@TatianaKirillova Please take a look at this issue

**Comment by TatianaKirillova** [comment]
Hello, **@Freddie-Green**
Thanks for your request!
I can confirm that the problem exists. I created ticket 50827 in our private  tracker with your issue.

Problem reproduces in Document Server.

**Comment by trofim24** [comment]
Fixed in 6.4.0
