### ISSUE TITLE
Conditional formatting doesn't save properly in xlsx files

### ISSUE THREAD

**Issue by janxkoci** [ONLYOFFICE/DesktopEditors#637]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Opening an xlsx file with conditional formatting and saving it in OO 6.2 will result in corrupted formatting.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I attach two files that demonstrate the issue (as requested in https://github.com/ONLYOFFICE/DocumentServer/issues/243#issuecomment-858379854):

1. A file created in LO 7.1, with conditional formatting: [conditional_formating-created_in_LO7.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/6633236/conditional_formating-created_in_LO7.xlsx)
2. The same file modified and saved with OO 6.2: [conditional_formating-modified_in_OO6.2.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/6633237/conditional_formating-modified_in_OO6.2.xlsx)

**What is the expected behavior?**
The formatting should be properly preserved after saving it in OO.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I am using OnlyOffice `6.2.0.148` on Linux (elementary OS 5.1 Hera, based on Ubuntu 18.04). I installed the package as `flatpak` from [flathub.org](https://flathub.org/apps/details/org.onlyoffice.desktopeditors).

**Comment by janxkoci** [comment]
The issue is less severe when using ODF format (`.ods`), but still it's not perfect.

This is the same file as above re-saved to ODF using LO 7.1, then modified and saved again as ODF using OO 6.2:

[conditional_formating-created_in_LO7.ods](https://github.com/ONLYOFFICE/DesktopEditors/files/6633282/conditional_formating-created_in_LO7.ods)
[conditional_formating-modified_in_OO6.2.ods](https://github.com/ONLYOFFICE/DesktopEditors/files/6633283/conditional_formating-modified_in_OO6.2.ods)

**Comment by LuckySpecialist** [comment]
Hi, @janxkoci!
Could you describe the problem in more detail and attach some screenshots?
Оn my Windows 10 system and OO Desktop Editors 6.2 XLSX files look identical:
<img width="351" alt="OO_Desktop_xlsx_view" src="https://user-images.githubusercontent.com/19473546/121666235-b1721d00-cab1-11eb-8546-fa223031f48c.PNG">
and ODS files only differ in column width:
<img width="381" alt="OO_Desktop_ods_view" src="https://user-images.githubusercontent.com/19473546/121666288-bf27a280-cab1-11eb-8404-62679468dcc9.png">

**Comment by janxkoci** [comment]
Well, for start in the ODS file you can see missing negative data bars even in your screenshots.

Here is a screenshot (posted also in the linked issue) of the file after saving in OO and reopening in LO:

![Snímek z 2021-06-09 17-35-34](https://user-images.githubusercontent.com/19331850/121815852-b7662a80-cc78-11eb-8d71-0e731a09c809.png)

**Comment by LuckySpecialist** [comment]
A bit of theory: our application is based on the OOXML format and for LibreOffice it is ODF. When converting from one format to another, there may be problems.
Therefore, if you are talking about a problem with cross-conversion, then I will ask you to give a clear script and the source file, so that we can repeat the problem. If it is confirmed, we will inform our developers.
The files that you provided in the description did not show any problems.

**Comment by janxkoci** [comment]
The case of ODF files was just for the sake of completeness. I don't care about conversion between formats (I don't know anybody who uses ODF to be honest).

This issue is about modifying XLSX files with conditional formatting (created in another office suite) using OO, where saving the file corrupts the format, so it no longer renders properly in those other office suits.

**Comment by LuckySpecialist** [comment]
We are looking at the problem of displaying a document in our editor (not a third-party one) - right?
Then we take the original XLSX file you attached and compare it with the modified one in our editor and see the result. Judging by my screenshot above, they are the same.
Case closed?

**Comment by janxkoci** [comment]
No, we are looking at problem where OO **save feature** doesn't properly keep original format of a file, even though the OO website claims it always preserves format properly.

**Comment by LuckySpecialist** [comment]
I'm trying to find out if you have any format mismatches in our app. But so far, I only see screenshots of third-party editors.
Our main format is OOXML and here is the proof:
<img width="960" alt="MS_OO_Documents_SideBySide_Comparition" src="https://user-images.githubusercontent.com/19473546/122070451-a8a98000-cdfe-11eb-99ac-05757178cc91.png">
Your XLSX document is displayed the same way without loss of formatting.
If you do not like the display in third-party editors, then you can address it directly to them, we can not help here.

**Comment by janxkoci** [comment]
Well the only Excel I have access to is the web app, so it's not easy for me to check this, but I guess it's a valid reasoning, if OOXML is a priority.

Btw LO allow me to save in "MS Word" docx or OOXML docx. I mostly use the Word one (because Word didn't support OOXML very well in the past), but I could try the other tomorrow (I'm on phone now).

**Comment by janxkoci** [comment]
So I tried the OOXML in LibreOffice. Modifying the file in OnlyOffice will make the file render differently in different offices afterwards:

- LO = bad (similar to above)
- WPS office = better (similar to above)
- MS office for android = almost perfect (negative data bars with gradient are blue instead of red, solid-colours are okay)

![tempFileForShare_20210620-163047](https://user-images.githubusercontent.com/19331850/122677965-f9492080-d1e4-11eb-9c78-6b22781279d7.jpg)

So I guess it's really an issue with the other office suits. I'm closing this issue.
