### ISSUE TITLE
Scaling issue on laptop

### ISSUE THREAD

**Issue by telometto** [ONLYOFFICE/DesktopEditors#638]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Wrong scaling of the software

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I don't know how to reproduce it. I have installed it through `flatpak`.

**What is the expected behavior?**
The expected behavior would be that it opened in proper scaling.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Version 6.2.0 from flathub. OS: Fedora 34. Yes, it used to work flawlessly.
![Screenshot from 2021-06-10 20-47-54](https://user-images.githubusercontent.com/65364211/121580932-965dc980-ca2d-11eb-8e89-19bf6c5a703b.png)

**Comment by ShockwaveNN** [comment]
@telometto Could you state you display resolution and display size?

**Comment by telometto** [comment]
1920x1080. I even tried to change it in the configuration file. However, opening the program reverts the config file to the original state.

**Comment by ShockwaveNN** [comment]
@telometto And display size? In inches?

**Comment by telometto** [comment]
Pardon, I missed that part. It's a 13" display (PC model: Dell E7270).

**Comment by ShockwaveNN** [comment]
Oh, as far as I remember we got troubles with samll displays with FullHD resolution

@matveevms could you take a look? Do we already have an open issue for this?

**Comment by maydayv7** [comment]
Yes, same problem here with a Dell Inspiron 15 5509

**Comment by unomi-zan** [comment]
Any update on this issue? It's too big on 100% scaling and everything is blurry on 125% scaling on wayland.

**Comment by matveevms** [comment]
Sorry for the long wait. Please tell me, is the problem still relevant in new versions of the editor?

**Comment by maydayv7** [comment]
It seems to be alright now (OnlyOffice 7.2). Thanks a lot!

**Comment by matveevms** [comment]
Thank you for contacting us.
