### ISSUE TITLE
OO v6.3, zilexa tweak to change language - powerpoint issue: spelling not working on Title page

### ISSUE THREAD

**Issue by Iangh59** [ONLYOFFICE/DesktopEditors#642]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I used zilexa's tweak to change the language to en-AU, https://github.com/zilexa/Ubuntu-Budgie-Post-Install-Script/tree/master/onlyoffice. It works fine with .docx and .xlsx, but with .pptx there is an issue: the en-AU spelling does not work on the Title page.

Opening a new presentation it seems to be working fine
![2021-06-29time09-00](https://user-images.githubusercontent.com/62003324/123714258-4f8b2300-d8b9-11eb-8afb-0d2fd7ab3c9c.png)

but if I add my favourite American word "center" to check the spelling is working, the language changes to Czech.
![2021-06-29time09-01](https://user-images.githubusercontent.com/62003324/123714417-97aa4580-d8b9-11eb-8692-cd90f1209890.png)

when I deselect the section the language returns to en-AU, but center is not flagged as a spelling mistake.
![2021-06-29time09-01_1](https://user-images.githubusercontent.com/62003324/123714530-d50ed300-d8b9-11eb-8d3b-4be0dec626b3.png)

To get it working I need to add a new slide.
![2021-06-29time09-02](https://user-images.githubusercontent.com/62003324/123714557-e48e1c00-d8b9-11eb-94a5-85ccbdfd262a.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Please see above.

**What is the expected behavior?**
en-AU spelling should work on Title page

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Editors version 6.3.1.56
Kubuntu 20.04

I didn't check whether it was working properly in 6.2.

**Comment by ShockwaveNN** [comment]
Since this is an ufficial way to change language - only solution I see to wait until we fully implement changing language in fully supported way

Or at least you can try to see if this hacked worked in any previous version and in that case we'll try to figure out why it broked

**Comment by Iangh59** [comment]
Is it on the roadmap?

**Comment by ShockwaveNN** [comment]
@Iangh59 sorry, I'm not aware of this

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
