### ISSUE TITLE
Customize zoom/scroll speed and zoom limits

### ISSUE THREAD

**Issue by julianomasson** [ONLYOFFICE/DesktopEditors#650]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I can't change the zoom/scroll speed and zoom limits.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Customize the zoom/scroll speed and zoom limits.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Version 6.3.1.56, Windows. I don't know.

**Comment by ShockwaveNN** [comment]
Hi, could you describe you proposition in more details? Because we do not fully understand that you want

Is this setting present in some other office suites?

**Comment by julianomasson** [comment]
Hi, sorry, I tried to stick with the default questions.

I recently switched to ONLYOFFICE from LibreOffice, and the first thing that I noticed is the difference in zoom/scroll speed. The amount of scroll "ticks" needed to move the same amount of content on the screen is bigger in ONLYOFFICE. Since I'm used to LibreOffice this caused the wrong feeling that OLYOFFICE is slower.

The zoom limits is also a little bit different (and maybe the cause of different acceleration curves in the zoom speed?) ONLYOFFICE goes from 50% to 200% while LibreOffice goes from 20% to 600%. It can be a little exaggerated, but it helps me to show some content to people that are further from the monitor.

I tried to find this setting in LibreOffice and I couldn't find it as well.

I really liked the ONLYOFFICE, this was the most noticeable difference , maybe I just need some more time to get used to it.

**Comment by ShockwaveNN** [comment]
I think for increasing zoom limits is better to create separate issue

But about fast scroll - could this be a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/536

**Comment by julianomasson** [comment]
I don't think it is a duplicate, I don't experience this behavior with spreadsheets.

**Comment by ShockwaveNN** [comment]
ah, this is for Document Editors?

@Rita-Bubnova could you create an enhancement with new option to setup scroll speed for single mouse scroll?

Personally I don't think we need or even able to implement this option, but it's up to dev team to decide if we need it

**Comment by julianomasson** [comment]
Yes, it is for documents.

I think it would be easier for people switching from LibreOffice, but I understand that is a mostly unnecessary complexity in the UI.

Thanks.

**Comment by ShockwaveNN** [comment]
I just take a look at my system and seems scrolls speed are very similar

Could you record a video with similar comparison on your system?


https://user-images.githubusercontent.com/668524/124621608-15a2b980-de83-11eb-884b-175c24f787fd.mp4

**Comment by julianomasson** [comment]
I couldn't make the video fit in the 10MB restriction, so here is the link: https://drive.google.com/file/d/1Dy4NSYxpHn0ZxBt6nl2p1wURbg601mgK/view?usp=sharing 

With both side by side the difference isn't so noticeable, Libre is just a little bit faster.

**Comment by ShockwaveNN** [comment]
@julianomasson So, I cannot see any major difference of scroll speed it both cases, so I'm not sure, but I think we should not do anything in that situation

Also I'm not 100% sure that scroll speed is not something specific and we can change it

**Comment by julianomasson** [comment]
Ok, thanks for your time.

**Comment by roman-kuleshov** [comment]
Hi, did you guys figure out how to increasing zoom limits? Is it even possible? So a user can go up to 600%
