### ISSUE TITLE
The SpreadSheet doesn't complete the cross-sheet calculations after restart

### ISSUE THREAD

**Issue by dsuserds** [ONLYOFFICE/DesktopEditors#652]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

After I open a .ods what I made with OnlyOffice, some calculations(made with onlyoffice too!) referring to other sheets display "#VALUE!". If I just edit those cells manually and press enter - without changing anything - they work again.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Step 1: create a column in Sheet1 with a few numbers and then SUM them.

Step 2: refer to the sum with `=IF(Sheet1!A6<10,"OK",IF(Sheet1!A6<100,"Too Big!","Huge!"))` in Sheet2

**What is the expected behavior?**

OnlyOffice should calculate the formulas again after restart.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

OnlyOffice: 6.2.0.148, Ubuntu 20.04

**Comment by Rita-Bubnova** [comment]
Hello, @dsuserds. 
I checked it in ONLYOFFICE Desktop Editors version 6.3.1.56 on Windows 10. And this problem don't reproduce.
Could you update the version of Desktop Editors to 6.3.1 and check bug?

**Comment by dsuserds** [comment]
I downloaded the latest version and it still has the issue:

![on_load](https://user-images.githubusercontent.com/80279857/124617686-6c09fb00-de77-11eb-9e12-cefd1b5bf1f4.png)
![formula](https://user-images.githubusercontent.com/80279857/124617682-6b716480-de77-11eb-9b41-dbc51df96540.png)
![evaluated](https://user-images.githubusercontent.com/80279857/124617676-6ad8ce00-de77-11eb-81e4-d62edc3168ba.png)

When I load the document it still shows the "#VALUE!" text and I need to edit each cell and press Enter.

**Comment by Rita-Bubnova** [comment]
@dsuserds Could you attach file with problem?

**Comment by dsuserds** [comment]
Here: [test.ods](https://github.com/ONLYOFFICE/DesktopEditors/files/6794111/test.ods)

**Comment by Rita-Bubnova** [comment]
@dsuserds, thank you for file.
If you recalculate in cells B27, B28, B29 ("Calculation" option on the "Formula" tab) will the values ​​be correct?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by dsuserds** [comment]
@ShockwaveNN the response wasn't needed because the question didn't make sense. The calculations still don't trigger so the bug still exists. Manually triggering recalculation is not relevant.

**Comment by ShockwaveNN** [comment]
My teammate is asked you a question and you didn't answer at all for half a year

"Is this question related to the problem" - it's up to us to decide, but I'll reopen this issue if you answer mentioned question

**Comment by dsuserds** [comment]
The answer is in the issue description - the problem is the lack of automatic recalculation and not that I can't trigger it manually. If you think if it's up to you to decide then you didn't understand the issue at all. And if you really cared you could have tested what you wanted a thousand times over the last months. Your teammates didn't do anything about this bug for half a year and this along with a lack of certain features made me use excel over this program suite. I'll close this ticket for you so you can rest fine because bugs cease to exist when we close their reports.

**Comment by ShockwaveNN** [comment]
>  then you didn't understand the issue at all

Yes, we are. We do not understand your issue, because the description of the issue was very vague

> I'll close this ticket for you so you can rest fine because bugs cease to exist when we close their reports.

Ok, thank you, sorry that our completely free support do not meet your expectations

**Comment by dsuserds** [comment]
It's truly sad that you've a problem understanding a simple issue with a reproducible test case attached. "Cross-sheet calculations don't trigger automatically after loading the spreadshit" - gosh, what could be the issue!? It's fine, spreadsheet app development isn't for everyone and you can do a lot of other things in life! 

No problem, free QA is apparently not your thing - just like QA in general.

**Comment by Rita-Bubnova** [comment]
> the problem is the lack of automatic recalculation

This is a duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/1321.
