### ISSUE TITLE
When OnlyOffice freezes it becomes a defunct zombie process and can't be killed properly

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/DesktopEditors#653]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

When OnlyOffice freezes, `kill -9` and `kill SIGCHLD` don't work on it. This is a programming bug.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Make the program freeze with some bigger spreadsheets and you won't be able to close it without a full system reboot.

**What is the expected behavior?**

OnlyOffice should quit with X and should handle system signals.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

OnlyOffice: 6.2.0.148, Ubuntu 20.04

**Comment by ShockwaveNN** [comment]
Could you attach some sample big spreadsheet with this you have situation?

**Comment by dsuserds** [comment]
I downloaded [this file](https://github.com/ONLYOFFICE/DesktopEditors/files/6764512/Dark.Souls.3.Hyper.Armor.Parry.Timings.2.0.DLC1.ods) from someone's public google drive.

**Comment by dsuserds** [comment]
Just a quick note: the freezing is not consistent.

**Comment by ShockwaveNN** [comment]
On my system `kill` is very fast

See my video:


https://user-images.githubusercontent.com/668524/124483175-b37a8380-ddb2-11eb-901f-07cbc5650f0e.mp4

Or by handing up you mean when app literally not responsive, not just waiting for file to load

In that case I'm not sure that we can do something if we cannot simulate this situation reproducable

**Comment by dsuserds** [comment]
Kill works fine but when it's frozen it doesn't receive the signals. I can't give you a reproducible way but when it happens it becomes an unkillable zombie process.

**Comment by ShockwaveNN** [comment]
I'm not very good at understanding zombie process

Maybe some kind of way to simulate this?

**Comment by dsuserds** [comment]
This is a pretty simple app about it: https://www.geeksforgeeks.org/zombie-processes-prevention/
It also explains when processes become defunct.

**Comment by ShockwaveNN** [comment]
Thanks I'l read this, but seems by first glance it do not anwser my question - could we perform some kind operation on process to simulate it's becoming the zombie

**Comment by dsuserds** [comment]
From the article:

_If the parent decides not to wait for the child’s termination and it executes its subsequent task, then at the termination of the child, the exit status is not read. Hence, there remains an entry in the process table even after the termination of the child. This state of the child process is known as the Zombie state._ 

I think you can create a test suite for this.

**Comment by ShockwaveNN** [comment]
> I think you can create a test suite for this.

I don't think I can, if you able to provide one this will be very helpfull

**Comment by dsuserds** [comment]
Is this C++? I've a little experience with Qt and GTK.

**Comment by ShockwaveNN** [comment]
> I've a little experience with Qt and GTK.

Me neither

Maybe @K0R0L can take a look at this issue and deduct something, but I'm not sure

Until someone make a reproducible case I don't think we can do anything

**Comment by Rita-Bubnova** [comment]
The issue is closed due to absence of feedback and status update.
