### ISSUE TITLE
OnlyOffice Spreadsheet drag-and-fill doesn't work with numeric function parameter increments

### ISSUE THREAD

**Issue by dsuserds** [ONLYOFFICE/DesktopEditors#654]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

Dragging VLOOKUP where only the column reference number should get increased doesn't work.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Reference a data set with VLOOKUP then increase the column reference with the vlookup columns to the right.

**What is the expected behavior?**

OOS should increase all parameters, not just cell references.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

OnlyOffice: 6.2.0.148, Ubuntu 20.04

**Comment by Rita-Bubnova** [comment]
Hello, @dsuserds.
Could you attach file with problem?

**Comment by dsuserds** [comment]
Hi!
The formula is at Sheet1!B2:C2 - if you extend it to E2 it won't increase the column index, it'll just repeat the 2 and 3 indices.
[Book1.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/6770811/Book1.xlsx)
Another problem is that I can't extend vertically either because I need to anchor it to the row(A2) because I won't be able to extend it horizontally.

**Comment by alinasafonova** [comment]
Hello, @dsuserds
I extended formulas to the right in ONLYOFFICE and in MS Excel and got the same result:
![Screenshot_20210708_123111](https://user-images.githubusercontent.com/53475320/124902307-79e08d00-dfeb-11eb-8f34-97a024d503f9.png)
![Screenshot_20210708_122825](https://user-images.githubusercontent.com/53475320/124902404-8fee4d80-dfeb-11eb-95c7-a01e396c359e.png)

**Comment by dsuserds** [comment]
Hello @alinasafonova! Yeah, it's sad but it would be great if it would work.

**Comment by Rita-Bubnova** [comment]
Hello.
@dsuserdsб we do not plan to change this in Desktop Editors. This behavior is the same as in MS Excel, because XLSX is the main format for ONLYOFFICE Desktop Editors.

**Comment by ShockwaveNN** [comment]
This issue was closed since we are not planning to change that
