### ISSUE TITLE
FR: bullet points animation

### ISSUE THREAD

**Issue by ggrrll** [ONLYOFFICE/DesktopEditors#655]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
missing  bullet points animation

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

I think this is also missing in the DE, but I am using the web app on owncloud 

this has been reported already here
https://dev.onlyoffice.org/viewtopic.php?t=27403
and I was wondering if there are updates 

Thanks

**Comment by ShockwaveNN** [comment]
Hi currently we do not support not only bullet points animations, but other animations also, so this is duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/348

**Comment by razzeee** [comment]
Should this be reopened, as animations are now there, but bullet points seemingly can't be animated?

**Comment by ShockwaveNN** [comment]
@razzeee I think so, but original topic on dev.onlyoffice.org is lost so I think it's better to create a new issue with file example and we'll analyze it
