### ISSUE TITLE
DesktopEditors Connect to Cloud option no longer works. 

### ISSUE THREAD

**Issue by yoasty** [ONLYOFFICE/DesktopEditors#658]
**I want to report a *bug***

**What is the current behavior?**
CONNECT TO CLOUD and then adding a cloud by selecting personal.onlyoffice.com or logging in with Google-account, both open a browser-window to allow user-input for the login. But both fail to login and when trying to log-in with google their systems complain that the browser is too old. (see OCRd screenshot below.)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. start desktopeditors. 
2. choise "connect to cloud" then add-cloud for a personal.onlyoffice.com account or try to log in with a google-UID. This will open a browser as a tab in desktopeditors. 
3. use details to try to log in with credentials. Fails. 

When trying to use google-ID this text shows (OCR'd screenshot. ):
"Couldn't sign you in
This browser or app may not be secure.
Try using a different browser. If you're already using a
supported browser, you can refresh your screen and try
again to sign in"

**What is the expected behavior?**
The expected behaviour is to log in to the site and offer document-access in tabs in desktopeditors. I really like that option. 

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

ChromeOS/Cloudready and Manjaro-Linux. Both are rolling and have all updates processed. Desktopeditors in the deb-variety and appimages show the same problem. I have noticed this behaviour since Desktopeditors 6.2 and now in 6.3.

**Comment by matveevms** [comment]
Thank you for report.
I can confirm - this is bug, issue 51147 in our private issue tracker.

**Comment by yoasty** [comment]
Installed 6.4.1 and cloud is working again. Great. Thanks.
