### ISSUE TITLE
App freezes just after hitting close

### ISSUE THREAD

**Issue by necros2k7** [ONLYOFFICE/DesktopEditors#660]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
App freezes just after hitting close
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Install, open any document, try to close with right top cross icon
**What is the expected behavior?**
Don`t freeze
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
6.3.1 , win10x64 20h2
ps. if I remember right same issue was reported by couple of users in forum

**Comment by ShockwaveNN** [comment]
Could you record a video?

**Comment by necros2k7** [comment]
Will try

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
