### ISSUE TITLE
[Feature] 125% 175% Scaling

### ISSUE THREAD

**Issue by utk-dev** [ONLYOFFICE/DesktopEditors#664]
**Do you want to request a *feature* or report a *bug*?**
Feature

Laptops with 15 inch screens and 1080p resolutions are very common. 125% is the perfect sweet spot for scaling on such systems, especially on Desktop Editors. I am willing to contribute in whichever way possible to make this happen.

**Comment by Rita-Bubnova** [comment]
Hello, @utk-dev.
Thank you for enhancement.
This is issue 47624 in our private issue tracker.

**Comment by ShockwaveNN** [comment]
Issue 47624 is also about 175% scale so this issue should be also about it

**Comment by MehdiChinoune** [comment]
I need 250% scale for my laptop with 15.6/4K display.

**Comment by ShockwaveNN** [comment]
@MehdiChinoune Could you create separate issue about 250% scaling? Because we currently have no plans to implement this and to not to clubber this issue for 125 and 175 which will available some time soon

**Comment by utk-dev** [comment]
@ShockwaveNN how about using SVG icons everywhere in the UI so that these scaling issues can be solved once and forever... I am sure this will be a lot of work (specifying relative lengths of items instead of fixed etc.) but it will still be less than the work that the team has to put in for every new scaling request.

**Comment by ShockwaveNN** [comment]
@utk-dev It's up to developers to decide. They 100% tryed to implement solution using SVG and as far as I remember - result was blurry and worse that original situation

**Comment by Rita-Bubnova** [comment]
Now we are testing 125 and 175% scaling on Desktop Editors. We will add it in the next major release. 
A lot of commits related to this feature, so without any particular commit reference.

**Comment by jmaris** [comment]
Any update on this? and how would we go about enabling this ?

**Comment by ShockwaveNN** [comment]
@jmaris Thanks for noticing, seems that we forgot to close this issue

125% and 175% and some other display scaling is already implemented for quite a time, but for some specific, like 300% we got separate issues
