### ISSUE TITLE
[BUG] Can't remove deb package. What is the package name?

### ISSUE THREAD

**Issue by RDKRACZ** [ONLYOFFICE/DesktopEditors#668]
v6.2.0 on Pop OS 21.04.
`sudo apt remove onlyoffice-desktopeditors` results in `No apt package "onlyoffice-desktopeditors"`
None of the commands below can find the package
`apt search onlyoffice-desktopeditors` `apt search desktopeditors` `apt search onlyoffice` .

What is the package name?

**Comment by ShockwaveNN** [comment]
If you using Pop OS maybe you've installed flatpak?

```
flatpak list
```

This may help you

**Comment by RDKRACZ** [comment]
I did install flatpak version, wanted to switch from snap. Didn't know you can't just start flatpak app as you can snap (if you have onlyoffice snap you can just type onlyoffice-desktopeditors, don't know why you can't do that with flatpak)

Thanks for the help.
