### ISSUE TITLE
Spellcheck isn't working (except local editing)

### ISSUE THREAD

**Issue by realkot** [ONLYOFFICE/DesktopEditors#67]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I work on remote docs in desktop editor, spellcheck inactive:
![image](https://user-images.githubusercontent.com/24507273/30911412-3287f30c-a391-11e7-90a6-7242c043beb2.png)
When working in browser the spellcheck is working:
![image](https://user-images.githubusercontent.com/24507273/30911512-9492c658-a391-11e7-8af0-73b233730562.png)

**What is the expected behavior?**
Spellcheck works in desktop editors.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Win7 x64 Pro
OO DE x64 4.4.1.342

**Comment by realkot** [comment]
Any info\update about this issue?

**Comment by agolybev** [comment]
Hi Artem, we'll investigate it.

**Comment by ShockwaveNN** [comment]
I think this issue should be resolved by current stable version. Feel free to comment.
