### ISSUE TITLE
[NOISSUE] Issue templates preview.

### ISSUE THREAD

**Issue by RDKRACZ** [ONLYOFFICE/DesktopEditors#677]
## I created this issue to showcase the issue forms and get some feedback before making any PRs.

You can see the code here: https://github.com/RDKRACZ/DesktopEditors/tree/forms-tests/.github/ISSUE_TEMPLATE

### Here is what users will see when they click the "New issue" button:

<details>

![Screenshot from 2021-07-21 00-33-52](https://user-images.githubusercontent.com/43277609/126404371-57fe145a-f42e-498c-893f-76378e69049d.png)

</details>

The Appimage/Flatpak/Snap package button redirects the users to the appropriate issue tracker before making an issue, ex. the Appimage button will redirect to https://github.com/ONLYOFFICE/appimage-desktopeditors/issues?q=. There the users will see a similar template chooser but only with the bug report and feature request form.

### Feature suggestion form:

<details>

![Screenshot from 2021-07-21 00-34-30](https://user-images.githubusercontent.com/43277609/126404872-15b96a2e-1ae0-4b64-849e-703b07a18c2a.png)

</details>

### Bug report form:

<details>

![Screenshot from 2021-07-21 00-35-37](https://user-images.githubusercontent.com/43277609/126404916-036596cf-1d9f-4fc1-a331-b6f2a5e4f639.png)

Closer look at the OS chooser:

![Screenshot from 2021-07-21 00-35-46](https://user-images.githubusercontent.com/43277609/126404923-22f3bc61-2688-4d1a-9f38-593e0a737110.png)

</details>

**Comment by ShockwaveNN** [comment]
I totally love those templates, thank you

One minor touch - Android and iOs apps are separate entities from `DesktopEditors` and I think they should be removed from OS Chooser

**Comment by RDKRACZ** [comment]
I removed:
- mentions about the mobile versions from the template description and OS chooser.
- OS chooser from the Appimage, Flatpak, and Snap versions because these packages are Linux only.

I think I should also remove the feature request template from the Appimage, Flatpak, and Snap versions because it's unlikely someone would have a package/version-specific feature request. Instead, maybe add a redirect to the main repo for a feature request or just edit the "OS native packages" into "OS native packages and feature requests" (this should be the best option because it would allow having four buttons instead of five on these repositories).

A Look from the Appimage repository:

![Screenshot from 2021-07-22 01-10-33](https://user-images.githubusercontent.com/43277609/126571256-e28bb669-c110-46fc-b82a-95d9f1f83276.png)

**Comment by ShockwaveNN** [comment]
I think we should start from this repo since 90% issue are posted in here, not in snap or flatpak (usually issue reporters do not check if problem actual for only one specific installation method)

So I think the sooner we start using this template - sooner we can analyse if this helped users to post more detailed reports, or are they just delete everything and post something like "plese help, not woking"

Could you create a PR with this changes to this repo?

**Comment by RDKRACZ** [comment]
Sure, will open PR now.

> (...) or are they just delete everything

What differs issue forms from the standard template.md is that the users cannot delete any content of the template but yeah they can just ignore questions and write "please help" in all required fields.

**Comment by ShockwaveNN** [comment]
Thanks you very much, we merged your issues

I think we'll monitor how well they work for users and collect feedback and if everything is fine - make similar forms for DocumentServer repo
