### ISSUE TITLE
Native title bar

### ISSUE THREAD

**Issue by k4r7u** [ONLYOFFICE/DesktopEditors#68]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
Non native title bars on elementary OS

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
It would be great to be able to use native title bars on Linux. I am currently using elementary OS Loki and the dark title bar with non native minimize, maximize and close buttons looks a little off. Alternatively is there a way to "mod" the title bar color and buttons?

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
DesktopEditors 4.4.1.338
OS: elementary OS Loki 0.4.1

**Comment by maxkadushkin** [comment]
try to launch app with --system-title-bar key

**Comment by k4r7u** [comment]
Thank you very much.
Launching it with this flag uses the system title bar. Looks perfect on elementary OS.

**Comment by ShockwaveNN** [comment]
@janxkoci You should edit at `~/.config/onlyoffice/DesktopEditors.conf` file and maybe remove it at all

**Comment by janxkoci** [comment]
That didn't work :confused: 

I should mention I installed OnlyOffice as `flatpak` and turned on the setting by running:

```bash
flatpak run org.onlyoffice.desktopeditors --system-title-bar
```
