### ISSUE TITLE
Poster-making features (e.g. portrait mode) in presentations app

### ISSUE THREAD

**Issue by janxkoci** [ONLYOFFICE/DesktopEditors#680]
**Do you want to request a *feature* or report a *bug*?**
Feature request.

**What is the current behavior?**
In presentations, I don't see any possibility to change slide orientation (e.g. portrait for making posters), or even aspect ratio (for different monitors / projectors).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
It's more of an omission than a real bug. Hence a feature request.

**What is the expected behavior?**
Other office suites allow changing aspect ratio and slide orientation (from landscape to portrait). This allows adapting the presentation to monitors / projectors with other aspect ratios, or to make posters.

In academia, people often use MS Powerpoint / LO Impress to create not just presentations for conferences, but also posters for poster sessions at those conferences. Yes, other software exists that can be more suitable (e.g. Scribus, LO Draw, etc). **But most people I know use Powerpoint.** Simply because it's already familiar and easy to use (especially when compared to e.g. Scibus).

If you want to attract these users, offer them portrait orientation in your presentations app. It's probably a very easy fix anyway and everybody will gain. And while you are at it the aspect ratios are a no-brainer too.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I have a version 6.3.1.56 (Ubuntu linux, flatpak). I'm not aware that this was possible in the past versions.

**Comment by ShockwaveNN** [comment]
This one?

![image](https://user-images.githubusercontent.com/668524/126762468-df985cb5-f48f-461e-95fb-0dd32e899f27.png)
![image](https://user-images.githubusercontent.com/668524/126762437-2966a776-9350-4003-80c5-83e57455a11d.png)

**Comment by janxkoci** [comment]
Aha! :smiley: 

Thanks, closing then.
