### ISSUE TITLE
Huge Memory Leak

### ISSUE THREAD

**Issue by longyn** [ONLYOFFICE/DesktopEditors#690]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

6.3.1

### Expected Behavior

No Memory leak

### Actual Behavior

Huge memory leak, System memory exhaust
![image](https://user-images.githubusercontent.com/5205838/127414488-ff61d277-5852-474d-8164-1b63709cadfc.png)

**Comment by ShockwaveNN** [comment]
Hi, memory leak rather hard to detect without any addional information

So

1. Does this leak happens on any file, or just by opening DesktopEditors without any file?
2. Does this leak happens on another pc with same scenario?
3. Could you record a video if there is some specific steps in which leak happens

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
