### ISSUE TITLE
Window snapping not working on Ubuntu 21.04

### ISSUE THREAD

**Issue by Netherquark** [ONLYOFFICE/DesktopEditors#696]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

6.3.1.56

### Expected Behavior

For window tilling, Ubuntu has the shortcut "Super + Left" or "Super + Right" like this:
![image](https://user-images.githubusercontent.com/65618735/128661233-4bcfa468-8813-492a-8f6d-c2b1c6d67e8a.png)

This works for mainly all GUI based programs. After using this combination, the following is visible:
![image](https://user-images.githubusercontent.com/65618735/128661362-451e7c60-51ea-4352-91cd-f6fd2d13511d.png)

With Settings on the left, and the Terminal on the right.

### Actual Behavior

Mostly, *nothing* happens if you press the keyboard shortcut for this.

### Reproduction Steps

1. Open OnlyOffice.
2. Try "Super + Left" or "Super + Right"

### Additional information

NA

**Comment by matveevms** [comment]
Hello, @Netherquark 
Thank you for reporting this bug
Issue 51840 has been created in our private issue tracker.

**Comment by Netherquark** [comment]
Note: I switched to Manjaro (GNOME), and the snapping works perfectly. The difference between installation was that on Manjaro, OnlyOffice is included by default, whereas on Ubuntu I added the PPA and installed using APT.

**Comment by ShockwaveNN** [comment]
@Netherquark Thanks for info, we still found that there is something wrong and reported a bug to our dev team

I don't think difference that in Manjaro it's included by default - the reason
Maybe some version differences, because we do not provide official Manjaro aur, so I really do not know which version is there

**Comment by Netherquark** [comment]
Its gone on Fedora-GNOME using the official RPM package. So I presume I can close this?

**Comment by AdmnJ** [comment]
Same issue on Arch Linux using the AUR and Gnome.
![image](https://user-images.githubusercontent.com/43836753/178114061-48b726ba-9450-49d3-834d-6e69915ef5b2.png)

**Comment by AdmnJ** [comment]
[Screencast from 07-09-2022 01:01:21 PM.webm](https://user-images.githubusercontent.com/43836753/178117656-fdf72ffc-c40e-47b9-b269-4b32d6863790.webm)

**Comment by ShockwaveNN** [comment]
@AdmnJ Yep, issue is still not resolved, we'll notify when there will be some changes

**Comment by Mylloon** [comment]
That is weird because it is working for me with the same configuration

**Comment by AdmnJ** [comment]
> 

I have been having the issue on my main PC but just recently did a basic install on a second machine using "default" configurations from the wiki guides... Same issue turned up there, so you might have something special in your setup that makes it work. Are you using a different version, window manager, or any non-typical packages that might change how windows are treated?

**Comment by XDmitryK** [comment]
This feature was released in version 8.2

**Comment by Rita-Bubnova** [comment]
DesktopEditors v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
