### ISSUE TITLE
DesktopEditors does not start after installation on windows 10

### ISSUE THREAD

**Issue by mm3** [ONLYOFFICE/DesktopEditors#7]
bug

ONLYOFFICE DesktopEditors v 4.1.2.270 x64 for windows 10
1. Run from icon on desctop failed
2. Run from start menu failed
3. Run from duble click on DesktopEditors.exe failed
4. Run from duble click on launch.bat failed

Application start only from command:

launch.bat "C:\Program Files\ONLYOFFICE\DesktopEditors\DesktopEditors.exe"

**Comment by maxkadushkin** [comment]
do you get some error messages when it's failed?

**Comment by mm3** [comment]
![application-error](https://cloud.githubusercontent.com/assets/985502/19678351/15c792b2-9aa6-11e6-8d16-a6bee50c2b19.png)

**Comment by maxkadushkin** [comment]
what about the edition of your win 10?

**Comment by mm3** [comment]
Edition: Windows 10 Home Single Language 
Version: 1607
OSBuild: 14393.321
System type: 64-bit

**Comment by maxkadushkin** [comment]
could you copy 5 libs (DjVuFile.dll, HtmlRenderer.dll, PdfReader.dll, PdfWriter.dll, XpsFile.dll) up one level from programfiles/.../desktopeditors/converter folder?

**Comment by mm3** [comment]
Yes it fix this problem.

**Comment by maxkadushkin** [comment]
good! irregular bug in installation package

**Comment by fitsuli** [comment]
Problem still there

RUS:
Проблема всё ещё присутствует, и у меня нет ни одного стороннего офиса - поставил только этот

**Comment by K0R0L** [comment]
Пожалуйста проверьте переменную среды PATH. Есть ли там ссылка на папку C:\Program Files\ONLYOFFICE\DesktopEditors\converter?

**Comment by fitsuli** [comment]
Кажется, всё на месте
![path](https://cloud.githubusercontent.com/assets/15420278/25240678/e478bf90-260c-11e7-896f-4a48f5808ef0.jpg)

**Comment by yatsukav** [comment]
I also ran into this problem. [Maxkadushkin's](https://github.com/ONLYOFFICE/DesktopEditors/issues/7#issuecomment-256683357)  decision helped. But I think that this is not a good idea to ask users to move files from one folder to another, where you need administrator rights.

**Comment by maxkadushkin** [comment]
yes, it's not a good idea, but it's a workaround as we haven't repeated the bug on out test computers yet

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
