### ISSUE TITLE
Save as PDF with 'overwrite existing' weird output

### ISSUE THREAD

**Issue by memen45** [ONLYOFFICE/DesktopEditors#70]
This is probably a bug.

Write a document,
Save as.. pdf -- output is correct
modify document
Save as.. pdf (with the same name)
Asks: Do you want to overwrite the existing file -> choose yes
Now the output is weird. Titles (paragraphs no longer than one line) are shown correct, all the other text is mixed up and completely unreadable:

1Thmup-vhsrgtipmersrzterpimup-vhsfpuupBehmvtiirilpfeuBongridhvrahubetgngR

The line above used to be a normal sentence.

Version:  4.4.1.342

**Comment by ShockwaveNN** [comment]
Could you attach original document, and which OS do you use?
I checked on Ubuntu, and everything seems fine for me

**Comment by memen45** [comment]
Using Windows 10, updated. For this example documents I copied a piece of text from Wikipedia
[Original docx](https://github.com/ONLYOFFICE/DesktopEditors/files/1381731/Document1.docx)
[Overwritten pdf file](https://github.com/ONLYOFFICE/DesktopEditors/files/1381732/Document1.pdf)

First time the pdf is correctly reflecting the word document.

**Comment by ShockwaveNN** [comment]
Hi, this is pretty old issue and should be fixed by now. Feel free to open new issue if problem still actual
