### ISSUE TITLE
Can not save docx to PDF on Mac OS

### ISSUE THREAD

**Issue by SolardiaX** [ONLYOFFICE/DesktopEditors#700]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

6.3.1

### Expected Behavior

It's OK to open/create and edit/save a .docx file, also is OK to save as .doc file.
Expect to save it as PDF too.

### Actual Behavior

When try to save it as pdf, no file generated and no error message return.

### Reproduction Steps

It's OK to open/create and edit/save a .docx file, also is OK to save as .doc file.
When save it as pdf, no file generated and no error message return.

**Comment by Gingetsu** [comment]
Hello @SolardiaX,
Is this problem repeated for all documents?
Could you attach some sample video with which you have problem?

**Comment by SolardiaX** [comment]
@Gingetsu ,
After check, I think this issue is due to the ttc font problem. 

To repeat:
1. Open or create a docx file
2. Enter any text (for my test, I use 'Hello World' in six languages)
3. Set text to use a ttc font (for example, set to 'AmericanTypewriter', also can pick any other ttc font from system fonts library)
4. Save (It's ok to save to docx)
5. Save as pdf. Now you find no expected pdf created and no error response.

**Comment by Gingetsu** [comment]
@SolardiaX ,
I checked it and this problem don't reproduce. Could you attach file with which you have problem?

**Comment by SolardiaX** [comment]
[Hello World.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/7032583/Hello.World.docx)
I use this document for test.

**Comment by Gingetsu** [comment]
@SolardiaX 
Thank you for reporting this bug
Issue #52278 has been created in our private issue tracker

**Comment by Gingetsu** [comment]
Hello, @SolardiaX . Our dev team is fixed your issue.
This fixed here: https://github.com/ONLYOFFICE/sdkjs/commit/7d49cdde8f11944176dce0c33949b8631c87df30

**Comment by ShockwaveNN** [comment]
Sorry, we forgot to mention that, seems that issue is fixed a long time ago, in v6.4.1

I'm closing this issue
