### ISSUE TITLE
Insert Image while editing in Document crashes OnlyOffice

### ISSUE THREAD

**Issue by StefanPopa98** [ONLYOFFICE/DesktopEditors#702]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

6.3.1.56

### Expected Behavior

After selecting insert an image from the toolbar, the application should open a file chooser to select the image.

### Actual Behavior

The application crashes instead

### Reproduction Steps

1. Open a Document in OnlyOffice
2. Select the "Insert" Tab
3. Select "Image"
4. Select "Image from file"

### Additional information

Happens on Pop!-Os 21.04

**Comment by yoasty** [comment]
ONLYOFFICE Desktop Editors version 6.3.1.56  installed as deb and also tried as appimage on debian 10.10 crostini..
I can just insert jpg and png images No problem whatsoever. 
Maybe more something POPOS or PopOS+Onlyoffice specific?

**Comment by Rita-Bubnova** [comment]
@StefanPopa98, Sorry for the long wait.
DesktopEditors v7.4.1 is released. Is this issue relevant?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
