### ISSUE TITLE
=NOW() returns right time, but wrong date

### ISSUE THREAD

**Issue by RicardoSQueen** [ONLYOFFICE/DesktopEditors#703]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

6.3.1-1

### Expected Behavior

NOW() function in suppose to return correct time and date.

### Actual Behavior

Using =NOW() function returns one day ahead. I am in UTC -3 (Brasilia time). I suspect the function gets the date from UTC 0 and then gets time from the system. Here's a screenshot from my spreadsheet:
![image](https://user-images.githubusercontent.com/64474885/131276907-cd000dc1-4fd2-42b9-ad5d-564bfc809238.png)
the Highlighted cell is the one with the formula "=NOW()" and it's returning tomorrow's date.
If I can remembred this issue tomorrow, I will try to use this function right before midnight in London and right after to see if that's the error.
I was using this Formula earlier and I did not find this issue at all..

### Reproduction Steps

open a spreadsheet late at night, somewhere local time is earlier than London, when London is already on the next day and use NOW() formula.
This is only a guess.. It's my best guess at the moment

**Comment by Rita-Bubnova** [comment]
I think, it's duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/1178.
