### ISSUE TITLE
Running the deb fails in WSL but running the appimage does not fail. 

### ISSUE THREAD

**Issue by yoasty** [ONLYOFFICE/DesktopEditors#704]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

6.3.1.56

### Expected Behavior

When the *.deb is installed in wsl under w10 it crashes. I thought this was just a fact of life, probably related to some dbus or other missing elements in wsl. 
The other day I downloaded the appimage. I extraced the appimage because appimages do not run in wsl, I had a look with my filemanager (double commander) and clicked and the appimage started and could be used. 

I then used the full path and filename to try to start the appimage and it failed with the same error as the deb-file does.
```
/squashfs-root$ desktopeditors

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-<uid>'

failed to get the current screen resources

shared memfd open() failed: Function not implemented

QXcbConnection: XCB error: 170 (Unknown), sequence: 170, resource id: 90, major code: 146 (Unknown), minor code: 20

[0826/201454.755829:FATAL:gpu_data_manager_impl_private.cc(897)] The display compositor is frequently crashing. Goodbye.

Trace/breakpoint trap (core dumped)
```

I suspect the XDG variable or standard-setting from double-commander influenced the environment. 
I retried and II can start the appimage by clicking on AppRun with the filemanager, but it crashes if I use the command 
~/squashfs-root/AppRun. 
You can clearly see the application start and create a window, but then the window closes and gives the message above. 

I prefer using desktopeditors to wps but wps works as a deb. 

### Actual Behavior

If I start the extracted appimage with a full commandline it crashes with 
```
/squashfs-root$ desktopeditors

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-<uid>'

failed to get the current screen resources

shared memfd open() failed: Function not implemented

QXcbConnection: XCB error: 170 (Unknown), sequence: 170, resource id: 90, major code: 146 (Unknown), minor code: 20

[0826/201454.755829:FATAL:gpu_data_manager_impl_private.cc(897)] The display compositor is frequently crashing. Goodbye.

Trace/breakpoint trap (core dumped)
```

but if I go to the folder with a file-manager and run by clicking AppRun it starts and works well. 

### Reproduction Steps

In wsl install the desktopeditors deb file. (download and run sudo dpkg -i <name of deb-file> )
download the appimage and extract the appimage (this will create squashfs-root folder)
try ./squashfs-root/AppRun   and it will fail with the same message as the db-file did.4

sudo apt install doublecmd-qt 
doublecmd&
go to the squashfs-root/ folder and click on AppRun 
the appimage starts.

**Comment by ShockwaveNN** [comment]
Is there any particular reasons why you want to use DesktopEditors in wsl with and not native windows version?

I try to think about it, but seems for me it's just complicate things a lot

**Comment by yoasty** [comment]
I mainly work in ChromeOS / crostini and I want to replicate the environment as closely as possible to wsl so I can switch between the two. The requirement involves a java tool that archives and unarchives documents to be worked on. so it basically allows to work on a central repository of docxs with multiple people allowed to edit/view the files (though editing is only one at a time. The Java app starts the wordprocessor. ). I work 99% of the time in crostini, but the days I work in wsl I want the environment to be as identical as possible. So I'd prefer to work in desktopeditors.

**Comment by ShockwaveNN** [comment]
@yoasty Ok, we'll try to take a look at this problem, but no promises, since I think it's very strange way to use our product

**Comment by yoasty** [comment]
I understand. If desktopeditors runs in wsl it could offer an easy solution for locked down machines. I prefer it because it allows epubs, and pdfs with materials to be used for processing the docxs all in one application.  The app-store is locked down so installing in win is not possible.

**Comment by Rita-Bubnova** [comment]
@yoasty, DesktopEditors v7.4.1 is released.
Please state is this problem still actual for you?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
