### ISSUE TITLE
250% scaling

### ISSUE THREAD

**Issue by MehdiChinoune** [ONLYOFFICE/DesktopEditors#708]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Offer 250% scaling option which the default scaling for 15.6/4K display.

**Comment by soundlift** [comment]
附议

**Comment by ShockwaveNN** [comment]
@soundlift Please, only use English in our issue tracker

**Comment by LuckySpecialist** [comment]
Hi, @MehdiChinoune!
Submitted Bug 52447 to our private bug tracker.
Thanks for your feedback.

**Comment by mig4** [comment]
Also please add 300% scaling which is the default for 4K 13" screens. In fact this may not be enough for some so maybe supporting anything in range between 100-500% would make sense.

**Comment by MehdiChinoune** [comment]
It looks like It is partially fixed with 7.1.0.
The app font size (not document) is not scaled, still looks small.

![تعليق توضيحي 2022-05-13 170819](https://user-images.githubusercontent.com/79349457/168323737-07d135f8-14da-4de0-bba8-5f10fa58668d.jpg)
There is not option to change scale or font size!

**Comment by compumatco** [comment]
Yes, please support 250 and 300% UI scaling - 4K screens need these.  Using max 200% zoom means I have to squint to see the UI elements on my screen.  It's not really workable, and this is my favourite office suite.  Why is it that the launcher screen supports force-scale options of any number (even decimals) but the app tabs don't?  Is it because the UI element icons are pixel-based and not scalable vector icons?

**Comment by roman-kuleshov** [comment]
up

**Comment by roman-kuleshov** [comment]
Hi @LuckySpecialist, @ShockwaveNN , we are using ONLYOFFICE as well and we need to be able to zoom up to 500%. Your documentation says that it should work - `Zoom – to set the required zoom value from 50% to 500% from the drop-down list.`, but it doesn't seem to work, the limit is 200% for us.
Is this feature available? Can you guys point me to the right direction in case I have missed something.

**Comment by joewood9364** [comment]
Please implement more scaling options including 250% as 200 is still too small on 4k monitor.

**Comment by MehdiChinoune** [comment]
Fixed in 7.5.0
