### ISSUE TITLE
File missing when build in Visual studio kindly help

### ISSUE THREAD

**Issue by MohsinAli512** [ONLYOFFICE/DesktopEditors#71]
some files are missing when I build this project on VS 2017. File like drawingCoreInfo.cpp and File.cpp and I don't know where this issues comes from. kindly help

**Comment by maxkadushkin** [comment]
what module do you compile?

**Comment by MohsinAli512** [comment]
I am running power point editor 




---- On Tue, 14 Nov 2017 16:01:34 +0500 maxkadushkin &lt;notifications@github.com&gt; wrote ----




what module do you compile?

**Comment by maxkadushkin** [comment]
the project consists 6 sub modules. what sub module do build on vs2017 and get errors about missed files?

**Comment by MohsinAli512** [comment]
i am running ASCOfficePPTFile-&gt; Test Module. and error snapshots given below.




---- On Tue, 14 Nov 2017 16:15:47 +0500 maxkadushkin &lt;notifications@github.com&gt; wrote ----




the project consists 6 sub modules. what sub module do build on vs2017 and get errors about missed files?

**Comment by K0R0L** [comment]
It is a library used only in the Convection of the PPT in the PPTX. We do not provide files to compile in Visual Studio
