### ISSUE TITLE
Visual inconsistency

### ISSUE THREAD

**Issue by Niwton** [ONLYOFFICE/DesktopEditors#711]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hi, I love OnlyOffice! I use it in KDE Neon it integrates almost perfectly into the system just a few details are bothering me and triggering my TOC, the print window in the spreadsheet has a modern look and integrates with the application, but in the document and presentation use a qt look pure, I would like to request that the same visual harmonization be done in the spreadsheet.

![Screenshot_20210918_202959](https://user-images.githubusercontent.com/24793957/133911174-96bbad4a-bc15-49d8-94ab-2860e549231e.png)
![Screenshot_20210918_203019](https://user-images.githubusercontent.com/24793957/133911175-161e30ec-4cbe-40cb-b79c-863e8bea43ae.png)

![Screenshot_20210918_203031](https://user-images.githubusercontent.com/24793957/133911176-0fb3dcde-8ae5-400e-bbd9-7f0a0b2a3158.png)

**Comment by ShockwaveNN** [comment]
@matveevms please take a look, I think we may have already an issue about old look of this window

**Comment by matveevms** [comment]
Hello, @Niwton 
Sorry for the long wait for a response. At the moment, we have changed the print window to a system one. Now, when printing, you first see a preview window, and then the system print window opens. If you have any suggestions, you can leave them in this issue and we will definitely consider them.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
