### ISSUE TITLE
Bookmarks for cloud connection

### ISSUE THREAD

**Issue by JeanLouPtflbx** [ONLYOFFICE/DesktopEditors#713]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hi,
I'm starting to use OnlyDesktop with Seafile clouds, at the moment It's quite nice.
Can be better if you add a kind of Bookmark in Cloud tab, to remember servers with login / password, so you just have to click to connect.

Thanks,

**Comment by ShockwaveNN** [comment]
1. Could you specify DesktopEditors version and your host os
2. I think Seafile connection should be listed in here, with saved password:
![Screenshot_20210923_133624](https://user-images.githubusercontent.com/668524/134493138-cae12015-618f-4f4d-9e82-03ab1bb1f5f1.png)

**Comment by JeanLouPtflbx** [comment]
Hi,
I use OnlyOffice desktop version 6.3.1 on MacOS Big Sur 11.2.3
And I connect to many Seafile server from version 8.0.4 to 8.07.
Seafile is listed in "Connect to cloud", when clicked, it open window, I enter the URL of my seafile server, then a tab is open on seafile login page. So if I need to connect to another server, I have to redo all the process.
I would be nice if I can bookmark my servers ( owncloud/nextcloud/onlyoffice ) on the "Connect to cloud" page.

**Comment by ShockwaveNN** [comment]
Could you try to find any public nextcloud\owncloud or create temp portal for onlyoffice and see if problem actual for any connection or only Seafile?

**Comment by ShockwaveNN** [comment]
Also please look at https://helpcenter.onlyoffice.com/installation/desktop-connect-seafile.aspx

Part about
ONLYOFFICE_DESKTOP_EDITORS_PORTAL_LOGIN = True

**Comment by JeanLouPtflbx** [comment]
Thanks a lot ! 
My bad, got an error in the line :
ONLYOFFICE_DESKTOP_EDITORS_PORTAL_LOGIN = True
