### ISSUE TITLE
Conditional Formatting doesn't seem to be supported on linux

### ISSUE THREAD

**Issue by dsuserds** [ONLYOFFICE/DesktopEditors#719]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

6.3.1.56

### Expected Behavior

"Conditional Formatting" should show up on the toolbar or in the cell menu.

### Actual Behavior

N/A

### Reproduction Steps

Right click on a cell and the "Conditional Formatting" option won't be there.

**Comment by ShockwaveNN** [comment]
> Version information
> 6.3.1.56

We'll add support of Conditional formatting adding only in v6.4

Currently, this version is not released but everything is good - we'll release it today or tomorrow

**Comment by ShockwaveNN** [comment]
We released v6.4 of DesktopEditors a while ago, this should be resolved
