### ISSUE TITLE
Ole Automation

### ISSUE THREAD

**Issue by regs01** [ONLYOFFICE/DesktopEditors#721]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Would be great if OnlyOffice will also fully support OLE automation with Word.Application compliance. This might be big feature to make, but it would killer feature. Would make very small business depending on programs using OLE automation to move away from expensive MS Office.

**Comment by ShockwaveNN** [comment]
Hi, could you provide maybe link to MS documentation, because currently I've no idea what are you talking about

But maybe this page helps you - https://api.onlyoffice.com/plugin/basic
You can automate some actions using our macros API

**Comment by regs01** [comment]
I think it's this
https://docs.microsoft.com/en-us/office/vba/api/excel.application(object)
https://docs.microsoft.com/en-us/office/vba/api/word.application

It's not only about macros within documents. It's when external application, which you don't have control over, makes a document and does some changes into it through OLE calls.

**Comment by ShockwaveNN** [comment]
I think in the current state you can only make a plugin which auto-start on document editing start and perform some actions

But I still do not fully understand the scenario, mostly because I read MS documentation you've provided but still do not fully understand any real usercase

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
