### ISSUE TITLE
Wrong date format in russian

### ISSUE THREAD

**Issue by Alex01d** [ONLYOFFICE/DesktopEditors#725]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package), Linux (RPM package)

### Version information

6.1.146

### Expected Behavior

15 апреля 2006

### Actual Behavior

апреля 15 2006

### Reproduction Steps

Example:
1) in advanced settings select regional settings: Русский (Россия)
2) fill a cell with a date like 15.06.2006
3) select a date format (the most close format is 'апреля 15 2006', which is wrong for russian)

**Comment by alinasafonova** [comment]
Hello, @Alex01d
Thank you for report.
I can confirm - this is bug, issue 48720 in our private issue tracker.

**Comment by rsnegirev** [comment]
Hi @Alex01d 

This problem is fixed in https://github.com/ONLYOFFICE/sdkjs/commit/5b1fcf11a32946e65f0d27619baedf1e1523e2ef

It will be released as v7.4.0.

**Comment by DenisDeeSign** [comment]
DesktopEditors v7.4.0 are released so I close this issue. Feel free to comment or reopen it if you got further questions.
