### ISSUE TITLE
Get data function in spreadsheet 

### ISSUE THREAD

**Issue by Carlhenrikhansen** [ONLYOFFICE/DesktopEditors#726]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

6.4.1

### Expected Behavior

Import data via the new "Get Data" function in spreadsheet 

### Actual Behavior

Can't open/import .csv and .txt files in the new "Get data" function in spreadsheet, tested the same function in windows and here it works fine, it's not possible to select the file in macOS
![get data macOS](https://user-images.githubusercontent.com/92092110/136376184-295e2c54-722e-4615-a64f-07316e1a0c24.png)
![get data windows](https://user-images.githubusercontent.com/92092110/136376192-8ae51a0c-c86d-44c9-b809-e1f97a01c78b.png)

**Comment by Gingetsu** [comment]
@Carlhenrikhansen 
Thank you for reporting this bug
Issue #53057 has been created in our private issue tracker

**Comment by HectorB-2020** [comment]
I use this "Get data" function quite intensively. Mine is 7.1.1.57 (Windows).

**Comment by ShockwaveNN** [comment]
Sorry, seems we forgot to close this bug

It was fixed in v7.0.0
