### ISSUE TITLE
Bullet point shown and exported wrong in .docx

### ISSUE THREAD

**Issue by h8ghbzc9bbr8c7** [ONLYOFFICE/DesktopEditors#731]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

6.4.1.46

### Expected Behavior

The bullet points should be displayed and exported with the correct symbol (a bullet point)

### Actual Behavior

When opening a .docx created with Microsoft Office which contains bullet points in OnlyOffice the bullet points are displayed (and exported to .pdf) with a wrong symbol (character) for the bullet point. It may be (but is unlikely) that this is caused by my local installation which is not absolutely standard.

### Reproduction Steps

Open the attached .docx and compare the attached .pdf which are created with MS Office and OnlyOffice

### Additional information

[DOCX-TestBullet.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/7315697/DOCX-TestBullet.docx)
[DOCX-TestBullet-MSOffice.pdf](https://github.com/ONLYOFFICE/DesktopEditors/files/7315698/DOCX-TestBullet-MSOffice.pdf)
[DOCX-TestBullet-OnlyOffice.pdf](https://github.com/ONLYOFFICE/DesktopEditors/files/7315699/DOCX-TestBullet-OnlyOffice.pdf)

**Comment by matveevms** [comment]
@h8ghbzc9bbr8c7, Hi. You are using the third party font "Univers for UniS 55 Roman Rg" in your document. Can you provide this font to replay your script? And please indicate your operating system.

**Comment by matveevms** [comment]
Hello, @h8ghbzc9bbr8c7 
Is the problem still relevant in desktop version 6.4.2? Before saving the document in pdf format, do you have markers displayed?

**Comment by h8ghbzc9bbr8c7** [comment]
Thanks! The bug is fixed in 6.4.2. Unfortunately I do not understand what you mean with "markers displayed" - can you give me some hint?

**Comment by ShockwaveNN** [comment]
if bug is fixed for you I'll close this issue, thanks
