### ISSUE TITLE
Certain special characters use fallback font instead of microsoft font.

### ISSUE THREAD

**Issue by hydroEng** [ONLYOFFICE/DesktopEditors#737]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

6.4.1.46

### Expected Behavior

When printing special characters such as ḥ (U+1E25) or ṣ  (U+1E63) using the times new roman font, it is expected that the app will show them in the times new roman font. 

### Actual Behavior

When printing special characters such as ḥ (U+1E25) or ṣ  (U+1E63) using the times new roman font, they print in a fallback font (probably Arial? not sure). I do not know if this issue extends to other fonts (some fonts print fine, others do not). Note that times new roman does have these characters included, it seems OnlyOffice is falling back for no good reason.

Compare:

OnlyOffice:
![image](https://user-images.githubusercontent.com/59785388/137815985-06b0ed4a-c853-48f9-a615-95cf0a0a6a32.png)

LibreOffice:

![image](https://user-images.githubusercontent.com/59785388/137816045-b1d7abfe-b219-43ef-bc52-e19893e676c6.png)

I am not sure if this is a linux issue or an onlyoffice issue, but these same characters show up fine on LibreOffice on the same system (Fedora 34). I had the same problem on Ubuntu.

This is an issue because special characters are often used in humanities / linguistics papers, which usually want a very specific font (often Times New Roman). The problem carries over when exporting to pdf, which makes onlyoffice not suitable for anything requiring special characters.

### Reproduction Steps

1. Paste special characters ḥ or ṣ (this problem may extend to other special characters).
2. Change the font to Times New Roman (again, this problem may extend to other fonts, I have not tested).

**Comment by suryaya** [comment]
Hi again, is anyone looking into this? I would like to confirm that this is an issue with how I have configured my OS and not OnlyOffice.

**Comment by ShockwaveNN** [comment]
@suryaya Sorry, currently we have no free time to look at this one

But @matveevms will look at this issue as soon as possible

**Comment by Rita-Bubnova** [comment]
@hydroEng, Sorry for the long wait.
DesktopEditors v7.4.1 is released. Is this issue relevant?

**Comment by hydroEng** [comment]
> @hydroEng, Sorry for the long wait. DesktopEditors v7.4.1 is released. Is this issue relevant?

Yup, still an issue on version 7.4 unfortunately.

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/59785388/77024b9f-7c05-4910-a328-1481865bb04a)

**Comment by matveevms** [comment]
Hello, @hydroEng 
Perhaps the problem is related to your font or the selection of similar ones. Please tell me what version of the TNR font you have installed?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
