### ISSUE TITLE
Replacement for VBA functions

### ISSUE THREAD

**Issue by eerbano** [ONLYOFFICE/DesktopEditors#752]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

In some old spreadsheets I have, I used a lot of VBA functions inside cells, please, do not confuse macros, I really mean custom functions that execute from inside a cell.
But, I failed to find some similar replacement in Onlyoffice, I tried to write some javascript code to run from inside a cell, but failed.
Is there any way I could do it?

**Comment by ShockwaveNN** [comment]
Hi, not sure that I really get that you want

Could you provide the simplest example of this function?

But generally speaking we got two subsystems for replacing VBA macros - it's [plugins](https://api.onlyoffice.com/plugin/basic) and our own macros you've already mentioned

**Comment by eerbano** [comment]
In MS Office, macros are declared with the "Sub" keyword, but functions are declared as functions.

The difference is this:
Macros run outside the spreadsheet scope, so, you need the API to access the cells

Functions you insert directly inside the cell, and you dont need to use the API to access the spreadsheet, since the function will receive the variables that you insert when calling the function from inside the cells, and will return a value directly to that cell.

In the cell, in the spreadsheet you call the function like this:
`= BinarySearch(O1:O100)`

In the VBA sourcecode you have the function declared in a individual "file", like this:
`Function BinarySearch(. . .) As Boolean 
'. . . 
 ' Value not found. Return a value of False. 
 If lower > upper Then 
  BinarySearch = False 
  Exit Function 
 End If 
'. . . 
End Function`

I know that ONLYOFFICE DesktopEditors dont use VBA, but, I would like a replacement for that feature, to call JS code inside the cells the same way.

**Comment by ShockwaveNN** [comment]
I think I got your idea and I'm not sure that we got that functionality

@askonev please take a look - can we do that and if not - please create enchantment issue

**Comment by askonev** [comment]
HI @eerbano! At the moment, interaction with the internal functions of the tables has not been implemented. The solution to this problem could be to check the data from the cell that is returned to the macro script.

Macros scripit
```js
    oSheet = Api.GetActiveSheet();
    oRange = oSheet.GetRange('A1'); // The cell contains the result of method
    
    if(oRange.GetValue2() == "#VALUE!") {
        console.log('false');    
    }
    else {
        console.log('value', oRange.GetValue());    
    }
```

**Comment by askonev** [comment]
@eerbano One more thing. In one script, you can only execute an internal method and get a value using the Api.RecalculateAllFormulas() macro method. This is because the internal methods are executed after the script runs.

```js
    oSheet = Api.GetActiveSheet();
    oSheet.GetRange('A1').SetValue('=sum(2,2)');
    oRange = oSheet.GetRange('A1');
    Api.RecalculateAllFormulas();
    console.log('value', oRange.GetValue());
```

**Comment by eerbano** [comment]
Hi,
That is a bit more complex than I thought, but ok, if there is no other way, I think that workaround will do for now. But, I hope to see this feature in a near future.
Thanks. Best regards.
