### ISSUE TITLE
Creating new Documents using Context Menu in Window 11

### ISSUE THREAD

**Issue by Loki-L1130** [ONLYOFFICE/DesktopEditors#757]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I have a fresh installation of Windows 11. But I do like to create a document quickly by using Context menu (Right Click) in the Desktop like Microsoft Office does.

I did see this option in Windows 10 not in Freshly installed Windows 11

**Comment by Rita-Bubnova** [comment]
Hello, @Loki-L1130.
This is known issue 37924 in our private issue tracker.

Maybe duplicate https://github.com/ONLYOFFICE/DesktopEditors/issues/623.

**Comment by Loki-L1130** [comment]
Yep, You are Right.
