### ISSUE TITLE
Saving to doc

### ISSUE THREAD

**Issue by iamthesenate1** [ONLYOFFICE/DesktopEditors#758]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I think it would be nice if onlyoffice could save directly to doc, as I sometimes work with older documents and it is annoying to save as docx and then convert back to doc with an online tool.

**Comment by ShockwaveNN** [comment]
Hi

1. You can convert docx to doc via Conversion API integrated to our DocumentServer
2. Sorry, but I don't think we're currently planning to implement saving to `doc` in DesktopEditors. A long time ago we have this button but we decided put all our forces to better support of ooxml (docx) format, and leave ability to convert via API for more advanced users

**Comment by iamthesenate1** [comment]
Ok. Thank you for your explanation.
