### ISSUE TITLE
Allow to choose a default layout

### ISSUE THREAD

**Issue by iamthesenate1** [ONLYOFFICE/DesktopEditors#759]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I would like to have the option to set a custom layout automatically when a new document is created.
Right now, I must go every time to layout-> last custom layout

**Comment by ShockwaveNN** [comment]
I'm not 100% sure that layout option do you mean, but you can replace new empty document which located at `/opt/onlyoffice/desktopeditors/converter/empty` path in Linux and similar path in `Program Files` in windows - to any file with any layouts

**Comment by iamthesenate1** [comment]
This is exactly what I meant. Thank you.

**Comment by ShockwaveNN** [comment]
You're welcome

I'll close this issue
