### ISSUE TITLE
 Segmentation fault. Can't run portable app on Solus 3.

### ISSUE THREAD

**Issue by Juankz** [ONLYOFFICE/DesktopEditors#76]
I use the Gnu/Linux distribution Solus 3, downloaded the portable app from the website and try to run it. This happens:

Executing **onlyoffice-desktopeditors.sh** I get:

```[1]    11066 segmentation fault  ./onlyoffice-desktopeditors.sh```

And executing **DesktopEditor** throws:
```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
[1]    11032 abort      ./DesktopEditors
```

Help wanted

**Comment by HellRoad** [comment]
@Juankz Hi 
I checked portable version for ubuntu 14.04, Debian 8 and another OS, this version worked correctly on Solus 3
but version for Debion 7, Ubuntu 12.04, Centos 6 not worked 

Try download version for ubuntu 14.04, Debian 8 and checking 
If it does not work, then write in more detail your system, which version of Solus and what graphical shell is installed

**Comment by Juankz** [comment]
Anyway I just installed the snap desktop editors. I think this can be closed
