### ISSUE TITLE
Opening apps with dark mode shows mixed-mode UI

### ISSUE THREAD

**Issue by janxkoci** [ONLYOFFICE/DesktopEditors#760]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

6.4.2.6

### Expected Behavior

Before the update to 6.4, opening a document in any of the apps with dark mode set was working okay.

### Actual Behavior

With version 6.4, the UI briefly becomes a mix of dark and coloured (light) mode when opening a document. See a screenshot below:

![Snímek z 2021-11-15 15-20-02](https://user-images.githubusercontent.com/19331850/141801990-c96422da-6ed4-446f-ac5f-cf6b3bdbff4b.png)

After a moment, the UI turns dark again, so this is really just a mild cosmetic issue.

### Reproduction Steps

1. Launch OnlyOffice
2. set mode to dark
3. open / create a document
4. the top of the UI will briefly show colours as if a light theme is set, then it switches back to dark again

### Additional information

My installation method is actually **flatpak**, but that option is not available in the drop-down menu above.

**Comment by Wo1fgang** [comment]
Hello!
@janxkoci , I was unable to replicate the problem on my computer.
Could you share the name of your OS please?

**Comment by janxkoci** [comment]
Actually I had some update this week and I no longer see it.

My system is elementary OS 5.1.7 (based on Ubuntu 18.04).

**Comment by ShockwaveNN** [comment]
In that case I'll close this issue, but feel free to comment if you got this problem again
