### ISSUE TITLE
Incorrect default bullet list icons

### ISSUE THREAD

**Issue by wallish77** [ONLYOFFICE/DesktopEditors#761]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (Manjaro community package and/or DEB via AUR)

### Version information

6.4.2.6

### Expected Behavior

The icon options for Lists would include standard symbols as shown on the OnlyOffice website and in other document editors, including square, dart-arrow, diamond, etc. (as seen in the image below from the OnlyOffice help page)
![image](https://user-images.githubusercontent.com/39662183/141831835-a95a02fb-12fb-4de9-8673-076c547b6e63.png)

### Actual Behavior

New documents and imported documents show incorrect/unexpected options for List bullets.  Seemingly random unicode icons are present as the default options, as seen in the image below.
![image](https://user-images.githubusercontent.com/39662183/141832100-5b86c338-94d2-444c-a671-a53cfe725799.png)

These icons seem static (i.e. they don't change to a different set upon closing and reopening the program).

### Reproduction Steps

1. Install OnlyOffice version 6.4.2 (or 6.4.1) on Manjaro Linux from the community repository or via the AUR
2. Create a new document or load an existing document created in MS Office
3. Create a new list and examine options for bullet icons

### Additional information

In case it was something to do with my system, I loaded up a manjaro-kde live environment in a vm.  The version of OnlyOffice included is 6-4-1.50.  It too shows odd symbols, but strangely enough they are an entirely different set:

![image](https://user-images.githubusercontent.com/39662183/141833007-c7f2ad87-1185-4993-80d9-94dbcc10dd67.png)

Also tested on:
* Pop OS live environment -> Icons are correct
* Fresh Arch install -> icons are incorrect as per the manjaro-kde image above.

**Comment by wallish77** [comment]
A note: this may be related to #731 but this occurs on new documents, not imported documents.

**Comment by ShockwaveNN** [comment]
@matveevms Please take a look at that issue

**Comment by wallish77** [comment]
I have some additional information to provide: The issue still holds true when installing from a snap and flatpak.  Maybe has something to do with a font lookup or location that is different/missing on arch but not Pop?

**Comment by matveevms** [comment]
Hello, @wallish77 
1. The assemblies you are using are not our official assemblies.
2. The workaround for your build is to add the opensymbol font to the / usr / share / fonts / TTF directory. (I attach the font)
3. We recommend using snap / appimage / flatpak on this system - these assemblies are official, but now this problem is present in the latest versions. I create issue 54539 in our private issue tracker
[opens___.zip](https://github.com/ONLYOFFICE/DesktopEditors/files/7719284/opens___.zip)
.

**Comment by wallish77** [comment]
> Hello, @wallish77
> 
> 1. The `aur` package you are using are not our official package. It's better to contact it's author (sorry, we do not have contacts). We do not provide any `arch` specific build officially
> 2. The workaround for your build is to add the opensymbol font to the / usr / share / fonts / TTF directory. (I attach the font)
> 3. We recommend using snap / appimage / flatpak on this system - these build are official, but now this problem is present in the latest versions. I create issue 54539 in our private issue tracker
>    [opens___.zip](https://github.com/ONLYOFFICE/DesktopEditors/files/7719284/opens___.zip)

Hello @matveevms,

Thank you, i can confirm that the above resolved the issue.

**Comment by ShockwaveNN** [comment]
In that case I'll close this issue
