### ISSUE TITLE
Presentations: multiple monitor and presenter view improvements

### ISSUE THREAD

**Issue by alexforencich** [ONLYOFFICE/DesktopEditors#764]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Several related minor things that should be changed with respect to presentations:

* When there are multiple monitors connected, or in particular an external projector, there needs to be an easy way to select which monitor to present on.  Dragging the UI over to the projector and starting the presentation from there is not convenient.
* Pressing the "start slideshow" button should start the presenter view when multiple monitors are present.
* Presenter view should start on the active monitor and the presentation on the other monitor (opposite of what it is now) (#285).
* Presenter view should have a button to "switch monitors" to quickly switch the presentation to the correct monitor (#597).
* The F5 key should be mapped to do the same thing as the "start presentation" button - start normal presentation when only one monitor is present, or start the presenter view when more than one monitor is present.

**Comment by Wo1fgang** [comment]
We prefer to have single issue for single problem, since we usually fix issues in different time and after some issues are fixed and some are not - it is very hard to track all of them in one issue.

**So please create separate issue for each request**

And as for mentioned duplicated issues - yes they exists, but didn't get fixed yet.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
