### ISSUE TITLE
Heading style / format gone after restart

### ISSUE THREAD

**Issue by Inrumpo** [ONLYOFFICE/DesktopEditors#771]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

6.4.2.6

### Expected Behavior

Heading styles / formats should look the same after closing and re-opening a .docx file.

### Actual Behavior

They don't.

![OnlyOffice Heading Issue](https://user-images.githubusercontent.com/11300164/143944853-3af162df-f3fa-4c7a-b0a9-2d0f2da1bae4.png)

The heading will _look_ like the "normal" format is being applied, even though the heading (Heading 2 in this example) is still selected.

### Reproduction Steps

1. Create .docx file
2. Write some text and add some headings. 
3. Save
4. Close
5. Re-Open
6. Heading format will have changed.

### Additional information

"Heading 1" seems to work fine though.

**Comment by TatianaKirillova** [comment]
Hello, **@Inrumpo**.Thank you for report.

I cannot repeat your problem. Please send a video reproducing your problem

**Comment by Inrumpo** [comment]
> Please send a video reproducing your problem

Here is a GIF showing the issue:
![OnlyOffice Issue Headings](https://user-images.githubusercontent.com/11300164/145097863-66882bcb-2828-45ea-a933-05e0c649d9ab.gif)

(I did pause the recording after closing ONLYOFFICE, opening the document again and while scrolling back down.)

As you can see, the styling of the heading is not preserved after saving the document, closing it and then opening it up again.

**Comment by TatianaKirillova** [comment]
Hello, **@Inrumpo**. Thank you for the video! I have not been able to replicate the text formatting loss issue after saving it. We advise you to update the application.

I also want to note the peculiarity of the behavior of our editor. If text is selected without a paragraph mark, then the text style is used and the paragraph style is displayed in the toolbar.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
