### ISSUE TITLE
FR - export as markdown

### ISSUE THREAD

**Issue by Jopp-gh** [ONLYOFFICE/DesktopEditors#775]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Markdown is a future proof, robust and very flexible document format. 
New apps featuring markdown as method, pop up like mushrooms these last years
Markdown unifies our fragmented workflow because we need to deal with less apps, to get our work done

Unluckily not one application is able to satisfy all our necessities, but, we can mitigate the problem by sharing same or very similar files formats. Therefore, asking you here to add a new file format is just a move in the right direction to solve a far bigger problem, and not just about "adding something new" because trendy or because my taste

Converting complex files with formatting like tables, math, links, images, ect through open source conversion tools like **Ted** and **pandoc** , let's say from *rtf* to *md* aren't trivial to archive and best results require a very good understanding of how these tools work - standard output isn't great but ok 

Said this, after the conversion you've to rework your documents, some of your documents will require inevitably more, some less reviews to be great, will say, easy and quick to read without awkward errors and /or meaningless superfluous tokens in it

**Comment by ShockwaveNN** [comment]
Hi, currently we're working on new plugin, which will do that - [export to markdown](https://github.com/ONLYOFFICE/plugin-doc2md/tree/master)

It's currently in development, and I cannot promise an exact time frame in which it will be released, but I hope this happens soon

**Comment by trofim24** [comment]
We've already released [doc2md plugin](https://github.com/ONLYOFFICE/onlyoffice.github.io/tree/master/sdkjs-plugins/content/doc2md). You may install it using [plugin manager](https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/Editors-User-Guides/AllEditors/Plugin-manager.aspx)
