### ISSUE TITLE
Text under buttons is too short in Russian interface

### ISSUE THREAD

**Issue by mikhailnov** [ONLYOFFICE/DesktopEditors#777]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

6.3.1.56

### Expected Behavior

There is enough place, titles of plugins could be not shortenned.

### Actual Behavior

![image](https://user-images.githubusercontent.com/15802528/144749962-c3b0b605-3b23-4e08-9e89-0b87f4ca48b4.png)

**Comment by Rita-Bubnova** [comment]
Hello, @mikhailnov.
Thank you for your report.
I create issue 54346 in our private issue tracker.

**Comment by VladimirProkofiev52** [comment]
Hello!
@mikhailnov 
We have fixed the problem in the new version of our editor.
You can update the desktop editor to version 7.5.1.23, in this version the problem has already fixed.

**Comment by mikhailnov** [comment]
Thanks

**Comment by Rita-Bubnova** [comment]
Desktop Editors v7.5.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
