### ISSUE TITLE
HiDPI scaling does not work in KDE Neon

### ISSUE THREAD

**Issue by timberfake** [ONLYOFFICE/DesktopEditors#78]
I am using **DesktopEditors 4.4.1.338** on **KDE Neon** (Ubuntu 16.04 based) and the application does not respect the systems DPI scaling factor, which makes icons really small and so the application is unusable for me. 
My screen is 3840x2160 px and is scaled by factor 2x. All other applications are scaling fine, so there seems to be an issue with the chromium framework used in this application.

Only solution I found so far is to start the desktop editors with:
**desktopeditors --force-device-scale-factor=2**
but you always have to minimize and maximize the window after opening a document, to avoid cut-off display.

**Comment by qwfy** [comment]
Having the same problem, also KDE with high dpi. Here is a screenshort compared with a native app KDE app:

![de](https://user-images.githubusercontent.com/11158705/38003712-6b7d5b84-326b-11e8-812d-eb709c1c1732.png)

desktopeditors --force-device-scale-factor=2 is way too much for me

**Comment by aenima1985** [comment]
I have the same problem in Manjaro KDE with version 4.8.7.392.

**Comment by regs01** [comment]
Same on Windows 10 (at least 1803). No scaling at all,  everything appears very little.

**Comment by ShockwaveNN** [comment]
Closing this issue in favor of #53
