### ISSUE TITLE
Find replace bullet points - corruption

### ISSUE THREAD

**Issue by johans3** [ONLYOFFICE/DesktopEditors#782]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

6.4.1

### Expected Behavior

Written Bullet points (in OnlyOffice) differ from imported/pasted bullet points from **Apple notes**

This difference looks bad, a document shouldn't use different bullet points. 

### Actual Behavior

If I do a find - replace of these  **Apple notes** bullet points and replace them with bullet points inserted in the find and replace field of Onlyoffice, then all text in the calc table will be replaced with meaningless character strings

### Reproduction Steps

1. Create a new calc table
2. Copy a bullet point list (eg. Grocery list) into it
3. Add a new item at the end of the list (eg. * milk - write a bullet point, not a '*' my phone doesn't support bullet point characters)
4. You'll see the written Bullet point isn't the same as the imported one
5. Find - replace all bullet points with the bullet point available in OnlyOffice and confirm

**Comment by ShockwaveNN** [comment]
@matveevms Please take a look at that issue

**Comment by matveevms** [comment]
Hello, @johans3 
Could you please attach your file and record a video of the problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
