### ISSUE TITLE
Keep original selection alive 

### ISSUE THREAD

**Issue by johans3** [ONLYOFFICE/DesktopEditors#783]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Immediate and clear comparison of all data aligned respectively in a row /column of a calc sheet

I'd like to be able to :
#### Scenario A
1. Select a row
2. Move with the arrow keyboard keys up or down without to lose the active selection (row selection) 

#### Scenario B
1. Select a column
2. Move with the arrow keyboard keys left or right without to lose the active selection (column selection) 

Another click on a cell can destroy the active selection, but scrolling up /down or left /right on the keyboard keys shouldn't

**Comment by ShockwaveNN** [comment]
Hi, is there a similar feature you looking for in another spreadsheet editor? MS Office, LibreOffice, or something else?

**Comment by johans3** [comment]
I replaced all office related applications with OnlyOffice, long time ago and I'm happy of this setup. I don't remember if other applications have this feature. 

The feature I'm suggesting is only a convenience to see immediately which data aligns, it's framing the important, "visually isolating" the important from the rest of the data - useful if you've to compare a lot of data in your spreadsheet. 

The existing feature, like the highlighted column sequence or row number is useful but definitely not enough. In short, I am asking for a stronger highlight for when I navigate rows /columns

**Comment by ShockwaveNN** [comment]
I show your idea to my team, but not sure that we in position to "invent new features"

**Comment by Rita-Bubnova** [comment]
@johans3, Could you explain what happens to the selected row (step 1) when you do step 2? Should the selected line be moved?

**Comment by CennoxX** [comment]
This is implemented in nearly all Excel-like programs: using the [scroll lock key](https://en.wikipedia.org/wiki/Scroll_Lock) you can move with the arrow keyboard keys without losing the active selection.

**Comment by johans3** [comment]
> @johans3, Could you explain what happens to the selected row (step 1) when you do step 2? Should the selected line be moved?

The selected table row wouldn't move, just the active selected row would "move" to the next line and highlight the next row.
Currently, if i select a row and move up or down with the arrow keys, the active selection jumps from the previous selected row to select the next cell only. Same applies to the column.

In short, the active selection (row or column) shouldn't get destroyed if I scroll my table

**Comment by Rita-Bubnova** [comment]
Sorry, I'm not sure I understand you correctly. So,
1. select first row,
2. press the `Down Arrow` key (on the keyboard).

Result:
Сell A2 selected.

This behavior is implemented in ONLYOFFICE Spreadsheet Editor and MS Excel.
@johans3 Do you want to change this?

**Comment by johans3** [comment]
1. select row A1
2. press the `Down Arrow` key 

Result:
Row A2 selected

**Comment by Rita-Bubnova** [comment]
@johans3 Thank you, now it is clear. 
In fact, we prefer to implement scenarios similar to those of MS Excel because many of our users choose ONLYOFFICE as an alternative to MS Office. That’s why we do not plan to alter the mechanics (including how selection works in spreadsheets) in the foreseeable future. 
But thank you for giving us the tip anyway!

**Comment by Rita-Bubnova** [comment]
@johans3,  Sorry I'm just a QA specialist, I can't try out this idea as a code snippet myself. But consider your suggestion accepted, I will share it with the developer team in any case.
However, I think that no alterations will be made to the original approach, as it can affect the user experience in negative ways where eventually we take more risk than gain.

**Comment by ShockwaveNN** [comment]
I'll close this issue since we're not planning to change it right away and reopen it in the future if something changes.
