### ISSUE TITLE
the cursor starts clicking a good few pixels below the cursor on screen

### ISSUE THREAD

**Issue by D0nnieD4rk0** [ONLYOFFICE/DesktopEditors#788]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

6.4.2-1

### Expected Behavior

click somewhere and actually click where the cursor is pointing

### Actual Behavior

after some 5 or 10 mins of use it starts doing it

### Reproduction Steps

use it for 10 mins more or less

### Additional information
im on arch linux now nut used onlyoffice on a clean install of fedora and experienced the exact same issue

**Comment by ShockwaveNN** [comment]
Hi, could you add information about your
1. display model
2. resolution
3. system dpi
4. ONLYOFFICE DesktopEditors interface scaling option?

**Comment by D0nnieD4rk0** [comment]
1. laptop screen idk
2. 1366x768
3. its a basic laptop with fancy high dpi stuff
4. auto

**Comment by ShockwaveNN** [comment]
How it can be high dpi  if it's only 1366*768?

I think we'll need exact model so there will be no confusion

**Comment by D0nnieD4rk0** [comment]
> 

shit mistyped 3.its "with no fancy high dpi stuff"

**Comment by ShockwaveNN** [comment]
Still need model number just in case if we need some info about graphical adapter, this may be a hardware problem

**Comment by D0nnieD4rk0** [comment]
where i find that ?? lshw or lspci aint doing shit

**Comment by ShockwaveNN** [comment]
I think some stickers on laptop body or model tags is enough

If not - there is some additional solution here:
https://askubuntu.com/questions/258922/how-to-display-notebook-model-number

**Comment by D0nnieD4rk0** [comment]
this a lot more trouble than its worth its the most generic shit ever and i doubt its got anything to do with dpi

**Comment by ShockwaveNN** [comment]
Which package installation method do you used?

Could you try snap, flatpak and AppIMage and see if result is different?

**Comment by D0nnieD4rk0** [comment]
with the latest version i havent seen it happen yet so im closing this issue

**Comment by ShockwaveNN** [comment]
Thanks, still not sure that caused it but good to hear it fixed
