### ISSUE TITLE
Bad rendering

### ISSUE THREAD

**Issue by murakami-marco** [ONLYOFFICE/DesktopEditors#796]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

6.4.2.6

### Expected Behavior

Render OnlyOffice when opening a file as shown below
![image](https://user-images.githubusercontent.com/823462/147173796-62bdb52f-0763-4ba7-896f-80692a84e746.png)

### Actual Behavior

When clicking on a doc file to open it on OnlyOffice, it displays weird as shown below
![image](https://user-images.githubusercontent.com/823462/147173662-05aac7ad-2dd3-4a0c-bcfb-bd231064e796.png)

### Reproduction Steps

Open any file

**Comment by ShockwaveNN** [comment]
@Wo1fgang Please take a look at that issue

**Comment by Wo1fgang** [comment]
Hi, @murakami-marco 
Can you please could you add information about what kind of Linux OS are you using and your PC hardware specifications?

**Comment by murakami-marco** [comment]
Hi @Wo1fgang!!! how are you??

Here you have the info

Operating System: KDE neon 5.23
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.3
Kernel Version: 5.8.0-7630-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530

**Comment by Wo1fgang** [comment]
Hey @murakami-marco 
Merry Christmas!

I've looked into your problem but unfortunately couldn't replicate it. Maybe because I installed a clean version of OS.
Can you tell me about any additional apps that could affect UI? I see that you have mirrored window icons for example. Maybe there are some compatibility issues between those and our app.

**Comment by murakami-marco** [comment]
Not so sure. I don't think I have an app that could affect OnlyOffice. It only happens if I double click a file to be opened, it doesn't matter if it's a document, spreadsheet or presentation file. If I open first OnlyOffice and then search a file, it opens as expected.

**Comment by Wo1fgang** [comment]
Sorry to say, but I couldn't replicate it either way. Also tried installing with snap, flatpak and AppImage, same thing there.
Maybe you could try different methods of installing Onlyoffice, see if there's any problem.
And of course, you could try uninstalling or disabling suspicious apps (that could affect UI), fresh installation of operational system, different system or different PC.

**Comment by murakami-marco** [comment]
I tried with AppImage and it's the same. However, I tried calling from the Konsole and the issue happens on --system-title-bar, if I call it like this: ./DesktopEditors-x86_64.AppImage --custom-title-bar --view=file_path, it displays correctly but if I call it using --system-title-bar instead of --custom-title-bar, the issue happens.
You could try this to see if it happens.
Thanks @Wo1fgang !!!

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
