### ISSUE TITLE
Border Line Styles not Showing v4.4.1.338 Fedora 27 KDE

### ISSUE THREAD

**Issue by procyclinsur** [ONLYOFFICE/DesktopEditors#80]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
Line styles doe not appear in Fedora 27 KDE, Editor version 4.4.1.338
![screenshot_20171219_160850](https://user-images.githubusercontent.com/34673206/34144919-1cf8f22a-e4d7-11e7-838e-b80f45648232.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I personally have not tried to reproduce it, but if you install Fedora 27 KDE in VirtualBox and then install DesktopEditors version 4.4.1.338 I would assume that you will see the same.

**What is the expected behavior?**
The expected behaviour is to be able to see the line styles for borders.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Fedora 27 KDE
DesktopEditors 4.4.1.338

I do not know about previous versions, this is my first time trying ONLYOFFICE

**Comment by HellRoad** [comment]
@procyclinsur 
Please check your test in version 4.8.6 386
You can take a new version on the site  (https://www.onlyoffice.com/download-desktop.aspx)

**Comment by procyclinsur** [comment]
I can confirm that the but has been fixed in version 4.8.6 386

Thanks
