### ISSUE TITLE
Readme.md should display Windows instead of Window

### ISSUE THREAD

**Issue by BenjaminJacober** [ONLYOFFICE/DesktopEditors#809]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

![image](https://user-images.githubusercontent.com/81405671/149786722-53e10e4f-98b1-48d7-b643-7b0c406e989a.png)

**Comment by ShockwaveNN** [comment]
Thanks for noticing, seems just a typo

I'll fix it in https://github.com/ONLYOFFICE/DesktopEditors/pull/810

**Comment by BenjaminJacober** [comment]
Thought so as well, tried fixing it but wasn't able to do so in 5 minutes, so i just created an issue ^^

**Comment by BenjaminJacober** [comment]
Ah, i see. I tried editing the [Platforms Windows | macOs | Linux] part.

**Comment by ShockwaveNN** [comment]
This issue is fixed in #810, forgot to close it
