### ISSUE TITLE
Add option to re-edit raw .docxf / OFORM

### ISSUE THREAD

**Issue by Inrumpo** [ONLYOFFICE/DesktopEditors#815]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

ONLYOFFICE 7.0 has introduced a new way to create forms. I like it.

But once I have saved my form I can only open it and edit the different fields. I can't edit the "raw" file again in case I'd like to add an option to a drop down list or correct a typo.

**Comment by KirillovIlya** [comment]
Hello, @Inrumpo.

Once you have saved .oform file it can't be changed outside of the fields area.  There is a raw version of your file in  .docxf format for your purposes, you can modify it whereever you want. When you will end to make changes to your .docxf file you can create a new .oform file.

**Comment by Inrumpo** [comment]
> There is a raw version of your file in _.docxf_ format for your purposes, you can modify it wherever you want.

Thanks. That did work. Unfortunately I've already saved my other form as .oform only and therefore can't go back. I now have to create that one again.
