### ISSUE TITLE
OFORM: Option for minimal width of dropdown field for PDF compatibility

### ISSUE THREAD

**Issue by Inrumpo** [ONLYOFFICE/DesktopEditors#816]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

## Issue
This GIF shows the issue:
![OnlyOffice field width issue issue](https://user-images.githubusercontent.com/11300164/150037891-9233a75a-e79c-47b0-b56f-0b14b7b49400.gif)

During export to PDF the width of the placeholder defines the width of the field. We need a way to add/force a minimal width of that placeholder field to avoid unreadable outcomes after exporting to PDF.

(In this example the `fixed size field` option will make the field wider, but still not wide enough.)

**Comment by TatianaKirillova** [comment]
Hello, **@Inrumpo**.
Thank you for report.
For fields with the "fixed size" property, you can make arbitrary sizes. If you drag the field border with the cursor, you can set the size of the form field you need (horizontally and / or vertically)

**Comment by Inrumpo** [comment]
Thanks! I didn't know that. That's a handy little feature.
