### ISSUE TITLE
When copying several lines of text and pasting it into a Microsoft Excel document, there are breaks between the lines.

### ISSUE THREAD

**Issue by Xazev** [ONLYOFFICE/DesktopEditors#817]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.0 6.4.2

### Expected Behavior

When copying rows in Microsoft Excel, rows are pasted without break
![ok](https://user-images.githubusercontent.com/11159920/150098700-ca4a1db5-63ed-43ee-a13b-79b15e2a58d2.png)
s

### Actual Behavior

When copying several lines of text and pasting it into a Microsoft Excel document, there are breaks between the lines
![problem](https://user-images.githubusercontent.com/11159920/150098514-27be0552-7ca1-491d-b200-a54a41536ba5.png)
.

**Comment by Wo1fgang** [comment]
Hi @Xazev 

I did not managed to reproduce this problem on my Windows machine.

If I understood correctly, you have Microsoft Office installed on Linux Mint (that probably works through Wine) and I think that causing the issue. Can you check this problem on Windows machine?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
