### ISSUE TITLE
OnlyOffice 7.0 macOS is missing the homepage

### ISSUE THREAD

**Issue by M-Rick** [ONLYOFFICE/DesktopEditors#822]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.0 (530)

### Expected Behavior

The home page should show menus to connect to a server or to open local files.

### Actual Behavior

The new macOS 7 release displays a blank page.

![Capture d’écran 2022-01-21 à 18 26 21](https://user-images.githubusercontent.com/2520948/150574116-0efaa23b-a713-4923-807e-34ca316f24e0.png)

**Comment by DenisDeeSign** [comment]
Hi @M-Rick,
did you update an earlier version of Desktop Editors or perform clean installation?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
