### ISSUE TITLE
Add "Mail Merge" option

### ISSUE THREAD

**Issue by notameow228** [ONLYOFFICE/DesktopEditors#824]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I have switched to linux recently and have taken a great liking to this office suite. The only feature that I have really missed over time is the option to mail merge, as supported by WPS office and MS office.

Would be nice to see this feature implemented.

Cheers <3

**Comment by ShockwaveNN** [comment]
Hi, thanks

You're right, we got MailMerge in DocumentServer for ages, but not in DesktopEditors

We already have issue about this, sorry still no progress
https://github.com/ONLYOFFICE/DesktopEditors/issues/733
