### ISSUE TITLE
Default file format

### ISSUE THREAD

**Issue by Loki-L1130** [ONLYOFFICE/DesktopEditors#827]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I am a Open source Enthusiast, I do mostly Open source software. So, coming to the point I started to save in the Open Document Formet (.odt) and similarly for Spreadsheets and Presentations. 

I do create files and use them constantly and I want to save them with the Open Source format. So, It would be great to have one.

**Comment by ShockwaveNN** [comment]
Hi we already got a similar request https://github.com/ONLYOFFICE/DesktopEditors/issues/517

But I don't think we'll do it any time soon, all our architecture is based on high compatibility with OOXML formats and I don't think we're planning to change it
