### ISSUE TITLE
File open dialog does not save its size

### ISSUE THREAD

**Issue by Cris70** [ONLYOFFICE/DesktopEditors#828]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.0.0.127

### Expected Behavior

Once I resize the file-open dialog I would expect it to open with the same size, the next time.

### Actual Behavior

The file-open dialog always opens with the same size, regardless of how many times I try to resize it.

### Reproduction Steps

1. click on "open local file"
2. click on "browse"
3. the "open document" dialog opens
4. resize the open dialog (e.g. widen it)
5. choose a document and open it
6. close the document you just opened
7. click on "open local file"
8. click on "browse"
9. the "open document" dialog opens and its size is the initial one, not the one you resized it to

**Comment by Wo1fgang** [comment]
Hello @Cris70 

Sorry for long wait

Can you clarify what kind of Linux OS are you on? Because I tried you scenario on Mint, Ubuntu and OpenSUSE and I couldn't replicate it

**Comment by Cris70** [comment]
Hi @Wo1fgang ,
I'm on OpenSUSE Tumbleweed (the rolling distro).

Cris

**Comment by Wo1fgang** [comment]
@Cris70 thanks, I'll install this OS and try this one more time

**Comment by Wo1fgang** [comment]
Hey @Cris70 

Sorry for long wait

I installed OpenSUSE Tumbleweed, tried the scenario but didn't manage to replicate the problem

Are you sure there's nothing installed that can affect the behavior of windows?
How about other apps, like LibreOffice, can you replicate the problem there?

And just to be on the same page, are you using RPM package or maybe AppImage of flatpak?
Maybe try clean installation of ONLYOFFICE?

**Comment by ShockwaveNN** [comment]
Thanks for your reply, I'll close this issue
