### ISSUE TITLE
Cannot link hyperlink text

### ISSUE THREAD

**Issue by Lululalu** [ONLYOFFICE/DesktopEditors#830]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.0.0.127

### Expected Behavior

The hyperlink is clickable.

### Actual Behavior

It's not clickable

### Additional information

PDF created using Adobe InDesign 2022

**Comment by ShockwaveNN** [comment]
Hi, this is a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1044

Very old issue, currently we still not resolved it
Actual only for PDF viewr
