### ISSUE TITLE
Onlyoffice closes when try open two documents in window mode

### ISSUE THREAD

**Issue by Juniorsnet** [ONLYOFFICE/DesktopEditors#839]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package), Linux (RPM package)

### Version information

7.0.0.127

### Expected Behavior

Open two windows with their respective document

### Actual Behavior

Onlyoffice closes

### Reproduction Steps

- Config onlyofice to operate in window mode.
- Close onlyoffice.
- Open a document vía file explorer, wait to onlyoffice open it.
- Open another document vía file explorer.

### Additional information

I tested in 3 distros (Centos, ubuntu, manjaro) and has the same behavior.

**Comment by matveevms** [comment]
Hello, @Juniorsnet 
Thank you for the report.
I can confirm - this is a bug, issue 55241 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
