### ISSUE TITLE
Color scheme and formatter do not work correctly

### ISSUE THREAD

**Issue by sleepless-ninja** [ONLYOFFICE/DesktopEditors#84]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Selecting color scheme, nothing changes.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Start new document, select color scheme style, corresponding body elements formatter (ie: Normal, Heading 1, etc) do not change to color scheme nor will document if it has content (even if content is entirely highlighted).

**What is the expected behavior?**
Change color scheme and format elements with selected color scheme.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Version 4.8.6.388. Windows 10. Didn't work before either. I have tried this on two different PCs.

**Comment by HellRoad** [comment]
@sleepless-ninja 
DesktopEditors using default colors, if you changed the text color for the default heading and updated it then after changing the color scheme heading color will change

**Comment by sleepless-ninja** [comment]
@HellRoad 
Thanks for pointing me in the right direction.

As you can tell from my report I am aiming to theme the formatting in order not to have to do this over and over.

Unless I'm missing something here, in order to maintain a theme of formatting and color I would have to maintain a boilerplate document to retain it.

**Comment by ShockwaveNN** [comment]
I'm closing this issue. it's pretty old.
Current behaviour of selecting font style is correct.
And to create a color theme it's need to be done on boilerplate document.
Feel free to comment on this issue.
