### ISSUE TITLE
It does not allow configuring a different page size for each one

### ISSUE THREAD

**Issue by andresgarcia0313** [ONLYOFFICE/DesktopEditors#844]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

It does not allow configuring a different page size for each one

**Comment by ShockwaveNN** [comment]
> a different page size for each one

Hi could you clarify for "each one" that?

You can select different page size for each one page for Documents, if you insert section break between them (TopToolbar -> Insert -> Break -> Insert Section Break -> Next page)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
