### ISSUE TITLE
PNG image turns black when printed or saved as PDF

### ISSUE THREAD

**Issue by xyont** [ONLYOFFICE/DesktopEditors#848]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

in Document i have successfully insert vector image (wmf) even the application restrict only bitmap format is allowed.

![2022-02-15 08_26_19-ONLYOFFICE Desktop Editors](https://user-images.githubusercontent.com/72367311/154230809-494683c2-ac4e-430a-8be0-097596a5319c.jpg)

editing, reopening the document is working without any problems. unfortunately saving in PDF is not as expected, the quality image are blocked by black colors.

![2022-02-15 08_27_01-DocumentContainsVectorImage pdf - Adobe Reader](https://user-images.githubusercontent.com/72367311/154230872-29d41070-b1b0-4699-8351-df281b29c32b.jpg)

high quality document are essential for technical writer and many others, supporting to one of these file type could be great features to improves.

attached original document:
[DocumentContainsVectorImage.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/8078373/DocumentContainsVectorImage.docx)

**Comment by TatianaKirillova** [comment]
Hello, [@xyont](https://github.com/michal-barteczko)
Thanks for your request!
I can confirm that the problem exists. I created ticket 55616 in our private  tracker with your proposal. But the picture in the document has a png extension, maybe you wanted to attach another document?
Problem reproduces in Document Server.

**Comment by xyont** [comment]
did not know how it recognize as PNG images, it is actually a WMF formats. 
also i try to zoom in to large enough (500%) and shown no lost in display resolutions.

![Zoom500documentcontainimage](https://user-images.githubusercontent.com/72367311/154488412-d159db8a-52bf-4c33-bb56-c7dcecc41ff0.png)

below is files with another WMF vector images, 
[DocumentContainsVectorImageWMF.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/8088843/DocumentContainsVectorImageWMF.docx)

**Comment by TatianaKirillova** [comment]
You just have a very large image size, so it seems that its increase goes without loss of quality
![размер картинки](https://user-images.githubusercontent.com/72191601/154496259-3b3e1de5-d85b-4032-9a8b-ea4a7bb21213.png)

**Comment by xyont** [comment]
attached links of original images and document i recreated.

[zipped files](https://filetransfer.io/data-package/ySDNYL2z#link)

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
