### ISSUE TITLE
Onlyoffice Desktop Editors fails to open on windows 10

### ISSUE THREAD

**Issue by ellisgeek** [ONLYOFFICE/DesktopEditors#849]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.0.0

### Expected Behavior

Onlyoffice Desktop editors should launch.

### Actual Behavior

After installing Onlyoffice Desktop editors nothing appears to happen. An icon appears in the taskbar and when hovered a white screen is visible. If right-clicking the window preview no menu is displayed (to move the window back on screen).

Clearing the %localappdata%\ONLYOFFICE folder does not help.

Uninstalling Desktop editors and cleaning up leftovers (Using BCUninstaller) and then reinstalling does not help.

Was able to launch desktop editors by right-clicking and running as admin. 

![Zoho_Assist_Ob1dop3Fid](https://user-images.githubusercontent.com/556100/154365773-151665f4-61d0-4364-8d22-157b4fd90737.png)

When launching DesktopEditors.exe with --log I only get a line with the appcast.xml url for updates and no further log messages.

### Additional information

This is a Domain Joined Windows 10 Pro desktop. None of our other computers have this issue.

**Comment by LuckySpecialist** [comment]
Hi, @ellisgeek.
My PC is also in the domain, but I do not observe a similar problem at myself.
We received a similar request, but since we could not repeat the problem in our environment and the user did not provide additional information for its localization, it remained unresolved.

- Do you have any antiviruses installed?
- Try to check for lone processes editors_helper.exe in memory, they may interfere with startup.
- Check the errors in the system log after launching the application. You can view it by running the command (Win+R): `eventvwr.msc /c:Application`

Perhaps the group policies of your organization somehow affect this.
Until we have a specific scenario to reproduce the problem, we will not be able to solve it.

**Comment by dreaddr** [comment]
Same issue here, running on Windows 11 and OnlyOffice 7.0 crashes and does not open. OnlyOffice 6.4 does not have this issue.

**Comment by xyont** [comment]
may this is specific cases, i'm running on windows 10 (64bit) also. not found any problem in starting and using the application. only small suggestion, could be start up loading to be improve and faster?

![2022-02-18 07_59_08-ONLYOFFICE Desktop Editors](https://user-images.githubusercontent.com/72367311/154619544-bd7a7ba2-d68d-40a5-8029-98ba4f86a49c.png)

**Comment by rbircher** [comment]
> Was able to launch desktop editors by right-clicking and running as admin.

This comment I find very interesting. Question: Do you have Windows 10 Pro? Do you have a seperate Admin Account and a User account without Admin rights?

**Comment by PokerFace128** [comment]
I have the same problem, can't start under user. Can be started in administrator mode. The components that are failing are as follows.
Faulting application name: editors.exe, version: 7.0.0.127, time stamp: 0x61e07529
Faulting module name: kernel.dll, version: 7.0.0.127, time stamp: 0x61e04202
Exception code: 0xc0000005
Fault offset: 0x0000000000065c33
Faulting process id: 0x1a58
Faulting application start time: 0x01d82a38b144006c
Faulting application path: C:\Program Files\ONLYOFFICE\DesktopEditors\editors.exe
Faulting module path: C:\Program Files\ONLYOFFICE\DesktopEditors\converter\kernel.dll

**Comment by PokerFace128** [comment]
I was supposed to process the form today, but this guy ruined it. Right now I can only use Libreoffice to work with tables.

**Comment by dreaddr** [comment]
Is this still not fixed? I still have to launch OnlyOffice as admin to get it to work. (Windows 11 Pro, I'll be happy to get any more details for fixing this as it is rather quite annoying, let me know what is needed and how to get them though)

**Comment by LuckySpecialist** [comment]
> Is this still not fixed? I still have to launch OnlyOffice as admin to get it to work. (Windows 11 Pro, I'll be happy to get any more details for fixing this as it is rather quite annoying, let me know what is needed and how to get them though)

Hello @dreaddr and @ellisgeek!
Is the problem relevant to you even on the current version 7.1?

**Comment by dreaddr** [comment]
@LuckySpecialist seems like its fixed on the latest version for me, will let you know if it happens again.

**Comment by ShockwaveNN** [comment]
Thanks for info, in that case I'll close this issue but feel free to comment if got any news/ideas

**Comment by ScamBuster** [comment]
Only Office 8.1 Windows 10 Pro Works generally. Can create documents, but wont open them, and throws this error. Tried reinstalling, but same.  Any known fix for this ?  

editors.exe-system error the code execution cannot proceed because kernel.dll was not found. reinstalling the program may fix the problem

**Comment by LuckySpecialist** [comment]
Hi, @ScamBuster!
Please, provide more complete information about your system, the version of the editors and the type of package installed.
Screenshots of the error or a video demonstration of the problem would be very useful.
