### ISSUE TITLE
Onlyoffice DesktopEditors on WindowsInsiders builds [test]

### ISSUE THREAD

**Issue by SimonTek27** [ONLYOFFICE/DesktopEditors#85]
**I started this topic in order to test ONLYOFFICE in the windowsinsider builds (x64)**

Hello, 
Nice to meet you all, my name is Simone and i am translator for the italian localization of Onlyoffice
as the title says i opened this topic to improve DesktopEditors in Windows 10 since i am a windowsinsider

I begin this topic with the **DesktopEditors v4.8.6.388 x64 on Win10 build 17083**
the DesktopEditors installation is smooth; at the first start of the software the main menu appears quickly but whether I try to create a new document or open an existing one, DesktopEditors takes many minutes before completing the operation; apparently, while loading seems to be blocked, it allows me to switch between the tabs and the DesktopEditor START menu. Once the loading process is completed the program can be used smoothly till it will be closed. Then if you try to restart it you have following file not found issues:

- PdfReader.dll

- DjVuFile.dll

- XpsFile.dll

- HtmlReader.dll

There's no solution but reinstall it, anyway, if a reinstall is done, everything loop as i described
Thanks for your attention

Best regards

**Comment by maxkadushkin** [comment]
Hello, @SimonTek27! thanks for report
does launching via desktop shortcut cause 'file not found' error? did you have installed app one from previous versions?
about slow document opening - could you share your pc configuration?

**Comment by SimonTek27** [comment]
hello @maxkadushkin 
yes it does via desktop shortcut. No, it is a fresh install.

here the config: windows 10 insiders preview x64 on a Q6600 2.40GHz 4Gb ram SSD disk GTX750ti video card.

Previous OO installation (version) was smooth on the same machine

**Comment by SimonTek27** [comment]
short update: yesterday MS released w10 build 17083 and i did several tests, OO works as first run and also if i create another user on the pc, after that  OO doesn't work anymore so i guess it could be something related to Appdata\local any ideas?

**Comment by SimonTek27** [comment]
hi,
i followed your instructions but it worked only once, i mean just for the first run.. however i found a workaround..
if i open an existing file OO runs smoothly and fast, once the loading process is completed i open a new tab to create a new document and that's it

**Comment by SimonTek27** [comment]
[FIX]
removing the shortcut on the taxbar, launch the app and then pin it to the bar again

**Comment by maxkadushkin** [comment]
did it resolve launching error on your PC? or it cause issues like launch via desktop shortcut?

**Comment by SimonTek27** [comment]
it did resolve
i'm unable to explain what was the difference between the two shortcuts.

once hint i could say to users is to check their pin to taskbar every major windows update

**Comment by ShockwaveNN** [comment]
I'm closing this issue since it should be resolved
