### ISSUE TITLE
Remember password/cookies for connected clouds between sessions?

### ISSUE THREAD

**Issue by ebousse** [ONLYOFFICE/DesktopEditors#861]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Using ONLYOFFICE Desktop Editors version 7.0.0.127, I have set up a "connected cloud" to my university Nextcloud+OnlyOffice instance. This works rather well so far.

However, unfortunately, each time I close and re-open OnlyOffice, and try to access this "connected cloud" entry, it asks me to log-in once more into the Nextcloud instance. This is a little time-consuming, especially in my case since I have to use an external password manager.

Could we imagine having OnlyOffice storing the cookies if the connection to NextCloud (same as a browser would do) to avoid having to enter credentials each time?

**Comment by ShockwaveNN** [comment]
Hi, I think it has something to do with your specific instance of Nextcloud

I think [we got a similar issue earlier](https://github.com/ONLYOFFICE/DesktopEditors/issues/599) - and I think we couldn't localize this problem on our instances
Could you find\setup some other instance of Nextcloud and see if save of credential work fine?
