### ISSUE TITLE
Digital signature: selecting encrypted .KEY file freezes the application

### ISSUE THREAD

**Issue by JoseskVolpe** [ONLYOFFICE/DesktopEditors#864]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (Other)

### Version information

7.0.0.127

### Expected Behavior

After selecting the private key .KEY file, i would just insert my private key password in the box and press ok

### Actual Behavior

After selecting the encrypted .KEY file, desktop editors freezes and won't exit
A workaround is to run onlyoffice from terminal and insert password in there **4 times**, since it requests the password there
The fact that it waits for the user to insert the password on the terminal session is what is causing the freeze on the interface

### Reproduction Steps

1 - Create a certificate with a encrypted private key (AES-256 was used)
2 - Go to security > Signature > Digital signature
3 - Select your generated .crt file
4 - Select your generated encrypted .key file

### Additional information

This bug was found on Manjaro Linux installed from package repository.
**ZST package version was installed**, wich is not officially packaged by ONLYOFFICE team

**Comment by ShockwaveNN** [comment]
> This bug was found on Manjaro Linux installed from package repository

Could you clarify which package you've installed? snap or flaptak or appimage

And if you have Ubuntu in our disposal - could you recheck this problem on deb version, I think this may be a bug specific to snap/flatpak/appimage version

**Comment by JoseskVolpe** [comment]
I'm not using any of them, i've installed it directly from Manjaro's repository, you can find the package here: https://manjaro.lucassymons.net/testing/community/x86_64/

I don't have Ubuntu installed on my machine, but i may try it later on a virtual machine or in another machine

**Comment by ShockwaveNN** [comment]
I think this may be problem with this package

It's not our official package, sorry but we do not provide any native version for Manjaro

We happy to help you with snap/flatpak/appimage and other installation type, but for this one - it's better to contact author of this
And I'm not aware who it is, this is first time I see this package

I know that there is unofficial AUR version for Arch/Manjaro - https://aur.archlinux.org/packages/onlyoffice-bin

**Comment by JoseskVolpe** [comment]
Tested by AppImage on Manjaro, i've got the same issue

**Comment by ShockwaveNN** [comment]
Ok thanks for infor

@matveevms please take a look

**Comment by matveevms** [comment]
Hello, @JoseskVolpe .
Could you attach a video of the problem?

**Comment by JoseskVolpe** [comment]
Sure
https://youtu.be/bRF90FT-a-c

I've also noticed the saved file is deleted after i sign my document, and then i'm unable to save it with the same name, so this confirms issue #865, although i've mistakenly described it wrong.
I tested it both native and AppImage

**Comment by ShockwaveNN** [comment]
@JoseskVolpe I don't think we made such fixes in v7.0.1 but maybe something changed in your configuration and this issue is not actual any more

I'll close it but if it occurs again - please contact us

And we'll look at another issue soon
