### ISSUE TITLE
Document is deleted after signing and won't save again

### ISSUE THREAD

**Issue by JoseskVolpe** [ONLYOFFICE/DesktopEditors#865]
~~### This issue is unique.~~

~~- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.~~

~~### Your idea.~~

~~After creating or editing a document and saving it as .PDF format, Onlyoffice deletes the original file... Please, don't do that, that's really annoying and is a high risk of losing your entire work that you might need to modify later~~
~~That's possible to convert PDFs, but the result usually is not good~~
~~I just lost my document and closed the application without the knowledge it would delete it, fortunately the PDF version is good, but i lost my signed DOCX version of the document. I really would not like to forgot that Onlyoffice does that and lost my file again.~~

I've noticed later it's not a feature after exporting it as PDF but a bug on document signing (Related to issue #864).

### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (Other)

### Version information

7.0.1.37

### Expected Behavior

After signing the file, the original file should be replaced with a digitally signed file

### Actual Behavior

After signing file, the application says it was successfully signed, shows my signature, but the file is deleted. I can't save it again unless if i save it with another name or another location, but the signature is lost .

### Reproduction Steps

1 - Create a certificate with a encrypted private key (AES-256 was used)
2 - Go to security > Signature > Digital signature
3 - Insert any reason and press "Select"
4 - Select your generated .crt file
5 - Select your generated encrypted .key file
6 - Insert your password
7 - Click ok > ok
8 - Look into wherever you saved the document

### Additional information

**I'm not using DEB version of the application**
This bug was found on Manjaro Linux installed from package repository (ZST package)

**Comment by TatianaKirillova** [comment]
Hi @[JoseskVolpe](https://github.com/JoseskVolpe). Thanks for the report.
Please provide your OS and version number of desktop editors.

**Comment by ShockwaveNN** [comment]
In light of @TatianaKirillova comment - I think your problem may be related to unofficial build usage, like described here

https://github.com/ONLYOFFICE/DesktopEditors/issues/864#issuecomment-1054089058

Please confirm if same problem is exists on official build (Ubuntu or any other supported os and/or flatpak/appimage/snap) and we'll take a look in more datails

**Comment by JoseskVolpe** [comment]
Couldn't reproduce it with AppImage, so that's a issue on native Manjaro's package

**Comment by ShockwaveNN** [comment]
In that case I'll close that issue

**Comment by JoseskVolpe** [comment]
However, it lost the digital signature by saving with another name

**Comment by JoseskVolpe** [comment]
¡Your welcome!

**Comment by ShockwaveNN** [comment]
I think this issue should be fixed in v7.1.0 but don't know exact commit

Feel free to comment if this issue still actual on latest stable version

**Comment by JoseskVolpe** [comment]
> I think this issue should be fixed in v7.1.0 but don't know exact commit
> 
> Feel free to comment if this issue still actual on latest stable version

Actually, it freezes when using a .crt file. Using a .pfx file generated from a .crt works.
A .crt file is a public certificate wich should be used to validate signatures, a .pfx file is used to sign documents
I think it could check the existence of a .pfx file and reject if it receives a .crt file without any .pfx in the path.

**Comment by ShockwaveNN** [comment]
DesktopEditors v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions
