### ISSUE TITLE
Bug: NSHtmlRenderer not found in ascdocumentscore.dll

### ISSUE THREAD

**Issue by yatsukav** [ONLYOFFICE/DesktopEditors#87]
*bug*

On application launching after update.

---------------------------
editors.exe - Entry point not found
---------------------------
Entry point in procedure ?CloseFile@CASCHTMLRenderer3@NSHtmlRenderer@@UEAAJ_N@Z not found in library DLL C:\Program Files\ONLYOFFICE\DesktopEditors\ascdocumentscore.dll. 
---------------------------
ОК   
---------------------------

Windows 10. Last version.

**Comment by HellRoad** [comment]
@yatsukav 
Yes it is bug and this will be fixed in next update
For correctly working DE needed remove and install again

**Comment by maxkadushkin** [comment]
is it after automatic update? or manual update?

**Comment by yatsukav** [comment]
@maxkadushkin ONLYOFFICE offered me to update and I agreed. I think it was automatic update?

**Comment by maxkadushkin** [comment]
yes, it was automatic update. and it was failure. could you reinstall app like @HellRoad suggested?

**Comment by ShockwaveNN** [comment]
Version 5.2.4 of DesktopEditors was released and issue should be fixed.
