### ISSUE TITLE
'Internet connetion Failed' in during openning a document....

### ISSUE THREAD

**Issue by rommy2015** [ONLYOFFICE/DesktopEditors#871]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

Wndows 10 - 20H2 - Windows Feature Experience Pack 120.2212.4170.0

### Expected Behavior

When I try to open a document I have gotten an error "Interner connetion failed ...."
Why ?

### Actual Behavior

![Screenshot_238](https://user-images.githubusercontent.com/24729823/157645450-c2fb28cd-f74c-4c0b-b445-fafdcda99926.png)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
