### ISSUE TITLE
Ability to customize numbered lists' index format

### ISSUE THREAD

**Issue by itsdmd** [ONLYOFFICE/DesktopEditors#873]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Operating System
Zorin OS 16.1 (Ubuntu 20.04 LTS)

### Version information
OnlyOffice DesktopEditors 7.0.1.37 - DEB Package

### Expected Behavior
An option to customize numbering lists' index format.

For example: instead of the default:
```
1. This is
2. A default
    a. Numbered list
3. Format
```

I can customize it to be something like:
```
1) This is
2) A customized
    (a) Numbered list
3) Format
```

### Actual Behavior
There's no option to change that in list setting in the current version

![image](https://user-images.githubusercontent.com/87557436/158094505-e873abeb-d983-4617-b7e8-251063fe5c35.png)

### Reproduction Steps
OnlyOffice DesktopEditors 7.0.1.37 Document > Home > Numbering > List Settings

### Additional Information
Hope this and more advanced features to customize numbered lists' format can be implemented since MS Office Word has a lot of parameters available for its numbered list and being able to also modify them within OnlyOffice, to my believe, will increase the suite's compatibility with .docx documents.

![image](https://user-images.githubusercontent.com/87557436/158095802-d648a56f-d8da-4551-8ce0-97eaed3db311.png)

**Comment by matveevms** [comment]
Hello, @itsdmd 

This is known issue - 43143 in our private issue tracker.
Thank you for report.

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
