### ISSUE TITLE
OnlyOffice displays PPT presentation from 1C incorrectly

### ISSUE THREAD

**Issue by szelga** [ONLYOFFICE/DesktopEditors#88]
OnlyOffice Desktop 4.8.6.388 x64, Windows 7 Pro SP1.

the presentation itself: http://1c-itil.ru/upload/uf/fb1/fb1058d142f0e35c51df4081254e4a79.ppt

see the attached screenshots:

OnlyOffice:

![ppt onlyoffice](https://user-images.githubusercontent.com/1784948/35608654-ce33b99c-067b-11e8-9c54-73fe24ca06a2.png)

Powerpoint 2010:

![ppt powerpoint](https://user-images.githubusercontent.com/1784948/35608655-ce5790ec-067b-11e8-8fc3-c29bd9c1861e.png)

LibreOffice 4.3 (for the complete picture):

![ppt libreoffice](https://user-images.githubusercontent.com/1784948/35608652-ce124370-067b-11e8-9058-e661aaaaa8eb.png)

**Comment by flaminestone** [comment]
Hello @szelga. This problem will be fixed in documentserver 5.1 and in future versions of desktop editors. Thanks for the issue

**Comment by szelga** [comment]
thanks.

**Comment by flaminestone** [comment]
Fixed
Version 5.1.29.350 (Desktop Editors)
