### ISSUE TITLE
Document is Deleted When Saving Change to Network Location Mounted by Nautilus (Linux)

### ISSUE THREAD

**Issue by BaronKrause** [ONLYOFFICE/DesktopEditors#880]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.1.37

### Expected Behavior

Opening a file from a mounted network location inside of Nautilus and saving will save the file changes.

### Actual Behavior

Opening a file from a network location mounted in Nautilus and saving will delete that file.

### Reproduction Steps

1. Mount a network location in Nautilus
2. Create a new file and save it to that location
3. close OnlyOffice
4. open OnlyOffice and open that new file
5. make a modification and save it
6. The file is now deleted

### Additional information

It seems to work fine from manually mounted locations done via the command line with CIFS, but the ones mounted through Nautilus that go to "/run/user/<userid>/gvfs/smb-share:server=<server IP>,share=<share name>" don't seem to work properly.

You can save new files to those locations, and open files from them, but if you open a file and save a change, the file is simply deleted. Ive tested this with multiple different mounted devices.

I believe this is something that use to work fine not that log ago.

This was tested on Pop OS 21.10 using the official ppa version of OnlyOffice on 2 different machines with the same result.

**Comment by matveevms** [comment]
Hello, @BaronKrause 
We are aware of this issue (issue 56211 in our private issue tracker) and it has already been fixed. The issue has been fixed via [ONLYOFFICE/sdkjs@46ee8c5](https://github.com/ONLYOFFICE/desktop-sdk/commit/e9393267e6e26a1eabe701be76f75ab525b5cbd7) and will be available as DesktopEditors v7.0.2, but we do not currently have an ETA date.

**Comment by yllekz** [comment]
Please expedite this, I lost a huge paper I was working on due to this bug :(

**Comment by ShockwaveNN** [comment]
DesktopEditors v7.1.0 is release and this issue should be definitely fixed
