### ISSUE TITLE
 Cannot reduce window size on linux - Same issue on mac: #379 

### ISSUE THREAD

**Issue by bambirombi** [ONLYOFFICE/DesktopEditors#882]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.0.1-1

### Expected Behavior

Resize the window as you can do with the rest of software (e.g.:firefox). You can resize to half of the screen, for example, firefox. 

### Actual Behavior

You cannot resize when you click with the mouse and carry onlyoffice to the right or the left. It does not adapt to half of the screen.

**Comment by Wo1fgang** [comment]
Hello @bambirombi
Could you please specify which Linux system you are on exactly and version of ONLYOFFICE? Because I don't remember this (7.0.1-1) version

**Comment by bambirombi** [comment]
Yes. It is arch linux. Installed from the official repositories (community). Now it is version 7.0.2-1 and the issue continues.

**Comment by Wo1fgang** [comment]
@bambirombi Sorry, but we (ONLYOFFICE team) do not provide any native version of DesktopEditors for Arch Linux

If you use flatpak\appimage\snap version of DesktopEditors - we'll be happy to help

I'm not sure which exactly version you meaning, but if it's installed via pacman - probably it was made not from our team and you better to contact it's creator

**Comment by bambirombi** [comment]
It happens exactly the same with the last AppImage.

**Comment by H-DOMINA** [comment]
I have this exact same issue when using onlyoffice in Fedora 36. Previously while using arch with kde everything worked just fine. I install both versions using Flatpak

**Comment by XDmitryK** [comment]
@bambirombi Hi
Do you keep having the same problem on version 7.3.3?

**Comment by bambirombi** [comment]
@XDmitryK No. Now it seems to work.
