### ISSUE TITLE
Can't maximize ONLYOFFICE window to the right or left side of the screen

### ISSUE THREAD

**Issue by r4rmas** [ONLYOFFICE/DesktopEditors#885]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.0.1 (531) Apple Silicon

### Expected Behavior

The expected behavior is that the user could maximize the ONLYOFFICE window to the left or the right side of the screen.

### Actual Behavior

The actual behavior doesn't allow the user maximize the ONLYOFFICE window to the right or left side of the screen.

https://user-images.githubusercontent.com/57473003/162660564-fa371c0e-66dc-4405-8430-da00055d31d7.mp4

### Reproduction Steps

1. Open OnlyOffice
2. Maximize the window to the left or the right side of the screen

### Additional information

- I'm using a MacBook Pro with M1 Pro chip
- MacOS Monterey 12.3.1
- My screen resolution is 3024 × 1964

**Comment by Gingetsu** [comment]
Hello, @r4rmas .
We know about this behaviour. We discuss this issue with our development team (issue 40055 & issue 48288 in our internal issue tracker).

**Comment by Gingetsu** [comment]
This issue fixed .
Feel free to comment or reopen it if you got further questions.
