### ISSUE TITLE
Change slide aspect ratio

### ISSUE THREAD

**Issue by Zstorm999** [ONLYOFFICE/DesktopEditors#889]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I have to create a slideshow for work, however to fit with the current style of the other related work done by others, the aspect ratio should be 4:3 instead of the default 16:9. 

I couldn’t find an option to choose the aspect ratio, even though the editor works fine with both. I had to create the slideshow in LibreOffice, change the aspect ratio there, and later import it into OnlyOffice.

**Feature proposed**
Add an option inside the slide parameters to choose an aspect ratio for all slides, predefined or with a dimension chosen by the user.

**Comment by ShockwaveNN** [comment]
Hi, do you mean this option?
![image](https://user-images.githubusercontent.com/668524/163556511-c17511e9-7870-41e7-b647-01dcf7b31ea5.png)

It's on this button
![image](https://user-images.githubusercontent.com/668524/163556563-45071510-b333-45ea-bbff-0a6f5b8f4bf0.png)

**Comment by Zstorm999** [comment]
Oh thanks, I couldn’t find it !

I’m closing the issue then
