### ISSUE TITLE
Can't Maximize OnlyOffice with Flatpak

### ISSUE THREAD

**Issue by hamuto** [ONLYOFFICE/DesktopEditors#890]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.1

### Expected Behavior

I expect it to maximize when I click on the maximize button.

### Actual Behavior

Before maximize:
![image](https://user-images.githubusercontent.com/39059643/163560571-e7996832-e9c8-4cbd-b72f-5dc01edf1ef5.png)
After maximize:
![image](https://user-images.githubusercontent.com/39059643/163560645-1fbee52f-1165-4374-9e87-037aa841fdbc.png)

I can't maximize the app.

### Additional information

I use the Flatpak package from the Pop Shop:
![image](https://user-images.githubusercontent.com/39059643/163560708-dea47808-6a30-4372-89a9-b0d34d5fcc02.png)

**Comment by hamuto** [comment]
If needed, I can share the default settings from Flatseal for the app

**Comment by hamuto** [comment]
I found a solution, it was changing the interface scaling:
![image](https://user-images.githubusercontent.com/39059643/163561064-ce534ced-e2b8-485b-8203-8766d420c09c.png)

**Comment by ShockwaveNN** [comment]
Yeah, I think problem was because for some reason interface scaling was not correctly setup by default, not sure why - if you really want it we can try to figure out reason with you 

But if not I will close this issue, feel free to comment through if you got some questions
