### ISSUE TITLE
Dark Mode activation in dumb location?

### ISSUE THREAD

**Issue by Thermalzombie** [ONLYOFFICE/DesktopEditors#894]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

People may disagree with me but I think having the Dark Mode activation in the hamburger menu is a dumb idea.  Having the Dark theme setting in the settings menu made me think there was no way to change the page color.  It took me a while to find the setting in the hamburger menu.

I also searched the internet for how to change page color in Onlyoffice and found nothing but mentions of Dark Mode. 

Thanks.

**Comment by Wo1fgang** [comment]
Hey @Thermalzombie 

In ONLYOFFICE update 7.1 there will be added a "View" tab, where you can easily turn on and off Dark Mode and change interface themes.

![image](https://user-images.githubusercontent.com/19489765/164425582-65b521f1-3fd5-46e5-a631-1952e90a161e.png)

Unfortunately, I can't provide you any details about when this version will be released

Hope you have a great day

**Comment by ShockwaveNN** [comment]
DesktopEditors v7.1 was released quite a time ago, closing this
