### ISSUE TITLE
Presentation editor doesn't show themes upoaded on the server (Nextcloud + DocumentServer)

### ISSUE THREAD

**Issue by jiriks74** [ONLYOFFICE/DesktopEditors#897]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.2.5

### Expected Behavior

When editing presentation  file synced with Nextcloud through DocumentServer themes that are available are shown and can be selected.

### Actual Behavior

When opening presentation file through Nextcloud in the DesktopEditors app, themes that are available on the server are not shown, only the default ones are there.

To use theme installed on the server, I have to open Firefox, go to Nextcloud, find the file, open it with OnlyOffice in the browser, select it there and then I can go back to DesktopEditors where the theme is applied due to collaboration. I have to do this every time I want to choose a non-default themes.

### Reproduction Steps

1. Put your `.pptx` theme to `/var/www/onlyoffice/documentserver/sdkjs/slide/themes/src` on the server
2. Run `/use/bin/documentserver-generate-allfonts.sh`
3. Wait until fonts and themes are done generating
4. Open/create a file and check that the theme you added is available in the browser
5. Login to Nextcloud in the DesktopEditors app
6. Open/create a file and check that the theme you added isn't available in the DesktopEditors app

### Additional information

I added multiple `.pptx` files and none of them worked. When I added some (probably borked) `.potx` files the theme generation failed as I saw only one, blank, theme both in browser and in the DesktopEditors app. All the themes can disappear from both, but when I added an extra theme it didn't appear in the DesktopEditors app. - Looks like it synchronizes only partially or that there's only a check that the local themes exist on the server as well and there is no theme synchronization at all.

It there any synchronization for themes? I also assumed that it opens the same eay as the browser (online editors) therefore everything available on the server would be available in the DesktopEditors app, but from this issue I assume it's the normal desktop editor and that it's accessing the file through an API not a webapp as in the browser version.

**Comment by ShockwaveNN** [comment]
Hi, could you attach pptx file you've used to generating themes, so we'll check your rather complicated case on same file

**Comment by jiriks74** [comment]
File is attached below

[Eleanor · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8543917/Eleanor.SlidesCarnival.pptx)

**Comment by jiriks74** [comment]
I added some more themes that I'm generating right now, so once it's done I'll update you whether any of them got synced between the server and desktop editors.

**Comment by ShockwaveNN** [comment]
So, I've checked your file on DocumentServer (without starting the DesktopEditor part)

And seems after placing file to `/var/www/onlyoffice/documentserver/sdkjs/slide/themes/src` and running `/usr/bin/documentserver-generate-allfonts.sh`

There is no new theme in the list of themes:
![image](https://user-images.githubusercontent.com/668524/165052270-fcb1e416-46f9-4d5e-b66e-5fb313a66f3b.png)

Are you sure you get them in the browser?

**Comment by jiriks74** [comment]
Yes I am sure. I added more themes, so you'll see a bunch of them in the screenshots of the web editors:

Web editors:
<details>

![image](https://user-images.githubusercontent.com/54378412/165103344-da9aa81f-1f36-4c61-a740-8212cc2580e5.png)

</details>

Desktop editors:
<details>

![image](https://user-images.githubusercontent.com/54378412/165103549-26f26baf-fde5-4ae1-88db-3bd4e5e04479.png)

</details>

I added them the same way as before.

**Comment by ShockwaveNN** [comment]
I think in that case I need some examples of your other themes

**Comment by jiriks74** [comment]
It's the same with them, but anyways, here they are:

<details>

[Bianca · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558376/Bianca.SlidesCarnival.pptx)
[Cordelia · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558377/Cordelia.SlidesCarnival.pptx)
[Cymbeline · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558378/Cymbeline.SlidesCarnival.pptx)
[Dardanius · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558380/Dardanius.SlidesCarnival.pptx)
[Dumaine · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558381/Dumaine.SlidesCarnival.pptx)
[Eleanor · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558383/Eleanor.SlidesCarnival.pptx)
[Ephesus · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558384/Ephesus.SlidesCarnival.pptx)
[Friar · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558385/Friar.SlidesCarnival.pptx)
[Hubert · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558387/Hubert.SlidesCarnival.pptx)
[Iago · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558388/Iago.SlidesCarnival.pptx)
[Imogen · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558390/Imogen.SlidesCarnival.pptx)
[Juliet · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558391/Juliet.SlidesCarnival.pptx)
[Knight · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558392/Knight.SlidesCarnival.pptx)
[Messala · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558393/Messala.SlidesCarnival.pptx)
[Nathaniel · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558396/Nathaniel.SlidesCarnival.pptx)
[Osric · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558397/Osric.SlidesCarnival.pptx)
[Puck · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558398/Puck.SlidesCarnival.pptx)
[Quince · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558399/Quince.SlidesCarnival.pptx)
[Tybalt · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558400/Tybalt.SlidesCarnival.pptx)
[Ursula · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558401/Ursula.SlidesCarnival.pptx)
[Vernon · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558402/Vernon.SlidesCarnival.pptx)
[Viola · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558403/Viola.SlidesCarnival.pptx)
[Volumnia · SlidesCarnival.pptx](https://github.com/ONLYOFFICE/DesktopEditors/files/8558404/Volumnia.SlidesCarnival.pptx)

</details>

**Comment by jiriks74** [comment]
Another thing. I've been looking into generating the themes locally (desktop editors) until we figure out why is it not syncing. Well I found how to do that on Windows. Linux instructions work only for the server as I couldn't find the necessary script(s) to make it work. I'm thinking of trying to just copy the (`sdkjs/slides/themes`) folder to the desktop editors.

**Comment by ShockwaveNN** [comment]
> Linux instructions work only for the server as I couldn't find the necessary script

Sorry I don't think we got proper instruction how to do that correctly

I think one alternative would be to edit empty files in some other software, with adding those themes and replace default DesktopEditor empty file to one with themes

**Comment by igwyd** [comment]
Hello @jiriks74 you can't adding themes in presentation, it's not implemented in DesktopEditors at this moment. We have issue 52233 in our private issue tracker, we are working on it. 
We have already fixed the problem with adding and displaying custom themes in documentserver (issue 56872 in our private tracker), the fix will be released in the next release.

**Comment by shu0406** [comment]
So this one will be fixed with v7.1?
https://github.com/ONLYOFFICE/DocumentServer/issues/246 

Will there be any instructions how to add custom themes on document server?

**Comment by jiriks74** [comment]
@shu0406 
There are instructions on how to add themes to documentserver [here](https://helpcenter.onlyoffice.com/installation/docs-community-add-themes-linux.aspx). The problem is that there are no instructions for desktop editor and that desktop editors won't show themes installed on the server.

**Comment by shu0406** [comment]
Thanks a lot for that information! I thought that it is not possible regarding that issue https://github.com/ONLYOFFICE/DocumentServer/issues/246

**Comment by jiriks74** [comment]
As shown in picture below, issue is solved

![image](https://user-images.githubusercontent.com/54378412/168167492-7555ff7c-0311-4032-a034-d2f56387b398.png)

**Comment by ShockwaveNN** [comment]
@jiriks74 glad that issue is resolved, since we gig a lot of troubles discussing it )

**Comment by jiriks74** [comment]
> @jiriks74 glad that issue is resolved, since we gig a lot of troubles discussing it )

Looks like it's working flawlessly. And with your arm64 server I get to generate my themes in like 20 minutes instead of 2 hours and 20 minutes and that's pretty awesome.

A quick question: Are you planning to support generating themes in DesktopEditors as well? (maybe ea simple interface where you'd see all themes, so you could delete them, and a button to upload a new one would be a nice thing, if you're able to generate themes individually - or you could regenerate all. And I think that that could be good for DocumentServer as well).

**Comment by ShockwaveNN** [comment]
> Are you planning to support generating themes in DesktopEditors as well?

Right now our developers do not decided that, issue 52233 is about generating themes in DesktopEditors

**Comment by ShockwaveNN** [comment]
@jiriks74 Yeah, simple plain issue about DesktopEditors themes support will be good, since this one is rather messy

**Comment by jiriks74** [comment]
> @jiriks74 Yeah, simple plain issue about DesktopEditors themes support will be good, since this one is rather messy

Ok, it'll be there sometime today
