### ISSUE TITLE
Page layout doesn't change when using LibreOffice's next page style feature.

### ISSUE THREAD

**Issue by Zardshard** [ONLYOFFICE/DesktopEditors#898]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.2.5

### Expected Behavior

Page layout should change when opening a .odt file saved by LibreOffice (such as [this](https://github.com/ONLYOFFICE/DesktopEditors/files/8539927/test.odt) file) that includes a page style change caused by the "Next Style" page style option. For example, this occurs when transitioning from the "First Page" page style to the "Default Page Style" via a page break.

### Actual Behavior

The page layout (in the example below, the page size) is the same on both pages.

### Reproduction Steps

1. Open LibreOffice (I used version 7.3.2.2 on Ubuntu 20.04 installed from the snap package)
2. Set the page style of the current page to "First Page." The "First Page" style is used because it has **Next style** set to "Default Page Style" by default.
    To do this:
    1. Select **View - Styles**
    2. In the sidebar that pops up (or was already up) press the **Page Styles** icon
    3. Double click **First Page**
3. Insert a page break by pressing **Insert - Page Break**
4. Change the "First Page" style's dimensions to make the transition from the first page's style to the second page's style obvious.
    To do this:
    1. In the sidebar, right-click **First Page**.
    2. Choose **Modify...**
    3. Select the **Page** tab
    4. Change the width and the height. (I set the width to 5" and the height to 3")
    5. Choose **OK**

    You should now have a small first page and a normal-sized second page.
5. Save the file. [This](https://github.com/ONLYOFFICE/DesktopEditors/files/8539927/test.odt) is the file you should get.
7. Open in ONLYOFFICE.

### Additional information

ONLYOFFICE displays the file properly when using manual page breaks. For example:
    1. Open the file created in the section "Reproduction Steps"
    2. Click on the second page. A text cursor should display in the second page.
    3. Press the backspace key until the second page is deleted.
    4. Press **Insert - More Breaks - Manual Break...**
    5. Choose **Default Page Style** in the **Page Style** menu.
    6. Save. You should get [this](https://github.com/ONLYOFFICE/DesktopEditors/files/8540604/test.odt) file.
    7. Open in ONLYOFFICE.

Also, the problem occurs with any page style that uses the **Next style** property.

**Comment by XDmitryK** [comment]
In MS Word the behavior is similar to Onlyoffice, but I created bug 57197 on our local bug tracker.

**Comment by XDmitryK** [comment]
This will be fixed in version 8.2
https://github.com/ONLYOFFICE/core/commit/e91c72a265fd60c284237a1e0ae3b8e6e8e19912

**Comment by Rita-Bubnova** [comment]
DesktopEditors v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
