### ISSUE TITLE
Font style is different on exported PDF

### ISSUE THREAD

**Issue by Petersoj** [ONLYOFFICE/DesktopEditors#899]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.0.1 (531) Apple Silicon

### Expected Behavior

Exporting a document to PDF format with the "Avenir Next" font (a font on macOS) should look the same on the exported PDF as it does on the ONLYOFFICE desktop editor.

### Actual Behavior

Exporting a document to a PDF (using File > Save as) will bold and italicize the "Avenir Next" font upon export.

### Reproduction Steps

1. Create a new document using the desktop Apple Silicon version of ONLYOFFICE.
2. Type something and set the font to "Avenir Next" but leave it as a regular character style (no bold or italics):
![Screen Shot 2022-04-23 at 2 28 49 PM](https://user-images.githubusercontent.com/14127217/164945211-5e55e64c-6510-4504-bd45-e4fa1ce30a8f.png)
3. File > Save as > and save the document as a .PDF.
4. Open the PDF and observe the font being bolded and italicized:
<img width="423" alt="Screen Shot 2022-04-23 at 2 30 42 PM" src="https://user-images.githubusercontent.com/14127217/164945272-c7174a66-738b-44aa-89b9-39fb1f41c56a.png">

For reference, here's what the font looks like bolded and italicized in the desktop editor:
![Screen Shot 2022-04-23 at 2 30 53 PM](https://user-images.githubusercontent.com/14127217/164945292-629edde5-1bd5-45c1-9236-eb45679bb55c.png)
As you can see, the screenshot of the exported PDF looks the same as the bolded and italicized font in the desktop editor. This is how I know the font is, for some reason, being bolded and italicized upon PDF export.

**Comment by AchillesBoi** [comment]
It's been more than a year since this bug was reported and it still happens. Is there a timeline on when to expect this bug to be fixed?

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
