### ISSUE TITLE
Trendline

### ISSUE THREAD

**Issue by flaurafauna** [ONLYOFFICE/DesktopEditors#903]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Add the ability to insert trendlines into charts like on every other office program.

**Comment by ShockwaveNN** [comment]
Thanks for your report, this is duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/965

Currently we have no exact time frame of implementing that
