### ISSUE TITLE
Error: An error has occurred while opening the file. Windows OS

### ISSUE THREAD

**Issue by D1RK-ui** [ONLYOFFICE/DesktopEditors#904]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.0.1.37

### Expected Behavior

Any supported file must open without errors

### Actual Behavior

After trying to open a file I get the following "an error has occurred while opening the file". I've found the solution of this problem, but it's on Linux, while I'm using Windows

### Additional information

System type: 64-bit operating system, x64-based processor

**Comment by ShockwaveNN** [comment]
Hi, does this error happens to any file (even new empty ones) or for some specific files. If only for specific - we'll need those files

**Comment by D1RK-ui** [comment]
This error happens to any file

**Comment by ShockwaveNN** [comment]
This is not right, could you try to reinstall DesktopEditors?

Also after installation - remove all data in Program Files - ONLYOFFICE - DesktopEditors folder

Maybe something went wrong after some update

**Comment by D1RK-ui** [comment]
I've done sharp as you had told me, but I still have this problem.
Honestly, I don't know, why is it

**Comment by D1RK-ui** [comment]
The way you mentioned Program Files - ONLYOFFICE - DesktopEditors, there my
program is living. If I delete this folder, then the program would be
deleted as well. So, what do you mean by "remove all data"?

**Comment by ShockwaveNN** [comment]
Oops, I'm sorry

I've meant that you should delete our application, after that delete all leftowers (if any) in Program Files) and after that install DesktopEditor anew and see if problem persists

**Comment by D1RK-ui** [comment]
Unfortunately, after performing all of the actions the problem persists

**Comment by LuckySpecialist** [comment]
Hi @D1RK-ui!
Unfortunately, you have not provided specific steps to deal with the problem.
Tell us how you open the file:
- Launch the application and select open file there?
- Use the system context menu to Оpen with...?
- Or maybe you have associations with the application and you double-click on the file?

Also, maybe you changed the default settings of the application to open documents in a separate window?

A few more additional questions:
- Do you have any antiviruses installed?
- Try to check for lone processes editors_helper.exe in memory, they may interfere with startup.
- Check the errors in the system log after launching the application. You can view it by running the command (Win+R): `eventvwr.msc /c:Application`

**Comment by D1RK-ui** [comment]
I use Windows built-in antivirus (it doesn't detect anything associated
with your app). And I tried to open a file *in different ways* and every
time I'm trying to create a new one or open an existing one, *I get the
same error message* (watch attached video). Also I don't have any
editors_helper.exe processes while using the editor. But I have a very
interesting thing: I tried to launch that editors_helper.exe and got
several messages about the absence of some DLL files (look at attached
photos). I tried to reinstall your app several times and I got the same
problems

**Comment by ShockwaveNN** [comment]
> several messages about the absence of some DLL files (look at attached
photos).

Seems that you've attached photos using github mail reply and this will not work, we cannot see them, you should attach them via web interface

**Comment by D1RK-ui** [comment]
Okay, I'll attach photos in other way
- https://user-images.githubusercontent.com/76046959/179421432-269795d5-7fde-4203-be4d-bd4e71d81e88.png
- https://user-images.githubusercontent.com/76046959/179421435-20d0e993-c12b-4d24-bc2a-22e46c9a7584.png
- https://user-images.githubusercontent.com/76046959/179421438-f734d379-535a-4c3d-9ece-bc93865699f8.png
- https://user-images.githubusercontent.com/76046959/179421439-1a3469ea-7b0c-42f2-b7c0-3f4a5bae1849.png

I also will attach a video to demonstrate you how the error occurs
- https://user-images.githubusercontent.com/76046959/179421509-a0fdd9a3-4bbf-4f7a-b3fa-fe1658ffe036.mp4

**Comment by LuckySpecialist** [comment]
Hi, @D1RK-ui!
Sorry for the long answer, but judging by the video that you attached, you have an error when creating a new file and not when opening an existing one - right?
In this case, try the following:
1. Close the application
2. Save a backup copy from the **_fonts_** directory, тo open it, run the command (Win+R):
`%LOCALAPPDATA%\ONLYOFFICE\DesktopEditors\data\fonts\`
3. Delete the contents of the **_fonts_** directory
4. Run the app again
5. Create a new file

Report the results, whether the problem remains.

**Comment by D1RK-ui** [comment]
Actually, I have an error every time, when I open any file whether an
existing one or a created one. I performed all of the action, but nothing
changed. Thanks for response

**Comment by D1RK-ui** [comment]
Alright, it will be a great option for me to change the service. I close this discussion. Good luck
