### ISSUE TITLE
picture stay joint after double upload

### ISSUE THREAD

**Issue by ggrrll** [ONLYOFFICE/DesktopEditors#906]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

online

### Expected Behavior

being able to handle multiple pictures, after uploading 2 (or more) at the same time

### Actual Behavior

if you try to move / increase size, they stay together 

ps: I think I will stop using OO ...there are too many missing features... UI has recently a bit improved, but UX is still quite behind 

### Reproduction Steps

upload two pictures are the same time 

(good luck trying to split them)

**Comment by ggrrll** [comment]
not sure... now it seems to be working...it is not consistent ( I am on https://www.switch.ch/drive/ , which imported OO online... UX is not very good)

**Comment by Wo1fgang** [comment]
Hey @ggrrll, sorry for long wait
I don't really understand the problem and can't reproduce it (when I upload multiple images, they don't need to be split), the behavior is similar to Microsoft, for example.

Can you share any video with this problem please? It would really help understanding the problem

**Comment by ggrrll** [comment]
ok never, 

I also cannot reproduce, as I cannot only import 'from-file' one picture at the time -- this is also something it could be improved 

thanks anyway
