### ISSUE TITLE
[Feature request] Move away from nodeJS/JS

### ISSUE THREAD

**Issue by CountOmega** [ONLYOFFICE/DesktopEditors#907]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I know this is a long shot and would take considerable effort to implement, but please consider moving away from JS for the desktop apps. Especially when saving lager spreadsheets, you can tell the performance is poor. Comparable programs like Gnumeric and LibreOffice Calc almost save instantly (tested it with the same document). Same goes for opening.

**Comment by ShockwaveNN** [comment]
Sorry, I don't think it's possible in near time

We constantly improving our loading times, but we do not plan to move from JS engine for something else for DesktopEditors

I think the main reason of this - that right now the engine for both DocumentServer and DesktopEditors are the same so there is not much human resources spend on developing DesktopEditors

So consider DesktopEditors are like `free addition` to our flagship DocumentServer
But if DesktopEditors will be on different engine - I don't think we'll be able to leave it completely free or have enough time to proper support it

So it's lesser of two eveils and we chose JS engine

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
