### ISSUE TITLE
OnlyOffice not maximizing

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/DesktopEditors#911]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.2.5

### Expected Behavior

When i press the program maximizes

### Actual Behavior

The program doesnt maximize

### Reproduction Steps

1: Click the maximize button
2: Program doesnt maximize

### Additional information

https://user-images.githubusercontent.com/104151562/166809358-e7b7ed7f-a774-4347-9fad-c811be6b6b02.mp4

**Comment by ShockwaveNN** [comment]
Hi, could you clarify your system name, desktop resolution, and scaling settings?

Because I've checked it on my popos 22.04 with FullHD display and 100% display scale - maximizing window works without any issues

**Comment by AurelioGlitch** [comment]
> Hi, could you clarify your system name, desktop resolution, and scaling settings?
> 
> Because I've checked it on my popos 22.04 with FullHD display and 100% display scale - maximizing window works without any issues

Resolution: 1920 X 1080 OS: Pop!_OS 22.04 LTS Scale: 100%

**Comment by ShockwaveNN** [comment]
Hm, you setup looks like exactly like mine and I'm not able to reproduce it

Are you sure that you've installed `deb` version of DesktopEditors, not something other version I need to check?

**Comment by AurelioGlitch** [comment]
> Hm, you setup looks like exactly like mine and I'm not able to reproduce it
> 
> Are you sure that you've installed `deb` version of DesktopEditors, not something other version I need to check?

yes im using the .deb

**Comment by ShockwaveNN** [comment]
Maybe some specific pop!_OS settings are enabled? Could you try it on another PC, because I've no idea that's the reason

**Comment by bcesarx** [comment]
Hi,

I have the same issue. I'm unsing ubuntu 22.04 LTS

**Comment by ShockwaveNN** [comment]
@bcesarx Hi, we still have no way to reproduce this issue, since it's ok on any version of Ubuntu I've tried

As for previous user I'll ask

> 
Maybe some specific pop!_OS (or ubuntu in your case) settings are enabled? Could you try it on another PC, because I've no idea that's the reason

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
