### ISSUE TITLE
How to build DesktopEditors by QT in WIN10?

### ISSUE THREAD

**Issue by dwang010** [ONLYOFFICE/DesktopEditors#912]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

After reading zhe URL :https://helpcenter.onlyoffice.com/desktop/documents/windows/compile-desktop-windows.aspx, I tried to build the project by QT . finally I failed. As a newman, I think  that detail steps to building such project is very useful.

**Comment by ShockwaveNN** [comment]
Sorry, this instruction is completly outdated and we'll remove it soon

But currently we have no proper instruction for compiling Windows version, sorry

Same problems are described in [here](https://github.com/ONLYOFFICE/build_tools/issues/105)
