### ISSUE TITLE
[feature request] Use system-native theme for default title bar

### ISSUE THREAD

**Issue by LeBrick-Studio** [ONLYOFFICE/DesktopEditors#913]
- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

___
Add a key or an option to show tabs and "ONLYOFFICE" menu button on top of **system** title bar. Perhaps make it optional (like in Firefox), e.g. use a separate key for it

## Examples:
![Mozilla Firefox with system title bar ON and OFF](https://user-images.githubusercontent.com/71165491/167263660-4cb8660a-73a6-4abb-9a24-5414ddbff383.png)Mozilla Firefox with system title bar ON and OFF

![Google Chrome's title bar on Windows 11, Windows 7 and Ubuntu 20.04](https://user-images.githubusercontent.com/93297305/168008637-29c193dc-b533-4bdb-9db2-ded1fe68bdd6.png)Google Chrome's title bar on Windows 11, Windows 7 and Ubuntu 20.04

**Comment by ShockwaveNN** [comment]
Hi, could you check command line flags:
```
--system-title-bar
```
and
```
--custom-title-bar
```

They change window behavior same way as Firefox on your screenshot

**Comment by LeBrick-Studio** [comment]
Well it's kind of not the same. The suggestion was to integrate tabs into native-themed title bar across all platforms by default (like the lower Firefox window), and --system-title-bar key will enable actual system title bar with tabs row under it (see upper Firefox window).

I made a few better illustrations


### How it works without any keys:
![oo1b](https://user-images.githubusercontent.com/93297305/167415132-c56f7584-7318-463e-8415-40d70d38d44d.png)
![oo1w](https://user-images.githubusercontent.com/93297305/167415141-65452857-d40a-4fd9-89fa-7447742c617e.png)


### How it works with `--system-title-bar` key:
![oo2b](https://user-images.githubusercontent.com/93297305/167415166-9c019eef-8580-49aa-9eee-488e8c0f0bae.png)
![oo2w](https://user-images.githubusercontent.com/93297305/167415170-34901234-f698-4ec8-8f91-97429fdd188b.png)


### What do I suggest:
![oo4b](https://user-images.githubusercontent.com/93297305/167415350-759267d8-5e0a-412c-9daa-bbd7c7a00fc3.png)
![oo4w](https://user-images.githubusercontent.com/93297305/167415363-57d2b6fe-5653-4044-8414-90e81efdd943.png)

**Comment by ShockwaveNN** [comment]
@LeBrick-Studio Not sure that we can do that in QT

Do you know any QT application that can do that?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
