### ISSUE TITLE
Search Bar in Cloud Extension

### ISSUE THREAD

**Issue by necib13** [ONLYOFFICE/DesktopEditors#918]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hello,

I think it would be nice to add a search bar on cloud extension, if i open my cloud without the desktop app i have one but if i do with ONLYOFFICE i have to search every file manually it discourage a lot to use the app,

Thank you for your time and have a great day

**Comment by necib13** [comment]
![SearchBar](https://user-images.githubusercontent.com/37078546/168569331-976f8de5-0a64-4104-a95c-4279271d22c6.png)
![WithoutSearchBar](https://user-images.githubusercontent.com/37078546/168569345-195c7bab-392f-4ab1-bf67-3fbf0349ae9d.png)

Im using Owncloud,

Here you can see if i open it on my browser i can use the searchBar to find my files (in some folder i have a lot so it really helps)

And on the other pictures if i connect my Owncloud to OpenOffice, the searchBar disappear so i cant search,

Hoping i have been clear enough

**Comment by matveevms** [comment]
Hello, @necib13.
I can confirm - this is bug, issue 57192 in our private issue tracker.
Thank you for report.

**Comment by matveevms** [comment]
Hello, @necib13 @jiriks74 
We received a response from the developers that this problem is not on the side of our desktop editors. This question should be addressed to OwnCloud and NextCloud developers, respectively. Thanks again for your report.
