### ISSUE TITLE
Cloud connection to nextcloud server opens dashboard for browsing - no cloud filesys added

### ISSUE THREAD

**Issue by daudtivan** [ONLYOFFICE/DesktopEditors#924]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

Full figures:
Elementary OS 6.1 (Ubuntu 20.04.3 LTS), kernel Linux 5.13.0-41-generic
Nextcloud server 22.2.3 by unodata.com.br

### Version information

ONLYOFFICE Desktop Editors version 7.0.1.37
Flatpak 1.12.7

### Expected Behavior

I expected to see a new nextcloud server added to the list of clouds, so I could open its files in on my local app

### Actual Behavior

After authentication, nextcloud's dashboard is displayed for navigation and I can work its files online, but no cloud gets added to the list.

### Reproduction Steps

1. click Add Cloud button
2. enter credentials and authenticate
3. nextcloud dashboard is displayed
4. close nextcloud tab
5. check list of clouds: no new cloud

### Additional information

Recorded my screen to demonstrate it
![OO-desktop-NC-cloud-issue](https://user-images.githubusercontent.com/91741832/169109580-1c6fa651-cba2-4d0b-bb07-2495f8e5d7eb.gif)

**Comment by daudtivan** [comment]
Just registered the same cloud on my tablet and it worked just fine.
That cloud was registered and the spreadsheet works as expected.
It is clearly an issue with the desktop app.

**Comment by ShockwaveNN** [comment]
Hi
> same cloud on my tablet and it worked just fine.

Yeah, mobile apps use the completely different engines to store data

Could you check two things?

1. Try deb version of DesktopEditors which is already v7.1.0, maybe this issue is fixed (not sure)
2. Try to connect to another nextcloud cloud, maybe the problem is somehow related to unodata.com.br setup

**Comment by daudtivan** [comment]
@ShockwaveNN Just did both what you asked and got same results: 
1) nextcloud from unodata.com.br opens for browsing and is not listed
2) nextcloud from tab.digital opens and gets listed

Any new attempt to 1:unodata.com.br results in just browsing. Credentials are saved and I can get to all my stuff there.

Apart from that, I wonder if opening the content of the cloud address is even correct, as all I want is to register remote clouds?
Not sure who decided for it, but I would say it's unnecessary.  A popup with a success message would do the trick and save time. 

The way it works today assumes one will guess its working as content is displayed from the remote location and then realize by yourself nothing else will happen after the content is rendered: no popups will come!
Simplifying that could result in a better user experience.

Question is: is that a bug? Or a feature request?
Your thoughts are welcome.

**Comment by daudtivan** [comment]
If you hv the patience, here's the gif with my attempts, right after setup (2:30 total)
![OO-cloud-connection-issue](https://user-images.githubusercontent.com/91741832/169297046-c891e28a-2d5e-4956-a192-db59935ad495.gif)

**Comment by ShockwaveNN** [comment]
UPD: our developers think that on unodata.com.br has not setup our connector for nextcloud on their side, but can't tell for sure without any access

**Comment by daudtivan** [comment]
> UPD: our developers think that on unodata.com.br has not setup our connector for nextcloud on their side, but can't tell for sure without any access

Invited my contact to join the discussion and check what could be happening on their side.

**Comment by daudtivan** [comment]
> > Apart from that, I wonder if opening the content of the cloud address is even correct, as all I want is to register remote clouds?
> > Not sure who decided for it, but I would say it's unnecessary. A popup with a success message would do the trick and save time.
> > The way it works today assumes one will guess its working as content is displayed from the remote location and then realize by yourself nothing else will happen after the content is rendered: no popups will come!
> 
> I'm sorry I don't get that part at all

Let's try this way:
A) user -> new cloud -> credentials -> content -> close content 
B) user -> new cloud -> credentials -> success msg

B is shorter and ends on a confirmation message which is more clear and saves time (as much as 30secs).
It should be the way to go in my opinion.

**Comment by daudtivan** [comment]
> UPD: our developers think that on unodata.com.br has not setup our connector for nextcloud on their side, but can't tell for sure without any access

What did they say about the fact IT IS working on the mobile app? Are there multiple setups?
The issue affects the desktop app only and I tend to believe it's one setup for all platforms.

**Comment by ShockwaveNN** [comment]
> What did they say about the fact IT IS working on the mobile app? Are there multiple setups?

The code for handling nextcloud are completely different in mobile apps than DesktopEditors

If I'm not mistaken - mobile apps uses `WebDav` to handle file access, but DesktopEditors use something provided from our connectors, which should be properly setup on Nextcloud side

**Comment by daudtivan** [comment]
I noticed webdav was requested +1y ago on #589 
That should be the way to go as it could simplify things and deliver an uniform UX among platforms.
Upvoted it.

**Comment by ShockwaveNN** [comment]
@daudtivan Thanks, better to leave comments, than upvoting, since we got no notification of upvotes, but every comment we add to our internal tracker to track user requests

**Comment by daudtivan** [comment]
@ShockwaveNN Thanks for the note. Will do.

**Comment by pon00** [comment]
It looks, that I have the same bug - no files , when connected to nextcloud. It is all OK in Windows
Linux mint 5.4.0-135-generic cinnamon
Package (DEB): onlyoffice-desktopeditors
Version: 7.2.1-36 

WebDav sounds good, but not for group editing the same file.

**Comment by stelioskat** [comment]
I am having exactly the same issue with ONLYOFFICE Desktop Editors version 7.2.1.36 (snap package) on PopOS.

I really hope it gets fixed or gets WebDAV support

**Comment by XDmitryK** [comment]
@daudtivan @stelioskat 1178
This problem has been previously seen on NC version 24 issue #1178 and below, you can update the NC and check if the problem still exist?

**Comment by cvinhaes** [comment]
I have the same problem, self hosted Nextcloud here. It used to work fine with older versions of OnlyOffice, now it does not work anymore. A tab with the files opens but no entry is added to the list of clouds.

**Comment by LuckySpecialist** [comment]
Hi @cvinhaes!
Which version of the Desktop Editors app, nextcloud server, and ONLYOFFICE connector are you using?

**Comment by cvinhaes** [comment]
> Hi [@cvinhaes](https://github.com/cvinhaes)! Which version of the Desktop Editors app, nextcloud server, and ONLYOFFICE connector are you using?

Hi Lucky,

I'm not sure about the Onlyoffice connector, I don't think I ever needed one. About the other apps:
OnlyOffice **Desktop** Editors v.9.3.1.8
Nextcloud v.31.0.14

**Comment by LuckySpecialist** [comment]
Hi @cvinhaes, the ONLYOFFICE connector must be installed for it to work correctly. Contact the nexcloud server administrator to clarify this information, and by the way, version 31 is EOL now.

**Comment by cvinhaes** [comment]
Hi @LuckySpecialist , do you mean[ this connector](https://helpcenter.onlyoffice.com/integration/nextcloud.aspx)?

Checking the documentation again I could find the following under the Desktop Editors section:
_It's supposed that you already have Nextcloud server, ONLYOFFICE Docs and the integration app installed and configured._ 

So your reply makes a lot of sense now. Thank you for the input again!
