### ISSUE TITLE
Romanian characters sometimes not displayed correctly in .ODT files

### ISSUE THREAD

**Issue by cypresstwist** [ONLYOFFICE/DesktopEditors#93]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

ODF files created in LibreOffice containing Romanian characters such as ”ș” and ”ț” are nod displayed correctly although they do appear in some places of the same document.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See attached screenshot and archived ODT file.

**What is the expected behavior?**

”ș” and ”ț” should be displayed correctly in files

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Using Linux, Ubuntu 16.04.3, ONLYOFFICE version 4.8.7.392.
![screenshot at 2018-02-17 15-39-22](https://user-images.githubusercontent.com/14321154/36341591-4feaf2d6-13f9-11e8-86ca-8c7b11fa6084.png)
[lista lucrari publicate razvan.odt.zip](https://github.com/ONLYOFFICE/DesktopEditors/files/1733710/lista.lucrari.publicate.razvan.odt.zip)

**Comment by HellRoad** [comment]
This is famous problem, her will be fixed in new version DesktopEditors (5.1 or newest)

**Comment by ShockwaveNN** [comment]
This problem should be fixed in DesktopEditors 5.2
I'll close this issue. If problem actual - please create new issue
