### ISSUE TITLE
[Feature Request] Right-Click on pinned taskbar icon function add

### ISSUE THREAD

**Issue by AbnormalN8** [ONLYOFFICE/DesktopEditors#931]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I would like to request a feature enhancement to the pinned taskbar icon to enable the ability to see recently opened documents and have the ability to pin them to the right-click menu for quick access.

Essentially duplicating what Microsoft Office currently has. I enjoy having quick access to my most used files only a right-click away.

e.g. 
![image](https://user-images.githubusercontent.com/26538102/170661844-ef1918c7-f875-493a-bfb1-d9c678316b03.png)

**Comment by LuckySpecialist** [comment]
Hi @AbnormalN8, according to your request, I have issued an enhancement #63817.
Thanks for the feedback.

**Comment by LuckySpecialist** [comment]
The requested functionality has been added in this [commit](https://github.com/ONLYOFFICE/desktop-apps/commit/9302386bb490f50da49b06a48c44421f801a2898) and will be included in the next version of the editors.

**Comment by Rita-Bubnova** [comment]
Desktop Editors v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
