### ISSUE TITLE
How to build DesktopEditors in windows ?

### ISSUE THREAD

**Issue by wxz879526** [ONLYOFFICE/DesktopEditors#932]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

How to build DesktopEditors in windows ?

**Comment by ShockwaveNN** [comment]
Hi, I'll mark this as duplicate of https://github.com/ONLYOFFICE/build_tools/issues/105#issuecomment-643986828

Sorry, but we still have no proper instruction for windows build
