### ISSUE TITLE
Find and Replace crashes the editor

### ISSUE THREAD

**Issue by bhlevca** [ONLYOFFICE/DesktopEditors#933]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.1 

### Expected Behavior

Not  Expect a Crash

### Actual Behavior

crashes when you press the replace button

### Reproduction Steps

1. select Find
2. Press replace 
3. Crash

**Comment by ShockwaveNN** [comment]
Hi, I've checked same scenario and there is no crush for me on Ubuntu 22.04

Could you describe this os are you using and clarify if you installing our official deb package, not some custom one because I never heard about such issue and I think we've noticed it if it happen on any system

**Comment by bhlevca** [comment]
I found the problem. The AppImage version that I used first was incomplete. I installed the `deb` version and I experienced the same crashes. When accidentally I did an `apt update` there was a complaint about missing some fonts from onlyoffice-desktop. I can't remember the name for sure but I think it was `fonts-crosextra-carlito`.  However, after installing those fonts the crash does not happen anymore. 

I think that you should fix the Appimage by adding the fonts. I like installing/using  Appimage better than packet-managed ones. If packaged properly they are the best/

**Comment by ShockwaveNN** [comment]
> The AppImage version that I used first was incomplete.

Could you describe what you mean it was incomplete? AppImage is a single file application and I do not understand how it may be incomplete

> However, after installing those fonts the crash does not happen anymore.

So are you saying if I find a system there is no `fonts-crosextra-carlito` and start AppImage DesktopEditors I can get same crash, am I right?

**Comment by bhlevca** [comment]
I know that the Appimage is a container. What I am saying is that I assume that the fonts are not included in the container.

It may be that the fonts are not at fault. However, after I installed the fonts the problem does not occur anymore. I have not tested the Appimage after installing the fonts and in fact, it should not matter.

I was getting the crash only when doing find/replace by pressing the arrow button.

**Comment by bhlevca** [comment]
Actually, this version is very buggy.  It hangs for no reason, it can't save sometimes the work that was done, during this time you can't even select text with your mouse. A big step back from 7.0.1 

Is it possible to download the previous version 7.0.1? Thanks

**Comment by ShockwaveNN** [comment]
Previous released aviable here https://github.com/ONLYOFFICE/DesktopEditors/releases

And for AppImage [here](https://github.com/ONLYOFFICE/appimage-desktopeditors/releases)

You can try them out but not sure that issues your described is introduced in new build, I don't think we've missed them, so maybe something wrong with your system or some very rare settings

**Comment by bhlevca** [comment]
It is possible  that there is something particular to my system. that's the reason I like  AppImage, which is supposed to have all dependencies included.   I am using KWayland as a window display, it could be one of the reasons.

Thanks for the link, I'll revert to v7.0.2 until a new version appears.

On another note: Is there any setting in DesktopEditors that would find/underline/highlight in-between words spaces that are more that 1 character wide? MS Office has it and it is a very useful feature.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
