### ISSUE TITLE
If you open the same file multiple times, it will open in multiple windows.

### ISSUE THREAD

**Issue by Xazev** [ONLYOFFICE/DesktopEditors#934]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, Linux (DEB package)

### Version information

7.1.0.215

### Expected Behavior

Expanding the window of an already open file as in MS Office, LibreOffice, WPS Office

https://user-images.githubusercontent.com/11159920/170940173-25e973eb-9432-4501-86f8-7fe5ff06f466.mp4

### Actual Behavior

If you open the same file multiple times, it will open in multiple windows.

### Reproduction Steps

https://user-images.githubusercontent.com/11159920/170939273-e55ac849-1a96-4965-9429-5b189370c4c4.mp4

### Additional information

The problem is reproduced on both Windows and Linux

**Comment by Wo1fgang** [comment]
Hello @Xazev

We fixed that issue (sorry, can't specify exact commit) in upcoming release that should be coming out in near future

Thanks you for making our product better

**Comment by ShockwaveNN** [comment]
DesktopEditors v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions
