### ISSUE TITLE
If you open a document when several documents are already open, then the window with the opened document does not expand. Both in window mode and in tab mode

### ISSUE THREAD

**Issue by Xazev** [ONLYOFFICE/DesktopEditors#935]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.1.0.215

### Expected Behavior

If you open a document when several documents are already open, then the window with the opened document does not expand. Both in window mode and in tab mode

### Actual Behavior

There is not even a warning like in Windows that "The file is already open"

### Reproduction Steps

https://user-images.githubusercontent.com/11159920/170942266-36731c3e-ba30-4afb-802f-a6226b664889.mp4

**Comment by Wo1fgang** [comment]
Hi, @Iangh59
I can confirm - this is bug, issue 49255 in our private issue tracker.
There's also an issue [#587 ](https://github.com/ONLYOFFICE/DesktopEditors/issues/587) with the same problem
Thanks for reporting
