### ISSUE TITLE
[Feature Request] In the preview add: Printer selection, number of copies and print range

### ISSUE THREAD

**Issue by Xazev** [ONLYOFFICE/DesktopEditors#937]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

In the preview add: Printer selection, number of copies, selecting duplex printing and print range. (doc and xls documents)

**Comment by matveevms** [comment]
Hello, @Xazev 
Please specify which operating system are you using?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by Tarek-Hasan** [comment]
Print selection added in v9.0, so all requested features in this issue has been implemented.

**Comment by Rita-Bubnova** [comment]
Hello @Tarek-Hasan, thank you for your report.
Feel free to comment or reopen it if you got further questions.
