### ISSUE TITLE
When opening a document in a window, it does not expand to full screen

### ISSUE THREAD

**Issue by Xazev** [ONLYOFFICE/DesktopEditors#938]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, Linux (DEB package)

### Version information

7.1.0.215

### Expected Behavior

Full screen opening

### Actual Behavior

https://user-images.githubusercontent.com/11159920/170951251-44daa4a7-8902-49ba-a043-367187eaf38d.mp4

**Comment by LuckySpecialist** [comment]
Hi @Xazev!
This is a known Bug 58399 on our private tracker.
Thank you for feedback.

**Comment by LuckySpecialist** [comment]
Hi @Xazev,
We have released a new version of editors 7.3, which includes a fix for the problem. Now new documents opened in a separate window inherit the Maximize mode.
Can you check it and let me know if everything is working correctly for you?

**Comment by LuckySpecialist** [comment]
The fix https://github.com/ONLYOFFICE/desktop-apps/pull/558 is included in release 7.3.
Issue can be closed.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
