### ISSUE TITLE
Ligature support

### ISSUE THREAD

**Issue by danvim** [ONLYOFFICE/DesktopEditors#94]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

There is no ligature for Fira Code.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Install Fira Code.
2. Try one of its ligatures, e.g. ```->```

**What is the expected behavior?**
You should see a connected arrow

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

4.8.7.392

**Comment by ShockwaveNN** [comment]
@danvim Thank you for an issue, we have plans for support of ligatures but not in near future

**Comment by Weasy666** [comment]
Hello! Wanted to ask if there was any progress on ligatures or if you have an eta?

**Comment by Rita-Bubnova** [comment]
Hello, @Weasy666.
Sorry, currently we have no ETA.

**Comment by jaredweinfurtner** [comment]
ligatures would be an awesome inclusion for technical presentations

**Comment by TatianaKirillova** [comment]
Hello! @jaredweinfurtner, ligatures are implemented in the current release

**Comment by jaredweinfurtner** [comment]
@TatianaKirillova: I am on `ONLYOFFICE 7.2.1` and do not see any support for font ligatures for Presentation (PowerPoint).  I am using [Jetbrains Mono](https://www.jetbrains.com/lp/mono/).

**Comment by TatianaKirillova** [comment]
@jaredweinfurtner yes, ligatures are implemented only for the document editor
