### ISSUE TITLE
Two icons in the taskbar

### ISSUE THREAD

**Issue by it2000-the-original** [ONLYOFFICE/DesktopEditors#948]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.1.0.215

### Expected Behavior

When you click on the launcher called "ONLYOFFICE Desktop Editors" the onloffice window should open which joins the launcher icon by having control of the window directly on the launcher as in the flatpak, snap and appimage version

Flatpak version:
![Schermata del 2022-06-09 11-52-55](https://user-images.githubusercontent.com/93731405/172820028-b8f611ea-74d9-4015-a784-a8b125c5a670.png)

### Actual Behavior

But instead when you click on the launcher a second icon appears on the taskbar called "DesktopEditors" which ruins the link with the launcher and this thing is not nice to see

What i see:
![Schermata del 2022-06-09 11-33-55](https://user-images.githubusercontent.com/93731405/172820895-06dba347-569e-4184-8e70-379f6c7b031e.png)

**Comment by Rita-Bubnova** [comment]
@it2000-the-original, Sorry for the long wait.
DesktopEditors v7.4.1 is released. Is this issue relevant?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
