### ISSUE TITLE
Forum broken.

### ISSUE THREAD

**Issue by Achaean** [ONLYOFFICE/DesktopEditors#95]
Actually not an only office bug.
I just want to report that forum (at dev.onlyoffice.org) is broken.
Although you can subscribe and login, you can't post.
There's no way contacting admins or the company directly, so I'm posting it here.

Bye! :-)

**Comment by ibnpetr** [comment]
Your comments probably were sent to a moderation queue.
The forum is alive, please check if your posts are approved.

**Comment by Achaean** [comment]
Nope! This isn't the case! :-)
(And I never received such a message (like "your comment awaits moderation").

From faq:
How do I post a topic in a forum?
To post a new topic in a forum, click the relevant button on either the forum or topic screens. You may need to register before you can post a message. A list of your permissions in each forum is available at the bottom of the forum and topic screens. Example: You can post new topics, You can vote in polls, etc.

Well...the aren't such indications (and I tried with different browsers.
Still can't post.
Oh well...fell free to discard this report or contact the forum mods - admins etc.
I wish you best of luck with it! ;-)
