### ISSUE TITLE
"End" key moves cursoe off page, resumes typing on next page

### ISSUE THREAD

**Issue by JesseSteele** [ONLYOFFICE/DesktopEditors#953]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.1.0.215

### Expected Behavior

When pressing <key>End</key>, the cursor should move to the last character of the current line.

### Actual Behavior

**In the Document** editor, pressing <key>End</key> often results in the cursor moving far right off the page, then when typing it resumes on the page below.

### Reproduction Steps

1. Open a document, such as .odt or .docx.
2. Type some text.
3. Press <key>End</key>.
4. Watch the cursor appear at the right of the page, which is off the printable area.
5. Continue typing.
6. This does not always happen. You may need to do some normal typing, but frequently using <key>End</key>.
7. Happened with document formats: .docx, .odt, .doc.

### Additional information

I stated that the installed OS is using the RPM package. Actually, I am using Manjaro/Arch Linux, using the native `onlyoffice` package from the main `pacman` repository. I encourage your team to add an option for Arch/Manjaro or "binary" builds. Because it is Arch, it will probably be one of your most recent versions.

**Comment by ShockwaveNN** [comment]
Hi, we'll look into your issue

But about

>  I encourage your team to add an option for Arch/Manjaro or "binary" builds

I don't think we'll do that until we will provide our official build for Arch/Manjaor packages. Right now it's build by someone else, not by our team

**Comment by JesseSteele** [comment]
I also noticed the same behavior with this issue when simply clicking to the right of the printable area. The cursor moves to the far right of an empty line, even with "Align Left" set, then typing begins on the next line or page.

**Comment by JesseSteele** [comment]
> 

Please at least have an additional option for selecting the Operating System, such as "Other/Binary Build". That should cover Arch since they build it directly anyway.

**Comment by JesseSteele** [comment]
> Hi, we'll look into your issue
> 
> But about
> 
> > I encourage your team to add an option for Arch/Manjaro or "binary" builds
> 
> I don't think we'll do that until we will provide our official build for Arch/Manjaor packages. Right now it's build by someone else, not by our team

Please at least have an additional option for selecting the Operating System, such as "Other/Binary Build". That should cover Arch since they build it directly anyway.

**Comment by JesseSteele** [comment]
I also noticed the same behavior with this issue when simply clicking to the right of the printable area. The cursor moves to the far right of an empty line, even with "Align Left" set, then typing begins on the next line or page.

**Comment by TatianaKirillova** [comment]
Hello, @JesseSteele!
Can't reproduce your problem. What system shell are you using? For the best understanding of the problem, attach a video, please

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
