### ISSUE TITLE
Croatian spell check and document language

### ISSUE THREAD

**Issue by mabasic** [ONLYOFFICE/DesktopEditors#96]
Is there support for croatian language spell checking?

It says that the text is croatian, but it is marked red.
When I try to set the language to croatian I cannot choose it from the menu.

**Comment by HellRoad** [comment]
Hi
This language will be avaible in the next update

**Comment by mabasic** [comment]
Awesome. Thank you

**Comment by mabasic** [comment]
Still no support for Croatian spell checking in the new version?

**Comment by Rita-Bubnova** [comment]
Hello, @mabasic.
Sorry for misleading message, seems we forgot to include new supported languages in DesktopEditors, they only aviable in DocumentServer for now. We try to fix it in next release of DesktopEditors. Bug 37860.
Thanks for noticing this.

**Comment by mabasic** [comment]
Is there a date when this will be implemented?

**Comment by ShockwaveNN** [comment]
Version 5.2.4 of DesktopEditors was released and issue should be fixed.
