### ISSUE TITLE
Paste from some applications removes line breaks (CR)

### ISSUE THREAD

**Issue by RolandBBerlin** [ONLYOFFICE/DesktopEditors#960]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, macOS 10.12 or higher

### Version information

7.0.1 (531)

### Expected Behavior

I copy information from a table in the application Monkey Office (bookkeeping software from ProSaldo). 
![original table in Monkey Office application](https://user-images.githubusercontent.com/48863382/174434711-791807ea-82c6-4a3b-b1a4-f2c0bd76a0bc.png)
Then I paste it into a table document in OnlyOffice. The fields of the table should be inserted as a table in several rows and columns. This works with Microsoft Excel and LibreOffice. 

I noticed this behaviour since switching to ONLYOFFICE  a few weeks ago.

### Actual Behavior

When pressing Ctrl+V the fields of the table are inserted in one single row. The line break is ignored.
![table when inserted into ONLYOFFICE](https://user-images.githubusercontent.com/48863382/174434825-f2104023-ea4e-49a5-b9cd-c879274a3119.png)

The line break is also ignored, when pasting into a text document - all fields are shown in one continuous line.

### Reproduction Steps

I found that OnlyOffice has this behaviour, when the text copied that has only CR line break (Classic Mac OS).
This I could reproduce with an editor that lets you choose the line break - in my case SubEthaEdit on Mac. I set the line break type to "Classic Mac OS (CR)". Then a type some numbers separated by Tab and then "Enter" and some other numbers.
When now in the editor all the text is marked and copied (Ctrl+A, Ctrl+C) and then pasted into Onlyoffice (Ctrl+V), the numbers appear in one single row/line.

### Additional information

I could reproduce this behaviour also with the online version of ONLYOFFICE.

**Comment by Rita-Bubnova** [comment]
@RolandBBerlin, Sorry for late restonse, seems we missed this issue.
DesktopEditors v7.4.1 is released. Please state is this problem still actual for you?

**Comment by RolandBBerlin** [comment]
The issue was fixed in version 7.2. Sorry for not closing the issue sooner.
Thanks for your work!
