### ISSUE TITLE
cant edit pdf file on docs

### ISSUE THREAD

**Issue by finete** [ONLYOFFICE/DesktopEditors#962]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.1.0

### Expected Behavior

having the insert/edit tab on a pdf file.

### Actual Behavior

only have the file and plugins tabs.
cant edit or add pages to pdf files even though the website says I can.

### Reproduction Steps

1. get a pdf file
2. open with only office desktop edition

**Comment by ShockwaveNN** [comment]
Hi, currently we have no pdf editor, we already have [issue](https://github.com/ONLYOFFICE/DocumentServer/issues/1359) about that

> cant edit or add pages to pdf files even though the website says I can.

Could you point out exact place where it said so

**Comment by finete** [comment]
![image](https://user-images.githubusercontent.com/34818222/174596198-faed1f95-c8e9-4b47-b114-136ef5fa880d.jpeg)

It's implied from here that you can do all the actions on all the formats

**Comment by finete** [comment]
On a second view it does only say convert, closing
