### ISSUE TITLE
Option to disable system-scaling and allow setting a custom interface scaling in Windows 11

### ISSUE THREAD

**Issue by Katzenwerfer** [ONLYOFFICE/DesktopEditors#965]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

(Using Windows 11, but there was no option in the dropdown)

### Version information

7.1.0.215

### Expected Behavior

On a more recent version, the ability for the program to respect the system-scaling options on Windows was added.
In Windows 11 (haven't checked about Windows 10) a feature was introduced to scale only the text on the interface separately from other elements, so you could have a small interface with a larger text. It could be expected that for compatibility options and accessibility a way to set a custom scaling, similar to previous versions, would be available.

### Actual Behavior

ONLYOFFICE doesn't respect the text scaling setting, so the interface ends up being both really small and with small text, without any way to change it independently of the system-wide scaling setting.

### Additional information

![image](https://user-images.githubusercontent.com/53267697/176064799-89001103-00a2-43bc-b329-142196422264.png)
100% system-wide scaling

![image](https://user-images.githubusercontent.com/53267697/176064851-a8ce02b8-d4e1-4b18-a023-0672d778c865.png)
125% system-wide scaling

**Comment by LuckySpecialist** [comment]
Hi @Katzenwerfer !
Thank you for contacting us, but one clarification is needed.
Have you changed the setting in the system, to make the text bigger, and want it to affect the editors, or do you want to switch the scaling of the application in the settings, as it was before?

**Comment by Katzenwerfer** [comment]
In this case, to switch the scaling of the application in the settings, as it was before.

**Comment by LuckySpecialist** [comment]
In this case, running the editor with the parameter `--system-scale=0` will help you.
You can read in the [online help](https://helpcenter.onlyoffice.com/installation/desktop-flags.aspx) how to do this.

**Comment by Katzenwerfer** [comment]
Ok, I might have missed that parameter when I was looking around the documentation. 
Launching the program with it works correctly.

Will be closing the issue now, thanks for the help.

**Comment by maxkadushkin** [comment]
hello @Katzenwerfer ! what system scaling do you use? and what scaling had you used in the app before it disappeared?
