### ISSUE TITLE
Sorting by date in the table doesn't work correctly

### ISSUE THREAD

**Issue by RDKRACZ** [ONLYOFFICE/DesktopEditors#966]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.1.0.215

### Expected Behavior

After sorting I should have the newest or oldest dates first.

### Actual Behavior

weirdly sorted mess

### Reproduction Steps

Download this file and try to sort the dates in the table
https://files.fm/u/fa87zs2sp or https://fastupload.io/BZlGLqxZEiHIow7

**Comment by RDKRACZ** [comment]
The same behavior happens in the onlyoffice online/personal/cloud editor

**Comment by alinasafonova** [comment]
Hello, @RDKRACZ

Current behavior is correct.
Dates in your file are written as text, so they cannot be correctly sorted as dates. Other editors (MS Excel, LibreOffice) also sort these dates as text.

**Comment by RDKRACZ** [comment]
Even after changing data type to date it still doesn't sort correctly (and doesn't in LibreOffice too so I have no idea what's going on)

![image](https://user-images.githubusercontent.com/43277609/177275954-ec14b172-d911-4111-9ee0-31c0688b76b0.png)

**Comment by alinasafonova** [comment]
@RDKRACZ
Probably this date format (dd/mm/yyyy) does not match your regional settings, so dates cannot be recognized.
You can try to fix dates in your file like this:

https://user-images.githubusercontent.com/53475320/177359226-aed77993-47ce-4426-a8be-adff90d960d1.mp4

Your dates probably will look different, it depends on your regional settings.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
