### ISSUE TITLE
Onlyoffice desktop off-screen issue

### ISSUE THREAD

**Issue by filkeith** [ONLYOFFICE/DesktopEditors#97]
There is a bug.

I was working with document on external monitor. Then, I've send my laptop to sleep, and disconnected monitor. Now all documents, that I'm trying to open, opens off-screen (it thinks that I still have external monitor). I don't have external monitor, because I'm on working trip, and can't move the window back.
Also I've tried all tricks that usually help with mysql workbench (it has the same problem):
- right click on task bar and choose cascade windows
![image](https://user-images.githubusercontent.com/1285713/37972469-1cb65d1e-31e1-11e8-817e-19dd07d4fa03.png)
- trying to move with shift+right click but there is no such menu in onlyoffice
![image](https://user-images.githubusercontent.com/1285713/37972555-4858a1de-31e1-11e8-9663-1f8d1be5f05a.png)

OS: Windows 10 Pro x64
OO: 4.8.7.392

**Comment by HellRoad** [comment]
Thanks for feedback
yes we knows this problem. We'll try to think of something

**Comment by Wad67** [comment]
This is still occuring

**Comment by Rita-Bubnova** [comment]
Hello.
@Wad67, thank you for the message.
I reproduced this problem on Windows 11, ONLYOFFICE Desktop Editors version 6.4.2.6.
I create issue 53484 in our private issue tracker.

**Comment by catbasilio** [comment]
Fixed in version 7.3
