### ISSUE TITLE
Interface scaling setting is missed

### ISSUE THREAD

**Issue by newsgroupspentamidine** [ONLYOFFICE/DesktopEditors#971]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I understand it's a better end goal to use windows scaling setting, but I only want to make OnlyOffice larger.

Unless I'm missing something I'm not a fan after spending the past hour trying to figure out why this setting was missing. finally found it burried on the github # Change log

"
#### All Editors

* Use system scaling option for screen on Windows 10 and later
"

**Comment by LuckySpecialist** [comment]
Hi @newsgroupspentamidine!
This is not an error, but a planned behavior by our design department.
You are not the first user who addresses this problem and there is already a bug 56532 for this.
I hope that in the future the decision will be reviewed and the option will be returned again.
At the moment, you can take the advice from [this post](https://github.com/ONLYOFFICE/DesktopEditors/issues/965#issuecomment-1169141895) and return the option manually.
Thanks for the feedback.

**Comment by Emil9736** [comment]
I also have the issue with scaling ui, everything is small.

**Comment by maxkadushkin** [comment]
hello! @Emil9736 and @newsgroupspentamidine , what system scaling do you use? and what scaling had you used in the app before it disappeared?

**Comment by yllekz** [comment]
Can confirm the setting is missing in Linux Mint 21 with a 4K resolution.

**Comment by ShockwaveNN** [comment]
@yllekz Please check that you got the latest version of DesktopEditors, this setting is missing only on the Windows version, and should be on the Linux system

If it's really not present - I think it's better to create separate issue

**Comment by LuckySpecialist** [comment]
Hi @newsgroupspentamidine!
Interface scaling option is back in 7.2 release, so you can check how it works for you and write back.

**Comment by ShockwaveNN** [comment]
Closing this issue since v7.2.0 was released several weeks ago

Feel free to comment or create new issue if got any related problems
