### ISSUE TITLE
Copying and Pasting an image from Firefox creates a distorted image

### ISSUE THREAD

**Issue by lookingafar** [ONLYOFFICE/DesktopEditors#974]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package), Windows 11 (22000.795)

### Version information

7.1.1-1

### Expected Behavior

The image is pasted correctly. See the screenshot
![Screenshot from 2022-07-14 12-42-36](https://user-images.githubusercontent.com/36126988/178900510-b1b1e4c0-592d-4547-8bd0-8ecee3c9e6f4.png)

### Actual Behavior

A distorted image is pasted in the document or presentation (see screenshot).
![Screenshot from 2022-07-14 12-41-40](https://user-images.githubusercontent.com/36126988/178900415-fac0af03-107d-4a0a-b499-5f4298421e1e.png)

### Reproduction Steps

How to reproduce
1. Open this link in Firefox (my version is 102.0.1 (64-bit))
https://cn.bing.com/images/search?view=detailV2&ccid=hTn6BxLP&id=035C70C829956C7CF72884602752356790C99053&thid=OIP.hTn6BxLP1rAf4x0QsrbtygHaD4&mediaurl=https%3a%2f%2felements-cover-images-0.imgix.net%2fba08e2b2-ca9b-4965-8a61-9c1fdfed801f%3fauto%3dcompress%26crop%3dedges%26fit%3dcrop%26fm%3djpeg%26h%3d630%26w%3d1200%26s%3df49b0459b79032051ae8cfd1ba5b5830&cdnurl=https%3a%2f%2fts1.cn.mm.bing.net%2fth%2fid%2fR-C.8539fa0712cfd6b01fe31d10b2b6edca%3frik%3dU5DJkGc1UidghA%26pid%3dImgRaw%26r%3d0&exph=630&expw=1200&q=music+lesson+cartoon&simid=608035282088180087&FORM=IRPRST&ck=ECCD5A0404DCB6758BC840B2CFBFCBB0&selectedIndex=1&ajaxhist=0&ajaxserp=0
2. Right click on the image and click "Copy image"
3. Open an empty presentation slide, click inside the slide (or an empty document), then press Ctrl+V to paste the image.
4. A distorted image is pasted instead of the normal one.

### Additional information

This happens on linux (Manjaro 21.3.3, Gnome 42.2, Wayland) and Windows 11 (22000.795) only with Firefox.
If I use Chromium 103.0.5060.114 on Manjaro, the image is pasted correctly.
The same image from Firefox is pasted correctly into Gimp

**Comment by ShockwaveNN** [comment]
Hi, I think it's a known bug 31484, we got some problems in some specific scenarios with aspect ratio of images

**Comment by ElenaMaaya** [comment]
This is fixed in DocumentServer v7.4.1.
Thanks for contacting us!

**Comment by Rita-Bubnova** [comment]
DesktopEditors v7.4.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
