### ISSUE TITLE
With the exception of the top row of the first worksheet, all the data on my spredsheet was deleted

### ISSUE THREAD

**Issue by JARC99** [ONLYOFFICE/DesktopEditors#976]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.1.1.57

### Expected Behavior

The program shouldn't delete my work if not told to do so.

### Actual Behavior

I saved my file continuously and never closed it before saving it. I opened it afterwards and only the first worksheet was left with only the first row of the data still there, the rest was gone. I had at least four worksheets with a full table each, this is the only thing left when I open the file.
![image](https://user-images.githubusercontent.com/53633517/179399625-b9315db3-9868-47dc-8c68-13cc61643f6b.png)

### Reproduction Steps

1. Create a spreadsheet file.
2. Save it.
3. Close the file.
4. At some point your data will be gone.

**Comment by ShockwaveNN** [comment]
Hi, I'm sorry to hear that all data is lost, but I'm not sure that we'll be able to localize the problem in your current scenario, because I'm sure it involved a lot more steps to fail without any errors

One thing I see is that you use `ods` format in your presentation, maybe it have something to do with that

**Comment by JARC99** [comment]
Yeah I used to use vanilla LibreOffice  but changed to OnlyOffice for the improved GUI. I'll try to used the default formats, maybe that way the file does not get corrupted

**Comment by ShockwaveNN** [comment]
@JARC99 Yeah, we try to make ods format as stable as possible now, but originally our suite was using ooxml format (xlsx), so it should be more stable

But if you will be able to find exact scenario then data loss is happened we'll try to fix this issue with highest priority

**Comment by JARC99** [comment]
I'll try to reproduce it and I'll keep you updated on my findings. Thanks for the quick response :-)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
