### ISSUE TITLE
Merge & center greyed out

### ISSUE THREAD

**Issue by yggdrasil27** [ONLYOFFICE/DesktopEditors#977]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

ONLYOFFICE/6.3.1.32

### Expected Behavior

when use merge and center. i expect it can be used as well, but it can't.

### Actual Behavior

sry for censorship of confidential data
![photo1658303533](https://user-images.githubusercontent.com/109654437/179928818-c2897181-6281-41ab-9223-9909749482ff.jpeg)
merge & center greyed out and it can't be used

**Comment by yggdrasil27** [comment]
ahhh i see, sorry for the wrong post
so i just need to update my version or what steps i have to do so that merge & center can be used again?

**Comment by ShockwaveNN** [comment]
`merge & center` should be available from the start of new presentation

![image](https://user-images.githubusercontent.com/668524/179933418-82c64d9d-bb8c-459f-a236-ba88949cca75.png)

Any chance you've using Nextcloud's Community Document Server?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
