### ISSUE TITLE
Bad pefromance and high CPU utilisation

### ISSUE THREAD

**Issue by Emil9736** [ONLYOFFICE/DesktopEditors#984]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

any

### Expected Behavior

Any versions have issue with low perfomance

### Actual Behavior

Bad performance on any version while opening files, creating new files. 

### Reproduction Steps

Open task manger or any such app to watch CPU utilization
Open any file readable by OnlyOffice 
or
start desktop editor
create new any documents
watch high CPU utilization 35-55% 

### Additional information

Intel 10th gen

**Comment by ShockwaveNN** [comment]
Hi, I think it's just how our application work, since we perform some convert jobs on opening any files

We constantly trying to improve our performance, but without some specific steps to reproduce or some speicif file which have unusual high CPU usage - I don't think we can do anything

**Comment by jbuencuerpo** [comment]
Hi, I have also relatively high CPU usage in linux (Pop-OS 22.04, Flatpak, AppImage and deb tested) in **idle** even with an empty word document. Like 10-15% usage per-document open without doing nothing, what prevents me to use it when running on battery.

I tried disabling the spell checker wild guess...), but I guess there is something running in the background. Let me know if I can do more tests. I typically use the flatpak version, but I can re-install the deb or the Appimage if necessary.

Thanks for the amazing software in any case,

**Comment by ShockwaveNN** [comment]
@jbuencuerpo Yeah, ples try dep package first and check it and if so - I think it's better to create a new issue

**Comment by jbuencuerpo** [comment]
I have opened #1000 
Best regards

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
