### ISSUE TITLE
Can't upload folder to CommunityServer via connected DesktopEditor

### ISSUE THREAD

**Issue by nixjdm** [ONLYOFFICE/DesktopEditors#985]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.1.1.57, installed with the repo instructions on https://helpcenter.onlyoffice.com/installation/desktop-install-ubuntu.aspx

### Expected Behavior

I expect the folder to appear and actually be uploaded. If it's a simple folder with few contents, I'd expect this to be very quick. If it's a large folder, I'd expect some indication of progress.

### Actual Behavior

I can select a folder to upload, click upload, and then get no feedback at all. The folder never seems to upload, and it's as if nothing happened. This happens trying to upload to "My documents" and "Common".

### Reproduction Steps

I simply used this on both "My dcouments' and "Common": ![Screenshot from 2022-08-01 10-56-55](https://user-images.githubusercontent.com/3431410/182190234-d00db85c-310d-4979-bf4b-2fb6b196390d.png)

I tried a folder with a single small pdf in it, and a folder with subfolders and many contents. Neither worked.

### Additional information

I'm particularly interested in using the desktop app to upload because I'd hope it has better performance than a browser. I have a lot of large folders I'd like to upload that the browsers choke on.

I'm also uploading to a private onlyoffice server, but I wouldn't guess that's important because browser uploads to this server generally work fine (unless they're large, but I think that's more the browser/webpage's issue, and not the server).

**Comment by matveevms** [comment]
Hello, @nixjdm
This is known issue - 51182 in our private issue tracker.
Thank you for report.

**Comment by matveevms** [comment]
Hi, @nixjdm.
The problem has been fixed in version v.7.4.0

**Comment by Rita-Bubnova** [comment]
DesktopEditors v7.4.1 is released so I close this issue.
