### ISSUE TITLE
Hyperlink to folder or file

### ISSUE THREAD

**Issue by MatveyM11** [ONLYOFFICE/DesktopEditors#986]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

OnlyOffice supports hyperlink to folders or files that were made in the LibreOffice, but in the OnlyOffice itself you cant add a hyperlink to something else than in a file itsels or on the WEB.
So I don't see here a single reason why not to add just a one more option in the hyperlink menu so the user could be able to add a hyperlink to a  folder or file.

**Comment by LuckySpecialist** [comment]
Hi @MatveyM11, since version 7.3, we have added support for links to external and local files, have you checked, is this what you need?

**Comment by MatveyM11** [comment]
> Hi @MatveyM11, since version 7.3, we have added support for links to external and local files, have you checked, is this what you need?

Yes, that's right what I needed, many thanks!
