### ISSUE TITLE
Interface language has too much wrong translation for Chinese

### ISSUE THREAD

**Issue by kenifanying** [ONLYOFFICE/DesktopEditors#993]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, Linux (DEB package)

### Version information

7.1.1.57

### Expected Behavior

Interface language correctly translated for Chinese.

### Actual Behavior

Interface language has too much wrong translation for Chinese

eg:

`Insert->Equation->Scripts` should translated to `上下标`

`Insert->Equation->Large Operators` should translated to `大型运算符`

`Insert->Equation->Radicals` should translated to `根式`

and so on.

### Reproduction Steps

Change Interface language to Chinese(中文）

**Comment by ShockwaveNN** [comment]
Hi, thanks for report, I think we already updated our translation for future version, which will be 7.2.0 (cannot tell estimate date of release sorry)

And right now on testing version it's looks like this:
![image](https://user-images.githubusercontent.com/668524/184470766-1a146572-b0b5-4102-98f5-cdc456834a23.png)

Is it ok? Sorry, I'm not good at chinese at all, but seems that symbols looks like your variants

Also if you've interesting in providing any help - you can read our contribution guide for translation [here](https://helpcenter.onlyoffice.com/guides/become-translator.aspx)

**Comment by kenifanying** [comment]
> Is it ok? Sorry, I'm not good at chinese at all, but seems that symbols looks like your variants

It seems that the translation is good enough for the sub menu under the `Insert->Equation`. But there are wrong translation in other places too, I will test it again after version 7.2.0 released.

**Comment by ShockwaveNN** [comment]
> But there are wrong translation in other places too

As I said you can contact our translation team and help them fix them, or you can report exact places with bad translation here, but without actual strings to look at, I don't think I can help you

>  I will test it again after version 7.2.0 released.

You can try it out right now, but please do not use it in production environment

You can run it by

```
docker run -itd -p 80:80 onlyoffice/4testing-documentserver-ee:7.2.0.137
```
